### ISSUE TITLE
Exemplo de uso

### ISSUE THREAD

**Issue by jrlubas** [BoletoNet/boleto2net#102]
Boa tarde Galera...

Desculpe minha ignorância, mas alguém teria algum exemplo de uso de geração de 1 boleto + geração de arquivo remessa cnab240?

Não estou bem habituado nas classes, métodos, etc.

**Comment by henrique25t** [comment]
Tem um projeto de teste. É só rodar ele com breakpoint para ver como funciona.
A ordem de procedimentos que eu fiz foi basicamente essa. Só fazer nessa ordem e popular os objetos com os seus dados. 
![image](https://user-images.githubusercontent.com/40005244/42574901-eeca56fe-84f5-11e8-85d7-61e2097840fa.png)

no meu caso eu retornei um ActionResut
