### ISSUE TITLE
Compatibilidade Net Core

### ISSUE THREAD

**Issue by tssa88** [BoletoNet/boleto2net#104]
Prezados, boa tarde.
Gostaria saber se esse projeto é compatível com NET Core?
Seria possível buildar/rodar o projeto em uma máquina linux?
Caso negativo, existe previsão?

**Comment by henrique25t** [comment]
É sim. Estamos usando ele aqui na empresa. Usamos .Net core MVC e está ok.
Eu baixei a solução no meu pc e vou aprendendo como funciona, mas no nosso programa da empresa estamos usando o pacote NuGet.

**Comment by ederfdias** [comment]
Henrique bom dia,  vocês adicionaram a DLL através do NuGet e não teve nenhum warning no projeto?
Adicionei no meu projeto ASp.Net Core e apareceu uma warning que talvez não seja completamente compatível com o projeto.
Aconteceu isso com vocês?
Obrigado.

**Comment by rcoproc** [comment]
Comigo aconteceu também, e será que irá funcionar com dotnetcore ???

![image](https://user-images.githubusercontent.com/7529472/47294134-27ac7300-d5da-11e8-918f-25ffab99e3b4.png)

**Comment by oscarpires** [comment]
também tenho tentado utilizar no aspnet core, porem o warning de que o componente exige o framework 4.6.1 sem compatibilidade plena com o aspnet core v2.0

**Comment by rcoproc** [comment]
Fiz o teste  e não funciona no aspnet core.. só funciona no aspnet MVC. Uma pena, será que alguém aqui já  fez alguma conversão para o dotnetcore ????

**Comment by rcoproc** [comment]
Este fork aqui https://github.com/Tagliatti/BoletoNetCore/ do Filipe Tagliatti está funcionando em Dotnetcore , só não sei se está atualizado.

**Comment by carloscds** [comment]
@rcoproc Tinha uma outra tread falando disto.

**Comment by carloscds** [comment]
@rcoproc Mas não está difícil, só precisamos trocar o componente de PDF para este: https://www.nuget.org/packages/NReco.PdfGenerator.LT

**Comment by carloscds** [comment]
@rcoproc Pessoal, dei uma olhada no codigo atual e teremos que remover o System.Web e tudo e também atualizar o NReco, como mencionei antes. É uma alteração considerável, já que a impressao do boleto foi toda feita com System.Web.

**Comment by penihel** [comment]
Na minha aplicação, eu tenho que gerar PDF a partir de HTML, em .NET CORE.

Eu resolvi transformando isso numa chamada pra um serviço externo

https://jsreport.net/

https://jsreport.net/learn/dotnet-local

Creio que seria a melhor opção

**Comment by carloscds** [comment]
@penihel O problema desta abordagem é este serviço sair do ar.

**Comment by penihel** [comment]
@carloscds 
Realmente, mas no meu caso isso não é um problema.
Eu só crio a imagem docker em uma webApp no Azure, e recebo uma url pra fazer as requisições. e esta URL sempre está online.


Mas existe uma solução local https://jsreport.net/learn/dotnet-local 
Nesta opção o JSReport cria um Server Local que junto com  a WebApp.
Porém esta opção só funciona com todas as opções se sua APP roda em uma VM no IIS. Se for uma WebApp Azure Windows, não rola. Rola se for linux.

Mas uma opção legal, seria a biblioteca pode ser configurada para definir qual serviço/classe de geração de PDF ela irá usar. Assim fica flexível.

**Comment by carloscds** [comment]
@penihel Precisamos de algo que seja compilado junto com o código, como é hoje. Senão aumenta a complexidade do uso do componente.

**Comment by olavorn** [comment]
> @penihel Precisamos de algo que seja compilado junto com o código, como é hoje. Senão aumenta a complexidade do uso do componente.

Fala @carloscds 

Como aquele branch do dnx não deu muito certo (rsrs) fiz uma abordagem diferente dessa vez pra ver se vai. Vamos manter esse [fork](https://github.com/ExodusSistemas/boleto2net), mas havendo interesse, fazemos um pull request.

Assim são 1 projeto quebram em 2 projetos + testes. 
* Sem pdf (netstandard2.2) -> 100% Html Embeded. boleto2.net
* O com PDF (pesado, mas 100% netstandard2.2) boleto2.net.pdf 
https://github.com/BoletoNet/boleto2net/issues/184#issuecomment-509087901

**Comment by carloscds** [comment]
@olavorn Que ferramenta de PDF você usou ? Pois o problema esta neste ponto. Eu mesmo ja fiz um clone do projeto e migrei para Core, mas sem o PDF.

**Comment by olavorn** [comment]
Usei a mesma que o NReco usa. 

```  c#
        public byte[] MontaBytesPDF(bool convertLinhaDigitavelToImage = false, string urlImagemLogoCedente = null)
        {
            return (new Wkhtmltopdf.NetCore.HtmlAsPdf().GetPDF(MontaHtmlEmbedded(convertLinhaDigitavelToImage, true, urlImagemLogoCedente)));
        }
```
Só que embarcar os executáveis na dll que deixa a lib pesada. Mas atualmente o projeto faz isso pra deixar mais simples.

**Comment by carloscds** [comment]
@olavorn Mas o nreco para Core é pago!

**Comment by olavorn** [comment]
Nao usei NReco. Usei a Wkhtmltopdf "que é a mesma que o NReco usa". Mas ela é free e Open Source.

**Comment by carloscds** [comment]
@olavorn Este é um executável, você testou no linux ? Eu já usei esta ferramenta em um projeto core.

**Comment by carloscds** [comment]
@olavorn Onde vc conseguiu as DLLs e o .SO, pois nao instala junto com o pacote do Nuget.

**Comment by olavorn** [comment]
Não cheguei a testar no linux para fins do boleto, mas tenho outra aplicação que usa um conceito parecido, e a mesma biblioteca. E com algumas dependências ela funciona no Linux sim sem problemas.

https://www.nuget.org/packages/Wkhtmltopdf.NetCore

**Comment by olavorn** [comment]
![image](https://user-images.githubusercontent.com/3752407/61372971-df6f6800-a86e-11e9-8bc4-a3079a8d317b.png)

**Comment by carloscds** [comment]
@olavorn Sim, muitos componentes são baseados neste arquivo. Acredito que podemos publicar isto. Lembrando que uma vez migrado para Core, quem utiliza .NET inferior a 4.6 não conseguirá mais usar. 
O que acha @rafd75 ?

**Comment by olavorn** [comment]
@carloscds talvez fosse o caso que criar uma tag v2 e um branch v2 a partir daí e mudar a versão com breaking changes. Ex: v3. Talvez interesse a outros manter a versão atual. Assim poderiamos ficar com dois pipelines pra publicar o nuget.

**Comment by rafd75** [comment]
bom dia @carloscds @olavorn  ...

Eu não consigo opinar nessa questão...

Mas se eu entendi bem o que o Olavo sugeriu, nós teríamos dentro de um mesmo projeto, as duas possibilidades, e se alguém implementasse uma nova carteira no branch Master, reaproveitaria no branch v2 ... Se for isso mesmo, acho uma boa ideia... 

No caso, migrar o Boleto2Net para Core, exigindo a versão 4.6, me parece um problema considerando o tanto de pessoas que utiliza o componente.

Uma outra alternativa, seria ter o BoletoCoreNet (como um terceiro projeto), mas perderia o reaproveitamento de novas implementações feitas no Boleto2Net (e vice-versa)... 

Enfim... o .NET não é minha ferramenta principal de trabalho e não conheço essas questões de versão para poder opinar neste assunto.... mas se puderem me explicar melhor, eu gostaria de entender as possibilidades.

**Comment by olavorn** [comment]
> @carloscds talvez fosse o caso que criar uma tag v2 e um branch v2 a partir daí e mudar a versão com breaking changes. Ex: v3. Talvez interesse a outros manter a versão atual. Assim poderiamos ficar com dois pipelines pra publicar o nuget.

Também poderíamos verificar as dependências fazerndo configuração multitarget no projeto.. Desta forma, creio que poderíamos aproveitar a grande maioria das classes nesse formato, ainda nas versões anteriores do .net. Só que ainda assim teriamos que ter uma separação inicial do projeto em todas as versões, e eliminação das dependências específicas de versões, como a classe control , .ashx etc.

System.Drawing é outro calo também.

**Comment by oscarpires** [comment]
bom dia pessoal

@carloscds não entendi a questão de não conseguir usar c/ versão inferior a
4.6. O boleto.net para Core não é na pratica, um projeto separado do
Boleto2Net framework 4;6? devido as profundas mudanças, estão sendo
mantidos e evoluídos paralelamente?
As melhorias e manutenções tendem a só ocorrer no BoletoNet Core ?

a propósito @carloscds, assisti sua palestra no teatro em Campinas.
Parabéns, mandou mto bem!

**Comment by olavorn** [comment]
@oscarpires , creio que se formos pelo caminho de criar uma estrutura comum que suporte todas as plataformas e criar projetos que apenas viabilizem agregação de mais serviços e funcionalidades que não são comuns (Ex: PDF), então creio que poderemos em um futuro próximo convergir pra todas as plataformas e evoluir as funcionalidades referentes ao negócio principal de maneira unificada.

**Comment by oscarpires** [comment]
@olavorn <https://github.com/olavorn> me parece que não será viável termos
uma estrutura comum, devido o .net core não possuir retrocompatibilidade
com o .net framework. Se os componentes forem migrados pro .net core, a
camada de visualização (razor) irá conseguir consumir, mas no .net
framework não. Precisará recompilar no .net framework, certo?
A tendência será evoluir o projeto no .net core e manter o legado no .net
framework ?

**Comment by carloscds** [comment]
@olavorn @oscarpires O problema de migrar para netstandard2.0 é que quebra a compatibilidade com .NET inferior a 4.6.1 (https://docs.microsoft.com/pt-br/dotnet/standard/net-standard). Sendo assim eliminamos usuários inferiores a esta versão.
Criar um novo branch/projeto pode ser a saida para inicarmos a portabilidade, mas como o @rafd75 falou, teremos trabalho dobrado para migrarmos coisas novas de um para outro.
Manter tudo em um único projeto pode ser complicado, pois estando no .NET Core fatalmente iremos implementar algo que quebra o código em versões anteriores.
Isto tudo em minha opinião é claro, fiquem a vontade para opinar :-)

**Comment by marcosgerene** [comment]
@carloscds @oscarpires @rafd75 @olavorn @thiagosoeiro 

Caros, vou falar como usuário.

Meus principais softwares são desktop, hoje uso a versão 4.6.2 do .Net.

Mudanças na versão do .Net sempre são traumáticas para quem vem do mundo desktop, como sou software house estamos falando em ter que atualizar o .net framework em uma quantidade razoavel de clientes (hoje está diminuindo, pois o windows 10 vem ajudando nesse sentido).

Bem recentemente migrei do 4.6.1 para o 4.6.2, parece simples, mas deu um suporte razoável... e bem, se eu tivesse feito antes o efeito era menor, porque era menos gente usando, menos maquinas... logo, chego à minha conclusão: Se a ideia for "quebrar" para quem usa abaixo da  4.6, este processo deve ser feito o quanto antes, menos pessoas afetadas, menor o trauma.

**Comment by olavorn** [comment]
Senhores, com relação ao princípio da retrocompatibilidade, estou quase convencido que [isso](https://github.com/BoletoNet/boleto2net/issues/104#issuecomment-512242359) supera a questão. 

Com relação as mudanças, nem veria a necessidade de discutir isso, pois poderemos abraçar ambos, o que teoricamente teriamos que ajustar, ao meu ver são dependências de construção internas na versão principal, tais como:
Objetivo: Migrar toda a lógica orientada a plataforma para projetos satélites:
1.  Abandono da dependência do System.Web e das versões utilizando o .ashx. =>  (boleto2net.webforms para quem tiver interesse)
2.  Abandono do System.Web (Classe Control, etc)  => (boleto2net.webforms)
3.  Priorização da logica de processamento de arquivo, leitura CNAB e geração em Hipertexto.
(ficaria na boleto2net)
4.  Impressão em PDF (boleto2net.pdf)

Desta forma, conseguimos manter o projeto base e seu desenvolvimento em um único ponto, e conseguimos evoluir canais e plataformas de maneira integrada.  

Proponho que a gente abra uma branch para isso, e eu me proponho a fazer um pull request inicial para avaliação baseado no nosso fork. Daí podemos avaliar e discutir as mudanças item a item no próprio pull request.

**Comment by carloscds** [comment]
@olavorn por mim ok!

**Comment by olavorn** [comment]
https://docs.microsoft.com/pt-br/dotnet/standard/frameworks

**Comment by carloscds** [comment]
@olavorn Eu já passei este link alguns comentários acima!

**Comment by olavorn** [comment]
Vou esperar o link da branch então, @carloscds. Pra a gente iniciar o PR.

**Comment by carloscds** [comment]
@olavorn @rafd75 Resumindo então: vamos criar outro projeto chamado "BoletoNetCore" e subir um código modificado la?

**Comment by olavorn** [comment]
Por mim, pode até ser uma branch desse por enquanto. Não creio que precise criar um novo projeto ainda. Ou vcs já querem começar com um nuget funcionando?

**Comment by carloscds** [comment]
@olavorn @rafd75 Criado: https://github.com/BoletoNet/BoletoNetCore

**Comment by rafd75** [comment]
Pronto! ... 


Fiquei boiando em alguns pontos, mas se o que eu entendi estiver correto, o projeto "Core" vai ser separado em 2 (parte do boleto em si + parte do PDF)... e isso faz com que ele funcione em qualquer ambiente desde que seja do framework 4.6 para frente... confere?

Se for isso, minha ideia aqui é - em breve - migrar do Boleto2Net para o BoletoNetCore - e passar a investir o tempo nesse novo projeto... (minha única condição de uso é que se mantenha uma padronização nos bancos/carteiras e obrigatoriedade de teste unitário de tudo   - pois foi isso que me motivou a sair do BoletoNet e refazer as coisas no Boleto2Net).

**Comment by carloscds** [comment]
@rafd75 Sera um unico projeto, trocando o NReco pelo outro.
