### ISSUE TITLE
Carteira 138 - Banco itaú

### ISSUE THREAD

**Issue by LuizMoreira** [BoletoNet/boleto2net#105]
Boa tarde, 

tenho acesso a um sistema que me retorna o XML com todas as informações, inclusive o código de barras, mas gostaria de usar o boletonet para apresentação do boleto. O código que o xml retorna de carteira é o 138. 
Como vcs sugerem que eu implemente essa alteração para somente apresenta o boleto com os dados que já tenho?

**Comment by rafd75** [comment]
@LuizMoreira , boa tarde.

1 - precisaria implementar a carteira 138... , algo parecido com o que acabei de responder nessa outra issue -> #106

2 - depois de implementada, imagino que você vai precisar pegar os dados do XML (não acho que somente o código de barras vai resolver para montar o boleto), e criar um boleto na DLL... Veja que, apenas o código de barras, identifica o banco, nosso número, vencimento e valor, mas não o nome do cliente, data de emissão, número do documento, entre outras informações...

**Comment by LuizMoreira** [comment]
Entendi! obrigado @rafd75
