### ISSUE TITLE
Nova carteira 176  Banco Itaú - Qual o esforço?

### ISSUE THREAD

**Issue by thiagosoeiro** [BoletoNet/boleto2net#106]
Se por ventura, eu precisar incluir um novo banco ou carteira, gostaria de saber o quão oneroso isso se torna? Mais especificamente a carteira **176** do banco **Itaú**.
Qual seria o esforço para implementação? Estou começando a estudar o código e gostaria de fazer isso por conta própria

**Comment by rafd75** [comment]
@thiagosoeiro , boa tarde.

Primeiro esforço: levantar quais as diferenças entre a carteira 176 e a carteira 109 (já implementada)

Se o layout cnab for o mesmo, o esforço é mínimo ... basta implementar a classe da carteira 176 e suas regras de geração de nosso número, etc... e depois os testes unitários...
