### ISSUE TITLE
Instrucoes do boleto

### ISSUE THREAD

**Issue by henrique25t** [BoletoNet/boleto2net#107]
Olá, estou com dúvidas sobre como eu devo preencher
"CodigoInstrução1"
"ComplementoInstrucao1" 
"CodigoInstrução2"
"ComplementoInstrucao2" 
"CodigoInstrução3"
"ComplementoInstrucao3" 
Gostaria de saber se tem uma tabela de normas ou algo do tipo que eu devo seguir para preencher esse código ou se o código é apenas para ser diferenciado na própria aplicação.
No boletoNet 1 existia a classe Instrução que dava para instanciar já selecionando se ela tinha valores a pagar e ela já se montava sozinha. Nesse aqui eu não entendi muito bem como usar essas instruções.

**Comment by rafd75** [comment]
@henrique25t , boa noite...

Nem todas as propriedades são utilizadas por todos bancos/carteiras... verifique no arquivo remessa (do banco desejado) se estão sendo utilizadas...

Caso estejam, simplesmente utilize o código que está no manual do banco. Vou chutar aqui, mas por exemplo: 06 pode indicar protestar após 6 dias.

OU seja, o que setar no CodigoInstrucao1, irá na primeira instrução do arquivo remessa.

Quanto as mensagens, como no exemplo "protesto em 6 dias", o Boleto2Net não irá gerar de forma automática... Para isso, utilize as propriedades MensagemInstrucoesCaixa e MensagemArquivoRemessa

**Comment by rafd75** [comment]
Isso mesmo... assim você coloca do jeito que preferir.... 

O motivo dessa alteração, é que, no projeto original, quando o pessoal implementava uma carteira, eles não criavam esses códigos em todas elas... a ideia é boa, mas dificulta a implementação/manutenção das carteiras...

Transformei em um string, e pronto... O lado negativo é o que vc apontou ... sem a "coleção" de operações definida dentro do projeto, você precisa do manual do banco para entender o que cada código significa...

Obs: O fato de você preencher o MensagemInstrucoesCaixa não desobriga a apontar os códigos de operação, ok? ... os códigos de operação são utilizados no remessa, para o banco entender o que você quer fazer com o título.... Uma coisa não elimina a outra.

**Comment by rafd75** [comment]
é... perdeu nesse ponto... mas eu me recordo, que a implantação não era completa, alguns bancos tinham, outros não... e esse foi o motivo de sacar isso para esse projeto.

Aqui, estou tentando - pelo menos - exigir testes unitários de todas as carteiras, com todas as variações de nosso número (dv) para garantir que ninguém terá problemas ao emitir boletos... por enquanto está funcionando...

**Comment by henrique25t** [comment]
Entendi. De qualquer forma, está ótimo. Obrigado pela ajuda. Uma última dúvida, ao concaterar as minhas instruções na MensagemInstrucoesCaixa tem que fazer uma quebra de linha para funcionar né?

**Comment by rafd75** [comment]
Isso... utiliza o <br /> que funciona... 

string x = "teste <br />outra linha<br />e assim por adiante<br /><br />se der errado, retorne... "

**Comment by henrique25t** [comment]
Ok. Muito obrigado pela ajuda.
