### ISSUE TITLE
Arquivo Retorno

### ISSUE THREAD

**Issue by tbispos** [BoletoNet/boleto2net#108]
Alguém tem arquivo retorno do banco do brasil para testes.
Obrigado!

**Comment by carloscds** [comment]
@tbispos Você nao consegue com o banco ?

**Comment by elton007** [comment]
Boa noite tipos,  me passa seu e-mail que lhe dou alguns.

**Comment by tbispos** [comment]
jonathan.gomess1@gmail.com
Obrigado!

**Comment by elton007** [comment]
Bom dia Jonathan,

Enviei para o seu e-mail,
Att
