### ISSUE TITLE
Data do crédito arquivo retorno CNAB240 SICOOB

### ISSUE THREAD

**Issue by krgm03** [BoletoNet/boleto2net#111]
Bom dia

Alguém que esteja utilizando Sicoob percebeu a data de crédito sendo retornada com o valor '00000000'?
Data do Crédito - Segmento U - 17.3U posição 146 até 153

**Comment by lvitorbh** [comment]
Ainda não estou tratando o retorno. Mas o layout do Sicoob anda mudando com frequência.

17.3U | 146 | 153 | 8 | - | Num | Data do Crédito | Data do evento que afeta o   estado do título de cobrança.     Utilizar o formato DDMMAAAA, onde:     DD = dia     MM = mês     AAAA = ano
-- | -- | -- | -- | -- | -- | -- | --

Pelo manual Teoricamente ela deveria vir preenchida.
http://prodados.com/osg/anexo/1836.34245Layouts_para_troca_de_informacoes-14092018.xls

**Comment by krgm03** [comment]
@lvitorbh, aqui os registros do arquivo de retorno continuam vindo com '00000000' na data de crédito na ocorrência '06 - liquidação'. Você já tratou o retorno? Reparou se aí no seu caso ocorre o mesmo problema?

**Comment by krgm03** [comment]
@rafd75, utiliza CNAB240 SICOOB em produção? Ocorre contigo o problema que citei acima?

**Comment by rafd75** [comment]
@krgm03  - uso o SICOOB aqui apenas no layout CNAB400.

**Comment by marcosgerene** [comment]
Utilizo CNAB240 No Sicoob em produção aqui e não venho tendo problemas...
