### ISSUE TITLE
Número Documento

### ISSUE THREAD

**Issue by tbispos** [BoletoNet/boleto2net#113]
Pessoa o número do documento do boleto pode ser duplicado ou seja repetido ?
Obrigado!

**Comment by rafd75** [comment]
bom dia.

NossoNúmero (do banco), entende-se que não deve ser repetido... (mas se não me engano, em alguns casos, se repete --- ou repetia, para cobrança não registrada)

Já o número do documento é de uso da empresa, e para o banco, não teria nenhum problema em repetir.

Aqui, usamos o número do documento como número da nota fiscal, acrescido da letra A, B, C dependendo da parcela... Ou seja, para nós, não se repete.

**Comment by tbispos** [comment]
O Nosso Número é o banco que fornece  ou é sequencial em cada boleto gerado?
Obrigado!

**Comment by rafd75** [comment]
depende da cobrança que você usa.

Se a emissão (impressão do boleto) for pelo banco, você pode escolher entre ele gerar (o nosso número) ou você. Se ficar com o banco, mande no CNAB o nosso número zerado (confirme essa informação com o suporte do banco). Se sua aplicação comanda o nosso número (mas não imprime o boleto), é necessário controlar e informar esse nosso número no arquivo CNAB.

Se a emissão (impressão do boleto) for pela empresa, você precisará controlar e obrigatoriamente gerar o nosso número.


Aqui, quando geramos o nosso número, uso um sequencial.
