### ISSUE TITLE
Grupo demonstrativo

### ISSUE THREAD

**Issue by tbispos** [BoletoNet/boleto2net#116]
O que seria isso no boleto ? 
É obrigatório ?
Obrigado!

**Comment by carloscds** [comment]
@tbispos Qual banco ?

**Comment by tbispos** [comment]
Itau

**Comment by rafd75** [comment]
@tbispos, boa tarde (estou um pouco atrasado aqui - nessa resposta - mas antes tarde do que nunca).

Eu não uso esse recurso, mas com ele, se não me engano, você consegue montar um extrato na parte superior da folha do boleto, como se fosse um cartão de crédito... 

Pode colocar as ocorrências que estão sendo cobradas no boleto... é como se fosse um relatório mesmo, para o pagador verificar o que consta no boleto.

Neste caso, o recibo do sacado, não deve ser impresso, dando espaço para esse demonstrativo. O boleto propriamente dito, é impresso no final da folha...
