### ISSUE TITLE
Alteração Annotation - [CarteiraCodigo("17/019")] / [CarteiraCodigo("17/027")]

### ISSUE THREAD

**Issue by rafd75** [BoletoNet/boleto2net#12]
@AlbertoMonteiro - Bom dia... 

Você poderia verificar o seguinte:

Alterar a Annotation CarteiraCodigo de string para um array de strings?

Obs:

As classes da Carteira 17 (Banco do Brasil), para variação 019 e 027 são idênticas... Ctrl+C / Ctrl+V...

Alterando essa annotation, será possível renomear a classe BancoBrasilCarteira17_019 para BancoBrasilCarteira17, que passa a responder pela variação 019 e 027... Excluindo a classe BancoBrasilCarteira17_027.

Acho que expliquei certinho ai... Qualquer dúvida, me chama!

Valeu, abs!

**Comment by AlbertoMonteiro** [comment]
@rafd75 feito!
