### ISSUE TITLE
Implementação de Arquivo de Remessa e Retorno de Pagamentos

### ISSUE THREAD

**Issue by eltoncezar** [BoletoNet/boleto2net#123]
Olá,

Aqui na nossa empresa ([iatecbr](https://github.com/iatecbr)), implementamos a geração de arquivos de remessa e retorno de pagamentos (utilizando a estrutura do boleto2net) para os seguintes bancos:
- Santander (em homologação com o banco)
- Bradesco (em homologação com o banco)
- Caixa (em desenvolvimento)
- Banco do Brasil (em desenvolvimento)

Gostaria de saber se há interesse em incluir isso no boleto2net, ou se o escopo do projeto é somente a cobrança registrada.

**Comment by rafd75** [comment]
@eltoncezar , bom dia... 

Interessante a ideia de contar com a opção dos pagamentos também...

Eu só não sei se é melhor implementar no Boleto2Net, ou talvez criar um projeto Pagamento2Net...

Nunca implementei nada aqui sobre pagamentos, mas acredito que a resposta acima, vai estar principalmente ligada ao objeto BOLETO....

Se o objeto do lançamento a ser pago for um "BOLETO" (acho que não deve ser isso), faria sentido implementar aqui.

Se for diferente, e acho que deve ser o caso , seria melhor um outro projeto, não? ... (por exemplo - linha digitável de um tributo / conta de consumo é diferente do boleto)

@carloscds  ??? O que acha?

**Comment by eltoncezar** [comment]
Olá @rafd75, e obrigado por sua resposta :)

Realmente, o objeto é diferente. Nós o chamamos de **PaymentDocument**, e é uma implementação mais genérica, já que além de boletos, você também pode pagar outros tipos de títulos, tributos e transferências.

O que nós utilizamos do Boleto2Net mesmo, foram as classes do namespace `Boleto2.Net/Util` para a geração e leitura de arquivo. Talvez se dividisse em outro projeto, poderia ser reutilizado.

Aguardo mais considerações :)

**Comment by eltoncezar** [comment]
eu vou criar um repositório e tentar subir o projeto pra vocês darem uma olhada, pode ser?

**Comment by carloscds** [comment]
@rafd75 @eltoncezar Já está criado: https://github.com/BoletoNet/Pagamento2Net, vamos codar ?

**Comment by rafd75** [comment]
top

**Comment by eltoncezar** [comment]
Estamos refatorando algumas coisas, e depois subiremos o projeto :)

**Comment by fferretto** [comment]
Olá, nossa estou precisando muito disso, estou implementando na empresa onde trabalho a opção de gerar boleto e efetuar pagamentos, O de gerar boleto, estou usando a biblioteca do Boleto2Net, e irei iniciar o desenvolvimento para a parte do pagamento... 

Isso irá me ajudar muito no meu trabalho.

**Comment by controllernet** [comment]
Valeu @rafd75 vou ver com o @eltoncezar  

@eltoncezar  boa tard sua implementação do PaymentDocument é para pagamento de fornecedores ???

Como funciona a lógica ?? Vc chegou a disponibilizá-la em algum repositório público ??

**Comment by eltoncezar** [comment]
Olá @controllernet sim, para pagamento de fornecedores, além de transferências, DOC/TED, títulos registrados e tributos.

Porém, vou ser sincero: implementamos aqui com a nossa equipe, e no final a estrutura de objetos ficou bastante amarrada com o nosso negócio. Eu estou reescrevendo essa parte, para algo mais genérico, mas o tempo está bem escasso... Acho que posso subir do jeito que está para um repositório meu, e depois que refatorar subo para o definitivo. O que acha?

**Comment by controllernet** [comment]
Ah legal @eltoncezar , quem sabe eu te ajudo a refatorar este núcleo. Nos interessa muito também esta parte. ah. Detalhe é em .NET MVC  ou dotnetcore ????
