### ISSUE TITLE
Mensagem Arquivo Remessa - SICOOB

### ISSUE THREAD

**Issue by lvitorbh** [BoletoNet/boleto2net#125]
O layout do arquivo de remessa do Banco Sicoob foi alterado.

https://www.bancoob.com.br/atendimentocobranca/CAS/2_Implanta%C3%A7%C3%A3o_do_Servi%C3%A7o/Sistema_Proprio/Layouts_para_troca_de_informa%C3%A7%C3%B5es.xls

18.3R | 100 | 139 | 040 | - | Alfa | Informação   3 | Mensagem 3.   Preencher com espaços em branco
-- | -- | -- | -- | -- | -- | -- | --
19.3R | 140 | 179 | 040 | - | Alfa | Informação   4 | Mensagem   4. Preencher com espaços em branco

O Arquivo BancoSicoob.cs deve ser alterado nas linhas 440 e 441 de:

`reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0100, 040, 0, msg3, ' ');`
`reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0140, 040, 0, msg4, ' ');`

para 

`reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0100, 040, 0, Empty, ' ');`
`reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0140, 040, 0, Empty, ' ');`

**Comment by lvitorbh** [comment]
Alguma previsão de realizar o Pull dessa alteração?

**Comment by rafd75** [comment]
@lvitorbh  bom dia...

deixa eu dar uma olhada aqui e já aproveito o embalo e faço isso tb... me da uns minutos

**Comment by rafd75** [comment]
Pronto... entrou no PR: #129

**Comment by lvitorbh** [comment]
:-)
