### ISSUE TITLE
Homologação Boleto Caixa

### ISSUE THREAD

**Issue by asilveirbr** [BoletoNet/boleto2net#128]
Olá pessoal, estou homologando o boleto com registro (14) junto a Caixa e apontaram 3 itens para acertar são eles:

Acerto 01.:  LOCAL DE PAGAMENTO*: Deve apresentar a expressão “PREFERENCIALMENTE NAS CASAS LOTÉRICAS ATÉ O VALOR LIMITE”

Acerto 02.:  Carteira.: Preencher com RG

Acerto 03.:  Em cumprimento ao disposto no Artigo 7º do Decreto 6.523, de 31/07/08, e na Circular BACEN 3.370/07, é obrigatório constar:

SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogios)
Para pessoas com deficiência auditiva ou de fala: 0800 726 2492
Ouvidoria: 0800 725 7474
caixa.gov.br

Pelo que percebi o valor default está "ATÉ O VENCIMENTO EM QUALQUER BANCO. APÓS O VENCIMENTO SOMENTE NA CAIXA ECONÔMICA FEDERAL."  e mesmo eu colocando no código o certo ele imprime o default.

Em relação a sigla da carteira, se eu colocar RG dá como carteira não implementada.

Peço ajuda pra resolver essas questões?

**Comment by rafd75** [comment]
@asilveirbr boa tarde...

Incrivelmente, estou fazendo esses ajustes agora... kkk - também estou homologando e veio exatamente essa situação para cá... 

espero terminar hoje ainda.

**Comment by asilveirbr** [comment]
Bom dia, alguma novidade quanto aos ajustes, há algo que eu possa ajudar?

Abraços

**Comment by rafd75** [comment]
@asilveirbr bom dia... 

#129  --- terminei na sexta, só esqueci de fazer o PR...

@carloscds  -  o PR ainda está pendente pelos testes... mas se passar, é só aprovar o PR...

**Comment by asilveirbr** [comment]
Olá, desculpe a ignorância, mas PR significa Pull Request?

**Comment by rafd75** [comment]
KK ... isso mesmo... nem sei se é "padrão" essa sigla... mas na velocidade aqui, digitei PR apenas.

**Comment by mdantasgyn** [comment]
Estou tendo problemas para homologar caixa, na carteira na impressão do boleto esta saindo SIG14 atualizei para a versão 1.61 do boleto2net e continua saindo esta inscrição ao inves de RG.

**Comment by marcdan** [comment]
> @asilveirbr bom dia...
> 
> #129 --- terminei na sexta, só esqueci de fazer o PR...
> 
> @carloscds - o PR ainda está pendente pelos testes... mas se passar, é só aprovar o PR...

rafd75, não estou conseguindo homologar o boleto conforme msg anterior, tem alguma idéia do que pode ser.

**Comment by rafd75** [comment]
bom dia...

Por favor, verifiquem se o código de vocês, está com a versão abaixo:

https://github.com/BoletoNet/boleto2net/blob/c1d65568484f56f6b735854afdce8f37bf77f955/Boleto2.Net/Banco/Carteiras/BancoCaixa/BancoCaixaCarteiraSIG14.cs#L19

**Comment by rafd75** [comment]
Completando... essa propriedade, aparece em 3 lugares no projeto:

![image](https://user-images.githubusercontent.com/11903379/47093234-299fbc00-d1ff-11e8-9df8-a1e9d13ff8ec.png)

Observe que o código ajusta para "RG" (boleto.CarteiraImpressaoBoleto = "RG"; ) no método FormataNossoNumero... ou seja, após criar o boleto, definir as propriedades, se não executar o "ValidaBoleto", não irá alterar para RG.

Se for esse o caso, faça manualmente, que deve funcionar. Após criar o boleto, e definir suas propriedades, faça manualmente... algo como abaixo...:

seuBoleto = new Boleto();
seuBoleto.ValorTitulo = 100;
seuBoleto.CarteiraImpressaoBoleto = "RG";

... depois de verificar isso, me da um retorno...

**Comment by marcdan** [comment]
> Completando... essa propriedade, aparece em 3 lugares no projeto:
> 
> ![image](https://user-images.githubusercontent.com/11903379/47093234-299fbc00-d1ff-11e8-9df8-a1e9d13ff8ec.png)
> 
> Observe que o código ajusta para "RG" (boleto.CarteiraImpressaoBoleto = "RG"; ) no método FormataNossoNumero... ou seja, após criar o boleto, definir as propriedades, se não executar o "ValidaBoleto", não irá alterar para RG.
> 
> Se for esse o caso, faça manualmente, que deve funcionar. Após criar o boleto, e definir suas propriedades, faça manualmente... algo como abaixo...:
> 
> seuBoleto = new Boleto();
> seuBoleto.ValorTitulo = 100;
> seuBoleto.CarteiraImpressaoBoleto = "RG";
> 
> ... depois de verificar isso, me da um retorno...

Descobri a falha, como estou usando em vb6, tinha uma dll da versão antiga na pasta do visual studio vb98 o que estava causando confusão no sistema... removi todas as dls e tlbs e refiz os registro agora 100%. Obrigado pelo atendimento rafd75

**Comment by mdantasgyn** [comment]
Bom dia, estou utilizando VB6 na geração do boleto e esta homologado ok, porém não consigo efetuar a leitura do retorno. Consigo rodar o LerRetorno() porém não consigo fazer a leitura dos dados do retorno. Alguem teria algum exemplo em vb6 para ler retorno usando o Boleto2Net ?

**Comment by rafd75** [comment]
@mdantasgyn  bom dia.

Alguma mensagem de erro?

Caso não tenha nenhuma, após rodar o LerRetorno(), você deve fazer um loop na coleção Boletos.
Para cada ocorrência do arquivo retorno, será criado um "boleto" na coleção "Boletos".

**Comment by mdantasgyn** [comment]
Sim, quando tento colocar o with boletos e end with para percorrer a colecao, o vb6 fecha só de executar nem chega neste processo.

**Comment by rafd75** [comment]
Aqui, trabalho com o FoxPro, e deve ser a mesma limitação do VB6... 

Eu uso a classe PROXY (do projeto)... e para ler cada objeto, uso o método abaixo:

https://github.com/BoletoNet/boleto2net/blob/d85147965796dbbd1b03916ac3bc8cd8edbaf646/Boleto2.Net/Boleto2NetProxy.cs#L159

**Comment by mdantasgyn** [comment]
Legal, este pode ser uma boa saida, teria como me enviar um modelo de implementação de leitura por este metodo no foxpro?
assim faço uma adaptação para o VB6 e posto se alguem passar por este problema

**Comment by mdantasgyn** [comment]
> Aqui, trabalho com o FoxPro, e deve ser a mesma limitação do VB6...
> 
> Eu uso a classe PROXY (do projeto)... e para ler cada objeto, uso o método abaixo:
> 
> https://github.com/BoletoNet/boleto2net/blob/d85147965796dbbd1b03916ac3bc8cd8edbaf646/Boleto2.Net/Boleto2NetProxy.cs#L159

Consegui ler pela classe proxy accessarboletoindice, porem não quer instanciar os boletos tento ler o nosso numero tipo Classe.Boleto.NossoNumero enão acesso o nosso numero. mas os boletos foram carregados pois vejo que me retornou pela quantidade dos boletos quantidadeBoletos me traz os 51 que constam no retorno. mas não consigo ler nenhum deles pelo objeto Boleto (Boleto.NossoNumero) por exemplo.

**Comment by rafd75** [comment]
Antes de ler, vc precisa "AcessarBoletoIndice() ... essa função, carrega o boleto que você informou no parametro, para o objeto boleto).

desculpe a pressa.

**Comment by mdantasgyn** [comment]
Valeu pessoal, eu estava fazendo corretamente o problema foi habilitar o objeto com para true nos assembly que não tinha feito. Tinha feito só no objeto principal. Agora estou conseguindo ler corretamente.
