### ISSUE TITLE
new Boleto(Banco.Instancia(x)) dando Null Reference

### ISSUE THREAD

**Issue by Forsaiken** [BoletoNet/boleto2net#130]
Um simples `Boleto boleto = new Boleto(Banco.Instancia(Bancos.Bradesco)); `
esta dando Null Reference de retorno e o mesmo ocorre pra qualquer banco que coloco, o que esta ocorrendo?

**Comment by rafd75** [comment]
Opa... 

Aqui, eu uso a classe Boleto2NetProxy, e não da problema... 

Tenta... 

Banco bradesco = Banco.Instancia(237);
Boleto boleto = new Boleto(bradesco);

se der erro, vai precisar depurar e ver onde está o erro.

**Comment by Forsaiken** [comment]
```
var bradesco = Banco.Instancia(237);
Boleto boletinn = new Boleto(bradesco);
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Vou tentar usar a versão anterior pra ver se é problema na mais recente.

**Comment by Forsaiken** [comment]
Bem as versões antigas estão dando a mesma coisa, ainda fiz outro projeto usei o mesmo comando e esta dando null reference, eu preciso de algo para fazer esse new Boleto?

**Comment by Forsaiken** [comment]
Eu verifiquei os códigos de teste e descobri que o IBanco precisa ser configurado, não basta colocar o Banco.Instancia, é necessario também colocar o cedente no IBanco. E um outro problema que acabei de perceber é que o Boleto2.NET tem dependencia (NReco.PdfGenerator) e o mesmo não esta no pacote do Nuget.

**Comment by cBarbosa** [comment]
você vai ter que instanciar o Cedente antes.
`var contaBancaria = new ContaBancaria();
_banco.Cedente = Utils.GerarCedente("1234567", "", "", contaBancaria);`
