### ISSUE TITLE
Erro no BoletoBancario.MontaHtml() azure

### ISSUE THREAD

**Issue by brunoofgod** [BoletoNet/boleto2net#133]
Boa tarde galera, alguém já teve algum problema quando faz a chamada do método BoletoBancario.MontaHtml() no servidores Azure? 

Localmente esta funcionando, porém na quando executo no servidor essa linha estoura um erro 500.

**Comment by dannieljunior** [comment]
teria como vc postar o stacktrace, pra tentar verififcar pra vc? Acho que o
erro se deve à null reference exception. Coisa especifica do seu ambiente
na nuvem
*Daniel Júnior*
Desenvolvedor
+55-62-98416.1070
Email: danniel.prg@gmail.com




Em sex, 21 de set de 2018 às 15:28, Bruno de Deus <notifications@github.com>
escreveu:

**Comment by brunoofgod** [comment]
O servidor fica lá até dar timeout

**Comment by dennyphilipp** [comment]
A versão free do servidor do Azure possui alguma limitação, mudamos para outra versão de configuração paga e funcionou normalmente.
