### ISSUE TITLE
Impressão de boleto

### ISSUE THREAD

**Issue by thiagothamiel** [BoletoNet/boleto2net#136]
Galera, se alguém puder me ajudar ficarei agradecido.

Dei uma pesquisada na Issues mas não achei nada sobre isso, então vamos lá.
Primeiramente gostaria de utilizar a classe boleto2net apenas para confeccionar o boleto, ou seja meu projeto faz a chamada de um WS externo do meu cliente que já retorna todos os dados do boleto, incluindo linha digitável e código de barras.

Eu gostaria de utilizar a classe boleto2net apenas para confeccionar o boleto, porém a Linha Digitável só aceita get.

Para eu setar os dados de linha digitável e código de barras é apenas pelo HTML ou existe outra forma?

Obrigado pela atenção até o momento.

**Comment by rafd75** [comment]
@thiagothamiel  bom dia.

A linha digitável e código de barras é calculado pelo componente, baseado nos dados do objeto boleto.

Se você informar data de vencimento, nosso número, conta/agência/convênio, (não sei as particularidades de cada banco), o sistema vai te retornar a linha digitável / código de barras, etc.

**Comment by thiagothamiel** [comment]
> @thiagothamiel bom dia.
> 
> A linha digitável e código de barras é calculado pelo componente, baseado nos dados do objeto boleto.
> 
> Se você informar data de vencimento, nosso número, conta/agência/convênio, (não sei as particularidades de cada banco), o sistema vai te retornar a linha digitável / código de barras, etc.

Isso eu entendi, mas a minha pergunta foi outra.
"Para eu setar os dados de linha digitável e código de barras é apenas pelo HTML ou existe outra 
forma?"

porque eu já recebo os dados do boleto por WS.

**Comment by rafd75** [comment]
Acredito que nesse caso, a biblioteca não vai atender essa necessidade...

Obs: O que você deseja é imprimir o boleto? Neste caso, você não teria que definir o beneficiário, pagador, endereço, dados da conta bancária, número do documento, data de emissão, etc, para que o boleto fosse gerado de forma completa?

**Comment by thiagothamiel** [comment]
> Acredito que nesse caso, a biblioteca não vai atender essa necessidade...
> 
> Obs: O que você deseja é imprimir o boleto? Neste caso, você não teria que definir o beneficiário, pagador, endereço, dados da conta bancária, número do documento, data de emissão, etc, para que o boleto fosse gerado de forma completa?

ok
