### ISSUE TITLE
Registro de Boleto via API JSON no Itau

### ISSUE THREAD

**Issue by cidmacedo** [BoletoNet/boleto2net#137]
Pessoal alguém já implementou o uso da API da banco Itau para realizar o registro do boleto utilizando JSON ? 
Obrigado,

**Comment by jpratesmoreira** [comment]
Eu tenho uma API Rest pronto. Caso tenha interesse em consumir entre em contato.

**Comment by rafd75** [comment]
@jpratesmoreira , bom dia!

Essa API seria uma camada intermediária entre o Boleto2Net e o banco? OU seria possível implementar no Boleto2Net a solução para integrar diretamente com o sistema bancário ?

**Comment by carloscds** [comment]
@rafd75 O ideal seria implementar como um novo serviço dentro do BoletoNet. My 5 cents!

**Comment by jpratesmoreira** [comment]
@rafd75 Isso mesmo. Me passa seu email que te envio a documentação da api.

**Comment by rafd75** [comment]
@jpratesmoreira , não entendi a resposta...

"Isso mesmo" significa que é um serviço seu, que iria fazer o meio campo entre o Boleto2Net e Banco?

ou 

"Isso mesmo" significa que conseguimos implementar a lógica dentro do Boleto2Net?

**Comment by jpratesmoreira** [comment]
@rafd75 um serviço meu, que ja atende os seguintes bancos Santander, Itaú, Bradesco, Sicredi, CEF, Banco do Brasil, Banrisul, Citibank, CrediSis, Banco ABC, Sicoob e Banestes.

**Comment by rafd75** [comment]
Entendi. Mas como o @carloscds comentou acima, neste caso, criar uma dependência do Boleto2Net que é aberto para um serviço privado acaba não sendo vantajoso para o projeto.

**Comment by carloscds** [comment]
@rafd75 Sim, neste caso precisamos desenvolver isto dentro do BoletoNet, nao depender externamente.

**Comment by jpratesmoreira** [comment]
Essa solução BoletoNet é em qual linguagem?

**Comment by carloscds** [comment]
@jpratesmoreira C#

**Comment by jpratesmoreira** [comment]
a minha api tb.

**Comment by DanielFilippo** [comment]
jpratesmoreira, pode me enviar a documentação da API? meu e-mail é daniel.filippolima@gmail.com obrigado

**Comment by carloscds** [comment]
@DanielFilippo @jpratesmoreira @rafd75 O que acham de incluirmos isto dentro do Boleto2Net, como uma outra classe?

**Comment by DanielFilippo** [comment]
@carloscds eu estava pensando a mesma coisa, uma outra classe sem dependência com o que já existe, queria ver essa documentação

**Comment by jpratesmoreira** [comment]
me passa seu email

**Comment by DanielFilippo** [comment]
daniel.filippolima@gmail.com

**Comment by carloscds** [comment]
@DanielFilippo Podemos fazer sim!

**Comment by DanielFilippo** [comment]
@carloscds, preciso ver como fazer aqui na empresa, eu estou morando fora do país, estou em Portugal, tenho o note da empresa que posso levar para casa, só que eu não tenho a senha do administrador, o chefe não passa, o VS que está aqui é o 2015, não consigo instalar nenhum outro por causa do administrador, eu vou conversar aqui ver se ele libera, porque é para o projeto.

**Comment by dannieljunior** [comment]
@carloscds Eu não sei em que pé está o projeto com relação aos boletos registrados via api on line, mas eu cheguei a fazer uma implementação do Bradesco, usando tipos genéricos como Rewquest e Response e injetando conforme o banco. Além disso criei uma classe de envio genérica abstrata para que fosse implementada para cada banco a usar API. Infelizmente eu deixei a empresa e a implementação ficou lá, porém eu tenho o conceito.

**Comment by rafd75** [comment]
@dannieljunior --- esse recurso iria ser muito legal para o projeto Boleto2Net ...

mas eu não sei nem por onde começar......  - Acho que na hora que alguém implementar um dos bancos, o resto vai na fila.... 

vou ficar de olho aqui.

**Comment by jpratesmoreira** [comment]
@rafd75 a vantagem de usar minha api é que vc implementa uma unica vez , nao precisando implementar para cada banco, pois cada cria sua api de forma diferente (uns usam rest, outros soap com autenticação oauth outros nao)

**Comment by rafd75** [comment]
Bom dia @jpratesmoreira , ...

Sim, entendi isso... Sem dúvida, não deixa de ser interessante.

O problema é que iriamos misturar uma solução de código aberto (Boleto2Net) com uma solução proprietária...

**Comment by CleberFreireSantos** [comment]
@jpratesmoreira bom dia, poderia confirmar seu email para conversarmos sobre essa API?

**Comment by jpratesmoreira** [comment]
é esse mesmo.


*Juliano Prates*
(31) 8897-4322


Em qua., 12 de ago. de 2020 às 10:19, CleberFreireSantos <
notifications@github.com> escreveu:

**Comment by lpaulods** [comment]
@jpratesmoreira, vc poderia me enviar a API do ITAU em ADVPL(help Facil)?

**Comment by leonardomarinadvpl** [comment]
Boa tarde, poderia compartilhar comigo API do ITAU em ADVPL?

leonardo-csp@hotmail.com
