### ISSUE TITLE
SICOOB - Código p/ Baixa/Devolução

### ISSUE THREAD

**Issue by lvitorbh** [BoletoNet/boleto2net#138]
Recebi uma nova versão do Documento de Layout do Banco Sicoob, onde o campo **Código p/ Baixa/Devolução** deveria ser preenchido apenas com zero.

38.3P | 224 | 224 | 001 | - | Num | Código   p/ Baixa/Devolução | Código para   Baixa/Devolução: "0"
-- | -- | -- | -- | -- | -- | -- | --

Segue o link do novo documento que estou baseando minhas informações: http://prodados.com/osg/anexo/1836.34245Layouts_para_troca_de_informacoes-14092018.xls

Olhando a classe **BancoSicoob.cs** ela possui o seguinte trecho de código para o CNAB240:

Método: 
`private string GerarDetalheSegmentoPRemessaCNAB240(Boleto boleto, ref int numeroRegistroGeral)`

Trecho:
```
switch (boleto.CodigoBaixaDevolucao)
                {
                    case TipoCodigoBaixaDevolucao.NaoBaixarNaoDevolver:
                        reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0224, 001, 0, 2, '0');
                        break;
                    case TipoCodigoBaixaDevolucao.BaixarDevolver:
                        reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0224, 001, 0, 1, '0');
                        break;
                    default:
                        reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0224, 001, 0, 0, '0');
                        break;
                }
```
Acredito que podemos alterar apenas para:
`reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0224, 001, 0, 0, '0');`

**Comment by rafd75** [comment]
@lvitorbh , bom dia... 

Tenho implantado o Sicoob em 2 clientes... ambos estão gerando com a informação "2" nessa posição.

Pior que não tenho o manual antigo, para saber se quando fiz o sicoob (acho que eu que implementei essa carteira no Boleto2Net) ...

Você chegou a mandar um arquivo com "2" e a homologação rejeitou?

De qualquer forma, concordo que o melhor é seguir o manual... Triste é esse monte de mudanças...

**Comment by lvitorbh** [comment]
@rafd75 tb tenho alguns clientes rodando e enviando com o código 2 em produção e nunca deram erro nenhum, mas fomos implantar em um novo cliente essa semana e enviamos uma remessa de teste para o banco para validarem e retornaram com esse "erro".

Outra coisa que eu estava fazendo e que nunca deu erro e no manual também fala é sobre as data de multa e juros.
Eu sempre colocava data de vencimento + 1 dia e o manual fala que é a própria data de vencimento.

Data da Multa | Data da Multa:   preencher com a Data de Vencimento do Título formato DDMMAAAA
-- | --

**Comment by rafd75** [comment]
bom...  então acho que o caminho é colocar o "0" mesmo...

já sobre a data da multa, eu (acho que)  sempre usei o próprio vencimento mesmo.
