### ISSUE TITLE
Retorno Boleto

### ISSUE THREAD

**Issue by mdantasgyn** [BoletoNet/boleto2net#143]
Bom dia, preciso muito de um exemplo de tratamento de retorno, pois nos arquivos de testes não tem implementado nenhum teste de retorno.

**Comment by rafd75** [comment]
@mdantasgyn , bom dia... 

```
Boletos boletos = new Boletos();
var arquivoRetorno = new ArquivoRetorno(boletos.Banco, (TipoArquivo)formatoArquivo);
using (var fileStream = new FileStream(nomeArquivo, FileMode.Open))
{
      boletos = arquivoRetorno.LerArquivoRetorno(fileStream);
}
```
Esse exemplo deve te ajudar... (retirei da classe Boleto2NetProxy)
