### ISSUE TITLE
Boleto Unicred

### ISSUE THREAD

**Issue by lvitorbh** [BoletoNet/boleto2net#144]
Pessoal alguém ja teve a necessidade de emitir boletos da Unicred?

**Comment by jeffersonjunglaus** [comment]
Amigo conseguiu implementar da UNICRED?

**Comment by gugaoliveira** [comment]
Eu tenho interesse de implementar, existe algum guia para isso? ou dica?

**Comment by rafd75** [comment]
Falando rapidamente aqui (e talvez seja uma oportunidade para documentarmos mais detalhadamente isso, para as próximas implementações)

1 - Criar a classe do BANCO.
2 - Criar a classe da CARTEIRA.
3 - Criar os testes unitários.

Para fazer o banco INTER, eu peguei o modelo do Bradesco, se não me engano, e dupliquei para INTER. Fiz o mesmo com a carteira. 
Fui ajustando (alterando) os campos de acordo com o manual... Com isso, Remessa e Retorno já estão funcionando.
Ainda não fiz a impressão, e faltam os testes (por isso não está disponível no projeto ainda).

O caminho é por ai.
