### ISSUE TITLE
Banco Brasil - 17/019

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boleto2net#145]
Bom dia,

Na wiki do projeto tem a seguinte instrução: 

>Carteiras Implementadas (Não foi homologada. Falta teste unitário)
>Banco do Brasil Carteira 11 (Variação 019)

Estou implementando para um cliente justamente esta carteira e nesta variação, o que posso fazer para ajudar vocês neste caso?

**Comment by rafd75** [comment]
@marcosgerene , bom dia.

Me parece, que o PR #142 tratou exatamente essa pendência...
Acho que o wiki está desatualizado.

Obs: Não fui eu que fiz os testes unitários. Não sei se a pessoa que fez, implementou apenas os testes considerando que a classe estava correta, ou se de fato, colocou em produção (entendo que fez a homologação com o suporte do BB) e depois fez os testes unitários.

Aconselho você abrir o ambiente de homologação no BB e validar os boletos emitidos para seu cliente.

OBs: Eu faço isso em todas as novas homologações aqui, independente da classe Boleto2Net ter o teste unitário implementado... 

Depois reporte aqui o que você fez... ok ?

**Comment by marcosgerene** [comment]
Eu enviei os arquivos para o banco homologar, são duas empresas emitentes de uma unica vez, vou retornar aqui na issue então se obtive sucesso.

Obrigado

**Comment by marcosgerene** [comment]
@rafd75 Implementação feita com sucesso!

**Comment by rafd75** [comment]
@marcosgerene legal!... 

Além dos arquivos, você chegou a homologar o boleto impresso também?

Caso negativo, imagino que esteja tudo correto, mas seria bom ficar de olho no primeiro título liquidado.

**Comment by marcosgerene** [comment]
@rafd75 não homologuei os boletos, mas mandei meu cliente gerar um de R$ 10,00 para ele e pagar. O boleto foi pago e o valor foi creditado na conta.

**Comment by marcosgerene** [comment]
@rafd75 rapaz, agora que vi relendo que tanto o wiki quanto o PR era da 11/019 e não da 17/019... o que homologuei e fiz o teste do boleto foi a 17/019 e não 11/019.

**Comment by rafd75** [comment]
Ah... então Banco do Brasil Carteira 11 (Variação 019) , apesar de ter os testes unitários (PR indicado), não é a que você (de fato) usou... 

Se não estou enganado, essa 17/019 é impressão pelo cedente. Enquanto a 11/019, emitida pelo banco...  (por isso não completei os testes... precisa pegar alguém em produção, enviar para o banco, e depois tentar gerar a segunda via pelo sistema e bater com o boleto do banco.) --- como meu cliente, na época, desistiu de usar a carteira, não consegui fazer o teste "de verdade"...

**Comment by marcosgerene** [comment]
@rafd75 no meu caso são só empresas de micro-pequeno-médio porte,o volume é pequeno, é mais vantajoso para eles enviar via e-mail os boletos pela segurança da entrega, provavelmente não vou usar essa carteira então
