### ISSUE TITLE
SICOOB - Problema no Trailler do Lote e do Arquivo

### ISSUE THREAD

**Issue by Fessini** [BoletoNet/boleto2net#146]
Pessoal estou com problema na homologação do arquivo de remessa, quando eu faço o teste retorna o seguinte problema como na imagem abaixo:

![image](https://user-images.githubusercontent.com/45390703/49095708-3678ec00-f250-11e8-8e6d-a825c58aef82.png)

Alguém já teve esse problema e pode me ajudar?

Abs,

**Comment by rafd75** [comment]
@Fessini , boa tarde...

Pelo que entendi, o problema está no trailler do "lote"... Se for isso mesmo, é gerado por essa função:

https://github.com/BoletoNet/boleto2net/blob/45210581f74faf7f821a04bc8785a73b376ffe74/Boleto2.Net/Banco/BancoSicoob.cs#L495

Me parece que não bate a posição da função, com a que está no seu relatório... 

Aqui, usamos SICOOB, mas não me lembro de ser 240... acho que só usamos aqui o layout 400... 

Se encontrar o problema, favor reportar..

**Comment by marcosgerene** [comment]
@rafd75 uso SICOOB 240 em produção aqui sem problemas.

**Comment by rafd75** [comment]
Bom... vamos esperar a resposta do @Fessini

**Comment by rafd75** [comment]
@Fessini 

Na minha versão, está assim:

`        private string GerarTrailerLoteRemessaCNAB240(ref int numeroRegistroGeral,
                                                                int numeroRegistroCobrancaSimples, decimal valorCobrancaSimples,
                                                                int numeroRegistroCobrancaVinculada, decimal valorCobrancaVinculada,
                                                                int numeroRegistroCobrancaCaucionada, decimal valorCobrancaCaucionada,
                                                                int numeroRegistroCobrancaDescontada, decimal valorCobrancaDescontada)
        {
            try
            {
                // O número de registros no lote é igual ao número de registros gerados + 2 (header e trailler do lote)
                int numeroRegistrosNoLote = numeroRegistroGeral + 2;
                TRegistroEDI reg = new TRegistroEDI();
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0001, 003, 0, "756", '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0004, 004, 0, "0001", '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0008, 001, 0, "5", '0');
                reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0009, 009, 0, Empty, ' ');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0018, 006, 0, numeroRegistrosNoLote, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0024, 006, 0, numeroRegistroCobrancaSimples, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0030, 015, 2, valorCobrancaSimples, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0045, 006, 0, numeroRegistroCobrancaVinculada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0051, 015, 2, valorCobrancaVinculada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0066, 006, 0, numeroRegistroCobrancaCaucionada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0072, 015, 2, valorCobrancaCaucionada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0087, 006, 0, numeroRegistroCobrancaDescontada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0093, 015, 2, valorCobrancaDescontada, '0');
                reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0108, 008, 0, Empty, ' ');
                reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0116, 125, 0, Empty, ' ');
                reg.CodificarLinha();
                return reg.LinhaRegistro;
            }
            catch (Exception ex)
            {
                throw new Exception("Erro ao gerar HEADER do lote no arquivo de remessa do CNAB400.", ex);
            }
        }`

Como ficou a sua função (inteira) ?

**Comment by marcosgerene** [comment]
@Fessini e @rafd75 

Emito boletos para controle interno da minha empresa no SICOOB, volume pequeno, 25~35/mês e nunca tive problemas na emissão, se existia uma falha, nunca foi reclamada pelo SICOOB.

Aguardo o PR para tentar entender as alterações

**Comment by Fessini** [comment]
Função Inteira lembrando que a configuração é do layout CNAB240:

private string GerarTrailerLoteRemessaCNAB240(ref int numeroRegistroGeral,
                                                                int numeroRegistroCobrancaSimples, decimal valorCobrancaSimples,
                                                                int numeroRegistroCobrancaVinculada, decimal valorCobrancaVinculada,
                                                                int numeroRegistroCobrancaCaucionada, decimal valorCobrancaCaucionada,
                                                                int numeroRegistroCobrancaDescontada, decimal valorCobrancaDescontada)
        {
            try
            {
                // O número de registros no lote é igual ao número de registros gerados + 2 (header e trailler do lote)
                int numeroRegistrosNoLote = numeroRegistroGeral + 2;
                TRegistroEDI reg = new TRegistroEDI();
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0001, 003, 0, "756", '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0004, 004, 0, "0001", '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0008, 001, 0, "5", '0');
                reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0009, 009, 0, Empty, ' ');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0018, 006, 0, numeroRegistrosNoLote, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0024, 006, 0, numeroRegistroCobrancaSimples, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0030, 015, 2, valorCobrancaSimples, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0047, 006, 0, numeroRegistroCobrancaVinculada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0053, 015, 2, valorCobrancaVinculada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0070, 006, 0, numeroRegistroCobrancaCaucionada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0076, 015, 2, valorCobrancaCaucionada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0093, 006, 0, numeroRegistroCobrancaDescontada, '0');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0099, 015, 2, valorCobrancaDescontada, '0');
                reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0116, 008, 0, Empty, ' ');
                reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0116, 125, 0, Empty, ' ');


                //Códigos sem minha alteração
                //reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0045, 006, 0, numeroRegistroCobrancaVinculada, '0');
                //reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0051, 015, 2, valorCobrancaVinculada, '0');
                //reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0066, 006, 0, numeroRegistroCobrancaCaucionada, '0');
                //reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0072, 015, 2, valorCobrancaCaucionada, '0');
                //reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0087, 006, 0, numeroRegistroCobrancaDescontada, '0');
                //reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0093, 015, 2, valorCobrancaDescontada, '0');
                //reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0108, 008, 0, Empty, ' ');
                //reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0116, 125, 0, Empty, ' ');
                reg.CodificarLinha();
                return reg.LinhaRegistro;
            }
            catch (Exception ex)
            {
                throw new Exception("Erro ao gerar HEADER do lote no arquivo de remessa do CNAB400.", ex);
            }
        }

**Comment by marcosgerene** [comment]
@Fessini acredito que o melhor seja abrir um PR para que os mantenedores possam analisar as alterações e aceitar/recusar conforme for.

**Comment by rafd75** [comment]
@Fessini bom dia... consultei o meu manual do SICOOB aqui (Versão atualizada em 15/12/2017) e realmente consta esses totais...

@marcosgerene - Você ainda tem o manual do Sicoob? ou vc já pegou pronta essa rotina aqui do grupo?   Seria interessante solicitar um manual atualizado (para seu gerente) e validar novamente o seu arquivo...

Estamos todos falando do SICOOB mesmo né? (Banco 756)

**Comment by marcosgerene** [comment]
@rafd75 Não, sequer precisei do manual... rs

Eu implementei com o Boleto2Net e mandei uma remessa de testes e esta foi aceita, desde então veio emitindo, já uso o Sicoob (sim, 756) a algo em torno de um ano e nunca tive problemas, por isso estou estranhando...

**Comment by rafd75** [comment]
@marcosgerene - você consegue pegar um arquivo que você gera, e mandar para validação?

Teoricamente é para dar erro... 

Talvez, não faça diferença esse trailler com os totais... ou seja, na homologação, o erro de totalizar é considerado, mas em produção, ele é ignorado... só pode ser isso.

De acordo com o manual, o código do @Fessini está correto. Se for o caso, eu faço o PR por aqui.

**Comment by Fessini** [comment]
@rafd75 - eu tenho o arquivo mas não está deixando anexar aqui.

**Comment by Fessini** [comment]
@rafd75 - Segui link do arquivo de layout
[Arquivo Layout](https://mega.nz/#!Y5MW2CQT!PBENyFueqFiOIW1F6Z_TNRpNs8w3-59CJXXpGPdFnik)

**Comment by rafd75** [comment]
O layout que tem aqui, bate com o seu ( @Fessini )
