### ISSUE TITLE
Dúvidas sobre Boletonet2

### ISSUE THREAD

**Issue by Westfallx** [BoletoNet/boleto2net#147]
Esse projeto aqui é para o .netCore?

**Comment by carloscds** [comment]
@Westfallx Eu migrei o projeto todo para .Net Core, mas ainda não fizemos o merge aqui porque o componente de PDF para .Net (NReco) é pago. Mas tá convertido: https://github.com/carloscds/boleto2net/tree/dotnetcore

**Comment by Westfallx** [comment]
@carloscds, Mas para fazer o pdf vcs tem algum componente em mente.. ou só precisa pagar NReco pago e sair usando?
Outra dúvida.. mas a parte que ele gera o html ainda funciona normalmente?
É que fiquei um pouco afastado no .net e estou pensando em migrar um projeto para .Netcore, se o componente para gerar o boleto em html estiver ok.. já vai ser uma maravilha

**Comment by marcosgerene** [comment]
@Westfallx existe uma versão do iTextSharp para .NetCore que é open Source e converte HTML para PDF, tem que ver se ele funcionaria de forma correta no projeto.

Existe hoje em dia também o FastReports que é uma baita ferramenta, também em .net core, e recentemente se tornou OpenSource, mas nesse caso ideia seria fazer uma nova impressão dentro deles e adicionar uma nova dependência, não sei se existe a opção de converter HTML para PDF lá.

Segue:
https://github.com/VahidN/iTextSharp.LGPLv2.Core
https://github.com/FastReports/FastReport

**Comment by carloscds** [comment]
@marcosgerene Baixa o código do meu repositorio e faz um teste.

**Comment by carloscds** [comment]
@Westfallx O @marcosgerene está sugerindo um componente.

**Comment by marcosgerene** [comment]
@carloscds 
>@marcosgerene Baixa o código do meu repositorio e faz um teste.

Vou testar com o iTextSharp e te dou um feedback

**Comment by carloscds** [comment]
@marcosgerene Este é o problema.
