### ISSUE TITLE
Arquivo Remessa CNAB 240 - Segmento P - Código do Juros de Mora

### ISSUE THREAD

**Issue by brunotrbr** [BoletoNet/boleto2net#148]
Olá, boa tarde,

Estou com uma dúvida. Nos métodos *GerarDetalheSegmentoPxxx* (/Banco/BancoBrasil.cs, por exemplo), quando o arquivo for *CNAB240*, na parte relacionada a cobrança de juros, é verificado somente se o tipo de juros cobrado é Diário (valor diário) ou Isento, mas não analisa se é cobrado um valor percentual mensal.

De acordo com o layout atual da Febraban [Versão 10.5](https://cmsportal.febraban.org.br/Arquivos/documentos/PDF/Layout%20padrao%20CNAB240%20%20V%2010%2005%20-%2005_11_18.pdf), o campo **Codigo Juros de Mora** (C018, na página 149), pode ser Valor por Dia(1), Taxa Mensal (2) ou Isento (3).

Não deveria ter uma validação verificando o Código de Juros de Mora (um novo campo no /Boleto/Boleto.cs ), uma taxa mensal de juros de mora (mais um novo campo no /Boleto/Boleto.cs) caso seja taxa mensal, e 3 possíveis casos no método *GerarDetalheSegmentoPxxx*, ao invés da forma que está atualmente?

Enquanto isso fiz um fork no projeto, alterei conforme minha sugestão acima e enviei o arquivo para homologação junto ao Banco do Brasil.

Caso seja homologado junto ao banco, faço o pull request?

Abraços
Bruno Bragança Mendes

**Cenário Atual**
![juros_boleto2net](https://user-images.githubusercontent.com/13382484/49466042-3051b500-f7e6-11e8-95d0-2f9c0b47bbf9.JPG)

**Documentação Febraban**
![juros_febraban](https://user-images.githubusercontent.com/13382484/49466044-30ea4b80-f7e6-11e8-967c-6d9f4c5a912c.JPG)

**Comment by brbmendes** [comment]
@rafd75 , bom dia.

Eu também não sei se todos os bancos implementam isso, mas achei que sim por se tratar de um segmento obrigatório e um padrão definido pela Febraban.

O TaxaJurosMensal seria adicionado no Boleto, correto? Poderíamos definir um valor padrão para ele (0,00) e fazer a validação dele antes dos demais, pois se não for explicitamente alterado ele não entra nesse caso nunca (ver exemplo abaixo).

Com relação a validação, eu teria como ver se seria homologado pelo Banco do Brasil, por ser o banco que o cliente está usando hoje. Eu acredito que não teria problema com os demais bancos, por se tratar de um padrão de arquivo, mas isso é suposição minha. Não tenho experiência o suficiente com arquivos de remessa pra afirmar que seria válido aos demais bancos.

Qual a sua sugestão? 

**Exemplo:**
![sugestao_bancos](https://user-images.githubusercontent.com/13382484/49507915-a39c0b00-f868-11e8-9c19-ed2637a1eeec.JPG)
