### ISSUE TITLE
Motivo da ocorrencia

### ISSUE THREAD

**Issue by henrique25t** [BoletoNet/boleto2net#149]
Olá. Quando eu leio o arquivo de retorno, ele me retorna uma lista de boletos. Eu não consegui achar em qual campo do Boleto que eu tenho o codigo do motivo da ocorrencia. Perdão se eu estiver falando besteira, mas seria possível alguem me iluminar nessa.

**Comment by marcosgerene** [comment]
```
var retorno = new ArquivoRetorno(banco, Conta.LayoutRemessa == LayoutRemessa.Cnab240 ? TipoArquivo.CNAB240 : TipoArquivo.CNAB400);
                var boletos = retorno.LerArquivoRetorno(stream);

foreach (var boleto in boletos)
{
   // testar se o boleto.CodigoOcorrencia é um código de baixa, no meu caso, código 6.
}


```

**Comment by henrique25t** [comment]
Ola amigo. Obrigado por responder. 
Essa parte ta ok aqui até o momento.
O meu problema é com o "Motivo da ocorrencia" que é diferente da "Ocorrencia". O motivo também tem um código assim como a ocorrencia.

No pdf do layout cnab da febraban vc vai encontrar os dois.
C044 - Tipo Movimento Remessa - que significa a Ocorrencia.
C047 - Motivo da Ocorrencia - que é o que eu quero obter
Se vc der um ctrl + F no layout e colocar esses codigos, tu vai ver que os codigos são diferentes.

Eu quero o motivo para mostrar na tela para o cliente.

**Comment by marcosgerene** [comment]
```
boleto.DescricaoOcorrencia
```

**Comment by rafd75** [comment]
@henrique25t , bom dia... 

Ao ler o arquivo retorno e preencher a coleção de boleto, as 3 propriedades abaixo são preenchidas:

```
//Identificação de Ocorrência
boleto.CodigoOcorrencia = registro.Substring(108, 2);
boleto.DescricaoOcorrencia = OcorrenciasCnab400(boleto.CodigoOcorrencia);
boleto.CodigoOcorrenciaAuxiliar = "";

```

CodigoOcorrencia é o código do que aconteceu na compensação: (e não a ocorrência enviada no remessa)... por exemplo o código 06... Nesse caso, a descrição dessa ocorrência estará na propriedade DescricaoOcorrencia (Ex: "Liquidação")... 

Existe ainda uma terceira propriedade chamada CodigoOcorrenciaAuxiliar que, em alguns casos, também é preenchida... Por exemplo, se um título foi rejeitado, no CodigoOcorrencia=03, DescricaoOcorrencia="ENTRADA REJEITADA" e CodigoOcorrenciaAuxiliar pode conter, por exemplo, alguns códigos que identificamo o motivo da rejeição (Ex: Vencimento inválido, ou CEP errado)... 

é isso.

**Comment by henrique25t** [comment]
É isso mesmo. Muitíssimo obrigado por me esclarecer. Agradecido.

**Comment by Kelcyo** [comment]
> @henrique25t , bom dia...
> 
> Ao ler o arquivo retorno e preencher a coleção de boleto, as 3 propriedades abaixo são preenchidas:
> 
> ```
> //Identificação de Ocorrência
> boleto.CodigoOcorrencia = registro.Substring(108, 2);
> boleto.DescricaoOcorrencia = OcorrenciasCnab400(boleto.CodigoOcorrencia);
> boleto.CodigoOcorrenciaAuxiliar = "";
> ```
> 
> CodigoOcorrencia é o código do que aconteceu na compensação: (e não a ocorrência enviada no remessa)... por exemplo o código 06... Nesse caso, a descrição dessa ocorrência estará na propriedade DescricaoOcorrencia (Ex: "Liquidação")...
> 
> Existe ainda uma terceira propriedade chamada CodigoOcorrenciaAuxiliar que, em alguns casos, também é preenchida... Por exemplo, se um título foi rejeitado, no CodigoOcorrencia=03, DescricaoOcorrencia="ENTRADA REJEITADA" e CodigoOcorrenciaAuxiliar pode conter, por exemplo, alguns códigos que identificamo o motivo da rejeição (Ex: Vencimento inválido, ou CEP errado)...
> 
> é isso.

@rafd75 não consigo encontrar o método "OcorrenciasCnab400(boleto.CodigoOcorrencia)" ou "OcorrenciasCnab240(boleto.CodigoOcorrencia)", estes devem ser implementados ou já existem?

**Comment by rafd75** [comment]
Já existem... 

No caso do 240, pelo menos até onde eu verifiquei, segue um padrão, então sempre utiliza essa função estática:
https://github.com/BoletoNet/boleto2net/blob/07b82d0d4a45038cf298638894ec833fa55bd433/Boleto2.Net/Util/Cnab.cs#L12

Já no 400, cada banco resolveu do seu jeito. Então, procure pelo método na classe de cada banco, como por exemplo:

https://github.com/BoletoNet/boleto2net/blob/07b82d0d4a45038cf298638894ec833fa55bd433/Boleto2.Net/Banco/BancoBrasil.cs#L358

**Comment by Kelcyo** [comment]
> Já existem...
> 
> No caso do 240, pelo menos até onde eu verifiquei, segue um padrão, então sempre utiliza essa função estática:
> https://github.com/BoletoNet/boleto2net/blob/07b82d0d4a45038cf298638894ec833fa55bd433/Boleto2.Net/Util/Cnab.cs#L12
> 
> Já no 400, cada banco resolveu do seu jeito. Então, procure pelo método na classe de cada banco, como por exemplo:
> 
> https://github.com/BoletoNet/boleto2net/blob/07b82d0d4a45038cf298638894ec833fa55bd433/Boleto2.Net/Banco/BancoBrasil.cs#L358

Obrigado...
