### ISSUE TITLE
Hierarquia dos Bancos

### ISSUE THREAD

**Issue by alexDevBR** [BoletoNet/boleto2net#15]
Primeiramente parabéns pela iniciativa. Já faz muito tempo que achava que o Boleto.Net precisava ser refeito, mas só descobri esse projeto hoje.

A hierarquia dos Bancos no projeto antigo estava meio confusa, tanto que eu fiz um PR para dar uma melhorada, em BoletoNet/boletonet#526.
Aqui já está bem melhor, mas queria dar uma sugestão:
A classe `Banco` está funcionando como um proxy para uma instância `_banco`.
Talvez seria melhor se ela fosse uma classe base para os outros bancos. Ela poderia ter uma função estática assim:

```csharp
static public Banco Instancia(int codigo)
{
    switch (codigo)
    {
        case 001: return new BancoBrasil();
        case 033: return new BancoSantander();
        case 104: return new BancoCaixa();
        case 237: return new BancoBradesco();
        case 341: return new BancoItau();
        case 756: return new BancoSicoob();
        default: throw new Exception($"Nenhum banco encontrado para o codigo {codigo}");
    }
}
```
Ela conteria tudo que é comum a todos os bancos, como por exemplo `Cedente`, `Codigo`, `Nome` etc., e cada um faria override e acrescentaria conforme necessário.

Se acharem interessante eu posso fazer a refatoração e gerar um PR. O que acham?

**Comment by carloscds** [comment]
@alexDevBR Se for seguir nesta linha, melhor fazer com uma factory, pq senao vai ter que ficar mudando este arquivo.

**Comment by alexDevBR** [comment]
A função `Instancia()` pode ser considerada um [Factory Method](https://stackoverflow.com/a/13029726/733760). Para cada banco será uma linha nova nessa função. Do jeito que está agora, para cada banco novo já tem que acrescentar uma linha no dicionário então não vejo muita desvantagem. Você acha melhor criar uma classe factory?

**Comment by carloscds** [comment]
@alexDevBR O ideal seria usar injeção de dependencia.

**Comment by alexDevBR** [comment]
Sim.. Pode ser adicionado mais para frente. O que você acha? Vale a pena tentar esse caminho? Eu posso tentar fazer isso essa semana e gero um PR, aí vc ve o q vc acha..

**Comment by carloscds** [comment]
@alexDevBR Manda ver!

**Comment by AlbertoMonteiro** [comment]
Infelizmente não tive como participar da conversa em tempo hábil, mas essa proposta ai, e o PR aceito, desfez todos os ajustes de melhoria de performance e desacoplamento que eu tinha implementado.

**Comment by alexDevBR** [comment]
Olá @AlbertoMonteiro,

Desculpe, não tive intenção de atrapalhar. Por isso criei o issue, para sugerir minha idéia e ver o que vocês achavam. Como ninguém foi contra achei que tudo bem.
A estrutura do `Banco` sempre me incomodou um pouco, tendo uma instância em `_banco` e passando todas as chamadas para essa instância. É difícil de debugar, pois em vez de ter uma exceção com um stack trace, acaba tendo várias exceções uma dentro da outra, cada uma com um pedaço do stack trace. Fora que cada chamada de função vira duas, pois chamamos Banco.xxxx que chama _banco.xxxx.
Enfim, se você estiver interessado podemos discutir os méritos de cada implementação e talvez chegar em uma que seja melhor que as duas.

Abraço,
Alexandre Weinberger

**Comment by alexDevBR** [comment]
@AlbertoMonteiro: 

> Sobre o _banco, não faz sentido existir varias instancias de um mesmo banco no sistema, elas podem ser singleton, e a classe Banco, faz o controle disso

Concordo que não há necessidade de criar várias instâncias, porém é preciso tomar cuidado pois no projeto antigo às vezes as pessoas adicionavam propriedades ao banco que eram referentes a um arquivo que estava sendo gerado. De qualquer maneira eu poderia alterar no meu codigo a função `NovaInstancia()` para retornar essas instâncias singleton. Renomearia para `Instancia()`.

> Sobre as duas chamadas, isso em runtime, provavelmente vai ser "inlineado" pelo JIT, então vai ficar sendo só 1 método mesmo.

Não é a performance da chamada que incomoda. É ruim para debugar, e é confuso. Cada vez que vai fazer uma chamada precisa entrar no Banco.xxxx para depois entrar no _banco.xxxx. Nos eventos OnLinhaGerada/OnLinhaLida cada chamada vira 4 pois a instância interna chama OnLinhaGerada que chama um evento que chama OnLinhaGerada na externa que chama o evento.
É muito confuso, e não consigo ver a vantagem.
Acho muito mais claro usar uma herança simples, onde as funções comuns estão na classe base e as específicas em overrides nas classes filhas.
Sobre inlining, só testando para saber, no x86, x64, mono etc.. 

> Bom, o ideal é que não fosse necessário do StackTrace, por isso que existe as exceções tipadas

Quando aparece uma exceção num log, é fundamental um stack trace para sabermos onde ocorreu um erro e qual foram as funções chamadas que causaram a exceção. A Exceção sendo tipada não ajuda com isso.

Aguardo suas opiniões a respeito.

**Comment by carloscds** [comment]
@AlbertoMonteiro @alexDevBR Este tipo de discussão, neste nível técnico, é o grande legal de projetos open source. Show de bola pessoal! Precisamos engajar mais pessoas :-)

**Comment by AlbertoMonteiro** [comment]
show @carloscds!!!

@alexDevBR Fiz um PR para irmos discutindo e refatorando.

Sobre o problema que você comentou de ter duas chamadas de métodos, no PR isso já foi resolvido, e também foi mantido a instancia de cada banco em um singleton além de evitar herança(que acaba engessando o código).

> Quando aparece uma exceção num log, é fundamental um stack trace para sabermos onde ocorreu um erro e qual foram as funções chamadas que causaram a exceção. A Exceção sendo tipada não ajuda com isso.

Sobre as exceptions, no PR acabou que foram removidas algumas exceções especificas do projeto. A exceção tipada não resolve isso, mas todas as exceções do boletonet que fazem geram uma nova stacktrace, elas envolopam a exceção anterior, e essa, por sua vez, pode ser obtida através do método `GetBaseException()`, nele tendo o stacktrace do código interno do projeto.

Exemplo:

```csharp
public string GerarDetalheRemessa(TipoArquivo tipoArquivo, Boleto boleto, ref int numeroRegistro)
{
    try
    {
        string detalhe = Empty, strline = Empty;
        switch (tipoArquivo)
        {
            case TipoArquivo.CNAB400:
                detalhe += GerarDetalheRemessaCNAB400Registro1(boleto, ref numeroRegistro);
                strline = GerarDetalheRemessaCNAB400Registro2(boleto, ref numeroRegistro);
                if (!IsNullOrWhiteSpace(strline))
                {
                    detalhe += Environment.NewLine;
                    detalhe += strline;
                }
                break;
            default:
                throw new Exception("Tipo de arquivo inexistente.");
        }
        return detalhe;
    }
    catch (Exception ex)
    {
        throw Boleto2NetException.ErroAoGerarRegistroDetalheDoArquivoRemessa(ex);
    }
}
```

Vamos supor que o método `GerarDetalheRemessaCNAB400Registro1` lançou um `NullReferenceException`, o catch do `GerarDetalheRemessa` envelopou a `NullReferenceException` em outra exceção, com um novo StackTrace.

No seu método do seu projeto no qual você chama o `GerarDetalheRemessa` no catch dele, seria algo assim:

```csharp
public string MetodoDoMeuProjeto()
{
    try
    {
        //Outras linhas         
        bancoDoBrasil.GerarDetalheRemessa(parametros);
        //Outras linhas 
    }
    catch (Boleto2NetException ex)
    {
        ex.GetBaseException(); //Aqui você vai ter a NullReference
    }
}
```

No catch do método acima, como descrito no comentário, o método `GetBaseException` vai retornar a `NullReferenceException` com o StackTrace original.

Reavaliando as mensagens das exceções que envelopam a exceção original, não vejo que elas trazem informação tão útil para o usuário da API do boletonet, então, acho que do jeito que está, não tem problema, porém, o fato de tipar a exceção, eu poderia ter catchs personalizados no meu código, que me possibilitariam tratar o erro de forma diferente, pois eu saberia que aquele erro veio do BoletoNet, e não do meu código.

Obrigado pela discussão!

Aguardando seu retorno, se você quiser conversar no PR, fique a vontade!!

**Comment by alexDevBR** [comment]
Olá Alberto ,
 
Vou tentar baixar o seu commit hoje para ver com cuidado porque pelo github fica difícil entender. Eu achei interessante o seu comentário: 

> além de evitar herança(que acaba engessando o código).

Nunca tinha ouvido falar que herança é algo ruim. Dei uma pesquisada e achei [isso aqui](http://www.dsc.ufcg.edu.br/~jacques/cursos/map/html/pat/herancavscomposicao.htm) que diz que há casos onde é melhor usar composição do que herança. Ele fala algo muito parecido com as [respostas que eu dei para uma pergunta muito parecida no stackoverflow](https://stackoverflow.com/a/11759272/733760), então não posso discordar (apesar que em um ou outro ponto eu discordo dele).
Era a isso que vc estava se referindo?

Se sim, a pergunta é se a relação entre Banco->BancoItau é a mesma que Pessoa->Passageiro, por exemplo.
Uma `Pessoa` pode assumir a função de `Passageiro`, depois a de `Agente`, etc.
Já um `Banco` não assume a função de `BancoItau`. Faz muito mais sentido dizer que `BancoItau` é um caso específico de `Banco` do que dizer que `Passageiro` é um caso específico de `Pessoa`.
Talvez neste caso não seja necessário evitar herança.

Sobre as exceções vou ver depois porque estou com fome agora!
Abs.!!

**Comment by AlbertoMonteiro** [comment]
Fala @alexDevBR!!

Herança, como diz no artigo, traz um acoplamento muito forte, e eu tenho muito medo de acoplamento forte, então, sempre que posso tento fugir dele.

Fico no aguardo da sua revisão!

**Comment by alexDevBR** [comment]
Olá Alberto,

Dei uma olhada no código e já ficou bem mais simples. Gostei. Ainda acho uma pena ter tanto código duplicado entre os bancos.. não precisa ter medo de usar herança! Mas já ficou bem melhor. Eu vou manter o fork para ir fazendo melhorias, pode ser? Se quiserem dar uma olhada estão bem vindos.

Abs!

**Comment by AlbertoMonteiro** [comment]
Blz @alexDevBR, que bom que você gostou. Dei uma olhada no seu fork, mas não identifiquei o branch que você está trabalhando, pelo que vi você ainda não atualizou com as últimos commits do master.
