### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by joaopelizari** [BoletoNet/boleto2net#150]
Pessoal, alguém pode me indicar como deixo de gerar a instrução de impressão e o recibo do pagador? Preciso imprimir apenas o boleto. Grato.

**Comment by rafd75** [comment]
@joaoluizsouza , boa noite... 

Vou colocar por cima aqui (estou sem tempo), mas acho que vai te ajudar a resolver isso... 

A Classe BoletoBancario tem várias propriedades que controla o que será ou não impresso... ex:
BoletoBancario.OcultarReciboSacado = true;

outras propriedades: OcultarInstrucoes / MostrarComprovanteEntrega / MostrarComprovanteEntregaLivre ,... etc.

Obs: não é a classe BOLETO, é a classe BOLETOBANCARIO - ok?

https://github.com/BoletoNet/boleto2net/blob/45210581f74faf7f821a04bc8785a73b376ffe74/Boleto2.Net/BoletoImpressao/BoletoBancario.cs#L96

abs
