### ISSUE TITLE
Especie de Documento

### ISSUE THREAD

**Issue by joaopelizari** [BoletoNet/boleto2net#152]
Boa tarde a todos. Qual a forma correta de acessar a especie do documento se tenho a literal (por exemplo DM) dentro de uma variável?

Grato.

**Comment by rafd75** [comment]
@joaopelizari , boa tarde.

Veja se esse link ajuda: https://stackoverflow.com/questions/16100/how-should-i-convert-a-string-to-an-enum-in-c

**Comment by joaopelizari** [comment]
No vb.net ficou asssim....


	(especie_docto) = "DM"

    Dim especDocEnum As TipoEspecieDocumento = ParseEnum(Of TipoEspecieDocumento)(especie_docto)

	***  especDocEnum fica com valor 2

    Public Shared Function ParseEnum(Of T)(ByVal value As String) As T
        Return CType([Enum].Parse(GetType(T), value, True), T)
    End Function
