### ISSUE TITLE
Adicionar mais de um lote no mesmo arquivo

### ISSUE THREAD

**Issue by Kelcyo** [BoletoNet/boleto2net#155]
Olá,
Alguém pode me informar como adiciono vários lotes no mesmo arquivo de remessa?
Gostaria de gerar um lote só com baixas e outro com inclusão, todos em apenas um arquivo.
Se alguém poder ajudar, solicito informar o código.

**Comment by rafd75** [comment]
@Kelcyo  

> Qual a razão de ser feito assim? Tem alguma diferença na prática, ou é apenas por questão de organização mesmo?

**Comment by Kelcyo** [comment]
@rafd75 
Para separação de boletos para baixa, para inclusão e etc..

**Comment by rafd75** [comment]
Entendi... mas é para organização interna isso?

ou é uma limitação do layout mesmo? ... cada lote, só 1 tipo de operação?

**Comment by Kelcyo** [comment]
Apenas para organização, facilita no manuseio...

**Comment by rafd75** [comment]
Entendi...

Teria que alterar algumas coisas no projeto para ele entender mais de um lote...

Não tenho certeza, mas acho que nem o BoletoNet (versão 1) tem isso... Pq eu usei a versão dele para gerar a base do Boleto2Net... e não me recordo de ter "tirado" essa funcionalidade...

**Comment by Kelcyo** [comment]
Beleza, fica como uma opção de melhoria.. Obrigado
Hoje minha atenção esta no [Manutenção utilizando WEBSERVICE](https://github.com/BoletoNet/boleto2net/issues/165)
