### ISSUE TITLE
Pra que serve o RegistroArquivoRetorno

### ISSUE THREAD

**Issue by evertonbatini** [BoletoNet/boleto2net#158]
Com qual informação do retorno é preenchido esse campo?

**Comment by rafd75** [comment]
@evertonbatini , bom dia.

Contém a linha completa (com 240 ou 400 posições) do arquivo retorno referente ao boleto que carregou na coleção.

Em alguns casos, pode ter mais de 1 linha por boleto, se o layout contemplar dessa forma.

Teoricamente, você só irá utilizar essa propriedade, se algum banco implementar alguma informação que não está prevista na classe boleto... Nesse caso, você teria que tratar qual banco, e qual a posição no arquivo retorno (fazer um Substring dentro dessa string para capturar o que deseja.)

**Comment by evertonbatini** [comment]
Ah sim, legal!

Já fica ai registrado pra quem procurar depois.

Valeu!
