### ISSUE TITLE
Descrição do campo codigoOcorrenciaAuxiliar

### ISSUE THREAD

**Issue by evertonbatini** [BoletoNet/boleto2net#159]
Bom dia, quando retorna uma 03 - Entrada Rejeitada, no codigoOcorrenciaAuxiliar eu tenho o motivo da rejeição, eu preciso tratar esse código pra descobrir a descrição do problema, ou o boleto2net tem essa descrição em algum lugar?

**Comment by rafd75** [comment]
@evertonbatini , bom dia... 

Não tem essa descrição não... Dei uma olhada no código, e a propriedade "DescricaoOcorrencia" se refere ao significado da "CodigoOcorrencia"

A solução seria criar a propriedade "DescricaoOcorrenciaAuxiliar" (na classe Boleto.cs) e depois implementar isso na classe de cada um dos bancos...

Levar em conta que alguns bancos retornam mais de uma ocorrência auxiliar, e nesse caso, todas as ocorrências (descrições) estariam na mesma  "DescricaoOcorrenciaAuxiliar" (assim como já ocorre de ter mais de um código na propriedade "CodigoOcorrenciaAuxiliar"

**Comment by evertonbatini** [comment]
Entendi, obrigado!
