### ISSUE TITLE
Boleto Cortando na direita

### ISSUE THREAD

**Issue by evertonbatini** [BoletoNet/boleto2net#160]
Bom dia,

Estou tendo um problema na visualização do boleto, está cortando na direita conforme imagem anexo

Estou fazendo da seguinte forma:

```c#
var bb = new BoletoBancario();
bb.Boleto = emitir.novoBoleto;

bb.GeraImagemCodigoBarras(emitir.novoBoleto);

bb.MostrarCodigoCarteira = true;
bb.GerarArquivoRemessa = true;
bb.ExibirDemonstrativo = true;
bb.MostrarEnderecoCedente = true;
bb.MostrarComprovanteEntrega = false;

webBrowser1.DocumentText = bb.MontaHtmlEmbedded(false, true);
```

Tem algum ajuste no tamanho do webBrowser ou algo assim? 

Ou a forma de visualizar é essa mesmo? Parece que está cortando na direita

![boleto cortando](https://user-images.githubusercontent.com/46816210/52787850-5e554000-3046-11e9-8758-5624f06b62ac.JPG)

**Comment by rafd75** [comment]
@evertonbatini , bom dia.

Nunca tinha reparado isso, mas está ocorrendo aqui também...
Vou dar uma olhada...

**Comment by evertonbatini** [comment]
Tranquilo

**Comment by rafd75** [comment]
Feito ... #167

**Comment by evertonbatini** [comment]
Como faço pra pegar essa atualização?

**Comment by rafd75** [comment]
@evertonbatini bom dia.

Você "clonou" o projeto aqui, ou baixou o ZIP? Se baixou o ZIP, acredito que se baixar novamente, vai estar atualizado já.

ou ainda, referenciou pelo NUGET? Se foi pelo NUGET, não sei se a versão já está atualizada lá.

**Comment by evertonbatini** [comment]
Utilizo pelo NuGet, está na versão 2.1.0.305, e mostra que é a última disponível

**Comment by carloscds** [comment]
@evertonbatini A ultima versao é de 18 dias atras.

**Comment by evertonbatini** [comment]
É estou com essa versão mesmo, acredito que precise de algo pra entrar a alteração e gerar uma nova versão

**Comment by carloscds** [comment]
@evertonbatini Estamos gerando uma versao a cada 30 dias. MAs você pod pegar a versao gerada no ultimo build. Eu coloquei o link no arquivo readme: https://github.com/BoletoNet/boleto2net/blob/master/README.md

**Comment by evertonbatini** [comment]
Ah sim, tudo bem, obrigado
