### ISSUE TITLE
Mensagem "Pagável em qualquer banco" para todos os bancos

### ISSUE THREAD

**Issue by rafd75** [BoletoNet/boleto2net#163]
Bom dia pessoal...

Por favor, respondam com sua opinião a respeito! ... 

Estou homologando um novo cliente no B.Brasil, e veio uma critica sobre a mensagem que aparece no topo do boleto, indicando o local de pagamento do boleto.

Até então, (BB) era "PAGÁVEL EM QUALQUER BANCO ATÉ O VENCIMENTO. APÓS, ATUALIZE O BOLETO NO SITE BB.COM.BR"   -   E a critica disse para alterar para "PAGÁVEL EM QUALQUER BANCO"

Já fiz a alteração aqui (na classe BancoBrasil.cs) ... mas será que não seria o caso de adequar a todos os outros bancos? Caso positivo, eu já altero todos, e faço o update aqui.... 

O que acham?

**Comment by rafd75** [comment]
Para o Banco do Brasil já está disponível -> #164 

Vou aguardar as respostas para -se for o caso - alterar os demais bancos...

**Comment by evertonbatini** [comment]
Após essa mudança que teve, da integração entre os bancos, acredito que faz sentido sim essa nova mensagem, pois mesmo após vencido, os pagamentos estão sendo aceitos em qualquer banco.

**Comment by evertonbatini** [comment]
Bradesco solicitou essa informação

“Pagável preferencialmente na Rede Bradesco ou Bradesco Expresso”.

**Comment by rafd75** [comment]
@evertonbatini boa tarde!

Acabei de receber, do Bradesco, a mesma solicitação... Já vou ajustar no projeto.

Em resumo: Não da para generalizar em todos os bancos (como foi a proposta inicial desta issue)... Melhor esperar a critica de cada um deles, e implementar... 

Em breve mando a atualização.

**Comment by rafd75** [comment]
#173

Pronto... Conforme novos bancos solicitarem, nós vamos ajustando.
Melhor aguardar cada banco se posicionar.
