### ISSUE TITLE
Help para um iniciante

### ISSUE THREAD

**Issue by rofreli** [BoletoNet/boleto2net#174]
Fiz o download da solução, mas algumas coisas não estou conseguindo entender muito bem.
Meu Visual Studio 2015, não esta entendendo estruturas como esta:

string[] ObterCodigos(Type type) => type.GetCustomAttributes(false).OfType<CarteiraCodigoAttribute>().First().Codigos;

Eu até posso reescrever este trecho, mas a cada nova versão teria de faze-lo o que não faz sentido.

Sabem me informar qual o problema?

Desde já grato!
![Capturar](https://user-images.githubusercontent.com/4404756/56219574-5d885c80-603d-11e9-9eeb-6e2ffff44510.PNG)

**Comment by rafd75** [comment]
@rofreli bom dia... 

O projeto só funciona no VS 2017 para frente...

Leia mais:
#4
#7

**Comment by rofreli** [comment]
Muito Obrigado pela rápida resposta, um abraço.
