### ISSUE TITLE
Erro CNAB400 Santander

### ISSUE THREAD

**Issue by aemsoftwarearacatuba** [BoletoNet/boleto2net#176]
Alguem poderia me dizer se o Santander CNAB400 foi implementado... pois esta gerando esse erro:

   em Boleto2Net.BancoSantander.GerarHeaderRemessa(TipoArquivo tipoArquivo, Int32 numeroArquivoRemessa, Int32& numeroRegistroGeral)

**Comment by rafd75** [comment]
Santander só tem implementado o padrão 240... 

Segue atalho para o código que gera a exceção por não ter o padrão 400.

https://github.com/BoletoNet/boleto2net/blob/07b82d0d4a45038cf298638894ec833fa55bd433/Boleto2.Net/Banco/BancoSantander.cs#L67
