### ISSUE TITLE
Valores de multa, desconto, outras deduções, e valor cobrado não aparecem

### ISSUE THREAD

**Issue by lucas-devplace** [BoletoNet/boleto2net#178]
Bom dia pessoal, estou utilizando a dll do boleto2net para gerar um boleto onde já tenho a maioria das infos do boleto registrado; (sendo uma segunda via do boleto)

porém ao preencher as infos o boleto não imprime os valores de multa, descontos, valor cobrado etc. apenas imprime o valor do documento;

Segue o código que estou usando abaixo:

```
  var boleto = new Boleto(_banco)
            {
                DataVencimento = model.BilletDueDate,
                ValorTitulo = model.DocumentValue,
                //ValorJurosDia = 1,
                //ValorAbatimento = 0,
                //ValorDesconto = Convert.ToDecimal(2.000),//model.Discount,
                //ValorMulta = Convert.ToDecimal(60), //model.Mulct,
                NossoNumero = model.OurNumber,//"000000025214", //model.OurNumber,
                NumeroDocumento = model.NumberNF,
                EspecieDocumento = TipoEspecieDocumento.NF,
                Sacado = GerarSacado(model),
                Carteira = model.Wallet,
                EspecieMoeda = model.Specie,
                MensagemInstrucoesCaixa = model.Instruction,

                DataDesconto = DateTime.Now,
                ValorDesconto = 0,

                DataMulta = DateTime.Now,
                PercentualMulta = 0,
                ValorMulta = 0,

                DataJuros = DateTime.Now,
                PercentualJurosDia = 0,
                ValorJurosDia = 0,

                CarteiraImpressaoBoleto = "101",


            };

            //Ação
            boleto.ValidarDados();
```

![boleto_issue](https://user-images.githubusercontent.com/45262742/58185179-e6239980-7c88-11e9-89a4-0b8722914f2a.PNG)

Alguém consegue me dar uma ajuda se seriam apenas preenchendo esses campos que apareceriam as infos ou se tenho que setar alguma coisa nesse trecho de código na minha controller?

```
BoletoBancario boleto = GenerateBilletPDF(model);
                    var boletos = new List<BoletoBancario>();
                    boletos.Add(boleto);
                    //boleto.MostrarComprovanteEntrega = true;
                    boleto.MostrarContraApresentacaoNaDataVencimento = true;
                    boleto.MostrarCodigoCarteira = true;
                    boleto.MostrarComprovanteEntregaLivre = true;
                    //var pdf = boleto.MontaBytesListaBoletosPDF(boletos, "Boleto", "", "", false, true);
                    var pdf = boleto.MontaBytesPDF();

                    return responsePDFGenerator(pdf, "Boleto");
```

**Comment by rafd75** [comment]
Fiz um ajuste ( #179 ) que deve resolver...

Não me recordo, mas acho que isso já existia no projeto e foi retirado pois quando estava com valor zerado, aparecia R$ 0,00 e na homologação de algum banco esse valor foi criticado.

Segui o padrão já existente... se for ZERO troca por "", caso contrário, troca pelo valor.

Infelizmente não consegui testar aqui... Vou aguardar seu retorno.

**Comment by lucas-devplace** [comment]
Opa Rodolfo, vi seu commit lá acho que resolveria sim o problema, hj eu uso a dll que instalei via nuget mesmo, esse commit já reflete na dll que tenho instalada ou teria que ser publicado no nuget?

A versão que estou usando da dll é a ultima disponível 2.1.0.305

**Comment by lucas-devplace** [comment]
@rafd75 referenciei a dll compilada no meu projeto e funcionou! Obrigado!

![image](https://user-images.githubusercontent.com/45262742/58193500-82559c80-7c99-11e9-99f0-8bd29acca005.png)

**Comment by rafd75** [comment]
OK... legal...

Com relação ao nuget, não é automático não... o @carloscds atualiza de tempos em tempos... 


Abs!

**Comment by rafd75** [comment]
@lucas-devplace boa tarde... 

preciso que você de uma olhada na issue  #184 --- fala exatamente sobre essa questão de imprimir os valores auxiliares...
