### ISSUE TITLE
Atualizar no NuGet

### ISSUE THREAD

**Issue by krgm03** [BoletoNet/boleto2net#180]
@carloscds bom dia
Por favor quando puder atualizar no NuGet
Obrigado!

**Comment by carloscds** [comment]
@krgm03 Feito, deve atualizar em alguns minutos!

**Comment by krgm03** [comment]
@carloscds, bom dia

Provavelmente você atualizou o Boleto.Net
O Boleto2.Net continua desatualizado

Obrigado

**Comment by carloscds** [comment]
@krgm03 Enviado atualização!
