### ISSUE TITLE
Leitura de arquivo de retorno CNAB240 Itau

### ISSUE THREAD

**Issue by csancor** [BoletoNet/boleto2net#181]
Queria saber se consigo realizar a leitura do arquivo de retorno cnab 240 do Itaú. Não estou conseguindo localizar onde o projeto faz o layout conforme a versão 5.0. Eu teria que acrescentar algo? Sou iniciante nesse assunto.

**Comment by rafd75** [comment]
@csancor, boa tarde!

O padrão 240 não está implementado no Itaú... somente o 400.

Teria que implementar nesses métodos:
(Obs: não sei se passou algum outro método despercebido...)

**REMESSA:**

https://github.com/BoletoNet/boleto2net/blob/37fae05fe430406782b1cfc3f3a5277c35086902/Boleto2.Net/Banco/BancoItau.cs#L50

https://github.com/BoletoNet/boleto2net/blob/37fae05fe430406782b1cfc3f3a5277c35086902/Boleto2.Net/Banco/BancoItau.cs#L71

https://github.com/BoletoNet/boleto2net/blob/37fae05fe430406782b1cfc3f3a5277c35086902/Boleto2.Net/Banco/BancoItau.cs#L104

**RETORNO:**

https://github.com/BoletoNet/boleto2net/blob/37fae05fe430406782b1cfc3f3a5277c35086902/Boleto2.Net/Banco/BancoItau.cs#L130

https://github.com/BoletoNet/boleto2net/blob/37fae05fe430406782b1cfc3f3a5277c35086902/Boleto2.Net/Banco/BancoItau.cs#L135

https://github.com/BoletoNet/boleto2net/blob/37fae05fe430406782b1cfc3f3a5277c35086902/Boleto2.Net/Banco/BancoItau.cs#L140

**Comment by csancor** [comment]
Obrigado pelo retorno rafd75. Eu estou tentando implementar os métodos de leitura mas na hora de recuperar os valores a disposição de posicionamento dos caracteres não trás o que pede no manual. Por exemplo a posição de 19 a 32 não mostra o CPF e CNPJ corretamente. Agradeço se puder me orientar a respeito.

**Comment by rafd75** [comment]
Copia o código que vc fez aqui que eu dou uma olhada...

Procura nos demais bancos, algum que já tenha o CNAB240 implementado... pode ajudar a fazer no Itau...
