### ISSUE TITLE
Sicredi - ReadMe

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boleto2net#183]
Boa tarde a todos,

Um cliente me solicitou a implementação do banco Sicredi.

Olhei no ReadMe e vi que o banco não estava na lista, mas achei esse PR https://github.com/BoletoNet/boleto2net/pull/175 com a implementação.

Poderiam me dizer se atualmente o projeto atende o banco Sicredi em produção?

**Comment by rafd75** [comment]
@marcosgerene - o README está desatualizado ... 

Foi implementado sim, inclusive com os testes (eu não uso aqui, mas aparentemente funciona...)

**Comment by marcosgerene** [comment]
@rafd75 excelente, obrigado.

**Comment by rafd75** [comment]
@marcosgerene  - Você implementou ai o Sicredi?

Caso positivo, vou atualizar o README

**Comment by marcosgerene** [comment]
@rafd75 ainda não é o mesmo cliente do BB do outro post, agora a tarde quero atualizar lá e ver o resultado, acredito que o Sicredi vai ser só pra julho

**Comment by rafd75** [comment]
bom... vou atualizar o README, pq no final das contas, implementado está...
E se tiver problema no uso, a gente corrige a classe... 

valeu...

**Comment by marcosgerene** [comment]
@rafd75 perfeito, obrigado
