### ISSUE TITLE
[BB][Dúvida] - Valor da multa

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boleto2net#184]
Boa tarde a todos,

Um cliente me procurou falando que os clientes deles reclamavam que o valor da multa saia no boleto no campo valor aonde não deveria sair.

![image](https://user-images.githubusercontent.com/15945003/59052994-b8cd1300-8866-11e9-8cfc-c77388cefc59.png)

Note o valor de R$ 23,57, eu sempre informei o valor da multa (até então só trabalhava com a Sicoob) mas nunca saiu no boleto, este é meu código:

![image](https://user-images.githubusercontent.com/15945003/59053079-ee71fc00-8866-11e9-8b8f-b5473e20bf6f.png)

Estou fazendo errado? Devo apenas informar as instruções na geração da remessa?

Obrigado,
Marcos Gerene F. Spirito

**Comment by rafd75** [comment]
@marcosgerene , boa tarde!

Por conta da  #178   foi feito o #179 que alterou esse comportamento.

Acredito que o motivo do questionamento anterior, era para emitir o boleto "atualizado" (ou seja, já vencido e recalculado com multa e juros)... 

Considerando o cenário acima, o código que você mandou, serve para imprimir o boleto e gerar o arquivo remessa? Ou apenas imprimir o boleto?

Caso seja só impressão, acredito que não informar "ValorJurosDia" resolva o problema... mas não daria certo gerar o arquivo remessa dessa forma.

Talvez será necessário criar uma propriedade no Boleto que indique se deve (ou não) informar os valores de juros e multa. Dessa forma, resolve o seu problema, e também o problema do @lucas-devplace (vou tentar copiar ele nessa issue a partir da dele)... assim centralizamos a discussão e encontramos uma solução comum... 

Vc entendeu o que houve?

**Comment by lucas-devplace** [comment]
@rafd75 no meu caso tratava-se de uma reimpressão de 2° via de boleto, onde eu já possuía todos os dados calculados vindos de um ERP que gerou a primeira via e eu só precisava exibir igual.

**Comment by marcosgerene** [comment]
@rafd75 no meu caso uso o mesmo código para gerar remessa e imprimir o boleto, estou enviando o boleto antes do vencimento

**Comment by rafd75** [comment]
@marcosgerene  e @lucas-devplace 

O #186 deve resolver...

**Por padrão, não imprime...** mas se precisar, é só setar boleto.ImprimirValoresAuxiliares = true; e pronto.

@marcosgerene e @lucas-devplace  - me retornem se estiver ok.

**Comment by lucas-devplace** [comment]
@rafd75 blz.

**Comment by marcosgerene** [comment]
@rafd75 vou testar agora a tarde no cliente, obrigado pela ajuda

**Comment by marcosgerene** [comment]
@rafd75 isso está disponivel no nuget?

**Comment by rafd75** [comment]
@marcosgerene , 

Não tenho acesso ao nuget ... ai é com o @carloscds

**Comment by marcosgerene** [comment]
@rafd75 vou retornar para a versão anterior, saindo a nova "reatualizo"

**Comment by olavorn** [comment]
Abri um fork que implementa essa atualização e outras situações específicas. O único banco que não funciona os testes atuais é o Siscred; (mas não sei se funcionava antes tb)

Como as alterações foram grandes, não é tópico só desta issue, mas se for o caso (e interesse dos mantenedores) implemento um pull request, só que recomendaria com um salto de versão.

as mudanças estão aqui: [https://github.com/ExodusSistemas/boleto2net](url)

As diferenças básicas são:
* PDF tratado em projeto separado e com dependências nativas (boleto2.net.pdf)
* Gestão de arquivos embeded diferente (sem .resx)
* Sem .ashx ou qualquer dependência da System.Web 
* netstandard 2.2 (asp.net core puro)
* MontaHtmlEmbeded como padrão base pra geração HTML 

Se alguem achar mais últil e tiver interesse em contribuir, basta me avisar e abrirei pra mantenedores. Vamos ter um pipeline próprio de geração de nuget tb, por necessidades do projeto.

**Comment by renanmthy** [comment]
Bom dia pessoal.
Estou tendo problemas referente a Multa no Arquivo Retorno. 
Ela simplesmente vem zerada, só retornando o campo Juros com valor.

Creio que pode é referente a linha **bol2net.ValorMulta = 0;**, e só estou aqui pra confirmar se é isso mesmo.
Logo que implementei o boletoNet eu passava valor aí, porém os clientes começaram a reclamar que os boletos estavam vindo com Multa sem estar vencido, ai arrumei essa solução provisória e achei que só de passar o **bol2net.PercentualMulta = contaCorrente.PercentualMulta;** o banco calcularia a multa automaticamente.

Devo voltar a enviar o valor para que o banco calcule a multa, ou somente o PercentualMulta ja resolve?

Segue meu código que gera o boleto para enviar na Remessa.
![image](https://user-images.githubusercontent.com/17087193/85858953-d5e6c380-b792-11ea-9054-d80412a18420.png)
