### ISSUE TITLE
GeraLayout / Remessa itau

### ISSUE THREAD

**Issue by gruponetvoo** [BoletoNet/boleto2net#187]
Pessoal antes antes de sair a obrigatoriedade de registro do boleto eu usava a primeira versão do boletonet  não atualizei o projeto e parei de emitir boletos pelo sistema por conta de erros no arquivo de remessa.

**1º - GeraLayout.**
Antes no final da minha instrução eu gerava uma pré-visualização do boleto e pós isso eu mandava imprimir ou gerar o pdf ou se tivesse errado eu fechava e gerava outro, agora no final da minha instrução não uso mais o GeraLayout(boletos); só que ao finalizar tudo ele abre a tela de pré-visualização mas em branco, alguém poderia ajudar para carregar o boleto na tela de pré-visualização se isso ainda for possível, uso o modelo de teste antigo boleto.net.ui.

**2º Remessa Itau 240**
Preciso voltar emitir boletos no sistema e fia a atualização de todo o projeto mesmo com toda dificuldade por conta de tanta coisa que mudou, só que estou em duvidas com arquivo de remessa, alguém poderia disponibilizar um arquivo de remessa gerado com um 2 boletos para mim comparar com  meu pois saiu umas coisas como IO antes de umas linhas e outras com muitos zeros e meu banco quer que eu envio o arquivo assim mesmo pois eles não tem um modelo de como deve ficar, porem eu gostaria de enviar com o mínimo de erros possível então decidi recorrer aqui com vocês.

**3º Minha função gera o PDF com os dados e o arquivo de remessa com dados também:**

Não sei se ajuda mas uso no final da função para gerar o boleto assim:

  //Gravo dentro do arquivo de remessa
                        using (FileStream file = new FileStream(fileNameRemess, FileMode.Create, FileAccess.Write))
                        {
                            //stream.WriteTo(file);
                            var stream = new MemoryStream();
                            var remessa = new ArquivoRemessa(boletos.Banco, Globals.ContaBancaria.TipoDeARQRemessa.CNAB240 == true ? TipoArquivo.CNAB240 : TipoArquivo.CNAB400, Globals.ContaBancaria.SequencialRemessa);
                            remessa.GerarArquivoRemessa(boletos, file);
                        }

                        //var rem = new ArquivoRemessa(boletos.Banco, TipoArquivo.CNAB240, saveFileDialog.OpenFile(), 1); //<== IMPLEMENTAR AQUI NUMERO SEQUENCIAL DO ARQ REMESSA!!!
                        
                        //Gerar boletos - aqui eu gravo os arquivos um a um porque mando via e-mail.
                        foreach (var boletorepdf in boletos)
                        {
                            var boletoBancario = new BoletoBancario() { Boleto = boletorepdf };
                            var pdf = boletoBancario.MontaBytesPDF(false);
                            var pathPDF = PathRemessa + $"{boleto.NumeroControleParticipante}.pdf";
                            File.WriteAllBytes(pathPDF, pdf);
                        }

**Comment by rafd75** [comment]
@gruponetvoo  bom dia...

1 - praticamente não usei a versão anterior do BoletoNet... não vou conseguir te ajudar.

2 - Manda seu arquivo pro banco homologar... é mais seguro do que você tentar comparar os dados.

3 - Da uma olhada na classe abaixo (eu uso ela para interagir com o FoxPro)... Além disso, tem o projeto de teste do Boleto2Net, também com exemplos de geração do arquivo remessa e boletos... 

https://github.com/BoletoNet/boleto2net/blob/master/Boleto2.Net/Boleto2NetProxy.cs

https://github.com/BoletoNet/boleto2net/tree/master/Boleto2.Net.Testes
