### ISSUE TITLE
Remessa CNAB400 banco Safra

### ISSUE THREAD

**Issue by marcel-ardaia** [BoletoNet/boleto2net#190]
Olá!

É minha primeira postagem por aqui então me desculpem se estiver fazendo algo errado.

Passei por homologação junto ao banco Safra e observei que na geração da remessa os campos de 206-218 podem ser utilizados para "Valor do abatimento concedido ou cancelado" ou para "Multa".
O projeto contempla apenas o caso de valor de abatimento.

Inclui uma regra para o caso de encontrar no CodigoInstrucao1 ou CodigoInstrucao2 o código 16 (código para multa) tratar o preenchimentos dos 206-218 da seguinte forma:

//-> Se houver multa.
                if ((boleto.CodigoInstrucao1 == "16") || (boleto.CodigoInstrucao2 == "16"))
                {
                    reg.Adicionar(TTiposDadoEDI.ediDataDDMMAA___________, 0206, 006, 0, boleto.DataMulta, ' ');
                    reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0212, 004, 2, boleto.PercentualMulta, '0');
                    reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0216, 003, 0, "000", '0');
                }
                else
                    reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0206, 013, 2, boleto.ValorAbatimento, '0');

**Comment by rafd75** [comment]
@marcel-ardaia , boa tarde ... 

Estava fazendo uma limpa nas issues passadas e só agora tomei conhecimento deste problema.
Verifiquei no manual, e apenas fiz um ajuste quanto a operação ser de registro (Ocorrencia=01) e a primeira instrução conter "16" ...

#272
