### ISSUE TITLE
Boleto Sicredi

### ISSUE THREAD

**Issue by railsonflima** [BoletoNet/boleto2net#193]
Olá pessoal,

Olhando o código fonte do projeto, vi que já existe implementação para o Banco Sicredi, mais no  README.md não consta como carteira homologada. Alguém já testou as implementações desenvolvidas para este banco? Ou poderiam informar se as gerações de boleto e remessa estão ok?

Muito obrigado

**Comment by marcosgerene** [comment]
https://github.com/BoletoNet/boleto2net/issues/183

**Comment by rafd75** [comment]
Bom dia... 

Já atualizei o README.md... 

Obs: eu não utilizo o SICREDI aqui... mas já tem gente usando sim...
Aqui, sem exceção, toda nova carteira implementada em produção, passa antes pela homologação do banco.... independente de já termos feito em outro cliente, etc... Melhor garantir!

**Comment by railsonflima** [comment]
Muito obrigado @marcosgerene e @rafd75.
 
Abraços
