### ISSUE TITLE
Bradesco -  CNAB 400 - Protestar não implementado

### ISSUE THREAD

**Issue by renanmthy** [BoletoNet/boleto2net#194]
Pessoal, falta implementar o "Protesto" para o CNAB 400 do Bradesco, ou esse código ja existe e eu não estou sabendo utilizar? Grato.

**Comment by rafd75** [comment]
@renanmthy bom dia.

No manual do Bradesco, tem essa instrução:

**157 a 160 - 1ª / 2ª Instrução**
Campo destinado para pré-determinar o protesto do Título ou a baixa por decurso de prazo, quando do registro. Não havendo interesse, preencher com Zeros.

Porém, caso a Empresa deseje se utilizar da instrução automática de protesto ou da baixa por decurso de prazo, abaixo os procedimentos:

**Protesto:
- posição 157 a 158 = Indicar o código “06” - (Protestar).
- posição 159 a 160 = Indicar o número de dias a protestar (mínimo 5
dias).**

Protesto Falimentar:
- posição 157 a 158 = Indicar o código “05” – (Protesto Falimentar)
- posição 159 a 160 = Indicar o número de dias a protestar (mínimo 5
dias).

**Comment by renanmthy** [comment]
@rafd75 bom dia.

Perfeito, vou seguir este procedimento!

Estava analisando o código do CNAB 240 e percebi que o mesmo tem um **switch(CodigoProtesto)**, ja o CNAB 400 não, por isso ficou a dúvida.

Poderíamos implementar o mesmo para que fique intuitivo o código por si só, sem a necessidade de acessar o leiaute para descobrir esta informação, ou da maneira como está já está correto?

**Comment by rafd75** [comment]
Então...

Aqui, sempre na homologação, a gente valida com o banco o que o cliente pede... e como cada banco é de um jeito, eu sempre verifico o manual nesse cenário.

Sua sugestão é interessante... o único problema é que por não ter um padrão, cada banco acaba fazendo de um jeito. E então no inicio do Boleto2Net era exatamente deixar isso o menos amarrado possível para não dar problema nos diversos cenários.

Neste caso... você notou que tem 2 tipos de Protesto? ... Se você travar o "06" no switch, não funcionaria para alguém que queira usar o protesto "Falimentar" (não faço ideia do que seja)...

**Comment by renanmthy** [comment]
Opa entendi perfeitamente! Aqui eu tinha marrado o switch no 06, porém pensando pelos seus dados levantados desfiz a manutenção no Boleto2Net e passei a utilizar o **CodigoInstrucao1** e **CodigoInstrucao2**, deixando assim meu ERP responsável por identificar as particularidades dos bancos. Este "Falimentar" não faço ideia do que seja tambem rsrs.

Deixamos aqui esta conclusão então: Utilizarmos sempre as propriedades **CodigoInstrucao1** e **CodigoInstrucao2** sem travar o componente!
