### ISSUE TITLE
[Sicredi] - Espécie do documento

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boleto2net#195]
Bom dia a todos,

Meu código:
```
boleto.EspecieDocumento = TipoEspecieDocumento.DM;
```

O erro:
![image](https://user-images.githubusercontent.com/15945003/61710428-0b379580-ad28-11e9-89e7-41d9f0b995e3.png)

Não existe a opção A (que seria duplicata mercantil), como devo proceder?

Att, Marcos

**Comment by marcosgerene** [comment]
![image](https://user-images.githubusercontent.com/15945003/61710584-518cf480-ad28-11e9-9a1d-5dc9ad86566c.png)

Acredito que encontrei a resposta no commit original "DMI", procede?

**Comment by rafd75** [comment]
@marcosgerene , bom dia.

Tudo ok com a sugestão de DM ou DMI retornar "A"... legal.

Só uma dúvida... Essa imagem com o código comparando o número do banco (748) e então força "DMI" na espécie, foi o que você fez no seu sistema para gerar o "A", isso antes do seu commit?

Se foi isso, ok... Mas se esse código estiver dentro do Boleto2Net, não deveria ser assim... (entendo que a implementação correta está no seu commit, ou seja, se espécie for DM ou DMI, retorna "A" para o sicredi).

**Comment by marcosgerene** [comment]
@rafd75  Sim, fiz no meu sistema para forçar um "A", depois olhei o código e joguei DM e DMI para A.

Abraços
