### ISSUE TITLE
Adicionei o boleto via Nuget mas esta dando erro.

### ISSUE THREAD

**Issue by Boscosantana** [BoletoNet/boleto2net#197]
Adicionei o boleto via Nuget mas esta dando erro.
"The type or namespace name boletoNet could not be found(are you missing a using directive or an assembly reference?)"

**Comment by carloscds** [comment]
@Boscosantana Manda um print do erro. Qual a versao do .NET que você esta utilizando ?

**Comment by Boscosantana** [comment]
Peço desculpa coloquei errado aqui.
Era pra colocar no boleto e não na versão boleto2.
Estou usando o VS2013

**Comment by carloscds** [comment]
@Boscosantana manda um print do erro da instalacao do pacote.

**Comment by Boscosantana** [comment]
![erronoiboleto](https://user-images.githubusercontent.com/5580907/62055703-84d0f700-b1f2-11e9-8a48-3f2fa5a3b263.jpg)

**Comment by rafd75** [comment]
using Boleto2Net; 

faltou o 2 ai no meio...

**Comment by carloscds** [comment]
@Boscosantana Pode validar ?

**Comment by Boscosantana** [comment]
Bom dia. não é o Boleto2.net.
Até por que estou usando o VS2013

**Comment by rafd75** [comment]
@Boscosantana bom dia.

Aqui é do Boleto2Net 

No caso, a BoletoNet, é nesse outro repositório:

https://github.com/BoletoNet/boletonet/issues

**Comment by Boscosantana** [comment]
Desculpa, coloquei errado.
