### ISSUE TITLE
[Impressão] - Código de barras

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boleto2net#199]
Bom dia a todos,

Como posso melhorar a disposição do código de barras no boleto em PDF?

Atualmente apresento uma certa dificuldade em ler o código de barras impresso.

Att, Marcos

**Comment by rafd75** [comment]
@marcosgerene ,

Utilizo a solução em alguns clientes, e nunca ninguém comentou sobre esse tipo de problema.

Qual a impressora que você usou? E o leitor?

**Comment by marcosgerene** [comment]
@rafd75 

L575 (Epson)

Leitor de celular mesmo, notei que o barcode é ruim, acho que deve ser algo no transportar o html para pdf.

Outros boletos parecem ter a qualidade do barcode "melhor", tem algo que eu possa fazer para melhorar isso?

**Comment by rafd75** [comment]
Não faço ideia do que fazer...

Nunca fiz esse teste (imprimir e ler no celular)... não sei como ficaria aqui.

Talvez se você pegar um boleto que chegou pelo correio, replicar a linha digitável na sua aplicação, e imprimir na L575 o mesmo boleto, usando a biblioteca, e depois comparar as imagens geradas (do código de barras do boleto impresso por você, e daquele impresso pelo banco), pode te mostrar se existe algo que possa ser melhorado...

**Comment by rafd75** [comment]
Melhorando: Um boleto que você imprimiu no seu sistema, e depois registrou no banco... emita a segunda via pela plataforma do banco e compare (mais fácil que o caminho inverso)

**Comment by dannieljunior** [comment]
Olá, eu adaptei minha classe que gera os boletos para usar o aspose
barcode, porém é um componente pago. Eu não gero a impressão pelo
boletonet, o uso apenas para gerar os dados formatados e calcular linha
digitável, código de barras gerar e ler os arquivos de remessa e retorno.

Em qua, 7 de ago de 2019 14:01, Rodolfo Duarte <notifications@github.com>
escreveu:

**Comment by marcosgerene** [comment]
@rafd75 eu fiz isso e o resultado é bem melhor, o código é bem mais nítido

**Comment by rafd75** [comment]
@marcosgerene  - bom dia.

Consegue colocar as duas imagens aqui?

**Comment by marcosgerene** [comment]
@rafd75 
>Consegue colocar as duas imagens aqui?

Printando o pdf da tela (exatamente no mesmo tamanho):

Sistema:
![image](https://user-images.githubusercontent.com/15945003/62709457-c2403c00-b9cb-11e9-9f54-1582f7bba5b2.png)

Banco:
![image](https://user-images.githubusercontent.com/15945003/62709387-a5a40400-b9cb-11e9-897b-4642dedf3687.png)


Imagens impressas:

![20190808_110351](https://user-images.githubusercontent.com/15945003/62709757-65915100-b9cc-11e9-869e-3eb076e2e259.jpg)

**Comment by rafd75** [comment]
Hum... de fato... o tamanho do código de barras com certeza prejudica a leitura.

Bom... em algum lugar tem (deve ter) como melhorar isso, provavelmente na classe "BoletoImpresso" (onde monta o HTML)... 

Mas não sei te dizer como foi feito, pq nessa parte, não alterei nada do código original do BoletoNet ... 

Tenho interesse no assunto, mas sem a menor possibilidade de agenda para estudar e ajustar isso.

No chute (escuro), talvez, alguma escala no HTML mesmo... mas precisa ter o cuidado para ver se não vai invalidar o código de barras...

Tarefa complicada de realizar.

**Comment by marcosgerene** [comment]
@rafd75 

Para aumentar o barcode, pelo pouco que vi da biblioteca, seria aumentar o tamanho na classe BarCode2of5i atualmente é 1,50, gerei com 2,100 para testar.

![image](https://user-images.githubusercontent.com/15945003/62714854-b8233b00-b9d5-11e9-983d-bc0caeee9e7a.png)

O resultado foi assustador rsrs...

![image](https://user-images.githubusercontent.com/15945003/62714915-d2f5af80-b9d5-11e9-82d5-c98a0fff8024.png)

[boleto.pdf](https://github.com/BoletoNet/boleto2net/files/3482440/boleto.pdf)

Bem, não sei como seria para manter a proporção e fazer funcionar, mas que é possível aumentar é....

**Comment by rafd75** [comment]
Ah, talvez seja por ai ... 

tenta com 1,6 1,7 e vai comparando com a do banco...

Quando bater o tamanho, verifique se as linhas também estão iguais...

**Comment by marcosgerene** [comment]
@rafd75 

esse 1 que passei para 2 (width) é inteiro, não sei se posso usar de forma quebrada

**Comment by marcosgerene** [comment]
[5dde148f-b600-481f-b72b-bd436f9fc3a6.pdf](https://github.com/BoletoNet/boleto2net/files/3482828/5dde148f-b600-481f-b72b-bd436f9fc3a6.pdf)
[50b45b55-4b9c-4703-b075-f2141ba744d6.pdf](https://github.com/BoletoNet/boleto2net/files/3482829/50b45b55-4b9c-4703-b075-f2141ba744d6.pdf)
[95c9ec9e-0d4b-4d78-a3a3-9ce51c239cd4.pdf](https://github.com/BoletoNet/boleto2net/files/3482830/95c9ec9e-0d4b-4d78-a3a3-9ce51c239cd4.pdf)
[2300d2ef-56eb-4893-b3af-fdf6c7d01323.pdf](https://github.com/BoletoNet/boleto2net/files/3482831/2300d2ef-56eb-4893-b3af-fdf6c7d01323.pdf)
[7536f171-eeab-4e3d-a525-e3f06c9b57af.pdf](https://github.com/BoletoNet/boleto2net/files/3482832/7536f171-eeab-4e3d-a525-e3f06c9b57af.pdf)
[5907989e-2234-4161-8561-f6536cd51e48.pdf](https://github.com/BoletoNet/boleto2net/files/3482833/5907989e-2234-4161-8561-f6536cd51e48.pdf)
[a0cf6135-782e-48e0-9117-4d44448cb6ee.pdf](https://github.com/BoletoNet/boleto2net/files/3482834/a0cf6135-782e-48e0-9117-4d44448cb6ee.pdf)
[cc2000ef-f02f-4c82-ae85-f93cacc29200.pdf](https://github.com/BoletoNet/boleto2net/files/3482835/cc2000ef-f02f-4c82-ae85-f93cacc29200.pdf)
[ed49fe43-09ba-4ec8-85eb-6586acfd5a07.pdf](https://github.com/BoletoNet/boleto2net/files/3482836/ed49fe43-09ba-4ec8-85eb-6586acfd5a07.pdf)


Esses boletos foram todos gerados em cima dos testes da sicoob, basicamente fiz isso:

![image](https://user-images.githubusercontent.com/15945003/62721957-c7a98080-b9e3-11e9-96c8-087027878207.png)
