### ISSUE TITLE
Valor Pago

### ISSUE THREAD

**Issue by rafd75** [BoletoNet/boleto2net#20]
Pessoal, preciso de uma opinião de quem já passou por isso.

Eu padronizei os nomes das propriedades da classe Boleto. E uma delas é ValorPago.

A ideia é que, nessa propriedade, seja armazenado o valor que o sacado pagou. Dessa forma, cada aplicação pode usar uma única lógica para realizar as liquidações na base de dados.

Explicado isso, peguei uma situação aqui... Mesmo cliente, que utiliza Bradesco e Itau.

O Bradesco cobra uma tarifa ao registrar um título. E quando este título é liquidado, o valor creditado na conta é o que o cliente pagou.

O Itaú não cobra o registro do título, mas cobra na liquidação. Então, do valor pago pelo cliente, subtrai o valor da tarifa e temos o valor do crédito na conta.

O resultado disso é:

Valor do Título: R$ 100,00
Valor do Pagamento: R$ 100,00

No Bradesco -> Tarifa R$ 0, Valor Crédito: R$ 100,00
No Itaú -> Tarifa R$ 2, Valor Crédito R$ 98

No Itau, para contornar o problema, dentro da minha aplicação (e não na DLL), estou somando ao valor pago, o valor da tarifa... Corrigiu o problema, mesmo quando o cliente paga em atraso (com multa, juros, etc).

Mais uma informação:

No manual do Bradesco, na posição 254 diz "VALOR PAGO" enquanto no Itau (mesma posição) diz "VALOR PRINCIPAL".

Acredito que, para resolver esse problema do jeito certo, seria termos 2 propriedades:

ValorPago => seria utilizada no Bradesco
ValorCredito => seria utilizada no Itau

Na aplicação final, ficaria fácil saber qual é a informação, e chegar no valor correto.

Qual a opinião de vocês?

OBS: Só ocorreu no ITAU isso... Caixa, BB, Bradesco, Sicoob, seguem o mesmo padrão.

**Comment by carloscds** [comment]
@rafd75 Rodolfo, acho melhor deixar isto para a aplicação resolver, pois cada desenvolvedor por tratar isto de um jeito!

**Comment by rafd75** [comment]
@carloscds - é o que eu fiz aqui... mas se isso for uma regra (Itaú considera valor creditado na conta corrente), está errado armazenar na propriedade ValorPago (o valor não bate com o pagamento do cliente).

Uma saída, considerando ser a regra do Itaú, seria fazer isso logo abaixo da leitura dos valores:

`if (boleto.ValorPago>0)
     boleto.ValorPago += boleto.ValorTarifas
`

Indiretamente estaríamos padronizando a propriedade ValorPago, e a aplicação poderia confiar no valor que recebeu da DLL, sem ter que tratar banco por banco...

**Comment by carloscds** [comment]
@rafd75 No layout do Itau o campo valor pago está com ou sem a tarifa ?

**Comment by rafd75** [comment]
Então, no Itau, não existe "VALOR PAGO". O manual diz "VALOR CREDITADO EM CONTA" e está descontando a tarifa.

A imagem abaixo é o arquivo retorno e manual do ITAU, com a situação que te falei.

![image](https://user-images.githubusercontent.com/11903379/28796264-423b6032-7613-11e7-9f04-a5655edbcaae.png)

Nos manuais dos demais bancos, para esse mesmo campo, diz:

No Bradesco: Valor Pago.
Na Caixa: Valor Principal pago pelo Pagador
No BB e Sicoob: Valor Recebido
No Santander: Valor Total Recebido

Ou seja, estou entendendo que o Itaú (Valor Credito) é diferente dos demais (Valor Pago, não necessariamente o valor do crédito).

**Comment by carloscds** [comment]
@rafd75 Neste caso o valor nominal é o valor do título sem descontos ou acescimos. É o que deveríamos usar! E preencher os campos desconto, acrescimo tbem.

**Comment by rafd75** [comment]
É verdade...  Mas o Juros, Desconto, Multa, já estarão informados no "valor lançado em conta corrente"... O problema é a Tarifa mesmo, que é subtraída do valor pago pelo cliente ... 

O código atual está assim:

```
                //Valores do Título
                boleto.ValorTitulo = Convert.ToDecimal(registro.Substring(152, 13)) / 100;
                boleto.ValorTarifas = Convert.ToDecimal(registro.Substring(175, 13)) / 100;
                boleto.ValorOutrasDespesas = Convert.ToDecimal(registro.Substring(188, 13)) / 100;
                boleto.ValorIOF = Convert.ToDecimal(registro.Substring(214, 13)) / 100;
                boleto.ValorAbatimento = Convert.ToDecimal(registro.Substring(227, 13)) / 100;
                boleto.ValorDesconto = Convert.ToDecimal(registro.Substring(240, 13)) / 100;
                boleto.ValorPago = Convert.ToDecimal(registro.Substring(253, 13)) / 100;
                boleto.ValorJurosDia = Convert.ToDecimal(registro.Substring(266, 13)) / 100;
                boleto.ValorOutrosCreditos = Convert.ToDecimal(registro.Substring(279, 13)) / 100;

```

Sugiro adicionar esta linha (somente no ITAU) após a leitura de todas as propriedades:
```
// Atenção: ITAU retorna o valor do crédito em conta corrente. Para ajustar o valor pago pelo sacado, estamos somando o valor das tarifas que foram descontadas para gerar o crédito em conta corrente.
if (boleto.ValorPago>0)
boleto.ValorPago += boleto.ValorTarifas
```

**Comment by carloscds** [comment]
@rafd75 eu acho que não Rodolfo, isto deve ficar a cargo do desenvolvedor da aplicacao, pq somando a tarifa o valor não fica igual ao retorno do banco.

**Comment by rafd75** [comment]
@carloscds - sim, fazendo o ajuste (somando a tarifa), fica diferente do retorno do banco, mas fica correto o "ValorPago" (que é o nome da propriedade) pelo cliente.

Do jeito que está, vai acontecer o que ocorreu aqui... Eu confiei no nome da propriedade "ValorPago" e fiz a liquidação do título do cliente.

Mas o ValorPago pelo cliente foi R$ 100, e o ValorPago que eu baixei, foi R$ 98. Ficou R$ 2,00 em aberto (que é a tarifa).

Entendo que, se deixarmos a soma para a aplicação tratar, eu, você e todos os outros que usarem a DLL vão precisar fazer isso na APP. Caso contrário, irão dar a baixa parcial do título, pelo valor do crédito na conta do cliente, ao invés do ValorPago pelo cliente.

Do jeito que está, fica confuso.   Vejo três soluções possíveis:

1 - A já apresentada (corrigir o ValorPago somando a Tarifa)

2 - Criar uma nova propriedade ValorCreditoConta, e no caso do Itaú, preencher essa propriedade e deixar o ValorPago zerado. Ai sim, a aplicação passa a ter 2 valores distintos e já vai saber o que fazer com cada um deles.

3 - Manter do jeito que está, armazenando o "Valor do Crédito" na propriedade "Valor Pago".

Eu - particularmente - acho a solução 1 melhor.

Obs: minha opção (pela 1) leva em conta o fato da propriedade ter o nome de "ValorPago". Acho que muita gente vai confiar no valor que está ai, e cometer o mesmo erro que ocorreu aqui.   O que acha?

**Comment by carloscds** [comment]
@rafd75 O problema da solução 1 é que a empresa não recebeu realmente o valor + tarifa, somente o valor. A solução 2 me parece mais razoável, mas com um ajuste, ValorPago mantem e ValorCreditoConta=Valor-Tarifa-Desconto+Juros, o que acha ?

**Comment by rafd75** [comment]
Falando do ValorCreditoConta, a resposta é "depende".

No Itau, isso funcionaria... No Bradesco, o valor é o pago pelo cliente. Pelo que entendi, se houver tarifa, o valor (do bradesco) é cheio.

Ou seja, se criarmos as duas propriedades:

ValorPago -> leitura do valor (sem contas) no Bradesco, BB, Santander, Sicoob e Caixa. No caso do Itaú, precisa fazer o ajuste (somar a tarifa)

ValorCreditoConta -> no Itau, apenas a leitura das posições 254 a 267. Mas no Bradesco, BB, Santander, Sicoob e Caixa, não existe esse campo lá, seria necessário, pegar o ValorPago (que está nessa mesma posição 254 a 267) e subtrair uma possível tarifa. Eu não tenho nenhum exemplo aqui (arquivo retorno) nessa situação, por isso não tenho como afirmar se é isso mesmo.


O melhor dos mundos seria termos as 2 propriedades mesmo. Onde ValorPago é sempre o valor que o cliente pagou, e ValorCreditoConta é o valor que o banco credita na conta do cliente.

+ uma informação: Aqui na Computar (usamos Bradesco), a tarifa é cobrada no registro do título no banco. Quando ocorre o pagamento, por exemplo, 5 títulos no mesmo dia, apenas 1 lançamento de crédito aparece na conta (somando os 5 títulos pagos, sem descontar nada.)

**Comment by carloscds** [comment]
@rafd75 O grande problema é que não existe padrão, então volto minha opinião para deixar a aplicacao tratar.

**Comment by rafd75** [comment]
Então... Opção 4 - E se tivermos as duas propriedades:

ValorPago:

ValorCreditoConta:

No caso do Itau, ficaria preenchido somente ValorCreditoConta (ValorPago zerado e a aplicação se vira)

Nos demais bancos, ficaria preenchido somente ValorPago (ValorCreditoConta zerado e a aplicação se vira).

Dessa forma, pelo menos, a aplicação saberá qual o valor que está vindo para ela (o que o cliente pagou, ou o crédito da conta)...

**Comment by carloscds** [comment]
@rafd75 Blz!

**Comment by rafd75** [comment]
#21 - Resolvido.

**OBS 1:** A propriedade ValorCredito já existia (passou despercebido).
Para evitar nova confusão, foi renomeada para ValorPagoCredito.

No banco Itau (CNAB400), preenchemos a propriedade ValorPagoCredito - para que fique claro que o valor que está ali, é do crédito em conta (não necessariamente o valor pago pelo cliente - conforme descrito acima). Neste caso, ValorPago fica zerado, pois não existe no arquivo retorno.

Nos demais bancos (CNAB400), preenchemos a propriedade ValorPago, deixando em branco ValorPagoCredito.

Dessa forma, a aplicação deverá tratar da melhor maneira que achar necessário, sabendo se o valor que ela está recebendo é o "Pago" ou "Creditado"

**OBS 2:** No caso do CNAB240, existem os 2 campos no layout. Neste caso, preenchemos os dois valores ValorPago e ValorPagoCredito.
