### ISSUE TITLE
Erro: Carteira Não implementada

### ISSUE THREAD

**Issue by aclimarin** [BoletoNet/boleto2net#202]
Olá pessoal, estou fazendo a implementação do Boleto2net. Estou utilizando a carteira 1 do Banco do Sicoob. Embora exista a classe BancoSincoobCarteira1, na hora de chamar o SetupCobranca, ele retorna a mensagem: Carteira Não Implementada: 1

Esse é o único erro que está retornando.

**Comment by lvitorbh** [comment]
Vc tem que usar carteira 1 e modalidade 01
[CarteiraCodigo("1/01")]

`ContaBancaria = new ContaBancaria
                        {
                            Agencia = bancoConta.agenci_b01.ToString(),
                            DigitoAgencia = bancoConta.dgvage_b01,
                            Conta = bancoConta.numcta_b01,
                            DigitoConta = bancoConta.dgvcta_b01,
                            CarteiraPadrao = **bancoConta.cart01_b01,**
                            VariacaoCarteiraPadrao = **bancoConta.modali_b01**,
                            TipoCarteiraPadrao = TipoCarteira.CarteiraCobrancaSimples,
                            TipoFormaCadastramento = TipoFormaCadastramento.ComRegistro,
                            TipoImpressaoBoleto = TipoImpressaoBoleto.Empresa,
                            TipoDocumento = TipoDocumento.Tradicional
                        },`

**Comment by aclimarin** [comment]
Obrigada! Era isso mesmo.

**Comment by aclimarin** [comment]
Então, agora eu estou obtendo Carteira não implementada: 1/01
