### ISSUE TITLE
Exibir boleto gerado

### ISSUE THREAD

**Issue by aclimarin** [BoletoNet/boleto2net#203]
Oi pessoa, estou dando prosseguimento a minha implementação. Consegui gerar um boleto, e através do debug pude ver a geração tanto do pdf quanto do html. 

A minha dúvida em relação à geração em html é:
Como obter o html gerado para ser exibido na tela?

No meu entendimento nenhum desses métodos corresponde a isso de forma pontual. 

![boleto2netproxy](https://user-images.githubusercontent.com/31768702/62910211-06c63180-bd56-11e9-911a-6cb45954c10c.JPG)

**Comment by rafd75** [comment]
@aclimarin  bom dia... 

Falando da classe Proxy, o primeiro parâmetro do método GerarBoletos() é exatamente o Nome do Arquivo que a biblioteca deve gerar.

Se você passar o nome do arquivo com extensão HTM, ele vai gerar o HTML... se a extensão for PDF, ele vai gerar o PDF... 

Então é só fazer algo assim:

DllBoleto.GerarBoletos("C:\BOLETOS\ARQUIVO.HTM" ... )

**Comment by aclimarin** [comment]
Então, consegui acessar o html, problema é que o html está sendo gerando com caracteres esquisitos no lugar de caracteres especiais.


`<tr class="ct h13 At">
<td class="w298">BeneficiᲩo</td>
<td class="w126">Agꮣia / C󤩧o do BeneficiᲩo</td>
<td class="w34">Esp飩e</td>
<td class="w45">Quantidade</td>
<td class="w128">Carteira / Nosso número</td>
</tr>`

**Comment by aclimarin** [comment]
Resolvi esse problema alterando o Boleto2NetProxy.

No método GerarArquivoTexto, mudei o Encoding de Default para UTF-8. Ficou assim:


```
private void GerarArquivoTexto(string texto, string nomeArquivo)
        {
            using (FileStream fs = new FileStream(nomeArquivo, FileMode.Create))
            {
                using (var sw = new StreamWriter(fs, Encoding.UTF8))
                {
                    sw.Write(texto);
                    sw.Close();
                    fs.Close();
                }
            }
        }
```
