### ISSUE TITLE
BoletoNetCore.Pdf exemplo

### ISSUE THREAD

**Issue by brunofelixbessa** [BoletoNet/boleto2net#207]
Pessoal alguém já viu ou sabe como gerar pdf agora como essa nova BoletoNetCore.Pdf

**Comment by carloscds** [comment]
@brunofelixbessa Seu projeto esta em .NET Core ou .NET Standard?

**Comment by jonatanfelipesiqueira** [comment]
@carloscds responde ai q preciso também , o meu esta em  .netcore , nao foi implementado geracao de remessa la ? eu consigo utilizar essa biblioteca aqui pro .netcore ?

**Comment by carloscds** [comment]
@jonatanfelipesiqueira Eu fiz um componente para gerar PDF: https://www.nuget.org/packages/HtmlToPDFCore/

**Comment by marcosgerene** [comment]
@carloscds  Excelente!

**Comment by Hernany** [comment]
> @jonatanfelipesiqueira Eu fiz um componente para gerar PDF: https://www.nuget.org/packages/HtmlToPDFCore/

Tentei usar e está dando erro no Wkhtmltopdf. Já instalei e desinstalei e fala que não foi encontrado. Sabe de algo que possa estar com erro neste pacote?

**Comment by jader1313** [comment]
Também não consegui usar. Algum lugar que tenha um exemplo ou alguma instrução?

**Comment by carloscds** [comment]
@Hernany Qual erro ?

**Comment by jader1313** [comment]
Na verdade não se trata de erro. Antes de mais nada gostaria de agradecer e elogiar a dedicação de todos os envolvidos no projeto e que graciosamente se doam para o mesmo. Sei como é difícil. Mas vai aqui o relato da minha dificuldade, que provavelmente não é só minha: cheguei ao projeto pesquisando na Web, mas não existe nenhuma dica de por onde começar, onde pesquisar ou onde podemos encontrar um projeto básico para que possamos começar nossos testes e aprender sobre p projeto. Pesquisando encontrei alguns exemplos de versões anteriores e "fuçando" nos testes consegui "começar" a fazer uns testes.

**Comment by carloscds** [comment]
@jader1313 Da uma olhada nos projetos de testes!

**Comment by rafd75** [comment]
@jader1313 bom dia!

Da uma olhada aqui:

https://github.com/BoletoNet/boleto2net/blob/master/Boleto2.Net.Testes/ExemploClasseProxy.cs

e aqui (Bradesco, mas tem dos outros bancos também):

https://github.com/BoletoNet/boleto2net/blob/master/Boleto2.Net.Testes/BancoBradescoCarteira09.cs

**Comment by jader1313** [comment]
@rafd75 bom dia!
Obrigado pelas dicas, mas por que classe proxy?

@carloscds com relação a minha sugestão para os administradores, sei que somos todos desenvolvedores. Uns mais, outros menos experientes. Uma explanação básica do fluxo da classe, indicando suas principais propriedades e métodos ajudaria bastante quem está conhecendo a biblioteca. Inclusive a indicação desse teste "específico" para começar e um por que do proxy.  Não precisa ser nada muito detalhado, só um ponto de partida. Somente uma sugestão. Obrigado.

**Comment by rafd75** [comment]
@jader1313   -    Eu utilizo a classe proxy para comunicar com outras linguagens (por exemplo: Visual FoxPro).

só indiquei o código, pq fica fácil de entender como setar as propriedades... mas você (se usar C#), não precisa dela não...

**Comment by jader1313** [comment]
@rafd75 na verdade estou testando no C# justamente para utilizar no VFP. Sabia que teu nome não me era estranho, comunidade VFP. rsrsrs

**Comment by rafd75** [comment]
kk - então a classe PROXY é pra você! kkk

**Comment by carloscds** [comment]
@jader1313 Obrigado pela sugestão, o que acha @rafd75  ?

**Comment by rafd75** [comment]
@carloscds  bom dia!

talvez, citar esses 2 links no read.me... com uma explicação.. ou talvez, criar um novo "teste unitário" para servir de guia... mas alguém precisaria fazer isso, eu não consigo agora.

Uma vez, alguém considerou fazer um wiki do projeto, mas a verdade é que um manual a parte do código, ao longo do tempo, não me parece uma boa (vai ficar desatualizado, o que é pior do que não ter um manual)...

**Comment by jader1313** [comment]
Vou colocar aqui pois acredito que está relacionado ao tópico e porque também é uma continuação da conversa.
Acredito que tem um pequeno bug no BoletoNetCore_ExemploProxy(), o código está testando o retorno de comandos anteriores. Pelo que vi faltou atribuir o resultado dos comandos a variável retorno, acho que deveria ser assim:
// Para gerar o arquivo remessa, após preencher a coleção de Boletos:
            **retorno =** classeProxy.GerarRemessa((int)TipoArquivo.CNAB400, nomePasta + @"ClasseProxy_Cnab400.Rem", 1, ref mensagemErro);
            Assert.AreEqual(true, retorno, "GerarRemessa: " + mensagemErro);

            // Para gerar o arquivo PDF
            **retorno =** classeProxy.GerarBoletos(nomePasta + @"ClasseProxy_Boleto.Pdf", ref mensagemErro);
            Assert.AreEqual(true, retorno, "GerarBoletos: " + mensagemErro);

Esse teste para gerar o PDF está passando mas não está gerando o PDF. O GerarBoletos só gera HTM, que não é o caso. Não estou muito à par mas acredito que vocês andaram alterando essa geração do PDF que na verdade é o ponto inicial do issue.

**Comment by jader1313** [comment]
Acabou misturando parte do código mas acho que deu para entender. rsrsrs

**Comment by jader1313** [comment]
@rafd75 com relação ao problema no teste que citei acima, vi que existe um projeto BoletoNetCore.Pdf, que possui um BoletoNetCorePdfProxy, que possui um GerarBoletos() que é idêntico ao do BoletoNetCoreProxy exceto que esse possui e chama o método GerarArquivoPDF(). Alterei o teste do proxy para utilizar essa classe(BoletoNetCorePdfProxy), só que aí levanta uma exception  na linha:
var pdf = new Wkhtmltopdf.NetCore.HtmlAsPdf().GetPDF(html);
relativa a um parametro Path1.

@carloscds citou acima uma outra classe https://www.nuget.org/packages/HtmlToPDFCore/
Então, se não estou equivocado, são 3 pacotes nugget: BoletoNetCore, BoletoNetCore.Pdf e HtmlToPDFCore
Quero gerar remessa, ler o retorno e imprimir o boleto. Preciso dos três? Poderiam dar uma luz sobre quais preciso e o por que dos 3?

**Comment by carloscds** [comment]
@jader1313 o HtmlToPdfCore substitui o BoletoNetCore.pdf

**Comment by rafd75** [comment]
@jader1313 - eu utilizo o projeto Boleto2Net ... que é diferente do BoletoNetCore... 

Se não me engano, o problema do NetCore estava relacionado ao PDF... mas não acompanhei de perto isso.

**Comment by joaojesusvictor** [comment]
Eu acredito que a dica do @jader1313 é bem relevante.

Seria muito bom ter uma introdução de como utilizar as bibliotecas BoletoNetCore, BoletoNetCore.Pdf e HtmlToPdfCore (se já existe, eu não encontrei, mas ficarei grato se alguém puder me mostrar aonde está).

Pois, levando em consideração meu caso, podemos dizer que sou novo em desenvolvimento e preciso gerar boletos para Bradesco, Itau, Santander, pelo menos, e gerar o pdf de cada boleto.

Todo lugar em que procuro, é comentado sobre o projeto BoletoNetCore, mas eu não faço ideia de como usar.

**Comment by carloscds** [comment]
@joaojesusvictor Da uma olhada nos projetos de testes: https://github.com/BoletoNet/boleto2net/tree/master/Boleto2.Net.Testes 
É um bom começo para entender como tudo funciona.

**Comment by rafd75** [comment]
@carloscds , acho que o @joaojesusvictor está falando dos projetos NetCore...

Eu não acompanhei isso...

**Comment by carloscds** [comment]
@rafd75 @joaojesusvictor Sim, la tambem tem projeto de testes, apesar de menor:
https://github.com/BoletoNet/BoletoNetCore/tree/master/BoletoNetCore.Testes

**Comment by carloscds** [comment]
@rafd75 @joaojesusvictor Mas acho legal a ideia de um projeto exemplo.

**Comment by rafd75** [comment]
@carloscds Ah, ok... mas é outro projeto...  o link que vc postou primeiro, era do Boleto2Net mesmo.

entendido...

**Comment by Graeber02** [comment]
em relação ao problema que vi que alguns tem em relação ao boletonetcore com o arquivo libwkhtmltox.dll e necessario adicionar ao projeto no caminho: bin\Debug a seguinte dll.
llink para dowload da biblioteca a baicho
[https://github.com/rdvojmoc/DinkToPdf/blob/master/v0.12.4/64%20bit/libwkhtmltox.dll](https://github.com/Abase-Sistemas/GestorWeb/issues/url) .

o boleto net core gera arquivo remessa tambem ou somente os boletos?

**Comment by carloscds** [comment]
@Graeber02 Gera remessa e retorno tambem.

**Comment by Graeber02** [comment]
teria como me indicar um exemplo?

**Comment by carloscds** [comment]
@Graeber02 Da uma olhada nos projetos de testes: https://github.com/BoletoNet/boleto2net/tree/master/Boleto2.Net.Testes
