### ISSUE TITLE
Dúvida, remessa banco Bradesco

### ISSUE THREAD

**Issue by Militao36** [BoletoNet/boleto2net#211]
Olá, sou novo na comunidade do BoletoNet, é estou com alguns problemas no arquivo de remessa do banco Bradesco.
Estou conseguindo gerar o arquivo de remessa, porém na hora de validar, está me retornando o seguinte erro `Linha 03 - Trailer de arquivo. Arquivo sem Trailer.` não estou achando oque significa isso. Alguém que utilize o componente poderia me ajudar por favor, desde já agradeço.

**Comment by rafd75** [comment]
@Militao36 , bom dia.

Uso o Bradesco em produção faz tempo (aliás, foi o primeiro banco que homologuei aqui) e nunca tive esse problema.

O registro trailer é gerado por esse método:

https://github.com/BoletoNet/boleto2net/blob/05e079877b04d3adaddc8597bc5c917a959a140f/Boleto2.Net/Banco/BancoBradesco.cs#L133

Verifique se seu código está passando por ele.

**Comment by Militao36** [comment]
@rafd75 Bom dia, está passando sim, fui usando o debug para ver se entrava e se dava algum erro, passou normalmente, nesse método.

**Comment by rafd75** [comment]
OK.. então "teoricamente", o trailer deveria estar no arquivo remessa gerado.

ao abrir o arquivo (bloco de notas), o registro não está lá ?

**Comment by Militao36** [comment]
Então o que e retornado por esse método, não está no arquivo de remessa gerado não.

**Comment by Militao36** [comment]
@rafd75  Como posso resolver esse erro? Estou pesquisando porém sem sucesso

**Comment by rafd75** [comment]
@Militao36  --- estou enrolado aqui.

se o método está retonando a string, segue depurando onde é que se perde.

obs: como te falei, uso o bradesco, sem problemas. (CNAB400 , se não me engano).

**Comment by Militao36** [comment]
@rafd75 Vou da uma olhada, vou depurar para ver oque ocorre.

**Comment by Militao36** [comment]
@rafd75 Boa tarde, encontrei oque estava ocorrendo, quando gero 1 boleto apenas, ele gera a remessa tudo certo, porém quando coloco mais de um boleto para gerar, ele da o erro na `Linha 03 - Trailer de arquivo. Arquivo sem Trailer` como se não adicionasse o trailer de arquivo.

**Comment by rafd75** [comment]
@Militao36  --- tem alguma coisa estranha ai ...

Aqui, eu sempre gero o Remessa com mais de 1 boleto... e sempre gera o trailer normalmente.

**Comment by Militao36** [comment]
Então eu fiz o teste aqui fui depurando todo o código completo até finalizar a geração, ai quando eu estou depurando gero tudo certo, más se eu deixar executar direto, não gera com o trailer.

Estou usando esse código, para gerar os boletos, e a variável objBoletos, é uma instancia de Boletos, que contem a quantidade 2( ou a quantidade que eu quero imprimir, ai passo para o gerar remessa, porém quando passo acima de 1 boleto, o trailer não vai

`csharp
//Gerar arquivo de remessa
var str = new MemoryStream();
var remessa = new ArquivoRemessa(objBoletos.Banco, TipoArquivo.CNAB400, 1);
remessa.GerarArquivoRemessa(objBoletos, str);
var arquivo = new FileStream(caminho + "/remessa.txt", FileMode.Create, FileAccess.ReadWrite);
str.WriteTo(arquivo);
arquivo.Close();
str.Close();
`

**Comment by Militao36** [comment]
Então achei um outro problema, quando gero 1 boleto ele gera com a trilha, porém quando jero com 1 boleto, funciona e com 4 porém com 2 e 3 boletos ele não adiciona a trilha, apenas quando e 1 ou 4 boletos.
