### ISSUE TITLE
Remover Imagem do Boleto Safra

### ISSUE THREAD

**Issue by igorbag** [BoletoNet/boleto2net#222]
Olá, boa tarde!! Tudo bem? você sabem se tem algum parâmetro para conseguirmos desabilitar a imagem do boleto? 

Agradeço!

Att,

**Comment by rafd75** [comment]
@igorbag , boa tarde.

Acho que não existe parâmetro para isso... O que você pode fazer, é acessar a pasta onde estão os logos dos bancos (veja o endereço da pasta no link abaixo) e alterar a imagem do safra para uma imagem transparente/branca...

https://github.com/BoletoNet/boleto2net/blob/ce29fddd0772690795bfada928ea8a9fc3662e4d/Boleto2.Net/BoletoImpressao/BoletoBancario.cs#L809

Deve funcionar... isso pq, a imagem é salva apenas 1 vez no disco (no caso, com o logo do banco).... Você substituindo essas imagens com "branco", não vai aparecer nada... 

Não sei o motivo disso, mas caso seja algo relevante para o projeto, o certo mesmo seria implementar esse parâmetro.
