### ISSUE TITLE
Editar Layout PDFGnerator para Emitir Boleto Carnê

### ISSUE THREAD

**Issue by Marlonwg** [BoletoNet/boleto2net#225]
Como faço para editar o layout do pdfgenerator para emitir boleto em formato Carne ?

**Comment by renanmthy** [comment]
Olá vi essa thread em aberto e consegui imprimir em via Carnê.
Segue o exemplo:
![image](https://user-images.githubusercontent.com/17087193/85893381-2a0c9a80-b7c9-11ea-9f9d-ba72121c5559.png)
![image](https://user-images.githubusercontent.com/17087193/85893545-6e983600-b7c9-11ea-883c-6cddb114fc08.png)
