### ISSUE TITLE
Banco Itaú

### ISSUE THREAD

**Issue by DanielFilippo** [BoletoNet/boleto2net#227]
Olá a todos, fiz o download da biblioteca para ver o seu funcionamento, pretendo usar ela este mês, e também fiz o download da boleto.net, vi que ná boleto.net está implementado as funcionalidades do cnab240 para o banco itaú, e na boleto2.net não está implementada, teria algum motivo especifico para isso? Pois precisarei utilizar o cnab240 do banco itaú, gostaria de saber se tem algum motivo para não estar implementada. Obrigado

**Comment by rafd75** [comment]
@DanielFilippo , boa tarde.

Quando a versão 2 do BoletoNet foi criada, todos os bancos/carteiras existentes na versão anterior foram excluídas, e a partir daí as novas implementações passaram a seguir um mesmo padrão.

No caso do Itaú, provavelmente até o momento (na versão Boleto2Net) ninguém precisou utilizar. Por isso não foi implementada ainda.

Não é difícil implementar... ainda mais neste caso (que a carteira já existe, e tem o layout 400 implementado)... Se precisar de algo pronto, a solução seria ficar com a versão anterior do BoletoNet. Ou, você precisaria implementar o cnab240 na Boleto2Net...

**Comment by DanielFilippo** [comment]
rafd75, o projeto do Boleto2Net está dando vários erros aqui, não sei se é pela versão do Visual Studio, eu sou novo no c#

olhe a imagem: 
![image](https://user-images.githubusercontent.com/5024631/71357019-00ee2180-257c-11ea-9d12-8b78a745c7a6.png)

com isso, não consigo executar os testes, e não vou implementar algo que não conseguirei testar

**Comment by DanielFilippo** [comment]
Poderia me ajudar? se for algo simples de corrigir esses erros, para eu poder implementar e testar, quero usar a boleto2Net mesmo, não a anterior, obrigado rafd75

**Comment by rafd75** [comment]
@DanielFilippo - Pelo que já vi anteriormente que o pessoal reportou aqui, sempre que acontece isso, é a versão do Visual Studio que não é compatível com esse projeto.

Pre requisitos: Visual Studio 2017 ou superior

Qual a sua versão?

**Comment by DanielFilippo** [comment]
é o 2015 rafd75, vou ver se consigo aqui então, obrigado
