### ISSUE TITLE
Problema com remessa Sicredi cnab 240

### ISSUE THREAD

**Issue by nathan-cervieri** [BoletoNet/boleto2net#228]
Olá,

Precisamos utilizar o cnab 240 para gerar uma remessa para a sicredi, mas toda vez ele dá uma exceção, dei uma olhada no código e percebi que só tem o cnab 400 implementado, existe alguma previsão de quando isso poderia ser alterado?

**Comment by carloscds** [comment]
@NoxShadow Da uma olhada no BoletoNet, acredito que la tenha. https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/Banco/Banco_Sicredi.cs
