### ISSUE TITLE
Banco Safra - Carteira 2

### ISSUE THREAD

**Issue by emellyaquino** [BoletoNet/boleto2net#23]
Essa versão aceita a carteira 2 do banco safra? 
Preciso implementar em um portal, 2ª via de boleto do banco Safra, mas sem a verificação do campo "nossonumero".

**Comment by rafd75** [comment]
Precisa implementar. Não tem banco SAFRA (nenhuma carteira) ainda.

**Comment by carloscds** [comment]
@emellyaquino Veja o projeto anterior: BoletoNet. Mas está desatualizado: https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/Banco/Banco_Safra.cs

**Comment by emellyaquino** [comment]
Irei olhar, muito obrigada!

________________________________
De: Carlos dos Santos <notifications@github.com>
Enviado: sábado, 12 de agosto de 2017 11:30:01
Para: BoletoNet/boleto2net
Cc: emellyaquino; Mention
Assunto: Re: [BoletoNet/boleto2net] Banco Safra - Carteira 2 (#23)


@emellyaquino<https://github.com/emellyaquino> Veja o projeto anterior: BoletoNet. Mas está desatualizado: https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/Banco/Banco_Safra.cs

**Comment by rafd75** [comment]
@carloscds - acho que pode fechar essa issue!
