### ISSUE TITLE
Envio automático para o banco Itau

### ISSUE THREAD

**Issue by MauricioCodeguez** [BoletoNet/boleto2net#230]
Olá, não sei se esse é o lugar certo para fazer esse tipo e pergunta.

Estou começando a trabalhar agora com geração de boleto bancário.

Esse projeto já tem alguma funcionalidade que faz o envio automático das remessas para o banco e consulta os pagamentos feitos? Se sim, onde fica essas funcionalidades? Se não, como que vocês estão fazendo esse processo de envio e recebimento?

Obrigado!

**Comment by rafd75** [comment]
@MauricioCodeguez , bom dia.

O projeto não possuí essa funcionalidade (integração automática com os bancos).
Esse é um recurso que o pessoal sempre pergunta, e sem dúvidas seria de grande valor para o Boleto2Net, mas até o momento ninguém implementou o "primeiro" banco...

Acho que falta o "caminho das pedras" para o pessoal acabar implementando em todos os bancos...

No meu caso aqui, enquanto isso não acontece, nós utilizamos o site do banco (homebanking) para fazer o envio do arquivo remessa e recepção do arquivo retorno.

**Comment by DanielFilippo** [comment]
Eu estava atrás disso para o banco Itaú, consegui conversar com um funcionário desenvolvedor, o mesmo me disse que desconhece quaisquer API do banco para fazer isso, o único jeito que ele me disse é que tem que ser manual mesmo, não sei os outros bancos

**Comment by rafd75** [comment]
Jeito tem, com certeza.... pq os e-commerces, hubs de pagamento, etc, você gera o boleto, e já paga no mesmo instante...

**Comment by MauricioCodeguez** [comment]
@rafd75 Boa tarde!

Então hoje você faz esse processo manual mesmo?

Como você falou, em alguns lugares você gera o boleto e já pode pagar no mesmo instante, essa é minha ideia no sistema que estou trabalhando, então eu não poderia depender de um processo manual.

**Comment by rafd75** [comment]
Sim, faço manual. Uma vez por dia, gero a remessa e transmito (quando existe novos boletos emitidos)

E diariamente pego o retorno (para processar as liquidações, etc.)

Eu também quero automatizar... mas apesar de ser importante, não é prioridade aqui.

**Comment by MatheusJordao** [comment]
Bom dia Mauricio,

Se ainda houver a necessidade de automatizar o processo no Itaú, entra em contato com o banco solicitando o EDI7. Nele você consegue fazer envio de remessa e recepção de retorno pelo CMD usando o programa que eles disponibilizam.
