### ISSUE TITLE
Retorno Itaú CNAB400 109

### ISSUE THREAD

**Issue by DanielFilippo** [BoletoNet/boleto2net#231]
Olá, eu estou enviando o arquivo de retorno, mas quando bate no boleto2Net me retorna sempre, "Erro ao ler arquivo.", alguem usa o arquivo retorno do Itau? CNAB400 carteira 109, obrigado

**Comment by carloscds** [comment]
@DanielFilippo Você validou o arquivo?

**Comment by DanielFilippo** [comment]
Carlos eu estava chamando o método de arquivo retorno passando a stream, fui ver o porquê do problema no boleto2net, e vi que ele instância um banco novo, e quando pega a primeira posição do retorno que é o cedente, ele não recupera o cedente, não faz nada aparentemente, então chamei um outro método que passa o banco, e depois um que passa a stream, aí funcionou
