### ISSUE TITLE
Padrão Arrecadação

### ISSUE THREAD

**Issue by eltonn007** [BoletoNet/boleto2net#232]
Boa tarde, tenho um sistema que precisa efetuar geração e boleto com o padrão febraban Arrecadação, o boleto2net  consegue gerar nesse padrão?
Obrigado,

**Comment by carloscds** [comment]
@eltonn007 Somente boleto, remessa e retorno.

**Comment by eltonn007** [comment]
Obrigado pelo retorno, 
Att,
