### ISSUE TITLE
[Dúvida] Geração Arquivo Remessa

### ISSUE THREAD

**Issue by MauricioCodeguez** [BoletoNet/boleto2net#234]
Pessoal, tudo bem?

Gostaria de saber como vocês fazem a geração do arquivo remessa, vocês geram um arquivo de remessa por dia ou um arquivo por boleto gerado?

Por exemplo, vocês tem algum lugar no sistema para gerar o arquivo remessa de todos os boletos gerados no dia de uma unica vez ou toda vez que gera um boleto vocês geram o arquivo remessa junto e enviam vários arquivos por dia para o banco?

Obrigado!

**Comment by rafd75** [comment]
Bom dia!

Por aqui, costumo orientar os usuários a gerar um arquivo por dia, no final do dia, após fechamento do faturamento.

Mas a forma que implementamos a rotina, permite que gere mais de um arquivo por dia.

**Comment by MauricioCodeguez** [comment]
@rafd75 Obrigado pela resposta.

Suponhamos que eu tenha um processo que gere 500 boletos em uma madrugada e salve esses boletos em disco, no final do dia eu quero gerar meu arquivo remessa, eu preciso gerar de novo todos esses 500 boletos para gerar o arquivo remessa? Pois o método de gerar o arquivo remessa espera os boletos como parâmetro, correto?

**Comment by rafd75** [comment]
Para gerar o arquivo remessa, você precisa popular a coleção de Boletos e gerar o arquivo.
Os dados que vc irá informar, são os mesmos que você informa imprimir os boletos, mas não precisa gerar o PDF... Fique atento ao Nosso Número (se vc imprimiu o boleto, vai precisar informar ele novamente para a remessa)... 

No projeto de teste do Boleto2Net, tem geração de arquivo. Veja o exemplo por lá de como fazer.

**Comment by MauricioCodeguez** [comment]
@rafd75 Entendi.

No meu caso eu salvo as informações do boleto no banco e o boleto em PDF em disco (necessidade do cliente ter esses arquivos em disco). Dessa forma então, eu posso pegar as informações dos boletos gerados no dia que estão no banco, preencher a coleção de Boletos e gerar o arquivo remessa, acho que vai funcionar.

Obrigado!

**Comment by rafd75** [comment]
é isso ai.

Eu não gravo o PDF aqui... eu gero quantas vezes necessário (usando as informações do banco)

**Comment by MauricioCodeguez** [comment]
Beleza então, vou tentar fazer dessa forma!

Vou fechar essa issue.

Valeu @rafd75!
