### ISSUE TITLE
Duvidas Protesto e Baixa/Devolucao

### ISSUE THREAD

**Issue by matheusrizzi** [BoletoNet/boleto2net#236]
Boa tarde pessoal, arrecem estou começando a utilizar a biblioteca, espero poder contribuir em breve.
Mas segue dúvida em relação ao protesto automático de boletos via bradesco, o que precisaria configurar no arquivo de remessa?

Atualmente preenchi só as informações abaixo:
```
            titulo.CodigoProtesto = TipoCodigoProtesto.ProtestarDiasCorridos;
            titulo.DiasProtesto = 7;

```

E o que seria essa questão de baixa/devolução?
```
            titulo.CodigoBaixaDevolucao = TipoCodigoBaixaDevolucao.NaoBaixarNaoDevolver;
            titulo.DiasBaixaDevolucao = 0;
```

**Comment by rafd75** [comment]
@matheusrizzi bom dia!

Eu não utilizo esse recurso, mas vou dar um "chute" aqui, e depois (se vc descobrir o certo) me avisa...

No Bradesco (que utilizo para fazer nossas cobranças), se um título não é pago em 60 dias após o vencimento, o Bradesco da baixa por prazo, cobra as tarifas dessa baixa e pronto.

Não sei se é o caso do Bradesco, mas acho que esse prazo (60 dias) pode ser configurável e se for isso, essa propriedade deve fazer esse ajuste.
