### ISSUE TITLE
Testes Sicredi falhando

### ISSUE THREAD

**Issue by rodolfoghi** [BoletoNet/boleto2net#239]
Fiz fork do projeto e sem alterar nada rodei os testes unitários, tem 9 testes falhando, todos do banco Sicredi.

![image](https://user-images.githubusercontent.com/9952024/75345715-0d447280-587c-11ea-9226-dc090cccb535.png)

**Comment by rafd75** [comment]
@rodolfoghi bom dia.

O Sicredi é o único banco que não utilizo atualmente (não sei quem fez a implementação dele aqui no Boleto2Net)... mas sempre tem alguém comentando sobre algo de errado nele.

O certo seria passar um pente fino nesse banco/carteira.

Sugiro aguardar alguém que já está usando em produção te posicionar a respeito.

**Comment by rodolfoghi** [comment]
Pelo blame, vi que o teste unitário foi escrito pelo @denerkrebs.
