### ISSUE TITLE
Posso implementar o pattern builder?

### ISSUE THREAD

**Issue by matheusrizzi** [BoletoNet/boleto2net#241]
Estou pensando em implementar o pattern builder para criar o boleto, o que acham?
Implementei a parte de leitura do arquivo local aqui pra mim, vejam como ficou:

![image](https://user-images.githubusercontent.com/15008457/75599204-67625500-5a81-11ea-9167-1f398145e7cd.png)

**Comment by carloscds** [comment]
@matheusrizzi O codigo fica muito mais simples!

**Comment by matheusrizzi** [comment]
Sim, fica muito bom e para a geração do boleto esse pattern seria o ideal, simplificaria muito.

**Comment by carloscds** [comment]
@matheusrizzi manda ver, mas colocar isto em uma classe separada para nao quebrar o codigo atual.

**Comment by matheusrizzi** [comment]
Certo, ja estou fazendo isto, olha como ficou a minha implementação do titulo agora com o builder:

![image](https://user-images.githubusercontent.com/15008457/76135478-09e08200-6006-11ea-9787-dec2c8abf4e3.png)

E como deixei a estrutura:

![image](https://user-images.githubusercontent.com/15008457/76135502-2977aa80-6006-11ea-9ce7-5011216d9d14.png)

Falta pouco, assim que tiver uma versão que seja possível utilizar
por completa submeto a alteração.

**Comment by carloscds** [comment]
@matheusrizzi Muito bom!

**Comment by rafd75** [comment]
Isso vai ficar top!

Está caminhando?

**Comment by matheusrizzi** [comment]
Na verdade tenho quase tudo pronto aqui, nao dei continuidade porque estava cheio de projetos hehe, mas vou agilizar pra subir um PR.
