### ISSUE TITLE
Impressão do Boleto s/ Agência e Código do Beneficiário Itaú 109

### ISSUE THREAD

**Issue by paulinhoamc** [BoletoNet/boleto2net#244]
Olá!
Estou tendo problemas na impressão do Boleto, está sendo gerado o PDF sem o campo Agência / Código do Beneficiário.
O que pode estar acontecendo?
Banco Itaú, Carteira 109.
Agencia s/ Dígito, Conta c/ Dígito.
Cedente/DígCedente não informados.

**Comment by rafd75** [comment]
@paulinhoamc , bom dia.

Qual o erro?

**Comment by paulinhoamc** [comment]
Não aparece os dados bancários do emitente.

**Comment by paulinhoamc** [comment]
Não aparece os dados bancários do emitente na impressão do boleto.

**Comment by paulinhoamc** [comment]
Quando instancio a conta bancária / cedente, devo chamar o método FormataCedente() de dentro do banco para poder, só assim, chamar a impressão do boleto.
Assim corrigi meu código.

```
            contaBanco.Cedente = new Cedente()
            {
                CPFCNPJ = _emitente.CNPJ,
                Nome = _emitente.Nome,
                Endereco = new Endereco()
                {
                    LogradouroEndereco = _emitente.Logradouro,
                    LogradouroNumero = _emitente.Numero,
                    LogradouroComplemento = _emitente.Complemento,
                    Bairro = _emitente.Bairro,
                    Cidade = _municipio.Nome,
                    UF = _emitente.UF,
                    CEP = _emitente.CEP
                },
                ContaBancaria = contaBancaria
            };

            contaBanco.FormataCedente();
```
