### ISSUE TITLE
Santander - CNAB 240 Segmento T

### ISSUE THREAD

**Issue by krgm03** [BoletoNet/boleto2net#25]
Bom dia
Primeiro gostaria de parabenizar todos os envolvidos no projeto pela iniciativa

Firmamos recentemente um contrato de prestação de serviços de cobrança em nossa conta no Santander

Recebemos a documentação do Santander na seguinte versão: 
Layout de Arquivo Padrão 240 – Cobrança Versão 2.8 Fevereiro/2016

Baixamos o fonte do boleto2net para realização de testes e parece que encontramos na implementação do BancoSantander algumas divergências nas posições das informações no método LerDetalheRetornoCNAB240SegmentoT

Por exemplo:

No método há o seguinte trecho de código  "boleto.Carteira = registro.Substring(57, 1);"

Enquanto a documentação diz:

![posicao cod carteira no seg t](https://user-images.githubusercontent.com/6650072/29568388-92c80d74-8726-11e7-9480-57223e58d8a2.png)

O Santander confirmou que a versão atual é realmente a que nos foi  enviada(Layout de Arquivo Padrão 240 – Cobrança Versão 2.8 Fevereiro/2016)

Se realmente houver as divergências ficamos à disposição para realizarmos as alterações

Obrigado

**Comment by rafd75** [comment]
@krgm03 bom dia! ... 

Kleber, eu que fiz o Santander. Por favor, aguarde até a tarde, vou olhar o meu manual e ver se não foi erro.

Te retorno ainda hoje...

**Comment by krgm03** [comment]
Ok

ainda em tempo, constatei que todas as posições das informações dentro do método LerDetalheRetornoCNAB240SegmentoT estão em desacordo com o documento 'Layout de Arquivo Padrão 240 – Cobrança Versão 2.8 Fevereiro/2016' 

Se precisar podemos enviar o pdf

Obrigado

**Comment by rafd75** [comment]
Com essa sua afirmação, certamente tem 2 layouts.

Lembro que, quando fiz, usei um manual... e ao fazer a comparação com o arquivo do cliente, estava tudo fora do padrão. Liguei no suporte... e nada batia... então me mandaram outro manual, refiz, e homologou...

Se eu não estou errando o "banco", deve ser isso.

Por favor, mande esse manual para meu email: rodolfo computar com br

vou comparar com o que eu tenho lá... 

Qual a carteira que você está implementando? é a mesma que eu fiz ?

**Comment by krgm03** [comment]
Enviamos no email conforme você pediu
Obrigado

**Comment by rafd75** [comment]
Confirmado! ... Foi exatamente o que falei acima... 

O meu layout (que fiz a Remessa) é exatamente o mesmo que o seu . Por isso a remessa está batendo... Código do manual: H7815 (está no rodapé do PDF)...

Mas a primeira versão do Santander, eu fiz (tanto a remessa, quanto o retorno) usando o outro manual 
- código H7822 de Agosto/2016...

Enfim... com tudo pronto (usando o manual H7822) fiz a homologação do arquivo. Evidente que deu um monte de problemas (no arquivo remessa)... Então me mandaram um novo manual (o mesmo que o seu - ou seja, atualizado) e então corrigi a remessa. Passou na homologação.

Liberei para o cliente (que solicitou) usar a carteira... Mas ele nunca usou... e acabou ficando o retorno baseado no manual errado - foto abaixo...

**Correção já feita!** - Tem um PR ( #26 ) aguardando a aprovação do @carloscds - ok?

**IMPORTANTE:** @krgm03 - por favor, apenas observe o campo NOSSO NÚMERO - por padrão, tem 7 dígitos + 1 verificador... No retorno, o campo tem 13 posições... Estou considerando que o nosso número esteja alinhado a direita, por isso, desconsiderei 5 posições, li 7 do nosso número e li mais 1 do dígito. Eu não tenho arquivo retorno de exemplo aqui (como disse, meu cliente pediu, mas não usou ainda)... Verifique se está OK essa implementação. (aproveita e veja os demais campos também, não conferi nenhum deles na prática).

![image](https://user-images.githubusercontent.com/11903379/29578938-88ce0d16-8747-11e7-881f-47d4e8c68055.png)

**Comment by krgm03** [comment]
Obrigado pela atenção

no layout 2.8(pdf que te enviei) o 'nosso número' possui 13 digitos(12 + 1) tanto na remessa quanto no retorno

e o arquivo de retorno que tenho aqui bate certinho como o que consta no pdf

**Comment by rafd75** [comment]
Hum.... vc tem razão... são 12 + 1...

Já sei pq está com 7 dígitos... no código de barras, diz o manual que usa "os sete **primeiros** dígitos", e eu entendi "sete dígitos" ... 

me da um minuto...

**Comment by rafd75** [comment]
Pronto... #28 

@krgm03 - acredito que agora esteja tudo OK... Fiz no escuro, os testes passaram.

Acredito que esteja tudo OK (fiz um ajuste no Teste Unitário, pois o nosso número não batia, tinha 5 zeros a menos)... Por favor, faça a homologação do seu cliente e se houver qualquer problema, retorne... OK?

**Comment by krgm03** [comment]
Ok! 

Vamos continuar realizando testes e daremos um feedback por aqui

Muito obrigado!
