### ISSUE TITLE
Nosso número sicredi

### ISSUE THREAD

**Issue by gabrielpotumati** [BoletoNet/boleto2net#253]
Bom dia, estou gerando o arquivo de remessa pro sicredi, e o nosso número tem dado em alguns boletos como inválido. Alguem passou por isso e conseguiu resolver?

**Comment by rafd75** [comment]
Oi @gabrielpotumati ,

Não vou conseguir ajudar nesta carteira, pois é a única que não implementei aqui ainda.

Mas, é bom ficar de olho neste código ai, pois é recorrente o número de issues sobre o Sicredi.

O certo seria passar um pente fino nessa carteira.

**Comment by carloscds** [comment]
@gabrielpotumati Compara a geracao do nosso numero com o do BoletoNet.
