### ISSUE TITLE
DefinirInstrucoes

### ISSUE THREAD

**Issue by flaviogsantos** [BoletoNet/boleto2net#254]
Estou implementando o Boleto2Net para banco Itau, carteira 109. Estou preenchendo a classe DefinirInstrucoes mas só aparece a primeira linha, mesmo enviando True para imprimirValoresAuxiliares.

retorno = classeProxy.DefinirInstrucoes("APOS O VENCIMENTO COBRAR MORA DE R$ 1,00 AO DIA",
                                                        "",
                                                        "01",
                                                        "APOS 05/06/2020 MULTA DE R$ 1,00 ",
                                                        "02",
                                                        "FAVOR ATENTAR PARA INFORMACOES ACIMA. PROTESTAR A PARTIR DO 5º DIA APOS VENCIMENTO.",
                                                        "03",
                                                        "OBRIGADO PELA PREFERENCIA (31)3333 3333",
                                                        True, mensagemErro)

**Comment by rafd75** [comment]
@flaviogsantos , boa noite... 

Faça assim:

retorno = classeProxy.DefinirInstrucoes("APOS O VENCIMENTO COBRAR MORA DE R$ 1,00 AO DIA </br> APOS 05/06/2020 MULTA DE R$ 1,00 </br> FAVOR ATENTAR PARA INFORMACOES ACIMA. PROTESTAR A PARTIR DO 5º DIA APOS VENCIMENTO. </br> OBRIGADO PELA PREFERENCIA (31)3333 3333",
"",
"",
"",
"",
"",
"",
"",
True, mensagemErro)

os parametros 1/2/3 são para você enviar códigos de instruções para o banco (ai tem que consultar cada manual)
