### ISSUE TITLE
Existe alguma função de Cancelar boleto junto ao banco?

### ISSUE THREAD

**Issue by valentimmx** [BoletoNet/boleto2net#255]
Boa tarde, andei pesquisando por aqui e não encontrei nenhuma forma de enviar instrução de baixa/cancelamento de título junto ao banco.

O Boleto2Net tem essa função implementada? Se sim, como proceder?

Grato desde já.

**Comment by renanmthy** [comment]
@rafd75 bom dia.
Muito boa sua dica, vou fazer esse teste e volto aqui pra dizer se deu certo.
Valeu meu querido! Abraço.

**Comment by renanmthy** [comment]
Pessoal estudei o leiaute FEBRABAN aqui e o campo utilizado para enviar essa informação de Baixa é chamado **"Código de Movimento Remessa"**.
Nele é possível informar os seguintes códigos da imagem em anexo.
No meu caso enviei **Boleto2Net.Boleto.CodigoOcorrencia = "02";** e agora estou esperando o retorno do banco p/ ver se deu tudo certo.

Obs.: CodigoOcorrencia vem por padrão "01" no Boleto2Net. É setado no construtor da classe.
![febraban](https://user-images.githubusercontent.com/17087193/84788873-03c74d80-afc6-11ea-8071-dc36cd56b028.PNG)

**Comment by rafd75** [comment]
Perfeito... é isso ai!

Você olhou no arquivo remessa, se foi respeitado o valor da propriedade?
Eu não estou certo disso, mas acho que essa implementação veio depois que a versão inicial do Boleto2Net foi publicada... e não lembro quem fez - mas acho que alterou no método gerar remessa, em todas as carteiras, o fixo "01"  para Boleto.Ocorrencia... 


Da um retorno se funcionou.
