### ISSUE TITLE
Homologação de boleto Itaú

### ISSUE THREAD

**Issue by francismelo** [BoletoNet/boleto2net#256]
Bom dia, estou realizando a homologação de boletos junto ao banco itau, e eles me fizeram algumas considerações no layout de impressão do boleto.
1 - Na mesma linha da literal "Instruções" e mesmo tamanho de fonte, deve ser inserida a mensagem: "(Instruções de responsabilidade do beneficiário. Qualquer dúvida sobre este boleto, contate o beneficiário)";
2 - A Lei Federal nº 12.039, que já está em vigor, exige a inclusão do endereço, da razão social e do CNPJ/CPF do beneficiário ou sacador Avalista* em todos os boletos de cobrança, no recibo do pagador, com o intuito de identificar o prestador do serviço/produto (emitente da nota) e facilitar o contato do pagador com o emissor, quando necessário;
3 - Conforme determinado pelo Banco Central do Brasil, por meio das circulares 3.598 e 3.656, em vigor a partir de 28/06/2013, Deve ser utilizadas às Novas Nomenclaturas nos boletos: Beneficiário: antigo Cedente, Pagador: antigo Sacado, Agencia\Código do Cedente:  Agencia\Código do Beneficiário, Recibo do Pagador: antigo Recibo do Sacado,  fica proibido boletos sem valor  e  sem vencimento,  ou com  as informações “Vencimento à vista” e “Contra apresentação”.

Seriam essas três alterações no layout de impressão do boleto, se vocês aprovarem gostaria de enviar um pullrequest com essas correções.

Desde ja agradeço

Parabéns pelo projeto

**Comment by rafd75** [comment]
@francismelo , bom dia!

item 2 e 3, por se tratar de normas que devem (ou deveriam) se aplicar a todos os bancos, entendendo que seja legal implementar.

o item 1, não ficou claro se é algo do Itaú, ou se aplica a todos os bancos... Nesse caso, fica a nosso critério, acho que se não prejudicar o espaço das instruções, não traria nenhum ponto negativo.

Por mim, ok. Aguarde outras opiniões do pessoal..

**Comment by DuduSantos** [comment]
Ola, pessoal tudo bem, estou fazendo a homologação na API do Itau e estou usando o projeto BoletoNet (Que diga-se de passagem agilizou muito a implementação) Porem o Itau esta pedindo as modificações no boleto conforme o colega acima descreveu. Algumas coisa consegui contornar facilmente porem a questão da  lei 12.039 realmente é um problema, tentei concatenar a informação para caber no banco Beneficiário porem o boleto fica com o layout desconfigurado. Ja teria uma solução para este problema?


![image](https://user-images.githubusercontent.com/39886613/131263253-7e709382-2fa7-4a0b-bb75-a1a3492dc630.png)

**Comment by DuduSantos** [comment]
Moçada verifiquei que isso já ta previsto ou já foi solucionado bata fazer boletoBancario.MostrarEnderecoCedente = true;

porem me surgiu outra duvida gostaria que fosse impresso no boleto a as informações referente ao protesto preenchi as informações em ComplementoInstrucao1 porem não foi impresso nada no boleto as únicas informações que sao impressas no boleto sao da variável MensagemInstrucoesCaixa. Hoje estou concatenando tudo na variável MensagemInstrucoesCaixa e adicionando quebra de linha mais acredito que não seria essa a melhor forma de fazer.... Alguém poderia me dar uma orientação?

**Comment by rafd75** [comment]
@DuduSantos bom dia.

Sobre a mensagem, é isso mesmo... 

**Se não me engano**, no BoletoNet (a primeira versão), ele interpreta os códigos de protesto, etc, e automaticamente gera a mensagem. Mas o problema de usar esse tipo de lógica é que cada banco usa um código de instrução diferente, a mensagem pode ser diferente, e ainda o caso de querer destacar a mensagem de protesto sem incluir a instrução de protesto para o banco.

O principal motivador de gerar a versão 2 da biblioteca era padronizar o código de todos os bancos/carteiras e deixar que as aplicações controlassem a lógica, ficando com o Boleto2Net apenas a função de gerar o boleto/remessa e ler o retorno.
