### ISSUE TITLE
Duvida Geral

### ISSUE THREAD

**Issue by santosvda** [BoletoNet/boleto2net#257]
Consigo usar o projeto Boletos2Net apenas para gerar o arquivo de remessa e continuar todo resto com o BoletosNet?

**Comment by rafd75** [comment]
@santosvda boa tarde!

Acredito que sim... Você iria simplesmente popular a coleção de boletos (no Boleto2Net) e depois gerar a remessa.... e fim.

Se for imprimir, você iria utilizar o BoletoNet como já implementado no seu sistema.

Fique atento em gravar o nosso número entre outros detalhes que não podem ter diferença entre o impresso e o arquivo remessa.

**Comment by santosvda** [comment]
O projeto emite boletos com o BB, Itáu, Santander e Bradesco, para todo o projeto estou utilizando o BoletoNet e apenas na parte de gerar arquivo de remessa CNAB240 para o Bradesco utilizei o Boleto2Net. Até então consegui gerar tudo normalmente, ainda não testei com o Banco, mas acredito que está tudo correto. Minha unica duvida foi ao popular as classes "Sacado" e "Avalista", pois até então meu entendimento era que Sacado e Avalista é quem paga o boleto, então preenchi ambas as tabelas com os mesmos dados.
