### ISSUE TITLE
Impressão de vários boletos em 1 pdf com Boleto2Net?

### ISSUE THREAD

**Issue by MrFurlan** [BoletoNet/boleto2net#258]
Boa tarde pessoal,

alguém já fez a impressão de vários boletos em 1 pdf com Boleto2Net?

 'Gera 1 Boleto em 1 PDF
            For Each b In Boletos
                Dim BoletoBancario = New Boleto2Net.BoletoBancario With {.Boleto = b}
                Dim pdf = BoletoBancario.MontaBytesPDF(False)

                Dim historico As String() = Titulo.Historico.Split(",")
                nomePDF = historico(0).Replace("REF.", "").Replace("-1-S", "").Replace(Environment.NewLine, "")
                If Not nomePDF.Contains("AGRUPAMENTO") Then
                    nomePDF += " " & historico(1).Replace("/", " de ").Replace(Environment.NewLine, "") & " " & Titulo.Cliente.Nome
                Else
                    nomePDF += " " & Titulo.Cliente.Nome & " - " & Titulo.Prorrogacao.ToString("dd-MM-yyyy")
                End If

                Dim pathPDF = Server.MapPath("Boletos/" & nomePDF & ".pdf")
                File.WriteAllBytes(pathPDF, pdf)
            Next

Alguma sugestão?

**Comment by rafd75** [comment]
https://github.com/BoletoNet/boleto2net/blob/855c6e605e9663c8ae2307cc685162d0448492f6/Boleto2.Net.Testes/Utils.cs#L199

**Comment by rafd75** [comment]
Ops... acho que o exemplo no projeto de Testes gera PDF individual...

Veja esse:

https://github.com/BoletoNet/boleto2net/blob/855c6e605e9663c8ae2307cc685162d0448492f6/Boleto2.Net/Boleto2NetProxy.cs#L541

**Comment by MrFurlan** [comment]
Olá Rodolfo,

 

Sim é individual, assim já faço também...

 

Preciso gerar vários e fazer a impressão em apenas 1 pdf.

 

Se achar algo agradeço...

 

Marcos.

 

De: Rodolfo Duarte <notifications@github.com> 
Enviada em: quinta-feira, 25 de junho de 2020 17:40
Para: BoletoNet/boleto2net <boleto2net@noreply.github.com>
Cc: MrFurlan <mrfurlan10@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [BoletoNet/boleto2net] Impressão de vários boletos em 1 pdf com Boleto2Net? (#258)

 

Ops... acho que o exemplo no projeto de Testes gera PDF individual...

Veja esse:

https://github.com/BoletoNet/boleto2net/blob/855c6e605e9663c8ae2307cc685162d0448492f6/Boleto2.Net/Boleto2NetProxy.cs#L541

**Comment by rafd75** [comment]
O da classe Proxy está pronto para fazer N boletos em 1 PDF... 

Basicamente vc faz o loop em todos os bolestos, gerando o HTML e concatenando todos eles... no final, transforma esse HTML unico em pdf.

**Comment by MrFurlan** [comment]
Teria um exemplo para enviar?

**Comment by MrFurlan** [comment]
Olá Rodolfo,

 

Teria um exemplo para enviar?

 

De: Rodolfo Duarte <notifications@github.com> 
Enviada em: quinta-feira, 25 de junho de 2020 19:09
Para: BoletoNet/boleto2net <boleto2net@noreply.github.com>
Cc: MrFurlan <mrfurlan10@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [BoletoNet/boleto2net] Impressão de vários boletos em 1 pdf com Boleto2Net? (#258)

 

O da classe Proxy está pronto para fazer N boletos em 1 PDF...

Basicamente vc faz o loop em todos os bolestos, gerando o HTML e concatenando todos eles... no final, transforma esse HTML unico em pdf.

**Comment by rafd75** [comment]
Já copiei aqui ... logo acima... 

Primeiro mandei o link da classe de teste (que faz 1 boleto por pDF) e logo abaixo, o link para a classe Proxy, que implementa a geração de todos os boletos em um só PDF.

**Comment by renanmthy** [comment]
Segue abaixo o exemplo que utilizo.
Passar a propriedade **FormatoCarne = true**

`public static byte[] GerarPDFBoletos(List<Boleto> boletos, bool imprimirModoCarne = false)
            {
                StringBuilder htmlBoletos = new StringBuilder();
                htmlBoletos.Append("<html><head>");
                htmlBoletos.Append("<style type='text/css' media='screen,print'>");
                htmlBoletos.Append(".break{ display: block; clear: both; page-break-after: always;}");
                htmlBoletos.Append("</style></head><body>");

                foreach (var boleto in boletos)
                {
                    var boletoTmp = new BoletoBancario()
                    {
                        Boleto = boleto,
                        OcultarInstrucoes = true,
                        MostrarComprovanteEntrega = false,
                        MostrarEnderecoCedente = true,
                        ExibirDemonstrativo = true,
                        
                        FormatoCarne = true
                    };

                    if(!imprimirModoCarne)
                        htmlBoletos.Append("<div class='break'>");

                    htmlBoletos.Append(boletoTmp.MontaHtmlEmbedded(false, true));
                    htmlBoletos.Append("</div>");
                }

                htmlBoletos.Append("</body></html>");

                return new NReco.PdfGenerator.HtmlToPdfConverter().GeneratePdf(htmlBoletos.ToString());
            }`

**Comment by MrFurlan** [comment]
Olá Rodolfo,

 

Não tinha visto .... implementei e deu certo, muito obrigado pela ajuda.

 

De: Rodolfo Duarte <notifications@github.com> 
Enviada em: quinta-feira, 25 de junho de 2020 22:24
Para: BoletoNet/boleto2net <boleto2net@noreply.github.com>
Cc: MrFurlan <mrfurlan10@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [BoletoNet/boleto2net] Impressão de vários boletos em 1 pdf com Boleto2Net? (#258)

 

Já copiei aqui ... logo acima...

Primeiro mandei o link da classe de teste (que faz 1 boleto por pDF) e logo abaixo, o link para a classe Proxy, que implementa a geração de todos os boletos em um só PDF.

**Comment by MrFurlan** [comment]
Olá Renan,

 

grato pela ajuda, implementei e deu certo...

 

De: renanmthy <notifications@github.com> 
Enviada em: sexta-feira, 26 de junho de 2020 16:42
Para: BoletoNet/boleto2net <boleto2net@noreply.github.com>
Cc: MrFurlan <mrfurlan10@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [BoletoNet/boleto2net] Impressão de vários boletos em 1 pdf com Boleto2Net? (#258)

 

Segue abaixo o exemplo que utilizo.
Passar a propriedade FormatoCarne = true

`public static byte[] GerarPDFBoletos(List boletos, bool imprimirModoCarne = false)
{
StringBuilder htmlBoletos = new StringBuilder();
htmlBoletos.Append("");
htmlBoletos.Append("<style type='text/css' media='screen,print'>");
htmlBoletos.Append(".break{ display: block; clear: both; page-break-after: always;}");
htmlBoletos.Append("</style>");

            foreach (var boleto in boletos)
            {
                var boletoTmp = new BoletoBancario()
                {
                    Boleto = boleto,
                    OcultarInstrucoes = true,
                    MostrarComprovanteEntrega = false,
                    MostrarEnderecoCedente = true,
                    ExibirDemonstrativo = true,
                    
                    FormatoCarne = true
                };
 
                if(!imprimirModoCarne)
                    htmlBoletos.Append("<div class='break'>");
 
                htmlBoletos.Append(boletoTmp.MontaHtmlEmbedded(false, true));
                htmlBoletos.Append("</div>");
            }
 
            htmlBoletos.Append("</body></html>");
 
            return new NReco.PdfGenerator.HtmlToPdfConverter().GeneratePdf(htmlBoletos.ToString());
        }`

**Comment by MrFurlan** [comment]
Agradeço a ajuda do Rodolfo e Renan, sugestão foi implementada e funcionou 100%.
