### ISSUE TITLE
Alterar leiaute de Impressão em modo Carnê

### ISSUE THREAD

**Issue by renanmthy** [BoletoNet/boleto2net#259]
Boa tarde amigos.
Gostaria de saber se tem alguma forma de eu ajustar a impressão dos boletos.
Quero remover uns espaços em branco da impressão em modo Carnê para que caibam 3 boletos na mesma folha.
Atualmente está gerando assim: (Com esse baita espaço entre os boletos)
![image](https://user-images.githubusercontent.com/17087193/85897416-a656ac00-b7d0-11ea-8944-08d69469859f.png)

**Comment by renanmthy** [comment]
Bom dia galera.
Achei uma maneira de corrigir esse espaçamento, é nos arquivos **Html.resx** e **BoletoNet.css**.
Fiz a correção porém não faço ideia de como mandar um pr aqui pro git.
**Alguém aqui que possa ajudar a subir essa correção pra mim?**
Segue abaixo o resultado da correção:
**MODO COBRANÇA 12 PARCELAS**
[MODO COBRANÇA 12 PARCELAS.pdf](https://github.com/BoletoNet/boleto2net/files/4845566/MODO.COBRANCA.12.PARCELAS.pdf)
**MODO CARNÊ 12 PARCELAS**
[MODO CARNÊ 12 PARCELAS.pdf](https://github.com/BoletoNet/boleto2net/files/4845567/MODO.CARNE.12.PARCELAS.pdf)

**Comment by rafd75** [comment]
@renanmthy , bom dia.

Eu utilizo a impressão "cobrança" (ou seja, não é carnê) desde que o projeto foi publicado, e nunca tive problemas quanto a quebra de página, mesmo quando gero 12 vencimentos em um único PDF.

Qual foi exatamente a alteração que você fez, pois isso pode quebrar o que já estava funcionando.

**Comment by renanmthy** [comment]
@rafd75 bom dia.
Eu não encontrei essa opção de cobrança que você implementa. Poderia me enviar um exemplo?
Alterei uma margem do CSS e removi uns espaços em branco que gerava no Html.resx.
Me envie um exemplo da sua implementação que eu dou revert aqui nas minhas alterações.

**Comment by rafd75** [comment]
@renanmthy 

O exemplo está aqui:
https://github.com/BoletoNet/boleto2net/blob/855c6e605e9663c8ae2307cc685162d0448492f6/Boleto2.Net/Boleto2NetProxy.cs#L542

É só fazer um ForEach em cada boleto da coleção, usando o <DIV> que tem nesse loop ai...
Depois que fez isso com todos os boletos, então sai do ForEach e na sequencia gera o PDF.

![image](https://user-images.githubusercontent.com/11903379/86138611-0f863a00-bac5-11ea-9864-4a7d947d9b3f.png)

**Comment by renanmthy** [comment]
@rafd75 voce pode me mandar um PDF emitido pelo seu método com os boletos em modo carnê pra eu ver como deveria ficar aqui?

Grato

**Comment by rafd75** [comment]
@renanmthy - eu  não uso o modo "carnê" ... 

Sempre emito 1 boleto por folha.

**Comment by renanmthy** [comment]
@rafd75  bom dia.
Então, as alterações que fiz foram no CSS, ja testei com o modelo cobrança e continua funcionando.
Pra eu dar commit aqui preciso justificar algo nos comentários do código?

**Comment by rafd75** [comment]
Faz o Pull Request dos arquivos alterados... 

Foi só o CSS mesmo? Não lembro de cabeça, mas tem HTML a parte...

As diferenças no arquivo serão apontadas pelo GIT assim que vc fizer o pull request.

**Comment by renanmthy** [comment]
@rafd75 como faço pra integrar meu working copy que tenho referenciado aqui em meu projeto com o git pra eu poder dar o pull?

**Comment by renanmthy** [comment]
Tenho as alterações aqui porém o projeto está na solution do meu ERP. Como faço para linkar com o git e dar commit nesse projeto?

**Comment by carloscds** [comment]
@renanmthy Você precisa baixar o codigo aqui do GitHub e depois atualizar os seus arquivos. Feito isto só mandar um pul request da sua conta do Git para esta.

**Comment by renanmthy** [comment]
Pessoal fiz a correção necessária p/ imprimir 3 boletos em 1 A4.
Veja o ticket  #266
