### ISSUE TITLE
Rateio de credito no arquivo de remessa Bradesco

### ISSUE THREAD

**Issue by francismelo** [BoletoNet/boleto2net#260]
Boa tarde, gostaria de saber se é possível adicionar o tipo de transação 3  no arquivo de remessa do banco Bradesco para rateio de crédito. Vi no código que existem apenas os registros de transação 1 para os dados do boleto e do tipo 2 que são referentes a mensagens. Também não encontrei nenhuma propriedade na classe de boleto que indica a possíbilidade de rateio de crédito

**Comment by carloscds** [comment]
@francismelo Você pode fazer a mudança e manda o PR.

**Comment by francismelo** [comment]
Muito obrigado Carlos,vou começar a fazer
