### ISSUE TITLE
Boleto Caixa com Codigo Cedente com 7 posições

### ISSUE THREAD

**Issue by ThalisonSantos** [BoletoNet/boleto2net#261]
Bom dia, fui implementar boleto num cliente e descobri que a caixa agora esta com código cedente com 7 posições e o boleto2net não esta prevendo isso

**Comment by rafd75** [comment]
@ThalisonSantos , bom dia.

Eles atualizaram o manual? O que foi alterado?

Provavelmente isso muda o arquivo remessa, e também os cálculos de dígito verificador, código de barras, etc.
Precisa de redobrar o cuidado ao implementar esse ajuste.

Seria prudente inclusive, após implementar, manter o teste unitário atual e adicionar uma nova bateria de testes considerando 7 dígitos.

**Comment by ThalisonSantos** [comment]
@rafd75 o gerente passou pro cliente esses manuais, não tenho conhecimento do boleto2net suficiente para fazer essa implementação
[MO67118016_leiaute_cnab240.pdf](https://github.com/BoletoNet/boleto2net/files/4852304/MO67118016_leiaute_cnab240.pdf)
[MO67119010_especificacao_boletos.pdf](https://github.com/BoletoNet/boleto2net/files/4852305/MO67119010_especificacao_boletos.pdf)

**Comment by rafd75** [comment]
@ThalisonSantos ... eu não consigo fazer isso agora.

Estou atolado de pendências aqui, sem chance até de agendar isso.

Precisa ver se alguém tem disponibilidade.

**Comment by ThalisonSantos** [comment]
@rafd75 sem problemas, sei que vcs fazem isso pra ajudar o pessoal

**Comment by ThalisonSantos** [comment]
depois de análise vi que talvez não seja necessário fazer modificações , vou fechar a issue qualquer coisa abro novamente.

**Comment by jader1313** [comment]
@ThalisonSantos poderia detalhar como você resolveu a questão do convênio de 7 dígitos?

**Comment by danibraganca** [comment]
@ThalisonSantos estou com o mesmo problema, vc resolveu de que forma?
