### ISSUE TITLE
Modificações efetuadas no codigo

### ISSUE THREAD

**Issue by integrasysnet** [BoletoNet/boleto2net#263]
Fiz algumas modificações na classe  BancoCaixa.cs, nos métodos de geração de Header e Segmento "´P" para se adequar ao novo layout da CEF, com código de cedente de 7 posições.
Como faço para enviar para a equipe que gerencia o código?

**Comment by carloscds** [comment]
@integrasysnet Você precisa enviar um Pull Request

**Comment by renanmthy** [comment]
@carloscds fiz uma alteração aqui tambem e ao tentar dar o Push pelo Visual Studio, da a seguinte mensagem:
Você poderia me ajudar?
![Boleto2 Net - Microsoft Visual Studio](https://user-images.githubusercontent.com/17087193/87425046-67d43600-c5b3-11ea-8460-8fa10459b9a4.jpg)

**Comment by carloscds** [comment]
@renanmthy você nao pode mandar Push na master do projeto, Precisa fazer um fork para sua conta do Git.
