### ISSUE TITLE
RETORNO SICOOB - Campo "Boleto.ValorJurosDia" vindo com Multa + Juros?

### ISSUE THREAD

**Issue by renanmthy** [BoletoNet/boleto2net#264]
Boa tarde pessoal

No leiaute febraban está informando que as posições 18 à 32 vem somado Juros/Multa/Encargos e tem o nome de "Acrescimos" :
![image](https://user-images.githubusercontent.com/17087193/87059094-47852f80-c1df-11ea-9ab7-10e8eecba9af.png)

Porém no Boleto2Net, esse valor é adicionado somente ao campo **Boleto.ValorJurosDia**, logo passa-se a impressão de que não ocorreu a multa no boleto, pois o campo **Boleto.ValorMulta** vem sempre zerado quando se trata do Sicoob.

**A dúvida é:** Este comportamento realmente está correto ou deveriamos fazer uma correção no Boleto2Net para que ele separe Juros e Multa em seus devidos campos, com base na porcentagem de Juros e Multa que informamos na **remessa**?

Obs.: Essa duvida surgiu porque meu ERP grava Juros e Multa em campos separados, e percebi que NUNCA estava salvando o valor da multa, somente os Juros.
![image](https://user-images.githubusercontent.com/17087193/87060528-042bc080-c1e1-11ea-9794-b470da435088.png)

Obs.: Tem uma parte desse meu questionamento na ultima interação com o ticket #184 , e gostaria de complementar aqui.
https://github.com/BoletoNet/boleto2net/issues/184#issuecomment-650164395

Grato desde já

**Comment by rafd75** [comment]
@renanmthy , boa tarde.

Seria ótimo separar. Mas eu não me recordo de identificar isso de forma separada no arquivo retorno...
Aqui trabalho com o Bradesco..  e se não me engano, ele soma tudo e manda no arquivo retorno o valor agrupado... (não manda separado)... 

Não sei dizer dos outros bancos... Da uma olhada no arquivo retorno e veja se vc identifica os valores separados...

**Comment by renanmthy** [comment]
@rafd75 boa tarde,
Ja verifiquei e vem tudo junto, de acordo com o leiaute febraban que postei acima.
Também verifiquei como seria feito o calculo no boleto2net automaticamente pra vir separado os valores, porém o Retorno Sicoob não retorna a porcentagem de Multa e Juros que foi informada na Remessa, logo não tem um parametro para fazer o calculo, somente o valor total de Acrescimos mesmo.
Atualmente estou fazendo o calculo dentro do meu ERP, pois tenho gravado a porcentagem que foi enviada na Remessa, porém nunca bate os valores do calculo com o total que veio no Retorno.

Segue o código que uso pra fazer a separação:
```
//Boleto2Net.Boleto boleto = new Boleto2Net.Boleto();
//var boletoFromSistema    = Boleto que vem do meu Contas a Receber, nele tenho os percentuais de Multa e Juros informado na Remessa

if (boleto.ValorJurosDia > 0)
{
	decimal Multa = (boleto.ValorTitulo * (boletoFromSistema.PercentualMulta / 100)); 
	decimal Juros = (boleto.ValorJurosDia - Multa);
	
	decimal diasAtraso = Convert.ToDecimal((boleto.DataProcessamento - boleto.DataVencimento).TotalDays);
	decimal jurosPrevistoAoDia = (boleto.ValorTitulo * (boletoFromSistema.PercentualJuros / 100));
	decimal totalPrevistoDoJuros = diasAtraso * jurosPrevistoAoDia;
	decimal diferencaJurosDoRetornoEJurosPrevisto = totalPrevistoDoJuros - Juros;
	
	if(diferencaJurosDoRetornoEJurosPrevisto > 0)
	{
	    //Sempre da alguma diferença aqui.
	}
}
```

**Comment by rafd75** [comment]
@renanmthy ... 

Rapaz......... eu não iria por esse caminho não ... kkk 

Se um banco truncar, e outro arredondar, já ferrou tudo.

Aqui eu gravo em um campo só...  Pelo menos não tive reclamação de clientes ainda.. .mas sei como é, sempre aparece um...

boa sorte!

**Comment by renanmthy** [comment]
@rafd75 então os clientes aqui requisitam saber o que é Juros e o que é Multa, ai por mais que explique que o banco manda tudo junto, ja sabe né. kkk
Bom, por hora vou deixar em aberto aqui, se aparecer mais alguem pra colaborar com ideias estamos aqui.

Obrigado pela atenção, abraço!

**Comment by rafd75** [comment]
@renanmthy , entendo ... sei como é.

seguinte: considerando que o valor é a soma de multa+juros (e nada além disso), eu faria assim:

Pega o valor original do título, e calcula a multa. ... e consideraria a diferença como juros. Simples assim.

Tem o lance do truncar/arredondar... mas a diferença seria centavos...

E ainda (TALVEZ) a possibilidade de algum banco somar algum outro acerto nesse campo. Aqui você teria uma diferença maior, se acontecesse isso.

Abs!

**Comment by renanmthy** [comment]
@rafd75 ja é isso que faço, veja acima como atribuo a variavel Juros.
O restante do calculo é só pra ver a diferença entre os Juros retornados do banco com o Juros calculado manualmente pelo sistema (Taxa de Juros * Quantidade de Dias de Atraso).
Por hora vou continuar usando assim como ja é, até que encontre uma maneira mais eficiente de obter os valores.
