### ISSUE TITLE
usando dll Boleto2Net com fox pro

### ISSUE THREAD

**Issue by ThiagoRodrigues22** [BoletoNet/boleto2net#265]
Gostaria de saber se alguem ja implementou essa dll no fox pro, caso sim, alguem teria documentação ou algum exemplo?
para criacao do boleto(pdf) e da geracao de remessa(txt)
desde ja agradeço.

**Comment by rafd75** [comment]
OPA! ... Essa é fácil kkk.

Dica: Boleto2Net.DLL deve estar na mesma pasta do seu EXE (e faça o registro dela no windows)
O comando para registrar é esse:
v4.0.30319\RegAsm.exe Boleto2Net.dll



Segue a sintaxe, mais ou menos por aqui (desculpe a pressa):

oBN = CreateObject("Boleto2NetProxy")
e depois, na sequencia, utilize esses métodos:

oBN.SetupCobranca( ... )

--- aqui começa o LOOP com os boletos da remessa...
m.msgErro = ""
If This.oBN.NovoBoleto(@msgErro) = .F.
	Return "Novo Boleto (BN): "+m.MsgErro
EndIf

oBN.DefinirSacado( ...
oBN.DefinirBoleto( ...
oBN.DefinirMulta( ...
oBN.DefinirJuros( ...
oBN.DefinirInstrucoes( ...
oBN.FecharBoleto( ...

--- fim do LOOP... (já preencheu a coleção dos boletos).

--- agora gerar a remessa:

oBN.GerarRemessa(

--- fim.

**Comment by ThiagoRodrigues22** [comment]
opaaa, parece ser bem tranquilo, mas me tira uma duvida, onde consigo localizar os paramentros das funcoes da dll, eu consegui baixar e gerar a dll pelo visual agr so me resta a duvida de como passar, os comandos que vc me mandou eu entendi, preciso so saber onde encontro as passagem de parametro(campos). 

exemplo:
obn.DefinirCedente(cnpj,nome,end,nro...)
oBN.DefinirSacado( cnpj,nome,end,nro.....)


caso tenha algum exemplo e quiser me enviar por email serei muito grato.

rthiagovision@gmail.com

**Comment by rafd75** [comment]
@ThiagoRodrigues22 bom dia...

Veja a classe "Proxy", no próprio Boleto2Net - segue o link do "SetupCobranca" - mas todos os outros métodos estão nessa mesma classe:

https://github.com/BoletoNet/boleto2net/blob/0cc75bf72a8a147f170c6ffdb70e40599d0a8317/Boleto2.Net/Boleto2NetProxy.cs#L23

**Comment by ThiagoRodrigues22** [comment]
estou conseguindo da andamento, so estou com um problema e nao estou conseguindo identificar, na funcao 'oBN.FecharBoleto(@msgErroDefinSacado)' esta me retornando um erro que nao estou achando no codigo da dll, 
erro: 'A cadeia de caracteres de entrada não estava em um formato correto.'
como encontro essas mensagem de erros?

**Comment by rafd75** [comment]
Isso já aconteceu comigo, mas não me lembro ao certo...

Tenta fazer um teste no C# mesmo (rodar o projeto de teste)... sinceramente não lembro o que era... talvez erro de versão de alguma outra dll que ele precise... não lembro mesmo.
