### ISSUE TITLE
Layout diferente de boleto

### ISSUE THREAD

**Issue by kleberlsantos** [BoletoNet/boleto2net#267]
Olá pessoal!
Quero deixar primeiro meus agradecimentos aos idealizadores e mantenedores desse Git...
Poderiam me informa como posso fazer um boleto diferente dos formatos apresentados.... a ideia é na parte do recibo do Pagador fosse impresso o demostrativo do serviço pago..

,Att Kleber Santos

**Comment by rafd75** [comment]
@kleberlsantos , bom dia... 

Da uma olhada nisso... Eu não uso aqui, então não sei te passar maiores detalhes.
Acredito que seja o que está procurando.

Se for isso mesmo, seria legal desenvolver um teste unitário desse modelo de impressão, até para servir como documentação para o pessoal que quiser implementar depois...

https://github.com/BoletoNet/boleto2net/blob/75071b13a1c4bdc8a6cef2ffa6263c943500f7a3/Boleto2.Net/BoletoImpressao/BoletoBancario.cs#L285

**Comment by kleberlsantos** [comment]
@rafd75 , man que rapidez na resposta... não tive nem tempo de ir ao banheiro.. kkkk
muito obrigado..eu vou dá uma olha irmão.. 
de qualquer forma vou anexei um modelo do que preciso
![exemploBoleto](https://user-images.githubusercontent.com/31196112/87540400-05903980-c676-11ea-9636-43c3bc164a09.png)

Att. Kleber Santos

**Comment by rafd75** [comment]
Me lembro desse modelo ai... CobreBemX, não é? Se não for, é igual...

Da uma olhada no recurso que te passei... Pode não ser exatamente igual, mas deve chegar no resultado.

Depois se funcionar, veja se consegue o teste unitário com uns exemplos para a gente incluir no projeto.

abs

**Comment by kleberlsantos** [comment]
Ok amigo.. mas uma vez. obrigado.. ainda estou no meio da implementação para incluir a impressão no meu projeto... então vou estar utilizando o modelo disponível de depois que tudo estiver ok eu parto para essa customização...
Att Kleber Santos
