### ISSUE TITLE
Erro ao gerar GerarHeaderLoteRemessaCNAB240 - Sicoob

### ISSUE THREAD

**Issue by MatheusJordao** [BoletoNet/boleto2net#269]
Bom dia,

De acordo com o validador do Sicoob está apresentando o erro: "Valor informado diverge do valor default definido para o campo: espaços em branco":

![image](https://user-images.githubusercontent.com/44534738/87682180-e963c980-c755-11ea-9ade-c79f2a376d34.png)

Vocês poderiam efetuar a correção de preenchimento?

![image](https://user-images.githubusercontent.com/44534738/87682312-12845a00-c756-11ea-8e80-a3747f5d2bf2.png)

**Comment by rafd75** [comment]
@MatheusJordao bom dia.

Na minha versão (local aqui), o código está correto (com espaço)...
Olhei meu manual, e de fato diz o mesmo (com espaço)...

Então fui ver o que ocorreu:

Em resumo:
A issue #208 
acabou gerando os PRs
 #209 
e
 #210 

@OdairPedro-HBSIS - O problema proposto (abaixo)

_Ao validar os arquivos no banco recebi o retorno de que o digito verificador da conta estava sendo preenchido com char space ao invés de zero, que é o recomendado pelo Sicoob._

tem como solução ideal que você informe o dígito (no seu caso, ZERO) nesta propriedade: Cedente.ContaBancaria.DigitoConta - Provavelmente você não está setando essa propriedade e por isso ocorreu o erro. Verifique isso no seu código.

Mas a solução proposta foi fixar "zero" na montagem do arquivo remessa...

https://github.com/BoletoNet/boleto2net/commit/6a53d3a4a187e49fd4bf15c4479467c2f4c83765#diff-345086fe29b9e5597d5f1706990e15f5

e depois:
https://github.com/BoletoNet/boleto2net/commit/1263f6caf9e0c6de15dc00f78752d479441e6651#diff-345086fe29b9e5597d5f1706990e15f5


@carloscds - Reverti o PR.

**Comment by MatheusJordao** [comment]
Certo, baixei o projeto local e realmente está preenchendo corretamente, vou encerrar a issue.

Obrigado pela ajuda.
