### ISSUE TITLE
[DÚVIDA] Banco do Brasil - Variações de Carteira (019, 027, 035...)

### ISSUE THREAD

**Issue by renanmthy** [BoletoNet/boleto2net#275]
Boa tarde pessoal.

Gostaria de saber se as **Variações de Carteira** do Banco do Brasil afetam a estrutura dos arquivos REM/RET, e se realmente há a necessidade de usar a Variação na validação de "Carteira não Implementada", pois se não há diferenças estruturais nos arquivos, creio que seja necessário validar somente a Carteira, sem a variação.

Trecho onde valida Carteira Não Implementada (17/035)
```
if (!CarteiraFactory<BancoBrasil>.CarteiraEstaImplementada(contaBancaria.CarteiraComVariacaoPadrao))
                throw Boleto2NetException.CarteiraNaoImplementada(contaBancaria.CarteiraComVariacaoPadrao);
```

Já pesquisei nos leiautes de particularidades do BB e não encontrei nenhum trecho especificando alguma configuração por "Variação".

Se alguém aqui ja tiver experiencia com isso, por favor relate aqui.

**Comment by rafd75** [comment]
Bom dia.

Aqui só uso a variação 019...
Não conheço bem o BB, e não sei o motivo das variações... Você que está com o problema ai, consegue verificar com o BB quando é usado cada tipo de variação? As vezes é só para definir regras diferentes para uma mesma carteira (ex: cadastrar no próprio banco, um % de multa na variação 019 e não cadastrar na 027... ou ainda não protestar / ou protestar na 035... e assim por adiante).

Se for isso, o layout (REM/RET) deve ser o mesmo para qualquer variação.

Precisaria saber o motivo de existir a variação para a gente ver com segurança o que fazer aqui.

**Comment by MatheusVCoelho97** [comment]
Boa tarde, estou com o mesmo problema, alguém teve alguma novidade sobre a carteira/variação 17/035? 

Obrigado desde já.

**Comment by rafd75** [comment]
@MatheusVCoelho97  - Veja minha mensagem acima...

Não tive retorno do @renanmthy ... mas o primeiro passo é entender o que muda entre as carteiras (código de barras, linha digitável, arquivo remessa/retorno).

**Comment by MatheusVCoelho97** [comment]
Certo, agradeço a disponibilidade, abraço!
