### ISSUE TITLE
Remessa recusada pelo Bradesco

### ISSUE THREAD

**Issue by hbadotti** [BoletoNet/boleto2net#276]
Boa tarde, estou tendo problema em gerar remessa pro Bradesco, eu segui esse exemplo do [Youtube](https://www.youtube.com/watch?v=MNqWe-veMno), fiz a alteração no exemplo para o Banco 237, alterações na carteira e etc etc etc, porém minha remessa está vindo com apenas 5 linhas e na quinta linha ela para no caractere 57 e não no 240...

Como sou novato na programação e no Visual Studio, estou tendo dificuldades para importar pelo NuGet a DLL, o código que baixei desse cara, não reconhece as DLL, mesmo eu colocando as referências e dando Imports...

Tentei pesquisar na internet porém cheguei a um caminho sem saída, estou vindo aqui recorrer a vocês... Obrigado

**Comment by rafd75** [comment]
@hbadotti boa tarde.

Copia o conteúdo do arquivo REM gerado aqui...

**Comment by hbadotti** [comment]
Ele me retorna esses dois arquivos de remessa.

> 75600000         224368434000107                    01234000000001234500EMPRESA COBRADORA             SICOOB                                  10608202015314800000108100000                                                                     
> 75600011R01  040 2024368434000107                    0123400000000123450 EMPRESA COBRADORA                                                                                             000000010608202000000000                                 
> 7560001300001P 010123400000000123450 001234561001014     10 221              2108202000000000002000000000 02N0608202012108202000000000000006712108202000000000000450000000000000000000000000000000012                       3000   090000000000 
> 7560001300002Q 011000003861018250NOME DO PAGADOR                         RUA DA ESQUINA PERDIDA LOGO ALI 569     BAIRRO         14154710CIDADE         SP0000000000000000                                        000                            
> 7560001300003R 01000000000000000000000000000000000000000

Colei aqui o retorno da remessa com todos os espaços, você vê que essa última linha tem apenas 67 posições...

Baixei novamente o código do rapaz do vídeo do youtube, compilei e testei... Nada de alterações... 

[remessa.txt](https://github.com/BoletoNet/boleto2net/files/5037603/remessa.txt)
[remessa2.txt](https://github.com/BoletoNet/boleto2net/files/5037604/remessa2.txt)

**Comment by rafd75** [comment]
@hbadotti ,

O arquivo remessa e remessa2 que você mandou, são do SICOOB (e não do BRADESCO).

**Comment by hbadotti** [comment]
Boa tarde, desculpe... Mas de qualquer maneira, eu tentei gerar a remessa do Bradesco e do Sicoob, do Sicoob foi a última que gerei e mesmo assim ela vem cortada...

**Comment by rafd75** [comment]
Não vou conseguir te ajudar... 

O máximo que consegui aqui, foi ver o código e aparentemente não tem nada de diferente nesse campo... 
Era para ter 15 zeros, e seguir... mas está cortando ali.

Os demais campos estão batendo certinho... 

Você vai precisar depurar isso em tempo de execução para ver o que é... Não tenho nem ideia para te passar.

![image](https://user-images.githubusercontent.com/11903379/90184033-e119a100-dd8a-11ea-9162-a12990eb4935.png)

**Comment by hbadotti** [comment]
Sim! Isso que está me deixando intrigrado, porque na linha que era pra escrever 15 zeros, ele escreve 8 (não lembro exatamente), não faz sentido o código executar uma linha pela metade desse jeito...

Bom, mas de qualquer maneira, o que é "depurar em campo de execução"? E como faço isso?

Muito obrigado.

**Comment by rafd75** [comment]
É colocar um breakpoint na execução do programa e verificar o fluxo ... alguma explicação para isso, tem que ter.

Veja - https://docs.microsoft.com/pt-br/visualstudio/debugger/debugging-absolute-beginners?view=vs-2019

**Comment by hbadotti** [comment]
Boa tarde! Rafd75 eu pesquisei sobre a questão do breakpoint (muito útil, agradeço por isso) porém eu fiz uma comparação da biblioteca que baixei no vídeo e a disponível aqui... Percebi que as duas tem algumas diferenças, porém quando tento importar pra esse projeto em VB.NET, ele aparece vários erros... Não consigo entender como posso implementar isso com meu projeto... Dê uma olhada na foto

![image](https://user-images.githubusercontent.com/34871994/90286642-48475c00-de44-11ea-881d-d000c887dbac.png)

**Comment by rafd75** [comment]
@hbadotti,

Infelizmente não vou conseguir te ajudar com isso.
Minha ferramenta principal não é o C#, e sei só o básico... VB, nunca abri aqui. Sorry.

**Comment by hbadotti** [comment]
@rafd75  Da uma olhada no edit que postei, obrigado

**Comment by rafd75** [comment]
_ele retorna o erro "Não é possível acessar um fluxo fechado", não faço ideia do que se trata..._ 

Eu também não... kkk - como te falei ... uso o C# para coisas pontuais, e quando engrossa, preciso caçar para ver o que é... 

É que você está tentando usar um projeto "pronto" (do vídeo) junto com o componente atualizado... Pode ter problema no projeto, e neste caso não vai rodar mesmo.

**Comment by hbadotti** [comment]
Pois é, ta tenso aqui... Não consigo achar outro projeto pronto pra poder testar... Sou um programador iniciante, preciso de algo pronto para começar a moldar meu programa... Dificil :(
