### ISSUE TITLE
Implementação boleto Safra carteira 1

### ISSUE THREAD

**Issue by Josebr1** [BoletoNet/boleto2net#278]
Pessoal, estou implementando o boleto Safra

Mas ele está sendo gerado por 53 dígitos, o normal seria 48 

Alguém sabe o que está acontecendo?

Se alguém já implementou, pode me dá aquela força?

**Comment by rafd75** [comment]
@Josebr1  - eu uso safra aqui...

Verifique os valores que formam o campo livre --- o problema deve estar em algum deles:

https://github.com/BoletoNet/boleto2net/blob/8fbcbbf0c689e280a31213e743c88f7c5658f9f8/Boleto2.Net/Banco/Carteiras/BancoSafra/BancoSafraCarteira1.cs#L31

**Comment by Josebr1** [comment]
Obrigado @rafd75, o erro estava no campo livre mesmo
