### ISSUE TITLE
Pagamento de cobrança

### ISSUE THREAD

**Issue by Daniel-kenobi** [BoletoNet/boleto2net#282]
Boa tarde pessoal. Eu estou trabalhando em um projeto de contas a pagar da empresa, e gostaria de saber se é possível efetuar pagamento de remessa utilizando o boleto2net. No caso nós temos a linha digitável dos boletos a serem pagos. Se for possível fazer isso quais as informações são necessárias para efetuar o pagamento da remessa  ? porque se precisarmos dos dados bancários do sacado seria um trabalho enorme conseguir as informações bancárias de todos os boletos em aberto

**Comment by rafd75** [comment]
@Daniel-kenobi boa tarde.

O Boleto2Net só faz a parte do "contas a receber" ou melhor "boletos a receber".

Não tem essa parte do "boletos a pagar"

**Comment by Daniel-kenobi** [comment]
Sabe me dizer se a lógica do arquivo de remessa para pagamento seria o mesmo ? Sou estagiário e estou meio perdido em relação a isso, li o manual de remessa do Itaú todo umas duas vezes e ainda parece algo bem complexo pra mim fazer, sabe me dizer se eu conversar com o gerente do banco ele poderá me auxiliar ?

**Comment by Daniel-kenobi** [comment]
E acho pouquíssima documentação disponível sobre contas a pagar, somente de sistemas "grandes" com esse processo já pronto

**Comment by rafd75** [comment]
@Daniel-kenobi nunca trabalhei com esse arquivo.

mas basicamente, tem que ler o manual, entender os campos que são necessários, e ir montando o arquivo texto.

na sequencia, encaminhar para o banco (em homologação) para validar tudo que foi feito e depois acompanhar os primeiros lançamentos em produção.

O banco costuma ter um telefone de suporte, mas para te tirar dúvidas sobre o conteúdo do arquivo, o que não inclui como montar um arquivo texto (isso você pode pegar o modelo de como o arquivo remessa é feito no boleto2net)
