### ISSUE TITLE
Gerar remessas em um único arquivo

### ISSUE THREAD

**Issue by jellyBott** [BoletoNet/boleto2net#289]
Olá, estou com um projeto na empresa e preciso gerar todos os arquivos de remessa em um único arquivo. Alguém tem algum exemplo disponível?

**Comment by rafd75** [comment]
@jellyBott , boa tarde.

Você quer gerar vários boletos em um só arquivo, é isso?

Se for, basta adicionar todos os boletos na coleção, e em seguida executar o método de criar arquivo.

No projeto de teste, existe isso implementado... por exemplo, no Itaú, carteira 109:
https://github.com/BoletoNet/boleto2net/blob/8e114c8fd5aab6d08572cc0341e313707eb1dc1d/Boleto2.Net.Testes/BancoItauCarteira109Tests.cs#L33

**Comment by jellyBott** [comment]
Bom dia, tenho que gerar todos os arquivos de remessa em um arquivo. Vou tentar desse jeito, obrigado.
