### ISSUE TITLE
Separar o core do projeto da impressão.

### ISSUE THREAD

**Issue by joaoluizsouza** [BoletoNet/boleto2net#29]
Não seria melhor seperar em 2 projetos diferentes?

**Comment by carloscds** [comment]
@joaoluizsouza Por quê você acha melhor separar ?

**Comment by joaoluizsouza** [comment]
@carloscds Por exemplo, eu uso só a parte de gerar arquivos e boleta. Caso separe já posso usar no netstandard 2.0.

**Comment by carloscds** [comment]
@joaoluizsouza Manda um PR :-)

**Comment by rafd75** [comment]
@joaoluizsouza - Você está considerando fazer essa separação?
