### ISSUE TITLE
Sicoob Carteira 1/01

### ISSUE THREAD

**Issue by EduardoSSL** [BoletoNet/boleto2net#291]
Olá pessoal tudo bem?

Estou tentando usar o Boleto2.net na versão dll para gerar o arquivo de remessa para o banco Sicoob porem fiquei meio perdido estou recebendo essa mensagem de erro "Campo Livre (1/014351748480000000035001) deve conter 25 dígitos." Será que alguém consegue me dar uma luz sobre o que pode estar acontecendo fico a disposição para fornecer mais informações se necessário. Sou  novato nesse mundo de boleto então acredito que devo estar fazendo algo errado quanto as informações que devo estar usando

**Comment by rafd75** [comment]
@EduardoSSL bom dia!

Veja no código abaixo, quais são as propriedades utilizadas para chegar nos 25 dígitos do sicoob - provavelmente você está usando alguma delas de forma errada:


https://github.com/BoletoNet/boleto2net/blob/ac2467d3a57ac6bd0cbb48f6150938d287229391/Boleto2.Net/Banco/Carteiras/BancoSicoob/BancoSincoobCarteira1.cs#L35

**Comment by EduardoSSL** [comment]
Fala Rodolfo tudo certo? 

Cara olha só pelo que percebi o problema ta nessa função aqui
```

 public string FormataCodigoBarraCampoLivre(Boleto boleto)
        {
            var cedente = boleto.Banco.Cedente;
            var contaBancaria = cedente.ContaBancaria;
            return $"{boleto.Carteira}{contaBancaria.Agencia}{boleto.VariacaoCarteira}{cedente.Codigo}{cedente.CodigoDV}{boleto.NossoNumero}{boleto.NossoNumeroDV}001";
        
        }
```
porem a documentação da Sicoob diz que o campo livre deve ser montado dessa forma
![image](https://user-images.githubusercontent.com/73853567/98050990-aa937580-1e11-11eb-97a7-8e8dd62f5307.png)

sendo assim me parece que esse codigo não é compatível com a documentação, O que o amigo me diz? será que estou interpretando mau? 

Ao meu entender o return deveria ficar algo como este correto?

`return $"01{contaBancaria.Agencia}01{cedente.Codigo}{boleto.NossoNumero}{boleto.NossoNumeroDV}001";`

Outra coisa que me chama a tensão é o final ali 001 ele esta fixo ele não deveria vir de alguma variável para incrementar de acordo com minhas parcelas?

Mais mesmo assim aplicando essa correção que sugeri o erro passa para a geração do arquivo de remessa onde cada linha deveria ter 240 carácter porem algumas tem mais e outras tem menos fico. Rodolfo a disposição e se de alguma forma eu puder contribuir para o projeto ficarei grato

**Comment by rafd75** [comment]
@EduardoSSL , ...

coloca um breakpoint nessa linha do "return ..." e veja qual o valor de cada propriedade que você preencheu o boleto. Deve estar faltando algo. Esse banco eu uso em produção e funciona.

Quanto ao 001 no final, sim, poderia ser o sequencial da parcela. Eu acho que fiz assim, pois não existe(ou não existia) uma propriedade na classe boleto que controle o número da parcela. Dessa forma, ainda que eu emita uma nota fiscal aqui, com 3 parcelas, serão gerados 3 boletos, com "nosso número" em sequencia, e sempre 001 no final. Acho que não faz diferença na prática quanto a isso.

**Comment by EduardoSSL** [comment]
@rafd75, 

Fiz um print aqui com os valores em cada variável tem coisa que me parece estranha tendo em vista aquele trecho da documentação que postei note que onde no campo carteira que é apenas 1 digito esta alocado o valor 1/01
a terceira variável que deveria ser a modalidade esta a variável variacaoCarteira que na verdade acredito que seja usado apenas em boletos do banco do Brasil, mais ela esta vazia e não tem valor nessa concatenação o campo cedente já esta trazendo meu numero da conta + dv (Acredito que aqui pode ser um erro meu) já que o proximo campo é novamente o DV que já estava concatenado. 


![image](https://user-images.githubusercontent.com/73853567/98180049-ec3e2200-1ede-11eb-8d43-181bf18b6a53.png)
 

Vou postar aqui em baixo o trecho de codigo que estou usando para que possa analisar mais claramente. fico a disposição um grande abraço

```
boletos.Banco = Banco.Instancia(Aux.StringToInt(d.cod_banco));
                foreach (var cc in sBancoConta.ListContaBanco)
                {
                    string cedente_agencia = cc.agencia_cod;
                    string cedente_conta = cc.conta_num;
                    string cedente_digitoConta = cc.conta_digito;
                    string cedente_codigo = cc.conta_num + cc.conta_digito;

                    boletos.Banco.Cedente = new Cedente
                    {
                        CPFCNPJ = cedente_cpfCnpj,
                        Nome = cedente_nome,
                        Observacoes = string.Empty,
                        ContaBancaria = new ContaBancaria
                        {
                            Agencia = cc.agencia_cod,
                            DigitoAgencia = cc.agencia_digito,
                            OperacaoConta = string.Empty,
                            Conta = cc.conta_num,
                            DigitoConta = cc.conta_digito,
                            CarteiraPadrao = cc.cod_carteira,
                            VariacaoCarteiraPadrao = "",//this.Conta.VariacaoCarteira, //Apenas Banco do Brasil
                            TipoCarteiraPadrao = TipoCarteira.CarteiraCobrancaSimples,
                            TipoFormaCadastramento = TipoFormaCadastramento.ComRegistro,
                            TipoImpressaoBoleto = TipoImpressaoBoleto.Empresa,
                            TipoDocumento = TipoDocumento.Tradicional
                        },
                        Codigo = cedente_codigo, 
                        CodigoDV = cedente_digitoConta,
                        CodigoTransmissao = string.Empty,

                        Endereco = new Endereco
                        {
                            LogradouroEndereco = cedente_endereco,
                            LogradouroNumero = cedente_logradouro_numero,
                            LogradouroComplemento = cedente_logradouro_complemento,
                            Bairro = cedente_bairro,
                            Cidade = cedente_cidade,
                            UF = cedente_uf,
                            CEP = cedente_cep
                        }

                    };
```

**Comment by rafd75** [comment]
Olhando rápido aqui.... Faça isso:

Boleto.carteira = "1"
Boleto.variacaocarteira ="01"

Veja se resolve

Em qua, 4 de nov de 2020 21:07, EduardoSSL <notifications@github.com>
escreveu:

**Comment by EduardoSSL** [comment]
@rafd75, Cara excelente dessa forma emitiu o arquivo de remessa sem qualquer erro aparente. vou deixar esses valores fixo na classe tendo em vista que cada carteira pelo que entendi vai ter sua propiá classe então acredito que dessa forma atende tranquilamente. Vou fazer as modificações e enviar ao banco para homologação. Fica aqui o meu muito Obrigado! E se puder contribuir de alguma forma fico a disposição...

**Comment by rafd75** [comment]
bom dia @EduardoSSL  ...

Quando você diz "deixar na sua própria classe", eu entendi que é em uma das classes do seu projeto... (e não alterar o código do próprio Boleto2Net para fixar isso, ainda que você tenha feito uma cópia do código em seu projeto) - Digo isso, pq vc vai ter problemas para atualizar sua versão do Boleto2Net no futuro.

Aqui, eu tenho uma tabela (ex: bancos) onde fica cadastrado a carteira e a variação, e uso os dados que estão nessa tabela para preencher as propriedades do Boleto2Net... Ou seja, não existe nada "fixo" na classe, e sim o valor que está no banco de dados.

Acredito que essa seja a melhor implementação... Se amanhã aparecer alguém querendo outra carteira, seria apenas cadastrar o "banco" safra no seu sistema e informar a carteira correta...

**Comment by EduardoSSL** [comment]
Bom dia @rafd75 ,

Perfeito, vou proceder conforme vc indicou, Eu encaminhei o arquivo pro banco e ele me devolveu que tenho que remover os caracteres não numéricos do CEP coisa simples. Porem de repente um uma futura modificação do Boleto2net isso possa ser feito diretamente na biblioteca não que faça grande diferença mais fica interessante que a biblioteca possa lidar com todo o processo sem que o implementador tenha que prestar muita atenção na documentação. Mais a biblioteca esta fantástica codigo muito bem escrito.

Segunda feira vou encaminhar novamente os arquivos ao banco e retorno aqui para fechar o post com o resultado.

**Comment by EduardoSSL** [comment]
Bom dia @rafd75 ,

Boletos homologados!! Obrigado pela ajuda!
