### ISSUE TITLE
Banco Bradesco - Carteira 04

### ISSUE THREAD

**Issue by tbacalhau** [BoletoNet/boleto2net#293]
Boa tarde!

É apenas uma dúvida: tem alguma previsão da implementação da carteira 04 para o banco Bradesco?

Essa é a única carteira que faltaria para eu migrar para o boleto2net, pois ela já implementa as que preciso: Bradesco 09 e Itaú 109 / 112.

Obrigado!

**Comment by rafd75** [comment]
@tbacalhau bom dia.

Não existe uma agenda ou previsão para implementar novos bancos ou novas carteiras...

Isso vai acontecendo com o tempo, de acordo com a necessidade dos usuários da biblioteca...

Se você precisa da carteira 04 do Bradesco, você teria que implementar e em seguida enviar o código para fazer parte do projeto aqui... Se for fazer mesmo, não esqueça de incluir os testes unitários dessa nova carteira.
