### ISSUE TITLE
Gravar um MemoryStream para um FileStream C# 

### ISSUE THREAD

**Issue by alexandrecr** [BoletoNet/boleto2net#294]
Olá,

não consigo gravar um MemoryStream num FileStream C# para gerar o arquivo remessa em C#, resulta nesse erro:
System.ObjectDisposedException: 'Não é possível acessar um fluxo fechado.'

Uso esse código num botão do Windows Forms
Boletos objBoletos = new Boletos();

            objBoletos.Banco = Banco.Instancia(756);
            objBoletos.Banco.Cedente = new Cedente
            {
                CPFCNPJ = "24.368.434/0001-07",
                Nome = "Empresa cobradora",
                Observacoes = "Pague isso logo que estou precisando...rs"
            };
            ContaBancaria conta = new ContaBancaria();
            conta.Agencia = "1234";
            conta.DigitoAgencia = "0";
            conta.OperacaoConta = string.Empty;
            conta.Conta = "12345";
            conta.DigitoConta = "0";
            conta.CarteiraPadrao = "1";

            conta.VariacaoCarteiraPadrao = "01";
            conta.TipoCarteiraPadrao = TipoCarteira.CarteiraCobrancaSimples;
            conta.TipoFormaCadastramento = TipoFormaCadastramento.ComRegistro;
            conta.TipoImpressaoBoleto = TipoImpressaoBoleto.Empresa;
            conta.TipoDocumento = TipoDocumento.Tradicional;

            Endereco ender = new Endereco();

            ender.LogradouroEndereco = "Rua Mamoré";
            ender.LogradouroNumero = "344";
            ender.LogradouroComplemento = "sala 206";
            ender.Bairro = "São João";
            ender.Cidade = "Sertãozinho";
            ender.UF = "SP";
            ender.CEP = "92400000";

            objBoletos.Banco.Cedente.Codigo = "123456";
            objBoletos.Banco.Cedente.CodigoDV = "6";
            objBoletos.Banco.Cedente.CodigoTransmissao = "000000";
            objBoletos.Banco.Cedente.ContaBancaria = conta;
            objBoletos.Banco.Cedente.Endereco = ender;

            objBoletos.Banco.FormataCedente();

            for (int I = 0; I < 1; I++)
            {

                //CRIAÇÃO DO TITULO
                var Titulo = new Boleto(objBoletos.Banco);
                Titulo.Sacado = new Sacado
                {
                    CPFCNPJ = "03861018250",
                    Endereco = new Boleto2Net.Endereco
                    {
                        Bairro = "Bairro",
                        CEP = "14154710",
                        Cidade = "Cidade",
                        LogradouroComplemento = "",
                        LogradouroEndereco = "Rua Da Esquina Perdida Logo Ali",
                        LogradouroNumero = "569",
                        UF = "SP"
                    },
                    Nome = "Nome do Pagador",
                    Observacoes = "Pagar com urgência para não ser protestado."
                };
                Titulo.CodigoOcorrencia = "01";
                Titulo.DescricaoOcorrencia = "Remessa Registrar";
                Titulo.NumeroDocumento = I.ToString();
                Titulo.NumeroControleParticipante = "12";
                Titulo.NossoNumero = "123456" + I.ToString();
                Titulo.DataEmissao = DateTime.Now;
                Titulo.DataVencimento = DateTime.Today.AddDays(15);
                Titulo.ValorTitulo = 200;
                Titulo.Aceite = "N";
                Titulo.EspecieDocumento = TipoEspecieDocumento.DM;
                Titulo.DataDesconto = DateTime.Today.AddDays(15);
                Titulo.ValorDesconto = 45;

                //PARTE DA MULTA
                Titulo.DataMulta = DateTime.Today.AddDays(15);
                Titulo.PercentualMulta = 2;
                Titulo.ValorMulta = Titulo.ValorTitulo * Titulo.PercentualMulta / 100;
                Titulo.MensagemInstrucoesCaixa = $"Cobrar multa de " + Titulo.ValorMulta.ToString() + " após a data de vencimento.";

                //PARTE JUROS DE MORA
                Titulo.DataJuros = DateTime.Today.AddDays(15);
                Titulo.PercentualJurosDia = 10 / 30;
                Titulo.ValorJurosDia = Titulo.ValorTitulo * Titulo.PercentualJurosDia / 100;
                string instrucoes = $"Cobrar juros de " + Titulo.PercentualJurosDia.ToString() + " por dia.";
                if (string.IsNullOrEmpty(Titulo.MensagemInstrucoesCaixa))
                    Titulo.MensagemInstrucoesCaixa = instrucoes;
                else
                    Titulo.MensagemInstrucoesCaixa += Environment.NewLine + instrucoes;

                //Titulo.CodigoInstrucao1 = String.Empty
                //Titulo.ComplementoInstrucao1 = String.Empty

                //Titulo.CodigoInstrucao2 = String.Empty
                //'Titulo.ComplementoInstrucao2 = String.Empty

                //'Titulo.CodigoInstrucao3 = String.Empty
                //'Titulo.ComplementoInstrucao3 = String.Empty
                Titulo.CodigoProtesto = TipoCodigoProtesto.NaoProtestar;
                Titulo.DiasProtesto = 0;
                Titulo.CodigoBaixaDevolucao = TipoCodigoBaixaDevolucao.NaoBaixarNaoDevolver;
                Titulo.DiasBaixaDevolucao = 0;
                Titulo.ValidarDados();
                objBoletos.Add(Titulo);

               // BoletoBancario htmlBoleto = new BoletoBancario();

            }

            if (File.Exists("Arquivos\\remessa.txt"))
                File.Delete("Arquivos\\remessa.txt");

            //GERA ARQUIVO DE REMESSA
            MemoryStream st = new MemoryStream();
            var remessa = new ArquivoRemessa(objBoletos.Banco, TipoArquivo.CNAB240, 1);
            remessa.GerarArquivoRemessa(objBoletos, st);

            
            FileStream arquivo = new FileStream("Arquivos\\remessa.txt", FileMode.CreateNew, FileAccess.ReadWrite);
          
            st.WriteTo(arquivo);
            arquivo.Close();
            st.Close();

SOLUÇÃO:
NA CLASSE ArquivoRemessa
//arquivoRemessa.Close();
//arquivoRemessa.Dispose();
//arquivoRemessa = null;

**Comment by Militao36** [comment]
Opa, eu tive o mesmo erro. Não entendi o porque ai fiz de um outro modo abaixo

```csharp
var str = new MemoryStream();
var remessa = new ArquivoRemessa(objBoletos.Banco, TipoArquivo.CNAB400, 1);
remessa.GerarArquivoRemessa(objBoletos, str);
var dados = Encoding.Default.GetString(str.ToArray());
using (StreamWriter file = new StreamWriter(caminho + "/remessa.txt"))
{
    file.Write(dados);
}
str.Close();
```


Pra mim resolveu ai não precisei comentar esses métodos dentro da modulo do boletonet, pois pensei que podia gerar algum erro futuramente.

**Comment by aldovrando-oliveira** [comment]
Olá, tudo certo? eu implementei dessa maneira e pra mim resolveu
```csharp
using (MemoryStream st = new MemoryStream())
{
    var remessa = new ArquivoRemessa(objBoletos.Banco, TipoArquivo.CNAB240, 1);
    remessa.GerarArquivoRemessa(objBoletos, st);

    var nomeArquivo = Environment.CurrentDirectory + "\remessa.txt";

    if (File.Exists(nomeArquivo))
        File.Delete(nomeArquivo);

    File.WriteAllBytes(nomeArquivo, st.ToArray());
}
```

**Comment by ferreira37** [comment]
> Opa, eu tive o mesmo erro. Não entendi o porque ai fiz de um outro modo abaixo
> 
> ```cs
> var str = new MemoryStream();
> var remessa = new ArquivoRemessa(objBoletos.Banco, TipoArquivo.CNAB400, 1);
> remessa.GerarArquivoRemessa(objBoletos, str);
> var dados = Encoding.Default.GetString(str.ToArray());
> using (StreamWriter file = new StreamWriter(caminho + "/remessa.txt"))
> {
>     file.Write(dados);
> }
> str.Close();
> ```
> 
> Pra mim resolveu ai não precisei comentar esses métodos dentro da modulo do boletonet, pois pensei que podia gerar algum erro futuramente. Dessa forma gerou o arquivo pra mim.

Cara valeu mesmo me ajudou muito. Estava enroscado nessa parte
