### ISSUE TITLE
Freelancer

### ISSUE THREAD

**Issue by rpotalara** [BoletoNet/boleto2net#296]
Caros developers, não encontrei outro lugar para essa dúvida, tenho uma demanda para substituir um componente chamado CobrebemX para outra solução de geração de arquivos de remessa/boleto e leitura de retorno e tenho alguns Bancos e Carteiras que meus clientes necessitam:

**Bradesco** - 09 - Com Registro
**Itaú**- 109 - Direta Eletrônica Sem Emissão - Simples
**Itaú** - 112 - Escritural Eletrônica - simples / contratual
**Banco do Brasil** - 17 - Direta Especial - Com Registro
**Banco do Brasil** - 17Vinculada - Direta Especial Vinculada - Com Registro
**Banco do Brasil** - 17Vinculada-7 - Direta Esp. Vinc. - C/Registro Convênio 7 dígitos
**Banco Cooperativo do Brasil** - 3194 - Crediguaçu
**Banco Cooperativo Sicredi S/A** - A - Simples - Cobrança com Registro

Preciso de desenvolvedores interessados na criação dessas carteiras e bancos e o desenvolvimento da troca do atual componente.

Obrigado e desculpe se não é o local correto.

**Comment by carloscds** [comment]
@rpotalara Você ja verificou no projeto se não tem estes bancos/carteiras.

**Comment by rpotalara** [comment]
> @rpotalara Você ja verificou no projeto se não tem estes bancos/carteiras.

Sim, não tem todos eles. Pelo menos na versão https://github.com/BoletoNet/boleto2net
