### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by thiagokernell** [BoletoNet/boleto2net#297]
Percebi aqui no gerenciador de pacote do visual studio que existe um boleto2.Net, pergunto se posso instalar esse pacote? Ele está atualizado com o que tem no fonte? Ou é mais garantido baixar o fonte diretamente, compilar e adicionar a referência do boleto2 no meu projeto?

**Comment by carloscds** [comment]
@thiagokernell Normalmente atualizado, mas nao diariamente. Par atualizacao mais rapida você pode usar o pacote do MyGet.
