### ISSUE TITLE
CNAB Santader 400 Posições

### ISSUE THREAD

**Issue by WillPvt** [BoletoNet/boleto2net#298]
Bom dia amigos, alguém aqui implementou o CNAB Santander 400 posições? Caso afirmativo, poderiam me passar ?
Desde já agradeço.

**Comment by carloscds** [comment]
@WillPvt no projeto do BoletoNet tem: https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/Banco/Banco_Santander.cs

**Comment by WillPvt** [comment]
dá pra usar os dois ao mesmo tempo ?

**Comment by carloscds** [comment]
@WillPvt Teoricamente sim.

**Comment by rafd75** [comment]
@WillPvt , boa noite.

Da sim ... mas não vai ser uma boa ideia não ... 

Os objetos são diferentes... propriedades diferentes... 

Acho que o caminho mais fácil, é pegar o código que tem pronto no BoletoNet (estou falando da geração e leitura do CNAB no padrão 400) e implementar aqui no Boleto2Net... 

Dessa forma, você não precisaria mudar nada na sua aplicação (considerando que ela já usa o Boleto2Net) e de quebra ficaria pronto para subir aqui no projeto.

**Comment by WillPvt** [comment]
> @WillPvt , boa noite.
> 
> Da sim ... mas não vai ser uma boa ideia não ...
> 
> Os objetos são diferentes... propriedades diferentes...
> 
> Acho que o caminho mais fácil, é pegar o código que tem pronto no BoletoNet (estou falando da geração e leitura do CNAB no padrão 400) e implementar aqui no Boleto2Net...
> 
> Dessa forma, você não precisaria mudar nada na sua aplicação (considerando que ela já usa o Boleto2Net) e de quebra ficaria pronto para subir aqui no projeto.

Até pensei em fazer isso, mas meu chefe disse que não vamos perder tempo com isso, mas caso realmente precise vou fazer isso e subo aqui
