### ISSUE TITLE
Nome do arquivo de remessa

### ISSUE THREAD

**Issue by thiagovalim** [BoletoNet/boleto2net#299]
Olá, existe alguma função para gerar o nome do arquivo de remessa de acordo com o banco? Pois alguns bancos como a caixa e o sicredi exigem nome específicos para o arquivo de remessa.

Ex: Sicredi

Nosso arquivo de remessa seria o 00000D19.CRM na primeira remessa do dia, a segunda seria RM2, RM3 e assim por diante. 00000 é o código do cedente, D é o mês de dezembro e o 19 o dia de hoje. O arquivo tem essa configuração de 8 dígitos e as letras são apenas para os meses com 2 dígitos. Outubro= O, Novembro= N e Dezembro= D. Os outros meses são de 1 a 9.

**Comment by rafd75** [comment]
@thiagovalim bom dia.

Não existe esse recurso no Boleto2Net.

**Comment by thiagovalim** [comment]
olá, já encontrei, existe sim.

ArquivoRemessa.NomeArquivo gera o nome correto do arquivo.

Obrigado

**Comment by rafd75** [comment]
@thiagovalim  -  viche! ... kkk essa passou batido ... 

obrigado por avisar (eu não uso isso aqui, vou considerar)
