### ISSUE TITLE
Criar boleto a partir de arquivo REM

### ISSUE THREAD

**Issue by leonardolb560** [BoletoNet/boleto2net#307]
Olá! Eu tenho alguns arquivos de remessa (.REM) do banco Bradesco, queria saber a viabilidade de criar os boletos a partir dele.

Obrigado desde já!

**Comment by rafd75** [comment]
@leonardolb560 bom dia!

Não existe esse recurso no Boleto2Net... 

Acho que é algo não tão comum, mas outras pessoas já postaram essa necessidade aqui...
Acredito que seria útil se fosse implementada na biblioteca e poderia seguir o mesmo padrão da geração do arquivo CNAB...
Ao invés de GerarRemessa

**Comment by leonardolb560** [comment]
Sim, seria legal porque minha plataforma integra com softwares financeiros que regram o arquivo de remessa, eu preciso apenas apresentar o pdf em tela
