### ISSUE TITLE
NETCoreApp (VS Code)

### ISSUE THREAD

**Issue by EveronBorges** [BoletoNet/boleto2net#308]
Estou tentando implantar o projeto pelo Visual Studio Code, com o banco Sicredi. 
Ao compilar o projeto, retorna o seguinte warning:
**_warning NU1701: O pacote 'Boleto2.Net 2.1.0.430' foi restaurado usando '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' em vez da estrutura de destino do projeto '.NETCoreApp,Version=v3.1'. Esse pacote pode não ser totalmente compatível com o seu projeto._**

E ao tentar gerar uma remessa, ocorre a seguinte exceção:
A message é a seguinte:
_**"The type initializer for 'Boleto2Net.CarteiraFactory`1' threw an exception."**_

E o inner exception é:
**_"Unable to load one or more of the requested types.\r\nCould not load file or assembly 'System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. O sistema não pode encontrar o arquivo especificado.\r\nCould not load type 'System.Web.UI.Control' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.\r\nCould not load type 'System.Web.IHttpHandler' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'."_**

O que me leva a crer que a biblioteca realmente não é compatível com o NETCoreApp. Vocês tem alguma build que seja compatível?
Obrigado, Éveron

**Comment by carloscds** [comment]
@EveronBorges Boleto2Net nao é compativel com .NET Core, somente BoletoNetCore.

**Comment by EveronBorges** [comment]
@carloscds Obrigado, era o que eu precisava.
