### ISSUE TITLE
Gostaria de saber quando irão disponibilizar os retornos e remessa para o Banco Votorantim ?

### ISSUE THREAD

**Issue by samuca12** [BoletoNet/boleto2net#309]

**Comment by rafd75** [comment]
Bom dia @samuca12 ...

Não existe uma agenda de implementação de novos bancos/carteiras no projeto.

Conforme aparece a necessidade dos usuários, como no seu caso, o que normalmente ocorre, é o próprio usuário implementar, testar e então disponibilizar o banco/carteira implementado para o projeto. Foi assim que o BoletoNet chegou até aqui.

Como citado, se é sua necessidade imediata, você precisaria implementar o Votorantim no projeto...
