### ISSUE TITLE
Exemplo C#

### ISSUE THREAD

**Issue by ViniBH** [BoletoNet/boleto2net#31]
Boa tarde!

Tenho um cliente que utiliza Santander (carteira 101 com nosso número de 13 digitos). 

Vi que foi corrigido no Boleto 2 (a versão antiga obriga nosso número de 12 digitos para o Santander), eu utilizo a versão antiga e não estou conseguindo migrar para o Boleto 2.

Alguém poderia disponibilizar um exemplo?

Desde já agradeço. 

Grande abraço e quero contribuir para o projeto também. 

Vinícius.

**Comment by ViniBH** [comment]
Por exemplo, no boleto antigo, utilizava este código para mostrar o título:

                        boleto.ValidarDados();

                        Boletos boletos = new Boletos();

                        boletos.Add(boleto);
                        pnl_boleto.Controls.Add(boletos());

Como seria este código no Boleto2Net?

**Comment by ViniBH** [comment]
Por exemplo, para mostrar o boleto no webForm utilizava o seguinte código:

.
.
.
                        //criando classe boleto bancário, atribuindo o boleto e outras propriedades nela e validando
                        BoletoBancario boleto_bancario = new BoletoBancario();
                        boleto_bancario.CodigoBanco = Convert.ToInt16(dr["NR_BANCO"].ToString());
                        boleto_bancario.Boleto = boleto;

                        boleto_bancario.GeraImagemCodigoBarras(boleto);

                        boleto_bancario.MostrarCodigoCarteira = true;
                        boleto_bancario.Boleto.Valida();
                        boleto_bancario.MostrarComprovanteEntrega = false;


                        pnl_boleto.Controls.Add(boleto_bancario);


Como faço isto no Boleto2net?

**Comment by rafd75** [comment]
@ViniBH - bom dia...

Eu não utilizo com webForm... então não sei exatamente o que seria "pn1_boleto.Controls", mas para emitir um boleto bancario, seria algo assim:

`
                // Banco, Cedente, Conta Corrente
                boletos.Banco = Banco.Instancia(numeroBanco);
                boletos.Banco.Cedente = new Cedente
                {
                    CPFCNPJ = cnpj,
                    Nome = razaoSocial,
                    Observacoes = observacoes,
                    ContaBancaria = new ContaBancaria
                    {
                        Agencia = agencia,
                        DigitoAgencia = digitoAgencia,
                        OperacaoConta = operacaoConta,
                        Conta = conta,
                        DigitoConta = digitoConta,
                        CarteiraPadrao = carteira,
                        VariacaoCarteiraPadrao = variacaoCarteira,
                        TipoCarteiraPadrao = (TipoCarteira)tipoCarteira,
                        TipoFormaCadastramento = (TipoFormaCadastramento)tipoFormaCadastramento,
                        TipoImpressaoBoleto = (TipoImpressaoBoleto)tipoImpressaoBoleto,
                        TipoDocumento = (TipoDocumento)tipoDocumento
                    },
                    Codigo = codigoCedente,
                    CodigoDV = digitoCodigoCedente,
                    CodigoTransmissao = codigoTransmissao,
                    Endereco = new Endereco
                    {
                        LogradouroEndereco = enderecoLogradouro,
                        LogradouroNumero = enderecoNumero,
                        LogradouroComplemento = enderecoComplemento,
                        Bairro = enderecoBairro,
                        Cidade = enderecoCidade,
                        UF = enderecoEstado,
                        CEP = enderecoCep
                    }
                };
                boletos.Banco.FormataCedente();

                // Novo boleto:
                boleto = new Boleto(boletos.Banco);

                var sacado = new Sacado
                {
                    CPFCNPJ = cnpj,
                    Nome = razaoSocial,
                    Observacoes = observacoes,
                    Endereco = new Endereco
                    {
                        LogradouroEndereco = endereco,
                        LogradouroNumero = numero,
                        LogradouroComplemento = complemento,
                        Bairro = bairro,
                        Cidade = cidade,
                        UF = uf,
                        CEP = cep
                    }
                };
                boleto.Sacado = sacado;

                boleto.NumeroDocumento = numeroDocumento;
                boleto.NumeroControleParticipante = nrControle;
                boleto.NossoNumero = nossoNumero;
                boleto.DataEmissao = dataEmissao;
                boleto.DataProcessamento = dataProcessamento;
                boleto.DataVencimento = dataVencimento;
                boleto.ValorTitulo = valorBoleto;
                boleto.Aceite = aceite;
                boleto.EspecieDocumento = Utils.ToEnum<TipoEspecieDocumento>(siglaEspecieDocumento, true, TipoEspecieDocumento.OU);

                boleto.DataDesconto = dataDesconto;
                boleto.ValorDesconto = valorDesconto;

                boleto.DataMulta = dataMulta;
                boleto.PercentualMulta = percMulta;
                boleto.ValorMulta = valorMulta;

                boleto.DataJuros = dataJuros;
                boleto.PercentualJurosDia = percJuros;
                boleto.ValorJurosDia = valorJuros;

                boleto.MensagemInstrucoesCaixa = instrucoesCaixa;
                boleto.MensagemArquivoRemessa = mensagemRemessa;
                boleto.CodigoInstrucao1 = instrucao1;
                boleto.ComplementoInstrucao1 = instrucao1Aux;
                boleto.CodigoInstrucao2 = instrucao2;
                boleto.ComplementoInstrucao2 = instrucao2Aux;
                boleto.CodigoInstrucao3 = instrucao3;
                boleto.ComplementoInstrucao3 = instrucao3Aux;

                boleto.CodigoProtesto = (TipoCodigoProtesto)codigoProtesto;
                boleto.DiasProtesto = diasProtesto;

                boleto.CodigoBaixaDevolucao = (TipoCodigoBaixaDevolucao)codigoBaixaDevolucao;
                boleto.DiasBaixaDevolucao = diasBaixaDevolucao;

                boleto.ValidarDados();
                boletos.Add(boleto);
`

Para saber como gerar HTML, PDF, Arquivo Remessa, ou Ler o Retorno, abra a classe Boleto2NetProxy, e consulte os métodos GerarBoletos (para PDF ou HTML), GerarRemessa e LerRetorno...

Infelizmente não vou conseguir te dar o exemplo que você precisa, mas acredito que você encontrará os métodos que precisa nos objetos Boletos e Boleto (do código exemplo acima).

**Comment by ViniBH** [comment]
Obrigado pela ajuda, ficou bem mais claro agora. 

Realmente vi que na classe proxy é possível gerar tanto em HTML quanto em PDF. 

Nesta nova versão é gerado um arquivo HTML para o boleto, enquanto na versão antiga do boletoNet eu injetava o HTML gerado na classe BoletoBancario  em um panel do webform.

Vou iniciar a migração, mais uma vez obrigado pela ajuda!

**Comment by rafd75** [comment]
opa... como te falei...

O projeto foi alterado, mas teoricamente deve funcionar exatamente como o anterior... 

Obs> Fica a dica: Se você já tem o projeto BoletoNet funcionando ai, não vejo motivo para trocar. Essa versão, teoricamente vai crescer mais lentamente, uma vez que o principal objetivo da versão 2 foi um controle maior do código (testes, etc)... Então, é um ponto a se analisar... Para implantar uma nova carteira, a dificuldade será maior, mas com certeza o código será muito mais confiável do que o projeto anterior... 

Abs!

**Comment by trinaldi** [comment]
@rafd75 Posso colocar esse exemplo no `README.md`?

**Comment by rafd75** [comment]
@trinaldi  - e ai? ... bom dia!

Seria interessante ter os exemplos sim... mas acho que podemos criar no WIKI, e depois, a partir do README.md apontar o link do "indice de exemplos"... 

Assim, se houver mais de um exemplo (usando sem a classe proxy, com a classe proxy, etc), podemos fazer 3 wikis - Um como um índice de exemplos, e outros 2 com cada exemplo.

Conforme forem surgindo mais exemplos, é só alterar ali... 

--- OU --- caiu a ficha aqui agora...

Criar um projeto dentro da solução para Exemplos... Seria melhor pois se alterar algo no projeto, o exemplo seria automaticamente atualizado... 

OU ---- melhor ainda .... criar exemplos como teste unitário do projeto de teste que já existe.... tudo documentado, etc... ficaria de referência para quem estivesse implementando o projeto.

**Comment by trinaldi** [comment]
@rafd75 

Show, acho válido tanto um Wiki como os exemplos.

O Wiki seria para quem não quer clonar ou baixar o projeto. Já os exemplos dentro da _solution_ seriam úteis para todos!

**Comment by rafd75** [comment]
Problema do WIKI é manter atualizado.

Eu acho que podemos aproveitar o projeto de teste... criar uma pasta "Exemplos" e gerar novos testes (adicionar um boleto, e depois testar se o vencimento está ok, sei lá... ) assim ajuda no uso da ferramenta e ainda por cima, serve de exemplo para implementar.

Fora que, como falei do WIKI, se algo for atualizado e quebrar o código, no WIKI ficaria errado, e no projeto, nem compilaria...

**Comment by trinaldi** [comment]
Correto!

Mas se for fazer um Wiki tem que manter atualizado mesmo.

**Comment by rafd75** [comment]
O duro é garantir que o WIKI fique atualizado, com tanta gente alterando o projeto.

Certeza que vai acabar tornando um exemplo que funcionava na versão anterior, sem funcionar na atual... e ai, quando alguém tentar utilizar o exemplo, não vai rodar. Melhor não ter um exemplo, do que ter um exemplo que não funciona.

mas acho que o projeto de teste (já existente na solution) é perfeito para isso, além de garantir que funcionará!

**Comment by trinaldi** [comment]
Pois é, é o melhor jeito de garantir!
