### ISSUE TITLE
Arquivo de Remessa - Permitir preenchimento das posições 94 e 106 (CNAB400, Bradesco)

### ISSUE THREAD

**Issue by GuroGuru** [BoletoNet/boleto2net#310]
Atualmente as posições [94 (Ident. se emite Boleto para Débito Automático)](https://github.com/BoletoNet/boleto2net/blob/ae074fa35a50ceff3f50641f16875e6aff06356d/Boleto2.Net/Banco/BancoBradesco.cs#L830) e [106 (Endereçamento para Aviso do Débito Automático em Conta Corrente)](https://github.com/BoletoNet/boleto2net/blob/ae074fa35a50ceff3f50641f16875e6aff06356d/Boleto2.Net/Banco/BancoBradesco.cs#L833) são preenchidos com o valor **Empty**.

No meu trabalho, surgiu a necessidade de preencher ambas posições.

Gostaria de saber se seria possível alterar a rotina para permitir o preenchimento, e me disponho a implementar a funcionalidade.

Obs.: Nomenclatura de posições conforme [documento de layout](https://banco.bradesco/assets/pessoajuridica/pdf/4008-524-0121-layout-cobranca-versao-portugues.pdf).

**Comment by rafd75** [comment]
Oi @GuroGuru - boa tarde!

Acho que se é necessário para gerar um arquivo remessa, deve ser implementado.

Precisaria criar as propriedades na classe Boleto e implementar na remessa.

Tem só que tomar o cuidado para  iniciar as propriedades com o valor "Empty" ... pois assim, quando trocar no arquivo remessa, tudo que está funcionando hoje, irá continuar funcionando ... e no seu caso, ao popular o objeto Boleto, informar os valores... 

Acho que é isso .

Se for implementar, faça um commit só desse ajuste, para não causar confusão com demais implementações (já que vai alterar a classe boleto).

Abs

**Comment by GuroGuru** [comment]
Bom dia, @rafd75! 

Valeu pelas orientações 👍

Atualizei as classes Boleto e BancoBradesco para abarcar as novas propriedades.

Abs

**Comment by rafd75** [comment]
Feito! Valeu, abs!
