### ISSUE TITLE
Extrema lentidão após a compilação da DLL

### ISSUE THREAD

**Issue by jcmprogramador** [BoletoNet/boleto2net#312]
Estou estudando a estrutura para conhecimento, implementação e uso da DLL. Utilizo o Visual Studio 2019 Community. Após compilada a DLL, esta passou a ficar quase 15 vezes mais lenta que a original, quando utilizando o método ArquivoRetorno, sem contudo ter sido modificada nenhuma linha de código. É necessário alterações nos parâmetros de compilação para gerar a DLL corretamente? Copiando novamente a DLL disposta no NuGet, tudo se normaliza. 
Podem me ajudar?

**Comment by carloscds** [comment]
@jcmprogramador Você compilou em debug ou release ?

**Comment by jcmprogramador** [comment]
Compilei em debug.

**Comment by carloscds** [comment]
@jcmprogramador Você sabe usar o Visual Studio Profiler ? Ele mostra onde esta a lentidao.

**Comment by jcmprogramador** [comment]
Não conheço mas, já vou estudá-la. O que achei estranho é o fato da original rodar com uma velocidade muito desejável e a compilada, ainda que não tenha nenhuma alteração em seu código, levar 15 vezes mais tempo na mesma rotina.

**Comment by carloscds** [comment]
@jcmprogramador Realmente nao faz sentido.
