### ISSUE TITLE
Logo do Banco + Codigo de Barras não esta sendo carregada

### ISSUE THREAD

**Issue by phooliveirasf** [BoletoNet/boleto2net#313]
Caros amigos, bom dia!! 

Procurei por aqui, mas nao encontrei.. estou iniciando no uso desta excelente ferramenta , no entanto, consegui adaptar para meu sistema, no entanto,quando gero o pdf não carrega a imagem da Logomarca do banco e do Codigo de Barras do boleto..

Poderiam me ajudar por favor?

grato!!

Paulo

**Comment by rafd75** [comment]
@phooliveirasf boa tarde.

Da uma olhada nessa issue: #140

Ela fala apenas sobre o logotipo do banco não estar atualizado, mas talvez seja algo relacionado aos arquivos locais que a biblioteca pode não estar encontrando... 

Veja se tem relação... (obs: eu nunca vi ninguém reportar esse problema antes).

**Comment by danielolinto** [comment]
Aconteceu comigo tb. Não carrega a logo do banco e nem o codigo de barras
