### ISSUE TITLE
Atualizar nuget

### ISSUE THREAD

**Issue by PedroPort3s** [BoletoNet/boleto2net#319]
Olá, gostaria que, quando possível, atualizar o pacote no Nuget, usando a biblioteca pelo Nuget, estou tendo o erro "Registro HEADER obrigatório" ao tentar gerar um arquivo de remessa do banco Sicred. Baixei o código fonte e referenciei em meu visual studio para conseguir debugar e achar onde estava o erro, desse modo, a remessa é gerada normalmente. Creio que o Nuget estando desatualizado está gerando este erro onde que o código fonte atual já foi corrigido o mesmo.

**Comment by carloscds** [comment]
@PedroPort3s Atualizacao feita!

**Comment by carloscds** [comment]
@rafd75 Você pode publicar ?

**Comment by carloscds** [comment]
@PedroPort3s Agora esta atualizado!

**Comment by PedroPort3s** [comment]
Deu certo agora, muito obrigado!
