### ISSUE TITLE
boletonet vs. boleto2net

### ISSUE THREAD

**Issue by flaviold** [BoletoNet/boleto2net#32]
Estou precisando gerar boletos em um projeto, e me deparei com os projetos boletonet e boleto2net. Procurei nos 2 projetos algo que explicasse a diferença entre eles mas não achei. alguem poderia me ajudar com isso?

**Comment by rafd75** [comment]
#1 

abs!

**Comment by flaviold** [comment]
obrigado pela resposta e desculpe pela desatenção ao não olhar para as issues fechadas.
