### ISSUE TITLE
Logo do sicredi desatualizada

### ISSUE THREAD

**Issue by PedroPort3s** [BoletoNet/boleto2net#320]
Olá, estou homologando a integração de cobrança junto ao Sicredi, a pessoa do Banco que está responsável em validar a integração me passou que a logo que vai no boleto está desatualizada, sendo assim não pode homologar, vocês poderiam atualizar a logo deles e atualizar o Nuget? [
![sicredi-logo](https://user-images.githubusercontent.com/54961255/128515833-950161ef-7498-46b4-99a2-6178d1b5865b.png)
](url)

**Comment by carloscds** [comment]
@PedroPort3s Pode trocar e enviar um Pull Request.
