### ISSUE TITLE
[Caixa - CNAB240] - Validação do Layout 

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boleto2net#329]
Senhores,

Estou com demanda para emissão de boletos Caixa, CNAB 240.

Segue o resultado da primeira validação:

![image](https://user-images.githubusercontent.com/15945003/135316164-66b2a62c-be70-4f70-a98d-2acb06066d26.png)

----

Linha 1 - Pede-se 101 ou 107, mas no fonte temos 050 fixado.

https://github.com/BoletoNet/boleto2net/blob/1d68a4f3f1fe76994975e1ca6566efc1f0b47734/Boleto2.Net/Banco/BancoCaixa.cs#L326
```
reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0164, 003, 0, "050", '0');
```

Manual:

![image](https://user-images.githubusercontent.com/15945003/135317663-e779ca00-7712-4da6-b742-e927b569cdf5.png)

![image](https://user-images.githubusercontent.com/15945003/135317655-410dd3eb-35c7-4422-b507-f7c9938421cb.png)

Aqui, especificamente, temos ainda outra situação, valida-se sempre 6 dígitos ao formatar o cedente, (e depois pede 9, achei estranho), mas neste caso podemos ter 7 dígitos dependendo da versão do layout.

https://github.com/BoletoNet/boleto2net/blob/1d68a4f3f1fe76994975e1ca6566efc1f0b47734/Boleto2.Net/Banco/BancoCaixa.cs#L37
```
Cedente.Codigo = codigoCedente.Length <= 6 ? codigoCedente.PadLeft(6, '0') : throw Boleto2NetException.CodigoCedenteInvalido(codigoCedente, 9);
```

---

Linha 2: Pede-se 060 ou 067 e está fixado 030

https://github.com/BoletoNet/boleto2net/blob/1d68a4f3f1fe76994975e1ca6566efc1f0b47734/Boleto2.Net/Banco/BancoCaixa.cs#L352
```
reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0014, 003, 0, "030", '0');
```

Manual:
![image](https://user-images.githubusercontent.com/15945003/135319224-4ba873cb-a4fa-4383-8393-8995af7656fd.png)

![image](https://user-images.githubusercontent.com/15945003/135319318-78685e3e-5bc0-49e1-984a-3a256ff37ce2.png)

030, aparentemente, é para retorno.

---

Linha 3 - Falha interna minha.

**Comment by rafd75** [comment]
@marcosgerene , boa tarde.

Os dois manuais que eu tenho aqui, da CEF 240 posições, são: V005 e V006 - ambos de Setembro de 2007.

Certamente, de lá pra cá, surgiram códigos de beneficiário com 7 dígitos, o que fez a versão ser alterada.

Acredito que o melhor seria atualizar para a versão mais recente. Porém, conforme o print do manual que você colocou ai, devemos ter muita atenção em verificar todo o resto dos campos do manual e comparar com o script do Boleto2Net. Isso pq, com 6 dígitos, existe um 0 na direita, e com 7 dígitos, não tem.   Isso válido para remessa e retorno.

Provavelmente a versão implementada vai continuar funcionando (aliás, está funcionando, pois aqui tenho casos de uso dessa carteira) - mas novos clientes, precisam homologar na versão mais recente.

**Comment by marcosgerene** [comment]
@rafd75 Fiz um commit mas ainda não abri o PR, vou tentar ver se alguém daqui pode revisar o manual e vou fazer alguns testes, mas o problema meu é, se eu simplesmente "mudar" alguns campos como meu commit sugere pode haver uma quebra em casos como o seu.

**Comment by rafd75** [comment]
Considerando que todos os campos (e posições) serão revisados, não acredito em quebra do que esteja funcionando não.

Veja - imagine um novo cliente aqui... vou precisar homologar e minha versão é antiga... 

Então vou corrigir, mas a alteração irá acabar chegando para quem já usa a versão "antiga"... e eu acredito que a nova versão continuaria funcionando.

Obs: o outro caminho seria implementar multiplas versões de layout, e setar de alguma forma isso... Mas entendo que essa solução é terrível... imagina daqui um tempo, quantas versões não estariam dentro do componente.

**Comment by marcosgerene** [comment]
@rafd75 faz sentido.

Vou revisar o CNAB 240 porque é o que vou mexer no momento, acredito que eu abra o PR entre essa e a próxima semana,

**Comment by rafd75** [comment]
OK... combinado.

**Comment by marcosgerene** [comment]
@rafd75 

A remessa foi validada om meus ajustes. Tive que mexer no código de barras, mais especificamente no campo livre, então vamos validar também o boleto gerado.

Os testes já exitentes passaram com sucesso:

![image](https://user-images.githubusercontent.com/15945003/135854344-35885297-6cc8-4670-9e6b-68c403909d32.png)

Assim que receber retorno dos boletos abro o PR.

**Comment by rafd75** [comment]
Legal ... !!!

**Comment by WillPvt** [comment]
> Senhores,
> 
> Estou com demanda para emissão de boletos Caixa, CNAB 240.
> 
> Segue o resultado da primeira validação:
> 
> ![imagem](https://user-images.githubusercontent.com/15945003/135316164-66b2a62c-be70-4f70-a98d-2acb06066d26.png)
> 
> Linha 1 - Pede-se 101 ou 107, mas no fonte temos 050 corrigido.
> 
> https://github.com/BoletoNet/boleto2net/blob/1d68a4f3f1fe76994975e1ca6566efc1f0b47734/Boleto2.Net/Banco/BancoCaixa.cs#L326
> 
> ```
> reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0164, 003, 0, "050", '0');
> ```
> 
> Manual:
> 
> ![imagem](https://user-images.githubusercontent.com/15945003/135317663-e779ca00-7712-4da6-b742-e927b569cdf5.png)
> 
> ![imagem](https://user-images.githubusercontent.com/15945003/135317655-410dd3eb-35c7-4422-b507-f7c9938421cb.png)
> 
> Aqui, especificamente, temos ainda outra situação, valida-se sempre 6 dígitos ao formatar o cedente, (e depois pede 9, achei estranho), mas neste caso podemos ter 7 dígitos dependendo da versão do layout.
> 
> https://github.com/BoletoNet/boleto2net/blob/1d68a4f3f1fe76994975e1ca6566efc1f0b47734/Boleto2.Net/Banco/BancoCaixa.cs#L37
> 
> ```
> Cedente.Codigo = codigoCedente.Length <= 6 ? codigoCedente.PadLeft(6, '0') : throw Boleto2NetException.CodigoCedenteInvalido(codigoCedente, 9);
> ```
> 
> Linha 2: Pede-se 060 ou 067 e está fixado 030
> 
> https://github.com/BoletoNet/boleto2net/blob/1d68a4f3f1fe76994975e1ca6566efc1f0b47734/Boleto2.Net/Banco/BancoCaixa.cs#L352
> 
> ```
> reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0014, 003, 0, "030", '0');
> ```
> 
> Manual: ![imagem](https://user-images.githubusercontent.com/15945003/135319224-4ba873cb-a4fa-4383-8393-8995af7656fd.png)
> 
> ![imagem](https://user-images.githubusercontent.com/15945003/135319318-78685e3e-5bc0-49e1-984a-3a256ff37ce2.png)
> 
> 030, aparentemente, é para retorno.
> 
> Linha 3 - Falha interna minha.

Bom dia amigo, estou com o mesmo problema, ja subiu essa alteração ?

**Comment by rafd75** [comment]
@WillPvt 

Acho que essa correção está no PR -> #330
