### ISSUE TITLE
Santander - Carteira 101 - REGISTRO DETALHE SEGMENTO P 

### ISSUE THREAD

**Issue by krgm03** [BoletoNet/boleto2net#33]
Boa tarde

No layout de arquivo 240 versão 2.8(H7815) de fevereiro de 2017 diz o seguinte

![codigo para protesto](https://user-images.githubusercontent.com/6650072/30724317-7c790e1a-9f13-11e7-9866-7151fb90c555.png)

![codigos para protesto](https://user-images.githubusercontent.com/6650072/30724221-e9014de6-9f12-11e7-84a4-9a093b7720a3.png)

Abaixo há o Enum TipoCodigoProtesto constante no Boleto2Net

"public enum TipoCodigoProtesto
    {
        Protestar=1,
        NaoProtestar=3
    }"

Na implementação BancoSantander.cs na linha 394 há o seguinte trecho de código
"reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0221, 001, 0, (int)boleto.CodigoProtesto, '0');"

Se eu não estiver equivocado a implementação ainda está de acordo com layout de versão antiga
Pois quando for para NÃO PROTESTAR devemos enviar o '0'

Obrigado!

**Comment by rafd75** [comment]
Bom dia!

Você está certo! Meu manual bate com o seu. Esse Enum está sendo utilizado também no BB, Caixa, Sicoob.
Consultei os manuais que tenho aqui... segue um Resumo...


**SANTANDER:**
0 | NAO PROTESTAR
1 | PROTESTAR DIAS CORRIDOS
2 | PROTESTAR DIAS UTEIS
3 | UTILIZAR PERFIL BENEFICIÁRIO
9 | CANCELAMENTO DE PROTESTO AUTOMÁTICO


**BANCO DO BRASIL**
O Banco do Brasil trata somente os códigos '1' – Protestar dias corridos, '2' – Protestar dias úteis, e '3' – Nãoprotestar.


**CAIXA ECONOMICA**
Código adotado pela FEBRABAN para identificar o tipo de prazo a ser considerado para o protesto.‘1’ = Protestar‘3’ = Não Protestar


**SICOOB**
Código   para Protesto: "1"


OBS: Considerei o manual do CNAB 240 de cada banco...


O Santander foi um dos últimos bancos que fiz... Esse Enum, eu criei pois achava que (falando do cnab240) seria um padrão, mas não é - agora sei...


Qual seria a melhor forma de resolver o problema? Alterar o ENUM para seguir um padrão do Boleto2Net e tratar separadamente (switch) em cada banco?    OU só fazer a adequação no Santander, mantendo o Enum do jeito que está?

**Comment by krgm03** [comment]
Bom dia

Pelo que você verificou o Santander é o que tem mais códigos
Acho que o Enum no Boleto2Net deve continuar sendo único e daí cada implementação resolve de acordo com as regras/códigos específicos

O que ocorre é que atualmente os dois códigos presente no Enum (Protestar=1, NaoProtestar=3) não atendem todas as situações e isso pode ser um problema para quem necessite de todas elas

No meu caso usarei apenas o 'NÃO PROTESTAR' ou o 'PROTESTAR(dias corridos)'. Não tenho necessidade de utilizar os demais

Ou seja, poderia ser feita apenas uma adequação na implementação do Santander e daí no futuro conforme surgir necessidade adicionar os demais códigos no Enum

Obrigado

**Comment by rafd75** [comment]
Resolvido do "jeito certo"...

Padronizei os enums TipoCodigoProtesto e TipoCodigoBaixaDevolucao (0=não, seguido de 1, 2, 3, para cada opção possível), e ajustei todos os bancos.

Assim evita ter que reescrever lá na frente... 

PR #34

**Comment by rafd75** [comment]
@AlbertoMonteiro - parece que o tal do CAKE está desatualizado...

O que eu faço para conseguir aprovar esse PR?

Erro -> https://ci.appveyor.com/project/carloscds/boleto2net/build/2.1.0.152

**Comment by krgm03** [comment]
Gostaria de conseguir ajudar...mas não uso o CAKE
Fico à disposição para ajudar no que conseguir

Obrigado pela atenção!

**Comment by AlbertoMonteiro** [comment]
@rafd75 aprova o meu PR https://github.com/BoletoNet/boleto2net/pull/35 e pede para o @krgm03 fazer rebase que ai vai da certo!

**Comment by rafd75** [comment]
Aprovar PR, é o @carloscds

**Comment by AlbertoMonteiro** [comment]
@carloscds coloca eu e o @rafd75 como colaborador do repo

**Comment by krgm03** [comment]
@rafd75 boa tarde

Não deu certo a atualização?

**Comment by rafd75** [comment]
@krgm03 --- tentei novamente = PR #37 - (após atualizar meu código), mas deu o mesmo erro nos testes automáticos... estou esperando instruções do @carloscds ou @AlbertoMonteiro de como fazer esse PR.

**Comment by krgm03** [comment]
Obrigado @rafd75 e @AlbertoMonteiro

**Comment by AlbertoMonteiro** [comment]
Por nada @krgm03 !!!!

**Comment by renanmthy** [comment]
Como ficou essa questão dos Codigos de Protesto? 
Estou implementando aqui em meu ERP essa parte de protesto e notei que o enum está padrão para todos os bancos. 
Foi implementada alguma validação do código em cada banco? Fico no aguardo...

**Comment by rafd75** [comment]
@renanmthy - seria bom verificar isso, não sei te dizer...

mas o correto é (seria) ter tratamento do enum para o correspondente em cada banco.
