### ISSUE TITLE
Metodo Random().Next() não é seguro para gerar número randomico

### ISSUE THREAD

**Issue by MAP-Akamae** [BoletoNet/boleto2net#331]
https://github.com/BoletoNet/boleto2net/blob/ae074fa35a50ceff3f50641f16875e6aff06356d/Boleto2.Net/BoletoImpressao/BoletoBancario.cs#L646

O método Random().Next() utilizado gera números repetidos gerando boletos com código de barras de outro boleto do mesmo email, 
minha sugestão é adicionar o método System.IO.Path.GetRandomFileName() para evitar erros nos emails.
string.Concat(new Random().Next().ToString(), System.IO.Path.GetRandomFileName().Replace(".", string.Empty))

**Comment by carloscds** [comment]
@MAP-Akamae Pode fazer a correção e enviar um PR.
