### ISSUE TITLE
BUG - GERAR SEQMENTO R BANCO SICOOB 

### ISSUE THREAD

**Issue by fabriciomoreirao** [BoletoNet/boleto2net#335]
A MULTA É CALCULADO PELO VALOR FIXO OU VALOR PERCENTUAL, EU NÃO CONSIGO SETAR O VALOR DO COD MULTA COMO 2, SOMENTE 0  OU 1;

Código   da Multa:     '0'  =  Isento     '1'  =  Valor Fixo     '2'  =  Percentual

**Comment by rafd75** [comment]
Oi @fabriciomoreirao ...

#336

Veja se esse ajuste resolveu o problema... 

Obs:
Informe apenas boleto.PercentualMulta
Deixe boleto.ValorMulta zerado... e não se preocupe com o CodigoMulta pois o componente irá gerenciar isso sozinho.

**Comment by fabriciomoreirao** [comment]
Muito obrigado, ficou correto agora!!
