### ISSUE TITLE
Banco Inter

### ISSUE THREAD

**Issue by rafd75** [BoletoNet/boleto2net#337]
Bom dia.

Estou com a remessa e retorno do Banco Inter pronto aqui.

O Inter tem uma limitação. O nosso número é gerado por eles, não é possível informar na remessa.
Isso impossibilita, por exemplo, a emissão do boleto bancário junto com uma nota fiscal, pois você não tem acesso, no momento da criação do boleto, ao nosso número.

Mas para aqueles que emitem a NF, e enviam o boleto no dia seguinte, não teria problema utilizar essa cobrança. Neste caso, o boleto é gerado, enviado pela remessa para processamento. No dia seguinte, no retorno ,você tem acesso ao nosso número que o banco inter gerou. E dai para frente, seria possível a impressão do boleto através do componente, gerar o PDF, enviar por email, etc.

Por padrão, o componente sempre calcula o dígito verificador do boleto. Isso permite o controle pela aplicação apenas do "nosso número", ficando o componente responsável pelo cálculo do Nosso Número, mesmo nos casos de impressão de segunda via.

Estou parado nesse ponto... No manual do banco inter, não tem o algoritmo para calcular o dígito do nosso número.

Pensei que, neste caso (carteiras onde o banco é responsável pela geração do nosso número), permitir informar o dígito quando a aplicação ao preencher a coleção de boletos no componente. Ou seja, se a propriedade NossoNumeroDV estiver preenchida, o componente aceita o valor informado. Se estiver em branco, o componente calcula. Talvez aplicar esse comportamento para todas as carteiras, deixando o componente com a mesma lógica para uso.

Seja como for, seria bom termos o algoritmo do nosso número usado pelo banco inter ... Alguém tem ideia onde conseguir isso?

Obs: No manual, só tem o algoritmo do DV da linha digitável...

Assim que resolver isso, já consigo subir a versão aqui.

**Comment by hbadotti** [comment]
Snow!

**Comment by WillPvt** [comment]
alguma novidade sobre isso, estou precisando desenvolver o cnab por banco inter

**Comment by WillPvt** [comment]
> Bom dia.
> 
> Estou com a remessa e retorno do Banco Inter pronto aqui.
> 
> O Inter tem uma limitação. O nosso número é gerado por eles, não é possível informar na remessa. Isso impossibilita, por exemplo, a emissão do boleto bancário junto com uma nota fiscal, pois você não tem acesso, no momento da criação do boleto, ao nosso número.
> 
> Mas para aqueles que emitem a NF, e enviam o boleto no dia seguinte, não teria problema utilizar essa cobrança. Neste caso, o boleto é gerado, enviado pela remessa para processamento. No dia seguinte, no retorno ,você tem acesso ao nosso número que o banco inter gerou. E dai para frente, seria possível a impressão do boleto através do componente, gerar o PDF, enviar por email, etc.
> 
> Por padrão, o componente sempre calcula o dígito verificador do boleto. Isso permite o controle pela aplicação apenas do "nosso número", ficando o componente responsável pelo cálculo do Nosso Número, mesmo nos casos de impressão de segunda via.
> 
> Estou parado nesse ponto... No manual do banco inter, não tem o algoritmo para calcular o dígito do nosso número.
> 
> Pensei que, neste caso (carteiras onde o banco é responsável pela geração do nosso número), permitir informar o dígito quando a aplicação ao preencher a coleção de boletos no componente. Ou seja, se a propriedade NossoNumeroDV estiver preenchida, o componente aceita o valor informado. Se estiver em branco, o componente calcula. Talvez aplicar esse comportamento para todas as carteiras, deixando o componente com a mesma lógica para uso.
> 
> Seja como for, seria bom termos o algoritmo do nosso número usado pelo banco inter ... Alguém tem ideia onde conseguir isso?
> 
> Obs: No manual, só tem o algoritmo do DV da linha digitável...
> 
> Assim que resolver isso, já consigo subir a versão aqui.

alguma novidade sobre isso, estou precisando desenvolver o cnab por banco inter

**Comment by carloscds** [comment]
@WillPvt O Banco Inter tem uma API que envia diretamente o Boleto, acredito que nem precisa de remessa e retorno.

**Comment by WillPvt** [comment]
> @WillPvt O Banco Inter tem uma API que envia diretamente o Boleto, acredito que nem precisa de remessa e retorno.
mas eu preciso desenvolver o cnab remessa e retorno e a emissao do boleto dentro do nosso sistema

**Comment by rafd75** [comment]
@WillPvt - Me passa seu email, que eu vou te encaminhar o código que eu tenho pronto. (não evolui além do que está escrito ai) e você tenta concluir.

obs: até onde eu fui, o banco inter não permite geração do nosso número pelo aplicativo. Então você precisa enviar em branco e aguardar o retorno para capturar o nosso número.

e ai tem o problema da impressão (de segunda via) que expliquei acima (sobre o calculo do dígito verificador).

**Comment by WillPvt** [comment]
> @WillPvt - Me passa seu email, que eu vou te encaminhar o código que eu tenho pronto. (não evolui além do que está escrito ai) e você tenta concluir.
> 
> obs: até onde eu fui, o banco inter não permite geração do nosso número pelo aplicativo. Então você precisa enviar em branco e aguardar o retorno para capturar o nosso número.
> 
> e ai tem o problema da impressão (de segunda via) que expliquei acima (sobre o calculo do dígito verificador).
valeu demais 
wilksonsilvahenrique@gmail.com
