### ISSUE TITLE
Boletos hibridos - Nova demanda

### ISSUE THREAD

**Issue by leoneljaime** [BoletoNet/boleto2net#340]
Boa tarde pessoal!
Utilizo este componente desde 2012, e estão de parabéns me atende em todos os bancos que preciso.

Este mês me surgiu uma nova demanda de desenvolvimento, um cliente precisa que saia na impressão do boleto um modelo novo que chamam de híbrido senão me engano. 

Gostaria de saber se tem previsão de alguma nova versão que contempla isso?

***Obs**: Liguei no Sicredi e nem tem previsão de liberar essa nova funcionalidade. 
Já Banco de Brasil e Itaú não tenho contatos para obter essas informações.
Estou colocando dessa forma porque se os bancos cooperativos for demorar, meu cliente cogita em abrir um conta e obter um contrato em outro banco.

Desde já agradeço e me desculpe senão for permitido esse tipo posto aqui, mas foi a única forma que encontrei para obter informações.

**Comment by rafd75** [comment]
@leoneljaime bom dia.

Não existe um roteiro de implementação de novos bancos/carteiras/funcionalidades no projeto.
É a própria comunidade que vai implementando as funções conforme as necessidades vão aparecendo.

**Comment by carloscds** [comment]
@leoneljaime Nao quer aproveitar e implementar ?

**Comment by carloscds** [comment]
@leoneljaime Sim, é um projeto open source. Pode colaborar, mas peco que siga o padrão ja existente. Pois ferramentas pagas podem prejudicar a natureza do projeto.
