### ISSUE TITLE
Validação do boleto

### ISSUE THREAD

**Issue by raphaelmorato** [BoletoNet/boleto2net#341]
Como faço para saber se o arquivo de remessa e o boleto estão sendo gerados com os valores certos?

**Comment by carloscds** [comment]
@raphaelmorato nao entendi a pergunta

**Comment by raphaelmorato** [comment]
como faço para homologar

**Comment by raphaelmorato** [comment]
O meu problema é o seguinte:
com o Boleto2net, eu gerei um boleto, que gerou os números do código de barras e tem um outro boleto que a empresa gerou que apresenta parte do código de barras diferente do boleto que gerei com o meu sistema.
Ambos os boletos estão com o mesmo valores de entrada.

O boleto que a empresa gerou está certo pq eles usam a anos, o boleto que gerei não deveria ter o mesmo código de barras?

Estou gerando boleto paraa o Santander.

**Comment by carloscds** [comment]
@raphaelmorato Ainda nao entendi o problema. Vc gerou um arquivo pelo boleto2net e outro em outro lugar ?

**Comment by raphaelmorato** [comment]
Isso mesmo.
A empresa tem um sistema que gera um boleto com uma outra biblioteca.
Eu gerei usando o Boleto2net e está dando diferença no código de barras

Gerado no Boleto2net
03399.44100 23800.000**400** 42751.00101**9**  **5** 86110000088537

Gerado pela empresa
03399.44100 23800.000**046** 42751.00101**4**  **1** 86110000088537

Não estou entendendo essa diferença, se os dados de entrada são os mesmo

**Comment by carloscds** [comment]
@raphaelmorato Pode ser sequencia do boleto, convenio, etc

**Comment by raphaelmorato** [comment]
obrigado, vou continuar tentando aqui.

**Comment by rafd75** [comment]
bom dia @raphaelmorato ,

Se os dados são os mesmos (incluindo conta, carteira, etc), o código de barras deveria ser o mesmo.

Manda aqui, a imagem dos 2 boletos... vou tentar ajudar...

é provável que a diferença esteja no "40" e "04" do quarto bloco. Estou considerando que o último dígito de cada bloco em negrito, são dígitos de conferência... e talvez, se o "40" virar "04", os demais dígitos serão corrigidos automaticamente.

**Comment by raphaelmorato** [comment]
bom dia, @rafd75 , muito obrigado.
Ontem depois muitas horas olhando o boleto, percebi que estava informando o dígito verificador do nosso número. Retirei e funcionou.
