### ISSUE TITLE
Validacao Conta bancária Caixa

### ISSUE THREAD

**Issue by carlosamorim84** [BoletoNet/boleto2net#345]
Bom dia.

estou tendo um problema para implementar o Boleto da Caixa.  Estou recebendo o seguinte retorno: "O número da conta (000300501476) deve conter 6 dígitos.". Até aí tudo bem! A questão é que o tamanho da conta da caixa é de 11 digitos + DV. Estou fazendo algo de errado? O que devo fazer para resolver essa questão?

ps.: Se eu alterar a conta para uma conta de 6 dígitos padrão funciona. Mas a conta da empresa não tem somente 6 digitos.

Desde já agradeço a atenção de vocês.

**Comment by HenriqueTelesOpenline** [comment]
Nesse seu número (000300501476) o 6 é o digito ?
Se sim, acredito que o número da sua conta seja 050147
Se você estiver baseando o número da conta pelo que consta no cartão, está errado.

No cartão tem alguns números antes da conta que não me lembro de cabeça o que significam, mas não são necessários quando se faz uma transferência. Acredito que pra emitir boleto também não o sejam.
Experimente fazer assim e tente homologar com o banco.
NumeroConta - 050147
NumeroContaDV - 6

**Comment by carlosamorim84** [comment]
Opa Henrique. em primeiro lugar agradeço pela resposta.

Na verdade o dígito é 7. Fica assim: 000300501476-7

Pelo que entendi, a conta então seria 501476-7

é isso?

**Comment by HenriqueTelesOpenline** [comment]
Acredito que seja exatamente isso @carlosamorim84 
Faz o teste ai e tente homologar com seu banco
Acredito que vai funcionar
