### ISSUE TITLE
Conversão .net

### ISSUE THREAD

**Issue by Marlonwg** [BoletoNet/boleto2net#346]
Alguém tem esse código convertido para .net Funcionando ???
E um tutorial de como implementa-lo

**Comment by carloscds** [comment]
@Marlonwg como assim convertido para .NET ?

**Comment by Marlonwg** [comment]
Para Visual Studio .net pois ele esta montado em C#

**Comment by carloscds** [comment]
@Marlonwg Mas o C# é tecnologia .NET e funciona no Visual Studio. Só precisa usar uma versão mais atualizada do Visual Studio, por exemplo 2017 ou 2019.

**Comment by Marlonwg** [comment]
Aonde fica o Tutorial de como implementa-lo ao código para gerar o boleto e para criar o arquivo de remessa e Retorno.
Estava usando o boleto Cloud https://boleto.cloud/ , Mas tenho que criar boleto via codigo e criar os cnabs

**Comment by carloscds** [comment]
@Marlonwg Nao conheco o boleto.cloud, no BoletoNet existe um exemplo nos projetos de testes. Mas estao todos em C#.

**Comment by Marlonwg** [comment]
Manda o link do exemplo pra gerar o boleto eo Carne mesmo que for em C# da de converter.
Eu posso montar em vb.net se usar a dll e fazer a chamada acho que nao teria diferença a linguagem de chamada

**Comment by carloscds** [comment]
@Marlonwg https://github.com/BoletoNet/boleto2net/tree/master/Boleto2.Net.Testes

**Comment by Marlonwg** [comment]
Blz vou tentar implementa-lo uma duvida nessa dll a conexão com o banco e feito de maneira autônoma consegue buscar o remessa retorno ou e necessário enviar ao banco e baixar o CNAB ?

**Comment by carloscds** [comment]
@Marlonwg A DLL nao trata conexao com banco.

**Comment by Marlonwg** [comment]
Ola carlos tem o código para ler arquivo CNAB400.REM e para Gerar o Retorno para o banco o Formato ?
Procurei aqui nos exemplos nao consegui.

**Comment by carloscds** [comment]
@Marlonwg Cada Banco gera no seu formado CNAB, vc precisa configurar.  @rafd75  você tem algum exemplo de geracao de remessa ?

**Comment by rafd75** [comment]
@Marlonwg, bom dia.

No projeto de teste, tem rotinas para criar a remessa - exemplo Itaú.

https://github.com/BoletoNet/boleto2net/blob/bd563eaa4d4d83ee2b03885224a4616b08fc1791/Boleto2.Net.Testes/BancoItauCarteira109Tests.cs#L31

Para ler o arquivo retorno, não existe teste, pois necessitaria de um arquivo exemplo... Os que tenho aqui, são de clientes.


--- outra coisa:

Não existe opção para "ler arquivo .REM" ... o arquivo .REM (remessa) é gerado a partir de uma coleção de boletos previamente preenchida pela sua aplicação no componente.

E não existe gerar .RET... acho que na sua pergunta, vc inverteu os termos...

**Comment by Marlonwg** [comment]
E no caso e Gerar o Arquivo Remessas e preciso ler o retorno.

**Comment by Marlonwg** [comment]
Este exemplo que tenho no BoletoNet funciona já no Boletonet2 nao.

**Comment by rafd75** [comment]
@Marlonwg , não vou conseguir te ajudar com isso... estou atolado aqui.

Mas esse método de teste do Itau, cria a instância do componente, preenche com 9 títulos, gera o arquivo remessa... gera o arquivo PDF com  os boletos... 

tem tudo que você precisa aqui:

https://github.com/BoletoNet/boleto2net/blob/bd563eaa4d4d83ee2b03885224a4616b08fc1791/Boleto2.Net.Testes/BancoItauCarteira109Tests.cs#L11
