### ISSUE TITLE
Comprovante de entrega BB 17/019

### ISSUE THREAD

**Issue by Boscosantana** [BoletoNet/boleto2net#348]
Boa tarde

Não vir como imprirmir o comprovante de entrega.
Tem ?

**Comment by rafd75** [comment]
@Boscosantana boa tarde

Eu acho que essa propriedade que controla a impressão (ou não) do Comprovante de Entrega:

https://github.com/BoletoNet/boleto2net/blob/bd563eaa4d4d83ee2b03885224a4616b08fc1791/Boleto2.Net/BoletoImpressao/BoletoBancario.cs#L83

**Comment by Boscosantana** [comment]
me passei, desculpe o incomodo.
