### ISSUE TITLE
Juros/Multa não aparecem no arquivo de remessa

### ISSUE THREAD

**Issue by raphaelmorato** [BoletoNet/boleto2net#351]
Estou gerando o arquivo de remessa (banco Caixa), porém, os dados do juros e multa não aparecem no arquivo de remessa. Tem que habilitar alguma flag ou algo parecido?

            boleto.DataMulta = valorFinanceiroCUL.DataVencimentoBoleto.AddDays(1);
            boleto.PercentualMulta = valorFinanceiroCUL.PercMulta;
            boleto.ValorMulta = valorFinanceiroCUL.ValorMulta;
  
            boleto.DataJuros = valorFinanceiroCUL.DataVencimentoBoleto.AddDays(1); 
            boleto.PercentualJurosDia = valorFinanceiroCUL.PercJuros;
            boleto.ValorJurosDia = valorFinanceiroCUL.ValorJurosDia;

**Comment by rafd75** [comment]
@raphaelmorato  -  alguns bancos (mas verifiquei aqui, e não é o caso da caixa) necessitam que se informe alguns códigos de multa/juros.

Teoricamente, era para incluir... Verifiquei a propriedade ValorMulta, e está nos dois layouts disponíveis (cnab 240 e 400).

Você já tentou depurar nesse ponto do código:

https://github.com/BoletoNet/boleto2net/blob/7038fb2e15ac200de6a24f3fa9c2aaa9eb855487/Boleto2.Net/Banco/BancoCaixa.cs#L245

obs: procure por ValorMulta, além do ValorJurosDia... e também o layout que está usando.
