### ISSUE TITLE
Logo BBrasil

### ISSUE THREAD

**Issue by Boscosantana** [BoletoNet/boleto2net#354]
Bom dia

Baixei a dll via NuGet.
Não encontrei como alterar a logo do Banco do Brasil.

**Comment by rafd75** [comment]
@Boscosantana boa tarde!

Essa parte (do logotipo), veio do projeto https://github.com/BoletoNet/boletonet que deu origem a este aqui.

Se não me engano, isso fica dentro dos arquivos do projeto, e uma vez utilizado, a DLL coloca o logo em uma pasta temporaria da máquina do usuário. Vi algo assim, muito tempo atrás, mas não me recordo direito e estou sem tempo para procurar aqui.

Da uma olhada no projeto original, e veja se lá alguém já postou algo a respeito... o que vc achar lá, provavelmente vai servir aqui.
