### ISSUE TITLE
Dados do beneficiário final

### ISSUE THREAD

**Issue by MateoRj** [BoletoNet/boleto2net#355]
Olá pessoal, eu faço o uso do BoletoNet, e um cliente pediu para que eu colocasse os dados do beneficiário final na remessa, inclui os dados mas o registro com essas informações não são gerados. É possível gerar esses registro no BoletoNet, ou só usando o Boleto2net :?
crio o resgitro dessa forma
![image](https://user-images.githubusercontent.com/119519649/204871175-f3542290-c358-4d50-aa31-614b2d9cfad7.png)

**Comment by rafd75** [comment]
@MateoRj boa tarde!

Se você estiver usando o BoletoNet, verifique se está implementado esses campos no banco/carteira que está gerando.

Idem se for o Boleto2Net. 

Acredito que essa informação possa estar presente em alguns bancos/carteiras, mas não em outros, ainda que o banco em questão aceite. Nesse caso, conforme manual do banco, seria necessário implementar o registro quando houver Avalista.

**Comment by MateoRj** [comment]
Olá @rafd75 . Boa tarde, estou usando BoletoNet, eu pelo menos não achei, será que alguém sabe dizer se tem ?

**Comment by rafd75** [comment]
Tenta publicar sua dúvida nesse repositório:

https://github.com/BoletoNet/boletonet/issues

**Comment by MateoRj** [comment]
beleza @rafd75 . Muito obrigado irmão !!
