### ISSUE TITLE
boa tarde, existe alguma documentação que eu possa estar lendo ? ou é os próprios testes unitários ?

### ISSUE THREAD

**Issue by robertorp** [BoletoNet/boleto2net#356]
Queria sabe para eu estar estudando a lib, agradeço desde já.

**Comment by rafd75** [comment]
@robertorp - da uma olhada nos projetos de teste da lib, que por lá, você vai entender como criar uma coleção de boletos, imprimir/gerar pdf e também o arquivo remessa.

**Comment by robertorp** [comment]
Show , obrigado ! @rafd75
