### ISSUE TITLE
Boleto está saindo sem o "Sacador Avalista"

### ISSUE THREAD

**Issue by hbadotti** [BoletoNet/boleto2net#357]
Bom dia, meus boletos não estão saíndo com o "Beneficiário Final" (Sacador Avalista)...

Ao gerar pelo boleto2net no corpo do boleto sai o "Avalista" normalmente, mas após validar o boleto no banco e baixar uma segunda via pelo banco, ou o pagador consultar o boleto, não aparece o "Avalista". 

Parte do código para incluir o "Sacador Avalista" (Beneficiário Final)
`                    
Titulo.Avalista = New Sacado With {
.CPFCNPJ = DocsAvalistas(ordem),
.Endereco = New Boleto2Net.Endereco With {
.Bairro = Bairro_Aval,
.CEP = CEP_Aval,
.Cidade = Cidade_Aval,
.LogradouroComplemento = Comp_Aval,
.LogradouroEndereco = End_Aval,
.LogradouroNumero = Num_Aval,
.UF = UF_Aval},
.Nome = Nome_Aval,
.Observacoes = "(" & MeuNumero(ordem) & ")"
}
`

2ª Via pelo sistema (note que o sacador avalista está presente no boleto)
![2aviabanco](https://user-images.githubusercontent.com/34871994/219055401-2a17323b-3f19-4c63-b441-9ba8e56f9181.png)

2ª Via do Banco (note que o campo beneficiário final está em branco)
![2aviabanco](https://user-images.githubusercontent.com/34871994/219054207-19d4f874-11ed-41b6-b6f1-6b6ca3968eb3.png)

**Comment by rafd75** [comment]
bom dia.

Verifique se no arquivo remessa, está indo essa informação.
Se tiver essa informação na remessa, verifique com o banco o motivo...

**Comment by hbadotti** [comment]
@rafd75 Eu estava olhando aqui o arquivo de remessa (CNAB240) e realmente o arquivo não está vindo com segmento "Y" (que aparentemente é o segmento que tem os dados do sacador avalista), apenas os segmentos "R", "P" e "Q"...

O que será que pode ser?

**Comment by rafd75** [comment]
No código do boleto2net.. o registro está implementado?

As vezes, não foi feito e por isso que não está indo.

Ou tem alguma condição para o registro ser gerado q vc não está se
atentando.

Da uma olhada no código fonte do componente, ...

Em qua., 15 de fev. de 2023 14:52, hbadotti ***@***.***>
escreveu:

**Comment by hbadotti** [comment]
@rafd75 Olhei aqui no código fonte e no banco sicredi não achei o segmento "Y" !! Pelo visto não foi implementado mesmo...

**Comment by hbadotti** [comment]
@rafd75 Eu me confundi aqui, o sacador avalista fica no Segmento "Q" na posição 154... Olhei aqui no meu arquivo de remessa e está constando o sacador avalista (benificiário final) de forma correta... Vou tentar entrar em contato com o banco aqui...
