### ISSUE TITLE
VFP9

### ISSUE THREAD

**Issue by InfiniteCodeBR** [BoletoNet/boleto2net#358]
Boa tarde. Alguém poderia me mandar uns exemplos de uso do BoletoNet para Visual FoxPro ?

**Comment by carloscds** [comment]
@rafd75 Acho que esta é com vc!

**Comment by rafd75** [comment]
opa...... com a DLL registrada no windows, tenta fazer isso:

oBN = CreateObject("Boleto2NetProxy")

em seguida, só consultar os métodos da classe Proxy:
Exemplo:

oBN.SetupCobranca( ... )

e para cada boleto que desejar incluir, faça o ciclo abaixo:

oBN.NovoBoleto( ...)
oBN.DefinirSacado( ...)
oBN.DefinirBoleto( ...)
oBN.DefinirInstrucoes(...) << aqui tem métodos para definir desconto, protesto, etc... 
oBN.FecharBoleto( ...)


Com a coleção preenchida... 

vc pode gerar os boletos:
oBN.GerarBoletos( ... )

ou gerar o arquivo remessa, ler o retorno,

oBN.GerarRemessa( ... )
oBN.LerRetorno( ...) 

e para limpar a coleção dos boletos:
oBN.LimparBoletos( ... )


Desculpe a pressa, mas o segredo está em registrar a DLL no windows (copie a DLL na mesma pasta do executável - e se for em ambiente de desenvolvimento, na pasta onde o VFP está instalado).  Com isso feito, é só olhar a classe PROXY do projeto Boleto2Net que vc vai encontrar um parse para tudo que a biblioteca faz.

[]s!

**Comment by InfiniteCodeBR** [comment]
E onde consigo baixar a versão mais atual da dll ?

Muito obrigado pela ajuda, estou saindo da cobrebemx somente agora, e tem
várias funcionalidades que preciso implementar, como boleto com pix, boleto
em PDF, etc.

Em qui., 16 de mar. de 2023 16:02, Rodolfo Duarte ***@***.***>
escreveu:

**Comment by InfiniteCodeBR** [comment]
Muito obrigado, consegui compilar a dll pelo Visual Studio, e ao registrar
só consegui pelo regasm.

Existe a possibilidade de ter uma versão com o PIX no boleto ?


*Fabiano Araújo*
(21) 9-6727-8135
(21) 9-9997-3250







Em qui., 16 de mar. de 2023 às 16:29, Rodolfo Duarte <
***@***.***> escreveu:
