### ISSUE TITLE
cnab400 banco santander

### ISSUE THREAD

**Issue by ladgodoy** [BoletoNet/boleto2net#36]
boa tarde, 

existe projeto para implementação da cobrança cnab400 do banco santander?

obrigado,

at,

luis

**Comment by rafd75** [comment]
Boa tarde!

Não está implementado. Precisa ser feito, mas acredito que ninguém esteja desenvolvendo neste momento, esse layout...

Para implementar, você precisa alterar apenas a classe BancoSantander:

1 - Os métodos GerarHeaderRemessa, GerarDetalheRemessa e GerarTrailerRemessa - use como exemplo as chamadas da classe BancoBrasil (que já tem CNAB240 e CNAB400 implementados).

2 - E cada um dos métodos que serão responsáveis por gerar os registros propriamente ditos: GerarHeaderRemessaCNAB400 , GerarDetalheRemessaCNAB400 (no BB, gera 2 registros: 7 e 5) e por fim GerarTrailerRemessaCNAB400.

Além disso, implementar o Teste Unitário (Conforme a classe Brasil_17_019_REM400)

Acho que é isso... Se fizer, não esqueça de mandar um PR no final para deixar disponível a todos.

**Comment by ladgodoy** [comment]
ok, obrigado, vou ver o que eu consig fazer.

**Comment by rafd75** [comment]
@carloscds - acho que pode fechar essa issue!

**Comment by WillPvt** [comment]
Também estou precisando implementar, alguém tem o código?

**Comment by carloscds** [comment]
@WillPvt Esta issue esta duplicada.
