### ISSUE TITLE
Remessa Banco Sicoob

### ISSUE THREAD

**Issue by KevimB** [BoletoNet/boleto2net#360]
Alguem tem um exemplo de codigo que esteja funcionando pra gerar a remessa do banco sicoob ?
Eu gerei minha remessa e na hora de fazer a homologação o banco me retornou que esta faltando digitos, esta ficando como se a remessa estivesse incompleta
Essa foi a mensagem que o banco me retornou
![WhatsApp Image 2023-07-03 at 09 28 11](https://github.com/BoletoNet/boleto2net/assets/48721632/5e39dc6a-5caa-449a-988d-c25f1c732e3c)

**Comment by carloscds** [comment]
@KevimB Ja deu uma olhada nos projetos de teste: https://github.com/BoletoNet/boleto2net/tree/master/Boleto2.Net.Testes
