### ISSUE TITLE
Homologado para api Cobrança do Banco do Brasil?

### ISSUE THREAD

**Issue by JASN2023** [BoletoNet/boleto2net#361]
Boa tarde pessoal!!
Há muito tempo que trabalhei com projeto de cobrança bancária, estou um pouco desatualizado.

Em relação a api Cobrança para registrar e consultar boletos, é possível utilizar o boleto2net, apenas para 
a geração do layout do boleto? Visto que arquivos remessas e retornos não são mais utilizados com a inclusão da 
api.

**Comment by carloscds** [comment]
@JASN2023 pode sim, sem problemas.
