### ISSUE TITLE
CNAB400 Banrisul Obsoleta - Migrar para CNAB240

### ISSUE THREAD

**Issue by sfheradev** [BoletoNet/boleto2net#362]
Remessas no layout CNAB400 não estão sendo mais aceitas pelo banco, somente em CNAB240, que até então não foi implementada, alguma pretensão do desenvolvimento ser retomado?

**Comment by rafd75** [comment]
Boa tarde.   Eu implementei o padrão 400 no Banrisul.
Na ocasião, era o que o cliente precisava...

Com relação a implementar novos padrões no sistema, são realizados de acordo com a necessidade de quem utiliza o projeto. Por isso, não existe nenhuma agenda programada.

Você precisaria, caso deseje utilizar, implementar esse padrão no Banrisul... Caso faça, mande um PR de volta para ser incorporado no projeto.
