### ISSUE TITLE
Cobrança do Banco do Brasil API PIX

### ISSUE THREAD

**Issue by joaospagno2023** [BoletoNet/boleto2net#364]
Ola Caro Amigos alguem ja tem algum exemplo de boleto com  marca pix gerado pelo sistema ou exemplo onde posso me expirar ?

**Comment by rafd75** [comment]
@joaospagno2023 boa tarde! ... No projeto Boleto2Net, não existe esse recurso.

**Comment by Josebr1** [comment]
Estou trabalhando nesta funcionalidade para o Bradesco, estou implementando seguindo a documentação do boleto hibrido.
Utilizando as informações de TXID e chave que são fornecidas no arquivo CNAB400.

**Comment by joaospagno2023** [comment]
Vc quer ajuda estou disponível

Em sex., 13 de out. de 2023 15:01, José Antônio ***@***.***>
escreveu:
