### ISSUE TITLE
Arquivo Remessa Sicredi cnab400 - Rejeitado-A6

### ISSUE THREAD

**Issue by ferreira37** [BoletoNet/boleto2net#365]
Boa tarde a todos!
Estou com um problema na remessa do banco Sicredi, ao enviar para o banco recebo a mensagem de rejeitado-A6.
No manual diz "A6 - Data da instrução/ocorrência inválida ".
Alguem saberia me dizer onde passo essa informação para fazer a correção?
Obrigado

**Comment by rafd75** [comment]
Opa... boa tarde!
Na minha opinião, esse banco/carteira precisa ser revisado por inteiro.
Sempre que tentam utilizar, da algum problema.
Infelizmente eu não tenho nenhum cliente que usa Sicred... Quando aparecer por aqui, eu vou refazer/revisar a classe toda.
Possivelmente os testes também devem ter algum tipo de falha...

**Comment by ferreira37** [comment]
> Opa... boa tarde! Na minha opinião, esse banco/carteira precisa ser revisado por inteiro. Sempre que tentam utilizar, da algum problema. Infelizmente eu não tenho nenhum cliente que usa Sicred... Quando aparecer por aqui, eu vou refazer/revisar a classe toda. Possivelmente os testes também devem ter algum tipo de falha...

Blza Obrigado

**Comment by FabioDlink** [comment]
@ferreira37 boa tarde. Conseguiu evoluir com a remessa do **SICREDI**?.
Eu também estou com dificuldade na validação do arquvivo de Remessa deste banco.

**Comment by ferreira37** [comment]
> @ferreira37 boa tarde. Conseguiu evoluir com a remessa do **SICREDI**?. Eu também estou com dificuldade na validação do arquvivo de Remessa deste banco.

Bom dia @FabioDlink !
Consegui homologar sim, esse código A6 no meu caso foi um erro bobo, era a formatação da data.
O erro que você está recebendo é esse mesmo?
