### ISSUE TITLE
É atual?

### ISSUE THREAD

**Issue by andrelncampos** [BoletoNet/boleto2net#366]
Pelas datas de atualização e das issues, me parece que este projeto não tem sido atualizado frequentemente. Devo usar este projeto ou o BoletoNet original? Ou há outra solução mais atual?

**Comment by rafd75** [comment]
Oi @andrelncampos , boa tarde!

Esse projeto é uma refatoração do BoletoNet.
O objetivo foi padronizar as classes de bancos que eu utilizava naquele momento.
Acho que fora esses bancos, implementaram o Sicredi (mas que o pessoal que usa costuma reclamar)

O BoletoNet nunca deixou de ser utilizado. Eu usei com o Bradesco (antes do Boleto2Net) e quando precisei da Caixa, acabei fazendo essa refatoração. Mas o BoletoNet tem mais usuários... e mais bancos/carteiras que esse aqui.

Sei também que tem um projeto com o NetCore, mas eu não uso.

Na minha opinião pessoal, se você for usar os bancos que estão aqui, eu ficaria com esse projeto (por questão de código mais padronizado). Porém, se for utilizar algum banco que não esteja no projeto, você irá precisar implementar (algo que possivelmente no BoletoNet já deve estar disponível).
