### ISSUE TITLE
@wellingtonarantesjunior , boa noite.

### ISSUE THREAD

**Issue by wellingtonarantesjunior** [BoletoNet/boleto2net#367]
@wellingtonarantesjunior , boa noite.

O que diz o manual referente a esse campo?

_Originally posted by @rafd75 in https://github.com/BoletoNet/boleto2net/issues/221#issuecomment-1955563637_
            
Entao pelo manual do BB esse campo deve conter '000' nas posicoes 210 a 212, nao sei se estou utilizando o componente errado, ou se realmente ele cria o arquivo de remessa com espaços vazios nessas posições.

https://www.bb.com.br/docs/pub/emp/empl/dwn/CNAB240SegPQRSTY.pdf

pagina 15 do manual campo 20.3Q - Cód. Bco. Corresp. na Compensação

**Comment by rafd75** [comment]
Vi que o manual é de Jan/24 e provavelmente ajustaram isso... 

Acredito que alterar a linha:
`
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0210, 003, 0, string.Empty, ' ');`

para
`
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0210, 003, 0, "0", ' ');`

resolva o problema. Faça esse ajuste, e se ficar ok, mande um pull request para publicar aqui no repositório.
