### ISSUE TITLE
Erro Sicoob Carteira não implementada: 1/01

### ISSUE THREAD

**Issue by DomicianoRibeiro** [BoletoNet/boleto2net#368]
Boa noite.
Utilizo o boleto2net a algum tempo, mais agora o sistema começou sem mexer em nada um erro "Carteira não implementada: 1/01", para o banco sicoob, vi um tópico pedindo para colocar fixos as duas propriedades abaixo, mais comigo não funcionou, já tentei varias coisas e nada.

                    CarteiraPadrao = "1",
                    VariacaoCarteiraPadrao = "01",

Eu utilizo não o código fonte mais sim a referência pelo nuget.

**Comment by rafd75** [comment]
boa tarde...

Parece estar correto... https://github.com/BoletoNet/boleto2net/blob/49bc62d6717eaae8069de3105f3de26f70a48dc7/Boleto2.Net/Banco/Carteiras/BancoSicoob/BancoSincoobCarteira1.cs#L7

**Comment by rafd75** [comment]
Da uma olhada no teste unitário do sicoob:

https://github.com/BoletoNet/boleto2net/blob/master/Boleto2.Net.Testes/BancoSicoobCarteira1_01Tests.cs

compara com seu código

**Comment by DomicianoRibeiro** [comment]
Boa noite.
Obrigado pela ajuda, mais sim está tudo correto, segue o código:

Só que o n da conta tem 9 digitos e só esta aceitando 8, ex: 200509002 não aceita e assim 00509002 aceita, só que dá erro na hora que manda o remessa no banco.

Isso começou do nada, o sistema era usado normalmente e com o mesmo código. 

![image](https://github.com/BoletoNet/boleto2net/assets/67517800/073d2c11-5011-4847-ae00-22a9af10587d)

**Comment by rafd75** [comment]
Já me perdi no seu problema... 

Se houve erro "Carteira não implementada: 1/01" ao instanciar o componente, como você conseguiu gerar um arquivo para o banco?

**Comment by DomicianoRibeiro** [comment]
bom dia.
Obrigado pela ajuda.

Mais o erro não é sobre a carteira, o erro que da é "O número da conta (200207002) deve conter 8 dígitos." e a conta tem 9 digitos.

**Comment by rafd75** [comment]
é que o título dessa issue é "Erro Sicoob Carteira não implementada: 1/01"
mas isso você já resolveu, certo?


Para o outro problema - sobre número de dígitos da conta - não consegui encontrar no Sicoob onde tem essa validação.

Passei a vista por cima na implementação do Sicoob, e no arquivo remessa, está alocado 12 caracteres para conta. (vi rapidamente, então posso estar enganado)

Você vai precisar depurar seu código e passar a classe/linha onde está falhando.
