### ISSUE TITLE
Banco Safra Problema para pagar o Boleto

### ISSUE THREAD

**Issue by ferreira37** [BoletoNet/boleto2net#372]
Bom dia a todos!
Estamos homologando a emissão de boletos para o banco Safra, mas estamos enfrentando o seguinte problema:
Fazemos a geração do boleto, registramos a remessa no banco (não apresentou problema na remessa até então), porém não é possível fazer o pagamento do boleto. No app bancário digito o código para fazer o pagamento e diz que o boleto não foi registrado, mas sendo que está lá registrado tudo certo.
Há mais de uma semana enviamos mensagem para o banco, mas não tivemos resposta até agora.
Alguém já passou por esse problema e conseguiu resolver?
Se puderem me dar uma dica agradeço.

**Comment by carloscds** [comment]
@ferreira37 neste caso você precisa enviar o boleto ao banco para eles validarem. Normalmente é erro de código de convênio.

**Comment by ferreira37** [comment]
> @ferreira37 neste caso você precisa enviar o boleto ao banco para eles validarem. Normalmente é erro de código de convênio.

@carloscds Obrigado pelo retorno.
Nós já enviamos e explicamos a situação no e-mail, o complicado é a demora pra responder.

**Comment by rafd75** [comment]
@ferreira37 boa tarde...

Isso está em produção, confere?

Sendo em produção, no dia seguinte ao envio da remessa, deveria voltar um arquivo retorno com a operação "ENTRADA CONFIRMADA" para cada um dos títulos enviados.

Se enviou 50 títulos, no dia seguinte, 50 entradas confirmadas.

Se isso não ocorreu, deve ser pelo que o @carloscds falou... tem algo errado (número do convênio) que não identificou a conta corretamente e os títulos não foram aceitos. E nesse caso, pode não existir um arquivo retorno. As vezes que isso ocorreu por aqui, falando com o gerente da conta do cliente, consegui rapidamente apoio da equipe de suporte do banco, que consegue visualizar o arquivo enviado, e o motivo da rejeição (sem retorno).

**Comment by ferreira37** [comment]
> @ferreira37 boa tarde...
> 
> Isso está em produção, confere?
> 
> Sendo em produção, no dia seguinte ao envio da remessa, deveria voltar um arquivo retorno com a operação "ENTRADA CONFIRMADA" para cada um dos títulos enviados.
> 
> Se enviou 50 títulos, no dia seguinte, 50 entradas confirmadas.
> 
> Se isso não ocorreu, deve ser pelo que o @carloscds falou... tem algo errado (número do convênio) que não identificou a conta corretamente e os títulos não foram aceitos. E nesse caso, pode não existir um arquivo retorno. As vezes que isso ocorreu por aqui, falando com o gerente da conta do cliente, consegui rapidamente apoio da equipe de suporte do banco, que consegue visualizar o arquivo enviado, e o motivo da rejeição (sem retorno).

Boa tarde @rafd75 !
Vou fazer isso que você sugeriu, verificar se teve o retorno dos títulos, se não tiver entrar em contato com o gerente novamente pra resolver logo isso.

**Comment by ferreira37** [comment]
Bom dia a todos!
Pessoal responderam o e-mail e me passaram as seguintes correções:

Boletos: Identificamos alguns erros para correção, favor verificar e corrigir conforme consta na ilustração.  
1.	Informada multa nos boletos porém não configurado na remessa.
2.	Alterar a nomenclatura de Sacador Avalista para Beneficiário final - (Obs: No boleto físico, o termo Avalista foi substituído por Beneficiário final, conforme Convenção entre Instituições do Sistema Financeiro Nacional FB-0061/2021”).  
Após realizar as correções, peço gerar novos arquivos (remessa txt e 3 boletos em PDF) e nos enviar para nova análise.

Esses eram os erros que eles identificaram.
Já fiz as modificações e está tudo certo agora.
