### ISSUE TITLE
Guia de Remessa Bradesco

### ISSUE THREAD

**Issue by dieggop** [BoletoNet/boleto2net#39]
Fala Galera, tudo bem?

Alguém já conseguiu implementar ou gerar as Guias de Remessa do Bradesco?

**Comment by rafd75** [comment]
@dieggop , bom dia... 

O que seria "guias de remessa" ?  é o mesmo que gerar o arquivo REMESSA CNAB?

se for, eu já uso faz tempo (foi o primeiro banco que implementei... Qual a dúvida?

**Comment by dieggop** [comment]
Ele mesmo RAFD, é que tou tendo um problema pra gerar essa do CNAB400 do Bradesco.!

Consegui gerar já do BB e da Caixa, tanto Cnab240 quanto Cnab400

mas bradesco, tou encalhado nesse erro

![image](https://user-images.githubusercontent.com/3966705/31017400-af4b59ec-a4fe-11e7-84d5-531ff51f5d69.png)

**Comment by rafd75** [comment]
@dieggop - o Bradesco deve utilizar alguma propriedade (que caixa e BB não utilizam) e deve estar com NULL.

Você não consegue depurar ai?

Eu estou gerando Bradesco normalmente. Mas aqui, para fazer toda a configuração, eu sempre uso a classe Boleto2NetProxy (métodos SetupCobranca e depois NovoBoleto / DefinirSacado / DefinirBoleto / ... / FecharBoleto) - para gerar o boleto (PDF ou HTML), o método GerarBoletos - e para gerar o arquivo remessa, , o  método GerarRemessa. Tudo isso, dentro da classe Boleto2NetProxy.

**Comment by dieggop** [comment]
Bacana @rafd75 , vou testar com essa classe, ainda não usei ela. Tava gerando de maneira padrão, ContaBancaria  / Cedente / new Boleto /  b.Valida() / objBOLETOS.Add / depois chamo os metodos que criei montaRemessa400(objBOLETOS, c) que dentro deles tem ValidarArquivoRemessa e GerarArquivoRemessa.

Vou tentar com esse Boleto2NetProxy que você citou

**Comment by dieggop** [comment]
Ahh, atualmente uso o BoletoNet normal... será que terei broncas? hehehe

**Comment by rafd75** [comment]
@dieggop - o erro está dando no Boleto2Net ou no BoletoNet?

se for BoletoNet - você precisa colocar sua dúvida aqui:

https://github.com/BoletoNet/boletonet/issues

**Comment by dieggop** [comment]
BoletoNet. Achei que eram mesmo projeto. Sorry man!

**Comment by rafd75** [comment]
Sem problemas! ... abs!

@carloscds  - pode fechar essa issue! hehe

**Comment by dieggop** [comment]
Abs!
