### ISSUE TITLE
Erro ao compilar (VS2015)

### ISSUE THREAD

**Issue by RogerMTT** [BoletoNet/boleto2net#4]
Boa tarde,

não consigo compilar usando o VS2015, existe algum requisito especial para o projeto ?

O VS2015 não está reconhecendo os comandos do tipo:

`Cedente.Codigo = codigoCedente.Length <= 6 ? codigoCedente.PadLeft(6, '0'): throw Boleto2NetException.CodigoCedenteInvalido(codigoCedente);
`

Em todas as linhas semelhantes ele acusa a falta do ";" e reclama do "<=" como 

> Invalid token '=>' in class, struct, or interface member declaration

**Comment by rafd75** [comment]
Eu estou usando o VS2017 e compila sem problemas.

@AlbertoMonteiro - Sabe dizer algo sobre não rodar no VS2015? Lembro de ter falado algo da versão do C# ou Framework... não me recordo bem.

**Comment by AlbertoMonteiro** [comment]
@RogerMTT O projeto usa C# 7, então você vai precisar do Visual Studio 2017 para compilar

@rafd75 respondido :D

**Comment by RogerMTT** [comment]
Obrigado @AlbertoMonteiro e @rafd75  !

Acabei de instalar e funcionou 100% ;)

Agora mãos à obra...
