### ISSUE TITLE
Participar do Projeto

### ISSUE THREAD

**Issue by natanaelsantosp** [BoletoNet/boleto2net#40]
Olá Gostaria de contribuir com o projeto, estou usando ele no ambiente de produção e vi que o código de ocorrência esta fixo, mudei para de acordo com o boleto. (Itau)

Arquivo:Boleto2.Net\Banco\BancoItau.cs

Linha:279
`reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0109, 002, 0, "01", ' ');`

depois
`reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0109, 002, 0, boleto.CodigoOcorrencia, ' ');`

Queria fazer o pull requests

**Comment by rafd75** [comment]
@natanaelsantosp bom dia!

Seria interessante, já fazer um PR considerando todos os bancos/carteiras implementados, para manter o padrão no projeto. Você conseguiria verificar os demais e depois então para fazer um PR ?

**Comment by rafd75** [comment]
Obs: Fui eu quem fiz assim. Na minha aplicação, eu só gero arquivo remessa para inclusões (por isso o fixo "01"). As demais operações, são comandadas no banco e eu atualizo a base no dia seguinte (com o retorno - por ex: alteração de vencimento).

Mas faz sentido implantar da forma que você comentou, assim fica mais flexível (eu só não sei se para outras operações, o resto do layout fica igual a operação 01).

Outra coisa importante - para não travar o que já está funcionando, essa propriedade (CodigoOcorrencia) deve ser inicializada com "01" sempre.

**Comment by natanaelsantosp** [comment]
Eu entendi essa lógica, mas me tira uma dúvida de como vc esta fazendo

So que aqui na empresa a gente não gosta de ficar 'refém' do banco, porque isso impede de ir para outros bancos. 

Eu posso fazer isso. Pode me dar acesso ao projeto?

**Comment by rafd75** [comment]
Eu sempre gero o arquivo remessa com a operação 01 (registro de novos títulos). Qualquer outra alteração, o usuário faz no homebanking. Após a alteração dele no homebanking, no dia seguinte, vem no retorno tudo que ocorreu, seja pagamento, alteração de vencimento, abatimento, e então atualizo nossa base de dados.

Quanto a alteração, o projeto é público... Clona, altera e faça um PR para aprovação. A única coisa que precisa ser feita, é que, **essa propriedade CodigoOcorrencia do objeto Boleto precisa ser iniciada com 01 para não dar problema em quem já está usando o componente**.

**Comment by natanaelsantosp** [comment]
Pronto,

Fiz conforme solicitado.

**Comment by natanaelsantosp** [comment]
Outra dúvida sabe me dizer como é o processo de atualização no nuget ?
