### ISSUE TITLE
Adicionar mais informações referentes ao arquivo de retorno

### ISSUE THREAD

**Issue by krgm03** [BoletoNet/boleto2net#41]
Bom dia

Pelo que vi em 'ArquivoRetorno.cs' e se não estiver equivocado não há propriedades, além dos boletos que compõe o arquivo, referentes ao arquivo de retorno,

Aqui por exemplo é fundamental eu ter as seguintes propriedades:
 
![novas propriedades arquivo de retorno](https://user-images.githubusercontent.com/6650072/31084038-c0b57056-a769-11e7-95e5-47acc3892940.png)

Aqui por enquanto estou usando apenas Santander mas acredito que essas propriedades também estejam presentes nos demais bancos

O ideal seria acessar tais propriedades em 'ArquivoRetorno' após chamar 'LerArquivoRetorno' para evitar fazer esse trabalho fora do boleto2net

**Comment by krgm03** [comment]
Boa noite, @rafd75 

Conforme citei no comentário acima, as propriedades 'Data de geração' e 'Nº sequencial', conforme mostra a imagem, ainda não constam no boleto2net

Estou disposto a implementar a inclusão, mas antes gostaria de trocar uma ideia para ver qual a melhor forma/local

O método 'LerArquivoRetorno' da classe 'ArquivoRetorno' retorna um 'Boletos', então uma alternativa seria incluir as propriedades na classe 'Boletos' conforme segue abaixo:

public class Boletos : List<Boleto>
{
        public IBanco Banco { get; set; }
        **public DateTime? dataGeracao { get; set; }** //NOVA 144 - 151 Data de geração do arquivo N 008
        **public int? numeroSequencial { get; set; }** //NOVA 158 - 163 Nº seqüencial do arquivo N 006
}

deixei Nullable mas acredito que essas propriedades estejam também nos layout dos demais bancos
o que acha?

**Comment by rafd75** [comment]
Bom dia!... 

Por se tratar de uma informação do arquivo todo (lote), o correto seria na classe Boletos mesmo, conforme você sugeriu...

O nome da propriedade, se puder ser usada também na geração do arquivo remessa, estão perfeitas... dataGeracao (remessa ou retorno), idem para o numeroSequencial.

No caso do numeroSequencial, se implementado, não seria o caso de eliminar o parâmetro do construtor da classe ArquivoRemessa, e passar a usar esse parametro? --- eu só não sei a forma correta de fazer isso para não quebrar o código existente, e ao mesmo tempo, não deixar uma mesma informação de 2 maneiras diferentes... 

 public ArquivoRemessa(IBanco banco, TipoArquivo tipoArquivo, int numeroArquivoRemessa)

ou, outra saída, seria usar dataGeracaoRetorno, numeroSequencialRetorno e então só preencher isso nesse caso.

ou ainda, criar uma classe DadosArquivoRetorno, com essas 2 propriedades dentro, e na classe Boletos, usar a DadosArquivoRetorno

sobre a questão do nullable, eu não sei te dizer... na verdade minha ferramenta principal (Visual FoxPro) trabalha com NULL, mas na prática, não uso. Talvez seja melhor pegar a opinião de outras pessoas...

@carloscds + @AlbertoMonteiro - seria interessante vocês darem uma olhada nessa issue aqui...

**Comment by AlbertoMonteiro** [comment]
@krgm03 de qual layout de arquivo retorno você está falando?

**Comment by rafd75** [comment]
@AlbertoMonteiro bom dia... são 2 campos que estão no header do arquivo (ou do lote), que informa a data que o arquivo foi gerado pelo banco, e o número sequencial desse arquivo.

ou seja, informação comum, independente do número de títulos no retorno.

provavelmente o @krgm03 utiliza essa informação para não ler arquivo duplicado no sistema, ou algo assim.

**Comment by krgm03** [comment]
@AlbertoMonteiro , Santander - Padrão 240 – Versão 2.8, conforme mostra a imagem do primeiro comentário

@rafd75, outra opção, e talvez melhor, seria colocar as propriedades dentro da classe 'ArquivoRetorno' e alimentá-las/carrega-las no método 'LerArquivoRetorno'

pois acho que na remessa a 'data de geração' e 'número sequencial' devem continuar da mesma forma, ou seja, com o boleto2net cuidando disso

**Comment by rafd75** [comment]
> @rafd75, outra opção, e talvez melhor, seria colocar as propriedades dentro da classe 'ArquivoRetorno' e alimentá-las/carrega-las no método 'LerArquivoRetorno'

Boa solução...

**Comment by AlbertoMonteiro** [comment]
@krgm03 Não tinha nenhuma informação na imagem que informasse que o layout era o CNAB 240.
Isso tem que ser analisado com calma, pois pode ser um layout só do bradesco, uma "modificação" do CNAB 240, e que deixaria de ser incompatíveis com os outros bancos.

**Comment by krgm03** [comment]
@AlbertoMonteiro, na imagem estão apenas as propriedades mesmo...o layout é do Santander e não Bradesco

Também acho que deve ser analisado com calma, por isso mesmo comentei que gostaria de trocar uma ideia sobre a melhor maneira

Imagino que todos os bancos devem fornecer a data de geração do arquivo de retorno e o número dele

**Comment by rafd75** [comment]
Acho que colocar as informações do arquivo retorno, na própria classe arquivo retorno, seria melhor que na classe Boletos...

**Comment by krgm03** [comment]
No método 'LerLinhaDoArquivoRetornoCNAB240' da classe 'ArquivoRetorno' existem apenas verificações para os segmentos 'T' e 'U' e a regra de verificação é geral, ou seja, igual para todos os bancos

Seria bem interessante haver aqui no repositório dos os documentos(pdf..) referente a todos os layouts já implementados

**Comment by krgm03** [comment]
Verifiquei nos layout dos bancos já implementados e constatei que há um padrão, ou seja, em todos o tipo de registro que indica 'REGISTRO HEADER DO ARQUIVO RETORNO' é igual a '0'(zero)

Inclusive as posições das propriedades 'data de geração' e 'número sequencial' são as mesmas em todos os layouts

Atualmente o 'Banco' é passado para o construtor da classe 'ArquivoRetorno'
Eu acho que seria muito importante o 'Banco' ser construído dentro da classe 'ArquivoRetorno'
Digo isso pois atualmente, caso eu não esteja enganado, pode ocorrer o seguinte:
- Instancio 'ArquivoRetorno' passando o banco 'Bradesco' por exemplo e depois chamo o método 'LerArquivoRetorno' passando um arquivo de retorno do banco 'Santander'. Se não me engano não há nenhum tipo de validação....o que pode ocorrer são erros na leitura de propriedades por estarem em posições diferentes nos layouts
- Outra situação e aqui mais problemática é instanciar o 'Arquivo retorno' passando o banco 'Santander' por exemplo e depois chamo o método 'LerArquivoRetorno' passando um arquivo de retorno também do banco 'Santander' mas de outra conta

Lógico que dentro da minha aplicação posso realizar validações, inclusive há em cada boleto os dados da conta, mas se o boleto2net carregasse o 'Banco' de acordo com o que há no arquivo de retorno já facilitaria bem mais
