### ISSUE TITLE
Codificação

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boleto2net#46]
Boa tarde,

Eu peguei este exemplo: https://github.com/BoletoNet/boleto2net/issues/31#issuecomment-328541440 e adicionei isto no final:
```
           var stream = new MemoryStream();
            var remessa = new ArquivoRemessa(boletos.Banco, TipoArquivo.CNAB240, 1);
            remessa.GerarArquivoRemessa(boletos, stream);
            File.WriteAllBytes(@"d:\remessa.txt", stream.ToArray());

            var lista = new List<BoletoBancario>();
            var boletoBancario = new BoletoBancario();
            boletoBancario.Boleto = boleto;

            var pdf = boletoBancario.MontaBytesPDF();
            File.WriteAllBytes(@"d:\boleto.pdf", pdf);
```

A ideia aqui é gerar um PDF para cada boleto e um arquivo de remessa para todos eles no formato CNAB240.

Esta implementação está correta? vi que os arquivos foram gerados, "batendo o olho" neles parecem estar ok, mas eu não entendi muito bem a diferença de boleto e boletobancario, etc.

Obrigado, Marcos

**Comment by rafd75** [comment]
@marcosgerene , tive a mesma impressão quando vi esse código no projeto BoletoNet.

A classe Boleto corresponde apenas aos dados (informações, propriedades) do boleto... 

Já a classe BoletoBancario, é a representação visual (papel) do boleto, com possibilidade de imprimir um descritivo dos lançamentos, comprovante do pagador, etc... 

Por isso, na geração do arquivo remessa, a classe BoletoBancario não é utilizada, pois somente a classe Boleto já contém as propriedades necessárias para geração / leitura dos arquivos.

**Comment by marcosgerene** [comment]
@rafd75 entendi, presumo então que o código que eu citei acima está correto.

Vou implementar isto em meu software e tentar homologar com a Sicoob.

Obrigado pelas informações
