### ISSUE TITLE
Ocorrencia - Código e descrição

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boleto2net#47]
Bom dia a todos,

Eu venho do ACBr com Lazarus e implementei ontem o boleto2.net no meu projeto, enviei agora os arquivos para análise.

Em primeiro lugar gostaria de parabenizar a todos pelo projeto, em especial o @rafd75 por este comentário https://github.com/BoletoNet/boleto2net/issues/31#issuecomment-328541440 que me fez entender o componente como um todo (eu já havia tentando usar o BoletoNet antes mas tinha achado muito confuso).

Bom, vamos ao que interessa:
Hoje o componente trata o código da ocorrência e a sua descrição como uma string, a minha proposta seria tratar isso como um **ENUM** e em cada banco tratar este enum, algo como faz o ACBr.

Como temos poucos bancos aqui ainda e o fonte do ACBr é aberto para ser consultado, o que adiantaria e muito a pesquisa do significado de cada código para cada banco, acredito que seja uma tarefa relativamente simples. Mesmo eu sendo novo no projeto se me passarem o padrão desejado eu mesmo posso fazer o PR para isto, mas antes gostaria de discutir qual seria o padrão da implementação e claro, se os contribuidores atuais do projeto compartilham da mesma opinião.

Att, Marcos

**Comment by marcosgerene** [comment]
Enum e decrições:
[enum e descrições.txt](https://github.com/BoletoNet/boleto2net/files/1394365/enum.e.descricoes.txt)

Aqui bastaria apenas tirar o "to" da frente e jogar a descrição como um "Description" (annotation) de cada um destes enum.

Feito isto o tratamento tem que ser diferenciado para cada banco e layout, pois alem da diferença entre bancos, no mesmo banco existem diferenças entre os cnabs

As ocorrências separadas por banco, arquivo e layout:
[Ocorrencias ACBr.txt](https://github.com/BoletoNet/boleto2net/files/1394352/Ocorrencias.ACBr.txt)

**Comment by rafd75** [comment]
@marcosgerene , bom dia.

Se não me engano, o projeto BoletoNet original, tem as ocorrências (protestar em tantos dias, não dispensar multa, etc) como enum.

Trocar para Código/String foi uma decisão que eu tomei quando tentei deixar o Boleto2Net mais "simples". No projeto original, se não estou enganado, existe um enum para o arquivo CBR643 do BB, e outro enum para outro Cnab e assim sucessivamente.

Acho que se a solução passar por criar um UNICO enum para cada situação (por exemplo, em especial a ocorrência do retorno = Liquidação, Cartório, etc) pode ser uma boa.

De qualquer forma, precisaria compilar esse monte de informação dos Txts anexos, e verificar se não vai complicar demais a implementação de uma nova carteira... Da uma olhada no projeto BoletoNet e veja se é isso que você está propondo.

Vamos aguardar outras opiniões a respeito...

**Comment by marcosgerene** [comment]
Obrigado pelo retorno @rafd75 

Na verdade a minha proposta surgiu quando estava escrevendo meu código para leitura do retorno.

```
int[] codigosBaixa = { 6, 9, 17, 25 };  //Exemplo de códigos de baixa no bradesco 400
var boletos = retorno.LerArquivoRetorno(stream); 

foreach (var boleto in boletos)
{
   if (codigosBaixa.Contains(boleto.CodigoOcorrencia.StrToIntDef()))
   {
      //Baixar o titulo no sistema
   }
}
```

Se fizéssemos isto pelo menos para o retorno o resultado seria assim:
```
//Aqui iriam as ocorrencias da baixa, não importa qual o banco, a numeração já vai ser tratada
var ocorrenciaBaixa = List<OcorrenciaRetorno>(){ ... };  
if (ocorrenciaBaixa.Exists(o=> o ==  boleto.OcorrenciaRetorno))
{
      //Baixar o titulo no sistema
}
```

O que ficaria mais "abstrato" no software, visto que se o componente aceita N bancos, eu teria que ter no minimo um int[] diferente para cada banco que eu implemento para não ter este problema.

**Comment by marcosgerene** [comment]
Eu não sei os Srs, mas nas duas empresas que trabalhei anteriormente e no meu software atual a implementação para boleto era basicamente enviar remessa de registro e pegar retorno para baixar o c.receber.

Neste caso outra solução seria criar um campo **bool Baixado** na classe boleto e retornar true tiver dentro de um array de códigos.

Exemplo:
```
BoletoBradesco.cs
...
public bool Baixado => string[] codigosBaixa = { "06", "09", "17", "25" }.Contains(this.CodigoOcorrencia);
...
```

**Comment by rafd75** [comment]
@marcosgerene --- olha só... 

falando do Bradesco (CNAB400)... você considera "Baixado" quando 6, 9, 17, 25.

Olhando rapidamente aqui - pelo proprio código do Boleto2Net:

6 - Liquidação normal
9 - Baixado Automaticamente via Arquivo
17 - Liquidação após baixa ou Título não registrado
25 - não encontrei a descrição desta operação.

Vou ficar somente com o 6 e 9. Aqui, na nossa aplicação, entendemos que a ocorrência 6, o cliente PAGOU o título e esse $ entrou na conta corrente... Já a operação 9, o banco BAIXOU o título (ou seja, tirou da carteira de cobrança dele), mas não houve pagamento, nem crédito na conta.

Por isso eu acho complicado essa forma de implementar... Ainda com o enum, teríamos que ter o enum.Liquidacao e o enum.Baixa, entre outros...  acho que essa inteligência, tem que ficar na aplicação mesmo, pois cada aplicação pode tratar de uma forma.

Só para curiosidade, no meu retorno, eu trato diversas operações (faço banco por banco, pq é diferente... mas o bradesco é assim - desculpe o código, peguei meu fonte - Visual FoxPro - e tentei deixar de um jeito fácil de entender...:):

"02" "ENTRADA CONFIRMADA"

"03" "REGISTRO REJEITADO",;

"06","15","17" "LIQUIDAÇÃO",;

"23" "CARTÓRIO"

"09","10") and At(Codigo Auxiliar = "20" "CARTEIRA DESCONTO"

"09","10") and At(Codigo Auxiliar = "14" "PROTESTADO",;

"09","10") and Codigo Auxiliar diferente de 14 ou 20)  "BAIXA"

"14" "ALTERAÇÃO VENCIMENTO"

qualquer outra ocorrencia, eu mostro como "OUTRAS OCORRÊNCIAS" e não faço nada no banco de dados.

Voltando a operação 09.;.. para mim, ela tem 3 significados --- as vezes, baixou na SIMPLES e foi para DESCONTO... em outros casos, baixou pq foi PROTESTADO.... e finalmente, a BAIXA propriamente dita... Observe que BAIXA não significa pagamento... em nenhum desses casos, houve crédito na conta.


Enfim... tenho muito receito da interpretação de quem desenvolve a carteira, para por exemplo, colocar um Baixado = true , o que para outra aplicação, pode não ter o significado correto.


De qualquer forma, a discussão é válida, mas acho que outros precisam opinar para chegar a uma solução legal. Se conseguir padronizar isso - de forma correta - no Boleto2Net, seria muito bom.

**Comment by marcosgerene** [comment]
@rafd75 estes números que coloquei foram exemplos de uso eu simplesmente peguei o bradesco e vi alguns que tinha escrito "baixa" e coloquei ali para exemplificar shaushausha

Bem, vamos ao que importa, o campo "Baixado" concordo plenamente que seja uma ideia ruim, mas acredito que você conseguiu entender a necessidade por trás disso, hoje se eu implementar 3 bancos com o ACBr eu so vejo os liquidados, agora se implemento usando o código preciso a cada novo banco implementado no software saber quais são os códigos de liquidação...

Sobre como implementar na verdade eu não sei nem como começar, precisaria estudar o projeto mais afundo, tive o primeiro contato com ele ontem. 

Estou aberto a sugestões e disposto a fazer o que tiver ao meu alcance.

**Comment by thiagokernell** [comment]
Voltando o tópico, acho interessante ter uma propriedade dizendo que o boleto realmente foi pago, no entanto se o sistema necessitar fazer uma trativa diferente de acordo com o código da ocorrência ele poderá fazer, pois é só manter o retorno desse código. 
Mas sugiro que seria interessante um campo que identificasse se o boleto realmente foi pago, considerando as particulariedades de cada banco, seria apenas uma propriedade a mais, e ai sim o boleto.net ficaria redondo..

**Comment by carloscds** [comment]
@thiagokernell A ocorrencia que o banco informa, normalmente 06, significa que foi pago. Existe tambem a data do pagamento que volta no retorno.
