### ISSUE TITLE
Agradecimento e proposta de ajuda

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boleto2net#49]
Boa tarde a todos,

Esta issue é para agradecer o trabalho de todos, com o exemplo dado pelo @rafd75 aqui https://github.com/BoletoNet/boleto2net/issues/31#issuecomment-328541440 eu consegui implementar o boleto2net e homologar meus boletos no Sicoob em ,menos de uma semana com pouco menos de 3 horas de programação, sendo que fiz tudo "do zero".

O componente está excelente, eu já havia tentando usar o BoletoNet uma vez e não consegui eu nem sei se o exemplo que citei acima se encaixa lá, mas quando tentei a usar a pouco menos de um ano achei o projeto absurdamente confuso, mas um simples exemplo de código resolveu meu problema.

A minhas proposta para contribuição seria documentar um pouco melhor ou disponibilizar alguns exemplos no wiki mesmo, parece que não mas uma classe chamada "Boleto" e outra "BoletoBancario" faz um iniciante (meu caso) apanhar muito e um exemplo de poucas linhas aliado a um pouco de boa vontade por parte de quem está fazendo (também meu caso) fez o problema "sumir" em questão de minutos.

Como podemos melhorar isso, estou disposto ajudar nesse sentido para que o projeto cresça cada vez mais.

Muito obrigado a todos, 

Abraços

**Comment by rafd75** [comment]
@marcosgerene que legal!

Blz... Sobre a documentação, exemplos, etc... eu acho que seria bacana em forma de teste unitário.

vejo no WIKI um problema... o exemplo de hoje, pode não funcionar amanhã... Mas se fizermos em forma de teste unitário, sempre irá funcionar...

Se fizermos um teste "exemplo" bem comentado, resolve os 2 problemas: Ensinar novos usuários a implementar o componente, e garante que o exemplo sempre funcional mesmo com as atualizações futuras no código.

**Comment by marcosgerene** [comment]
@rafd75 outos projetos como o ACBr.Sat e Zeus (NFe) tem um Demo em winforms/wpf mesmo, bem simples de usar, acredito que seja uma ideia interessante também nesse sentido

**Comment by Kelcyo** [comment]
Estou trabalhando com MVC e não estou conseguindo gerar a visualização do Boleto.
Na versão anterior o código era simples "ViewBag.Boleto = mBoleto.MontaHtmlEmbedded();", agora estou tentando mapear uma pasta no servidor e chamando o método para gerar os boletos, mas o mesmo não salva o arquivo:
var nomePasta = Server.MapPath("~/BoletosTemp");
                    if (Directory.Exists(nomePasta) == false)
                        Directory.CreateDirectory(nomePasta);
classeProxy.GerarBoletos(nomePasta + @"ClasseProxy_Boleto.pdf", ref mensagemErro);

Alguém tem alguma dica como utilizar em MVC a visualização do Boleto?

**Comment by rafd75** [comment]
@marcosgerene - ai sim... um projeto dentro da solution, pode ajudar, e não corre o risco de não ser atualizado conforme o projeto vai evoluindo... se uma alteração quebra o exemplo, a pessoa vai se atentar e corrigir, para manter o exemplo sempre confiável.

**Comment by lehfrz** [comment]
Boa tarde pessoal, vou começar a estudar o fonte para poder fazer a implementação...
O Zeus conta com um grupo no skype para apoio... o BoletoNet possui um tbm? se nao tiver poderíamos criar para facilitar a troca de informações entre os desenvolvedores..

**Comment by carloscds** [comment]
@lehfrz Hoje nao temos, mas pode ser uma boa ideia.

**Comment by elton007** [comment]
Boa noite!
Estou iniciando a implementação do boleto2net, onde posso obter exemplos práticos de como se utilizar inicialmente?
Há algum grupo ?
Obrigado!

**Comment by carloscds** [comment]
@elton007 No código fonte tem vários exemplo, principalmente nos testes.

**Comment by elton007** [comment]
Boa tarde @carloscds , ainda não obtive êxito, porém a luta continua rs

Obrigado!
