### ISSUE TITLE
Como Ajustar o tamanho da Fonte do Boleto Bancario

### ISSUE THREAD

**Issue by natanaelsantosp** [BoletoNet/boleto2net#50]
Boa Tarde Pessoal,

Alguém sabe como Ajusta o tamanho da fonte do boleto bancário ?

**Comment by carloscds** [comment]
@natanaelsantosp Existe um arquivo com o layout, mas o tamanho da fonte é padrão.

**Comment by natanaelsantosp** [comment]
Eu posso alterar esse arquivo ? E fazer uma pr ?

**Comment by carloscds** [comment]
@natanaelsantosp Os tamanhos são padrão! Sugiro não alterar.

**Comment by Kelcyo** [comment]
Observei que as fontes são tamanho padrão. Mas e o layout, eu posso ajustar o layout? se sim, onde realizo estas alterações?

**Comment by carloscds** [comment]
@Kelcyo O layout é padrão dos bancos, mudar as fontes e/ou estrutura pode gerar problemas de homologação.
