### ISSUE TITLE
Número do Arquivo Remessa

### ISSUE THREAD

**Issue by leopipolo** [BoletoNet/boleto2net#51]
Boa tarde,

Estou começando agora com a Boleto.NET e com geração de boleto de forma geral. Eu vi os exemplos e já tenho uma ideia geral do procedimento que devo adotar: primeiro crio uma instância da classe `Boletos`, defino o banco e o cedente, depois para cada boleto crio uma instância da classe `Boleto` com os dados específicos daquele boleto e adiciono aos boletos. Até aqui acho que está tudo bem.

Minha dúvida é na geração do arquivo remessa. Ao instanciar `ArquivoRemessa` eu preciso passar o parâmetro `sequenciaArquivo`. O que é esse parâmetro, e de onde eu devo obtê-lo? Me parece algo simples, mas como eu disse, estou começando agora com geração de boleto.

Muito obrigado desde já!

**Comment by marcosgerene** [comment]
Acredito que você esteja falando do campo `NumeroArquivoRemessa`, não encontrei campo  "sequenciaArquivo". Se for este o caso, segue explicação:

Cada remessa deve ter um número identificador, por padrão usa-se números sequenciais, não podem existir mais de uma remessa com o mesmo número, funciona como um Unique Key.

**Comment by leopipolo** [comment]
@marcosgerene é esse campo mesmo, eu devia ter passado do jeito que está na classe, mas acabei passando o nome que foi usado na classe `Boleto2NetProxy`. 

Então ele é como o "Nosso Número" do boleto, mas para o arquivo remessa? Aí para uma dada conta que vai gerar boletos, esse número tem de ser único e por padrão começa em 1 e vai incrementando conforme se gera remessas, é isso? Obrigado pela ajuda!

**Comment by marcosgerene** [comment]
>@marcosgerene é esse campo mesmo, eu devia ter passado o nome do campo mesmo, do jeito que está na classe, mas acabei passando o nome que foi usado na classe Boleto2NetProxy.

>Então ele é como o "Nosso Número" do boleto, mas para o arquivo remessa? Aí para uma dada conta que vai gerar boletos, esse número tem de ser único e por padrão começa em 1 e vai incrementando conforme se gera remessas, é isso? Obrigado pela ajuda!

Sim, mas não obrigatoriamente deve ser incrementado, a única exigência é que não se repita, nada impede que mande uma remessa 10 e a seguinte seja a 6. Obviamente a melhor solução é ir incrementando.


Se o sua dúvida foi sanada, por favor feche a issue.

**Comment by leopipolo** [comment]
@marcosgerene minha dúvida foi sanada sim, muito obrigado !
