### ISSUE TITLE
Como incluir instruções no boleto?

### ISSUE THREAD

**Issue by leopipolo** [BoletoNet/boleto2net#52]
Boa noite,

Estou convertendo um código que utilza a BoletoNet para Boleto2Net e estou com dúvida quanto as instruções. Estou com dúvida em particular nesse trecho de código que utilza a BoletoNet:

    var instrucao = new Instrucao_Itau {
        Descricao = "APOS O VENCIMENTO COBRAR MORA DE .................... " + jurosDia.ToString("C2") + " AO DIA"
    };
    boleto.Instrucoes.Add(instrucao);

    var instrucao2 = new Instrucao_Itau {
        Descricao = "APOS " + vencimento.ToString("dd/MM/yyyy") + " MULTA DE ..................... " + multa.ToString("C2")
    };
    boleto.Instrucoes.Add(instrucao2);

Verifiquei que relacionado à instruções a classe `Boleto` só tem as propriedades `CodigoInstrucao1`, `CodigoInstrucao2`, `CodigoInstrucao3` e `ComplementoInstrucao1`, `ComplementoInstrucao2`, `ComplementoInstrucao3`.

Como eu faço para adicionar esse tipo de instrução na Boleto2Net?

Muito obrigado desde já.

**Comment by rafd75** [comment]
Bom dia @leopipolo ... 

CodigoInstrucao / ComplementoInstrucao são aqueles códigos que cada banco implementa (algo do tipo: 10 = significa não protestar, etc)

As mensagens que você está perguntando, tem duas:

Boleto.MensagemInstrucoesCaixa = Mensagem para ser impressa no boleto, tamanho livre. Essa propriedade não é utilizada ao gerar um arquivo remessa.

Para a mensagem do arquivo remessa, utilize Boleto.MensagemArquivoRemessa , mas cuidado com o tamanho da informação que você coloca aqui, pois alguns bancos permitem até 40 caracteres. No começo do Boleto2Net, não existia essa divisão (era a mesma propriedade), mas como alguns bancos tem essa limitação, fizemos essa divisão para não ter problema do usuário escrever uma mensagem muito grande e não conseguir imprimir no boleto (quando o banco emite o boleto, e não a empresa...)

Outros bancos, apenas o fato de informar (no remessa) a taxa de juros, eles já geram a mensagem (no boleto impresso pelo banco).

Enfim... se sua dúvida está no boleto impresso pela própria empresa, é só fazer isso:

Boleto.MensagemInstrucoesCaixa = "APOS O VENCIMENTO COBRAR MORA DE .................... " + jurosDia.ToString("C2") + " AO DIA.  APOS " + vencimento.ToString("dd/MM/yyyy") + " MULTA DE ..................... " + multa.ToString("C2")...

**Comment by leopipolo** [comment]
Boa noite @rafd75 

Acho que entendi. Para especificar a instrução que vai escrita no boleto mesmo, em PDF, eu uso a propriedade `Boleto.MensagemInstrucoesCaixa`.

Aí se eu precisar de algo no remessa eu uso o `Boleto.MensagemArquivoRemessa`. Mas nesse caso que eu dei de exemplo, da multa e do juros, bastaria eu definir as propriedades `Boleto.PercentualMulta` e `Boleto.PercentualJurosDia`, e então só utilizar a `Boleto.MensagemInstrucoesCaixa` para apresentar isso no arquivo correto?

Obrigado

**Comment by rafd75** [comment]
isso mesmo... é assim que eu faço.... 

Mas, se a impressão do boleto for pelo banco (ou seja, só vai o remessa), após enviar o primeiro título, se certifique-se que o banco está imprimindo as mensagens (juros, multa) corretamente.

Me lembro, anos atrás, que um banco não imprimia as mensagens (apesar de constar os %), e foi só fazer um comando via agência, que resolveu o problema.

**Comment by leopipolo** [comment]
Esse comando via agência que você diz é o que enviamos através da propriedade `Boleto.MensagemArquivoRemessa`? Aí o que precisa constar nessa propriedade depende do banco, de modo que eu teria de me informar em cada banco como tem de ser preenchido?

**Comment by rafd75** [comment]
oi Leo.. 

Estou falando o seguinte: Se você não for imprimir o boleto na empresa (e sim no banco), ao mandar o arquivo REMESSA, você inclui as % de multa/juros nos campos próprios (numéricos).

O banco vai imprimir e encaminhar o boleto para o cliente. Verifique então, se ele (banco) está colocando os dizeres de multa/juros por conta própria (já que vc mandou os %).

Se não tiver, e eu não estiver me confundindo, alguns anos atrás, através do gerente da conta, ele mudou algo lá e passou a imprimir os dizeres...

A propriedade MensagemArquivoRemessa, se não me engano, tem bancos que não suportam, e outros, apenas 40 caracteres (dependendo do CNAB)... 

Já a propriedade MensagemInstrucoesCaixa, não tem validade para o arquivo REMESSA, mas será impressa no boleto caso o mesmo for impresso pela empresa (e não pelo banco).

**Comment by leopipolo** [comment]
Boa tarde @rafd75

Entendi, aí é algo que eu vou precisar verificar com cada banco, caso os dizeres não sejam incluidos por conta própria.

Obrigado pela ajuda, já consegui colocar as informações no boleto como acontecia na BoletoNet.
