### ISSUE TITLE
Geração de arquivos de remessa (Bradesco)

### ISSUE THREAD

**Issue by zeminoro** [BoletoNet/boleto2net#53]
Gostaria de saber como vocês procedem quanto ao envio de remessas ao banco via arquivo, 
Para cada boleto gerado é feito um arquivo de remessa pra registra-lo junto ao banco?? No caso do Bradesco tem que submeter via aplicativo, alguém já usou o WebTA ??

Gostaria de eliminar a necessidade de ter alguém selecionando boletos e mandando gerar via sistema um arquivo de remessa, e posteriormente tendo que enviar e obter arquivo de retorno manualmente.

**Comment by rafd75** [comment]
@zeminoro , bom dia!

Estou revisando as issues abertas, para dar uma limpa nos assuntos já resolvidos (ou esquecidos)... 

Se deseja retomar o assunto, verifique as issues:

#137  e #70 do usuário [cidmacedo](/cidmacedo)
