### ISSUE TITLE
Geração de Carné

### ISSUE THREAD

**Issue by JocinardoRodrigues** [BoletoNet/boleto2net#55]
Boa Tarde, a biblioteca faz impressão de Carnê?

Banco: Santander

Abraço.

**Comment by rafd75** [comment]
Boa tarde! ... 

Sinceramente eu não sei como testar isso... Não usei no BoletoNet (1)...

Se você já usa isso no BoletoNet, me passa o código que gera o carnê, que eu tento fazer o teste aqui.

**Comment by guimagcpd** [comment]
Boa tarde caros, alguém conseguiu esta opção de impressão em carnê no BoletoNet2 ? se sim, teria como contribuir mostrando o código de como alcançou esta rotina.

Outra coisa, se tiver também o modelo de como gerar o arquivo de Remessa do SICOOB, na CNAB 240 agradeço pois fui utilizar o modelo apresentado na classe proxy, porem da erro.

Desde já agradeço.

**Comment by rafd75** [comment]
@guimagcpd - sobre Carnê... não sei te dizer...

do SICOOB - qual o erro? ... eu (se não me engano) já uso esse layout.

**Comment by guimagcpd** [comment]
Muito obrigado por responder tão rapidamente...

Eu envio o arquivo de retorno ao componente. e o erro da chamada é este
"Erro ao ler arquivo."

a rotina que estou usando para solicitar a leitura do retorno é em vb.net esta.
eu instancio tudo. e alimento a classe com os parametros do cedente

 Dim _osBoletos As New Boleto2Net.Boletos
_osBoletos.Clear()
_banco.Cedente = New Boleto2Net.Cedente
_banco.Cedente.ContaBancaria = New ContaBancaria
_banco.Cedente.Endereco = New Endereco
..... continua

 Dim arquivoRetorno = New ArquivoRetorno(_banco, Boleto2Net.TipoArquivo.CNAB240)
 Dim fileStream = New FileStream(strArquivo, FileMode.Open)
_osBoletos = arquivoRetorno.LerArquivoRetorno(fileStream)

**Comment by rafd75** [comment]
@guimagcpd  --- eu uso a classe PROXY do projeto (com Visual FoxPro)... mas pelo que comparei, nosso código está igual.

Você já depurou e tentou localizar onde está causando o erro?

Como te falei, tenho um cliente que usa o SICOOB, mas eu não tenho certeza se é 240 ou 400...

**Comment by guimagcpd** [comment]
rafd75 , bom dia, teria como me mostrar um exemplo de como consumir a classe proxy para leitura de retorno ?

**Comment by renanmthy** [comment]
Olá consegui imprimir via Carnê.
Segue o exemplo:
![image](https://user-images.githubusercontent.com/17087193/85893381-2a0c9a80-b7c9-11ea-9f9d-ba72121c5559.png)
![image](https://user-images.githubusercontent.com/17087193/85893545-6e983600-b7c9-11ea-883c-6cddb114fc08.png)
