### ISSUE TITLE
Extrair apenas a geração do codigo de barras.

### ISSUE THREAD

**Issue by fabianosegal** [BoletoNet/boleto2net#56]
Bom dia antecipando agradecimentos.

estou precisando extrair apenas a geração do boleto CEF com codigo de barras. Seria possivel (sou iniciante) me informar como proceder? E como enviar ao codigo as informações para geração do mesmo com codigo de barras?

**Comment by rafd75** [comment]
Fabiano, bom dia... 

Veja a issue #54  --- tem um exemplo de uso.

**Comment by fabianosegal** [comment]
@rafd75 , obrigado pela resposta rápida! Estou totalmente iniciando e estou com VS2013. Fui dar um build e deu 523 Erros! Estou fazendo algo errado? Vi que tem a parte de Testes, onde abri o BancoCaixaCarteiraSig14Tests.cs mas não sei como "rodar". Perdão pela duvida tão crua!

**Comment by rafd75** [comment]
O VS não é minha ferramenta principal também... mas pelo que já li aqui, o projeto só compila no VS2017.

**Comment by fabianosegal** [comment]
Instalei e vi que falta a interface, ou seja, o formulario para poder iniciar os estudos do codigo. Tem algum exemplo disso que eu possa seguir? Alguem que tenha feito a tela de exemplo pra eu poder através dela gerar um boleto?

**Comment by rafd75** [comment]
Eu não tenho... Aliás, tenho, mas está escrito em Visual FoxPro... 

Na prática, falando do componente de Boleto mesmo, você apenas precisa definir o banco que irá usar (CEF) e criar uma coleção de boletos preenchendo os dados. Em seguida, gerar o PDF, ou arquivo Remessa, conforme sua necessidade.

**Comment by fabianosegal** [comment]
Sim, é nesse ponto que estou, sou advindo do delphi (quase 20 anos de delphi rs rs) meu primeiro projeto na empresa e ganho de cara produzir boletos.... Estou implementando um Form e vendo os comentarios pra poder ir "fuçando" e vendo o que consigo mas se alguem tivesse esse codigo com form fazendo tudo direitinho, ja me serviria demais pra estudo e evolução.

**Comment by fabianosegal** [comment]
Pessoal, teriam algum pdf já impresso pra eu saber se continuo utilizando? No caso eu preciso do formato A4 com 3 impressões por pagina, pois emitiremos carnês com até 12 parcelas.

**Comment by rafd75** [comment]
@fabianosegal , boa tarde... 

sei que faz tempo, mas se ainda interessar, houve um ajuste quando a impressão "carnê" -> #266
