### ISSUE TITLE
Envio para o banco

### ISSUE THREAD

**Issue by dalpogetto** [BoletoNet/boleto2net#58]
Pessoal boa tarde,

Esta classe faz o envio do arquivo de remessa e o recebimento do arquivo de retorno do banco ?
Ou devo usar o software do banco para envio e recebimento dos arquivos gerados por esta classe ?

Alguem poderia me esclarecer por favor, obrigado

**Comment by rafd75** [comment]
Boa tarde @dalpogetto 

Boleto2Net **não** faz a comunicação com o banco.

A partir de uma coleção de boletos, é possível imprimir, gerar PDF, ou gerar o arquivo remessa.
E a partir do arquivo retorno, ele popula uma coleção de boletos.

**Comment by dalpogetto** [comment]
Obrigado pela resposta .

Abraço

Em 19 de jan de 2018, à(s) 13:41, Rodolfo Duarte <notifications@github.com> escreveu:
