### ISSUE TITLE
Impressão HTML Banco ITAU

### ISSUE THREAD

**Issue by marcrib** [BoletoNet/boleto2net#60]
Olá, estou realizando a impressão do boleto em html usando o método  
`MontaHtmlEmbedded().ToString()`

Entretanto vejo que a Agência / Código Beneficiário estão vindo em branco, ou seja, não está sendo exibido no boleto.

```
using (var boletoParaImpressao = new BoletoBancario
            {
                Boleto = bol,
                OcultarInstrucoes = false,
                MostrarComprovanteEntrega = true,
                MostrarEnderecoCedente = true
            })
            {
                return boletoParaImpressao.MontaHtmlEmbedded().ToString();
            }

```

**Comment by rafd75** [comment]
@marcrib - eu estou usando Itaú... e não me lembro desse problema.

Você testou em outros bancos para ver se o problema também ocorre?

**Comment by marcrib** [comment]
@rafd75 esqueci de chamar o método "FormataCedente()". Sugiro que crie um método único que chame diretamente FormataCedente() e ValidaDados(), não faz sentido existir em separado, rsrsrs

**Comment by rafd75** [comment]
Se não estou enganado, o FormataCedente precisa ser executado uma vez só, após configurar o objeto BANCO, que contém a conta corrente, carteira, etc.

Já o ValidaDados(), acho que tem que ser chamado para cada boleto que estiver adicionando na coleção...

Até daria para implementar algo (uma propriedade) que começaria com FALSE e ao chamar o ValidaDados(), chamaria o FormataCedente() e mudaria para TRUE (ou seja, no primeiro boleto, iria validar o cedente também... depois não mais.

Eu só não sei (assim de cabeça) se funcionaria... teria que analisar.
