### ISSUE TITLE
Como migrar BoletoNet para Boleto2Net?

### ISSUE THREAD

**Issue by renanmthy** [BoletoNet/boleto2net#61]
Utilizo o projeto desde sua primeira versão e gostaria de fazer upgrade para **Boleto2Net**, porém não faço ideia de por onde começar.

Creio que existam várias outras pessoas no mesmo cenário, então deixo este tópico para registrar as experiências de quem já realizou esta migração e para quem quer realizar a mesma.

**Comment by rafd75** [comment]
Veja se ajuda: #31 

eu usei o BoletoNet apenas 1 vez... e em seguida migrei para o Boleto2Net... não me recordo exatamente o que eu fiz... mas pelo exemplo, da para ter uma ideia.

**Comment by renanmthy** [comment]
Bom dia,

Acabei de fazer a migração e não tive quaisquer problemas, muito prática essa versão 2 do BoletoNet.

É só popular os dados do Cedente, Sacado e gerar os boletos.

Uma dica que deixo é usar o arquivo **_Boleto2.Net.Testes\Utils.cs_** como exemplo, pois ele tem todos os métodos de testes de geração e impressão dos boletos.

Caso alguém sinta dificuldades ao fazer essa migração, entre em contato por aqui que dou uma mão. :)

**Comment by carloscds** [comment]
Excelente @renanmthy, que tal você escrever um roteiro do que fez para colocarmos no projeto ?

**Comment by renanmthy** [comment]
@carloscds desculpe a resposta rápida que dei aqui anteriormente, vou criar um roteiro sim, porém logo que eu tiver um tempinho disponível. Estou na correria da implementação de alguns bancos aqui, logo que terminar junto toda a experiencia que tive com o projeto e publico aqui pra gente. :)
Por hora a melhor dica que posso deixar é a que ja descrevi acima.

**Comment by carloscds** [comment]
@renanmthy Tranquilo, quando puder!

**Comment by renanmthy** [comment]
**Segue o roteiro que segui para a migração!**

1 - Adicione o projeto Boleto2Net à Solution, remova a versão antiga e dê um "clean" na solution. Isso irá mostrar os erros de referência, logo é só substituir pelo Boleto2Net.

2 - Agora baixe os 2 arquivos que deixei em anexo e verifique as diferenças entre eles. Sei que vão estar bem diferentes um do outro, porém a maioria das alterações que fiz foram referente a reestruturação do meu código, e não ao BoletoNet. 

Note que as maiores mudanças foram: 

**Na classe "ArquivoRemessa" -** Tanto em sua instanciação quanto no método "GerarArquivoRemessa", que agora recebe apenas 2 parâmetros, pois o restante das informações ele pega do objeto global "_banco",  passado ao instanciar "ArquivoRemessa".

**Na função "new BoletoBancario().MontaBytesListaBoletosPDF()" -** Esta não está mais presente no Boleto2Net, portanto adicionei um substituto para ele, "**FuncoesBoleto.GeraPDFBoletos()**", que retorna um byte[] com os arquivos PDFs.
OBS.: Você terá que adicionar o pacote nuget "NReco.PdfGenerator" ao projeto para usar essa função.

O restante continua da mesma maneira, só que mais intuitivo.

Veja abaixo a parte referente ao ArquivoRemessa:

**BoletoNet - Versão antiga**
```
var rem = new ArquivoRemessa(TipoArquivo.CNAB240);

MemoryStream ms = new MemoryStream();

rem.GerarArquivoRemessa(numeroConvenio, new Banco(codBanco), cedente, _boletos, ms, numeroArqRemessa);

retBoletos.ArquivoRemessa = Encoding.Default.GetString(ms.ToArray());
```

**Boleto2Net - Nova Versão**
```
var rem = new ArquivoRemessa(_banco, TipoArquivo.CNAB240, 1); //<== IMPLEMENTAR AQUI NUMERO SEQUENCIAL DO ARQ REMESSA!!!

MemoryStream ms = new MemoryStream();

rem.GerarArquivoRemessa(boletos, ms);

 retBoletos.ArquivoRemessa = Encoding.Default.GetString(ms.ToArray()); //<
```

Enfim, estas foram as únicas alterações que tive que fazer em meu projeto ao migrar a versão do BoletoNet, pode ser que você tenha que fazer algumas alterações a mais ou a menos, dependendo da forma como foi implementado em sua solução.

Espero ter ajudado!

 :)

**Comment by carloscds** [comment]
@renanmthy olha la: https://github.com/BoletoNet/boleto2net/blob/master/migracao.md

**Comment by rafd75** [comment]
É isso ai... valeu! TOP!

**Comment by cleitonjosermoraes1** [comment]
Olá, trabalho com C# MVC e no BoletoNet estou usando o arquivo Boleto.Net.MVC\Models\Exemplo.cs migrando para o Boleto2Net por que preciso de algumas carteiras novas.
A duvida é, terei de alterar o meu arquivo Exemplo.cs ou já existe alguma atualização do mesmo disponível?
