### ISSUE TITLE
Arquivo Retorno CBR724 Banco do Brasil

### ISSUE THREAD

**Issue by valentimmx** [BoletoNet/boleto2net#62]
Pessoal, estou tentando ler um arquivo de retorno do BB pelo componente porém o método **LerArquivoRetorno(arquivoRetorno);** não me retorna nada.

Logo na primeira linha da pra notar a informação CBR724. Seria esse um outro padrão de retorno, diferente do CNAB240? O componente da suporte para o mesmo?

Alguém por favor poderia verificar oque está acontecendo?

Segue em anexo uma parte do arquivo que estou tentando ler.
![xxasd](https://user-images.githubusercontent.com/17087193/35472388-6b13fb8e-0355-11e8-97c9-dab69a931ca2.PNG)

**Comment by rafd75** [comment]
@renanmthy  - boa tarde... 

O retorno do BB, eu implementei, mas foi o CBR643... verifique a possibilidade do cliente alterar essa configuração (de 743 para cbr643) com a agência do banco... se não for possível (eu não faço ideia do que seja esse layout da foto), o jeito seria você implementar esse formato no Boleto2Net.

**Comment by renanmthy** [comment]
@rafd75 entrei em contato com o pessoal do CENOP e esse arquivo é específico do aplicativo do BB.
Eles disponibilizam este e um outro arquivo retorno, que no caso é o qual estava procurando, CNAB 240.

Porém mesmo baixando e tentando importar o arquivo correto para o Boleto2Net ainda me retorna uma lista vazia de linhas lidas.

Vou ver oque pode estar dando de errado e mando a correção depois. Por hora é só. 
Podemos fechar este tópico. :)

**Comment by renanmthy** [comment]
Só aproveitando o tópico, a leitura do arquivo de retorno CNAB240 do BB está implementada em algum outro lugar?

Pois o método está assim no arquivo **BancoBrasil.cs**.
```
public void LerDetalheRetornoCNAB240SegmentoT(ref Boleto boleto, string registro)
        {
            throw new NotImplementedException();
        }
```

**Comment by rafd75** [comment]
@renanmthy - fui buscar aqui, no histórico, o momento da implantação do BB e me lembrei.

Eu que implementei a versão original. Meu cliente usa o CNAB400 (conhecido no BB como CBR641 para remessa e CBR643 para retorno) e foi isso que implementei...

Por algum motivo eu fiz a remessa 240 também (não me recordo agora, mas provavelmente tinha no manual e já deixei pronto...) - mas como não usei na prática, sem o retorno nesse formato, acabei não implementando. Será necessário fazer.

Olha só... Se for fazer, da uma olhada na classe do SICOOB, se não me engano, o padrão deles é muito parecido com o BB, e pode ser que você tenha a maioria do código pronto lá ... basta copiar as funções de leitura e verificar no manual o que precisa ser adequado.

**Comment by renanmthy** [comment]
@rafd75 estou implementando a leitura do retorno CNAB240 BB, são apenas 2 métodos: Ler Segmento T e Ler Segmento U.

Peguei como exemplo os métodos do BoletoNet V1, que estão muito bagunçados porém já é 50% do trabalho feito. Vou verificar o do SICOOB também.

Logo que concluir envio aqui pra vocês, porém vou precisar de uma ajudinha quando for fazer o PR, pois nunca realizei essa tarefa aqui.

**Comment by sommussebastiao** [comment]
@renanmthy deu certo a implementação?
