### ISSUE TITLE
Arquivo Remessa do Santander rejeitado

### ISSUE THREAD

**Issue by leopipolo** [BoletoNet/boleto2net#64]
Recentemente implementei a Boleto2Net em um sistema financeiro que precisa gerar boletos e arquivos remessa para Itaú e Santander.  O código de geração dos boletos é o mesmo e para o Itaú funcionou perfeitamente - os boletos foram gerados, e o remessa foi aceito pelo banco - mas para o Santander não está dando certo. Meu código é o seguinte: tenho uma classe `ContaBoletos` para representar a conta bancária, aí tenho um método que retorna um objeto `Boleto2Net.IBanco` a partir da conta:

    private Boleto2Net.IBanco ConfiguraBanco(ContaBoletos conta)
    {
        DadosPrestadorModel _dadosPrestadorModel = new DadosPrestadorModel();
        Boleto2Net.IBanco _banco = null;
        if (conta.Banco == EBanco.Itau)
        {
            _banco = Boleto2Net.Banco.Instancia(Boleto2Net.Bancos.Itau);
        }
        else if (conta.Banco == EBanco.Santander)
            _banco = Boleto2Net.Banco.Instancia(Boleto2Net.Bancos.Santander);
            
        _banco.Cedente = new Boleto2Net.Cedente
        {
            CPFCNPJ = conta.CNPJ,
            Nome = conta.RazaoSocial,
            ContaBancaria = new Boleto2Net.ContaBancaria()
            {
                Agencia = conta.Agencia,
                Conta = conta.Conta,
                DigitoConta = conta.DigitoConta,
                CarteiraPadrao = conta.CarteiraPadrao
            },
            Endereco = new Boleto2Net.Endereco()
            {
                LogradouroEndereco = _dadosPrestadorModel.Endereco,
                LogradouroNumero = _dadosPrestadorModel.Numero,
                UF = _dadosPrestadorModel.Uf.ToString(),
                Cidade = _dadosPrestadorModel.Cidade,
                Bairro = _dadosPrestadorModel.Bairro,
                CEP = _dadosPrestadorModel.Cep,
                LogradouroComplemento = _dadosPrestadorModel.Complemento
            }
        };
        _banco.FormataCedente();
        return _banco;
    }

Aí para gerar um boleto individual eu uso esse método (`boletoInterno` é instancia de uma classe `Boleto` do sistema, enquanto que `boletoExterno` é instância da classe `Boleto` da Boleto2Net):

    private Boleto2Net.BoletoBancario GeraBoletoIndividualBoletoNet(Boleto boletoInterno, Boleto2Net.IBanco banco)
    {
        Boleto2Net.Boleto boletoExterno = new Boleto2Net.Boleto(banco);

        var sacado = new Boleto2Net.Sacado()
        {
            CPFCNPJ = boletoInterno.Cobranca.Cliente.Documento,
            Nome = boletoInterno.Cobranca.Cliente.NomeCliente,
            Endereco = new Boleto2Net.Endereco()
            {
                LogradouroEndereco = boletoInterno.Cobranca.Cliente.Endereco,
                LogradouroNumero = boletoInterno.Cobranca.Cliente.Numero,
                LogradouroComplemento = boletoInterno.Cobranca.Cliente.Complemento ?? string.Empty,
                Bairro = boletoInterno.Cobranca.Cliente.Bairro,
                UF = boletoInterno.Cobranca.Cliente.Uf.ToString(),
                CEP = boletoInterno.Cobranca.Cliente.Cep,
                Cidade = boletoInterno.Cobranca.Cliente.Cidade
            }
        };

        boletoExterno.Sacado = sacado;
        boletoExterno.CodigoOcorrencia = "01"; // Registrar Remessa;
        boletoExterno.DescricaoOcorrencia = "Remessa Registrar";
        boletoExterno.Carteira = boletoInterno.ContaBoletos.CarteiraPadrao;
        boletoExterno.NumeroDocumento = RemessaHelper.AjustaAlfaNumerico(boletoInterno.NossoNumero.ToString(), 25);
        boletoExterno.NumeroControleParticipante = RemessaHelper.AjustaAlfaNumerico(boletoInterno.NossoNumero.ToString(), 25);
        boletoExterno.NossoNumero = RemessaHelper.AjustaDigito(boletoInterno.NossoNumero.ToString(), 8);
        boletoExterno.DataEmissao = boletoInterno.DataBoleto;
        boletoExterno.DataVencimento = boletoInterno.DataVencimento;
        boletoExterno.ValorTitulo = Convert.ToDecimal(boletoInterno.Cobranca.Valor);
        boletoExterno.DataJuros = boletoInterno.DataVencimento.AddDays(1);
        boletoExterno.PercentualJurosDia = boletoInterno.CalculaPercentualJurosDia();
        boletoExterno.ValorJurosDia = boletoInterno.CalculaPercentualJurosDia() * (decimal)boletoInterno.Cobranca.Valor / 100;
        boletoExterno.MensagemInstrucoesCaixa = "APOS O VENCIMENTO COBRAR MORA DE .................... " + boletoExterno.ValorJurosDia.ToString("C2") + " AO DIA <br />\n";
        boletoExterno.DataMulta = boletoInterno.DataVencimento.AddDays(1);
        boletoExterno.PercentualMulta = boletoInterno.CalculaPercentualMulta();
        boletoExterno.ValorMulta = boletoInterno.CalculaPercentualMulta() * (decimal)boletoInterno.Cobranca.Valor / 100;
        boletoExterno.MensagemInstrucoesCaixa += "APOS " + boletoInterno.DataVencimento.ToString("dd/MM/yyyy") + " MULTA DE ..................... " + boletoExterno.ValorMulta.ToString("C2");
        boletoExterno.EspecieDocumento = Boleto2Net.TipoEspecieDocumento.DS;
        boletoExterno.ValidarDados();
        Boleto2Net.BoletoBancario boletoBancario = new Boleto2Net.BoletoBancario();
        boletoBancario.Banco = boletoExterno.Banco;
        boletoBancario.Boleto = boletoExterno;
        boletoBancario.MostrarComprovanteEntrega = false;
        boletoBancario.MostrarEnderecoCedente = true;
        boletoBancario.MostrarCodigoCarteira = true;

        return boletoBancario;
    }

O usuário então testou com Itaú e Santander. O remessa do Itaú foi aceito pelo banco normalmente, mas o remessa do Santander foi rejeitado. Pedi para ele verificar se havia detalhes com o banco, mas não informaram nada.

Enviaram só um e-mail explicando o layout do remessa, alguns dados e falando sobre homologação. Pediram para enviar um remessa em um ambiente de testes.

Por que pode estar sendo rejeitado? Isso pode ser porque o banco exige que passe por esse ambiente de testes primeiro? No e-mail também tem código de convênio e código de transmissão, que no Itaú não precisou, será que é isso que está faltando?

Obrigado desde já pela ajuda!

**Comment by krgm03** [comment]
Boa tarde

Usamos atualmente o boleto2net em produção num convênio/contrato com o Santander para emissão de boletos 'cobrança simples com registro carteira 101' 

Primeiramente realizamos a contratação do serviço especificando que a emissão seria realizada via Sistema/Software próprio

Depois o banco nos enviou um e-mail com todo o material(layouts...) detalhando os passos a serem tomados
Dentre algumas informações que eles enviam neste primeiro e-mail estão:
Código do Convênio (ou PSK, ou Beneficiario)
Código da carteira a inserir na remessa
Código da carteira a inserir nos boletos
Código de Transmissão 240 posições
Código de Transmissão 400 posições
...
...

Basta seguir o e-mail enviado pelo banco. A cada etapa concluída o banco enviará um e-mail indicando qual será o próximo passo

**Comment by rafd75** [comment]
@leopipolo - aqui, foi do mesmo jeito que o @krgm03 comentou... 

Particularmente, eu NUNCA coloco uma cobrança para funcionar sem o OK do banco... se der alguma zica depois, e não houver homologação, a história fica complicada com o cliente hein.....

Mas, para falar que NUNCA fiz isso (mesmo), uma vez, já havia a cobrança implementada no cliente, e eu usei um arquivo remessa gerado no sistema antigo, e gerei uma idêntica no novo... abri os 2 arquivos REMESSA e comparei caracter por caracter (fiz um programinha na epoca)...  Como eram iguais, dei como homologado e segui o jogo... mas não aconselho fazer isso não...

**Comment by leopipolo** [comment]
@rafd75 @krgm03 agora eu consegui ter acesso aos detalhes do erro, e o que está sendo informado é o seguinte:

Nome do Campo     Descrição do Erro                                          Valor do Erro
REG.DETALHE           NUM.AG.CEDENTE/DIG.NAO NUMERICO     SEU NUMERO = 19162

O primeiro erro era referente a falta do código de transmissão, que o banco ainda não havia enviado. Colocando o código agora só tem esse erro mesmo.

Primeira coisa que analisei foi o número da agência, mas está tudo certo com ele no código, e a agência não tem digito.

Não sei o que pode ser isso. A minha configuração funciona perfeitamente para o Itaú. Na verdade, esse sistema já tinha o Itaú implementado, o desenvolvedor usou a BoletoNet, mas gerava o remessa manualmente. Quando fui fazer o Santander, deixei tudo pela Boleto2Net. O remessa do Itaú deu tudo certo, mas do Santander está dando esse erro.

Como posso descobrir o que é isso e resolver?

**Comment by leopipolo** [comment]
@krgm03 eu simplesmente não preenchi a agência. No Itaú deu certo isso. No seu caso, você chegou a deixar a propriedade nula e deu esse erro também? 

Outra coisa, é obrigatório que o nosso número seja feito usando a "fórmula de cálculo - módulo 11"? Digo isso porque no Itaú o nosso número foi feito sequencial (cada boleto incrementa um), e me pediram para que mantivesse a mesma sequência entre os dois bancos (exemplo: se o do Itaú está 100 e gerar um do Santander, esse será 101, e o próximo se for do Itaú será 102). Esse erro pode estar relacionado a não seguir aquela formula?

**Comment by krgm03** [comment]
@leopipolo, no nosso caso,  como havia comentado anteriormente, deixamos com o dígito 9

Na documentação(Layout de Arquivo Padrão 240 – Cobrança Versão 2.8) diz o seguinte em relação ao nosso numero:
"Nota 15: NOSSO NÚMERO
 No Arquivo Remessa: É recomendável, que este campo venha preenchido (conforme fórmula
de cálculo - módulo 11), pois será a “chave” de identificação do título
entre banco X cliente. Caso este campo esteja zerado, o sistema
atribuirá automaticamente um número para o título."

No nosso caso simplesmente atribuímos o 'NossoNumero' e deixamos o trabalho com o boleto2net chamando o método 'ValidarDados'

**Comment by leopipolo** [comment]
@krgm03 Eu pesquisei um pouco e descobri uma recomendação de utilizar o último número da agência no dígito. Eu fiz isso e o boleto remessa foi aceito. Estou esperando retorno do banco para homologação, mas aparentemente está tudo certo: o problema todo era que o dígito da agência não pode ir em branco.

Agora entendi, a Boleto2Net cuida do dígito verificador do nosso número. Eu não sabia disso, foi bom ficar sabendo.

Vou aguardar o retorno do banco para fechar a issue, mas acredito que esteja tudo certo mesmo. Obrigado pela ajuda!
