### ISSUE TITLE
Geração de segunda via de boleto

### ISSUE THREAD

**Issue by leonardopipolodegioia** [BoletoNet/boleto2net#67]
Boa noite,

Estou tentando descobrir como gerar segunda via de boleto. Se o boleto ainda não venceu, até onde eu sei seria só gerar o PDF novamente. Mas se o boleto já venceu, seria necessário fazer um novo com outra data de vencimento, com juros e multa adicionados, e registrar isso no banco correto? 

Eu olhei o manual do layout do arquivo remessa 240 do Santander, por exemplo, e encontrei o seguinte:

![captura de tela 2018-02-27 21 21 25](https://user-images.githubusercontent.com/6210828/36762943-ab205a2a-1c04-11e8-92a9-ea24253aadf0.png)

Pelo que eu entendi essas opções é o que é possível fazer pelo arquivo remessa.

O que eu pensei em fazer para gerar segunda via foi: criar uma instância de `Boleto` com o mesmo "nosso número" do boleto original, somar no valor a multa e juros necessários, e então utilizar o 06 para alterar o vencimento de modo a fazer um boleto novo com o mesmo número de registro, mas com os valores adicionais já computados e com nova data de vencimento.

É essa a abordagem correta para gerar segunda via? Se não é, como eu devo proceder?

Obrigado desde já !

**Comment by rafd75** [comment]
@leopipolo - O Boleto2Net não está preparado para enviar na remessa qualquer código diferente de 01.

Isso é interessante, mas não sei a dificuldade de se implementar (acho que, se você fizer uma alteração de vencimento - operação 06 - o layout da linha detalhe (no arquivo remessa) deve ser diferente da operação 01.

não sei a melhor maneira de se implementar isso. Vou acompanhar as demais respostas aqui para entender melhor também.

**Comment by krgm03** [comment]
Seria bem interessante. O Santander poderia facilitar as coisas anexando à documentação exemplos de arquivos de remessas para cada código.
Por exemplo: se eu quero dar baixa em um boleto basta eu informar o código '02' e o número do boleto? E as demais informações seriam de acordo com o original ou nem teriam necessidade?
Exemplos ou uma documentação mais detalhada ajudaria bastante. Na época questionei se havia mais alguma documentação e eles me disseram que não. 

Aqui quando um Parceiro deixa o boleto vencer e nos pergunta como proceder, enviamos o seguinte link para remissão de boleto vencido do próprio Santander   https://www.santander.com.br/br/resolva-on-line/reemissao-de-boleto-vencido

Quando precisamos dar baixa(remover) num boleto fazemos por enquanto pelo internetbanking mesmo

Importante: Você será taxado por cada uma dessas operações e receberá um registro com o valor da tarifa no arquivo de retorno

**Comment by rafd75** [comment]
sobre outras operações, se for o mesmo layout (mesmos campos), não seria complicado...
mas eu acho que não é bem assim não... se operação = '02' então o campo XXX deve ser preenchido assim... e por ai vai.

Sobre baixa, segunda via, etc... idem aqui....  fazemos igualzinho...

**Comment by krgm03** [comment]
@rafd75, boa tarde

"...mas eu acho que não é bem assim não... se operação = '02' então o campo XXX deve ser preenchido assim..."

Por isso mesmo que acho que o Banco deveria disponibilizar material mais completo e detalhado
