### ISSUE TITLE
Boleto.net Codeplex- Ajuda conversão

### ISSUE THREAD

**Issue by cidmacedo** [BoletoNet/boleto2net#68]
Pessoal minha aplicação é antiga, VS2010, utilizo o Boleto.Net que estava no CodePlex... Atualmente só utilizo para Gerar e Imprimir o boleto Itau e Bradesco.
Agora o projeto continua no VS2010 e preciso atualizar o componente para gerar o arquivo CNAB400 para registrar os boletos no ITAU e BRADESCO.

Existe algum lugar com exemplo de como fazer isto ? (Gerar o Boleto, Imprimir, Registrar)

**Comment by marcosgerene** [comment]
https://github.com/BoletoNet/boleto2net/issues/31#issuecomment-328541440

**Comment by cidmacedo** [comment]
Pessoal muito obrigado pela ajuda !!!
