### ISSUE TITLE
Erros de compilação (VS2017)

### ISSUE THREAD

**Issue by emersonjan** [BoletoNet/boleto2net#7]
Baixei o projeto e está com vários erros de compilação.
Estou usando VS2017, percebi que o projeto está utilizando a versão 4.0 do .NET Framework, alterei para versão 4.6.2 e continua com erros.

**Comment by carloscds** [comment]
@emersonjan O projeto é .Net 4.0, quais são os erros ?

**Comment by emersonjan** [comment]
Perdão, o projeto está compilando sem erro no VS2017, talvez meu VS esteja bugado, ele está acusando erro como segue na imagem.
![erro](https://user-images.githubusercontent.com/6568799/27097095-85761b0c-5049-11e7-93cc-fcf262c814f3.png)

**Comment by carloscds** [comment]
@emersonjan Qual versão do VS 2017 você está usando ? 15.2 ?

**Comment by alegsantos** [comment]
Não estou conseguindo compilar no VS2015 Community upd 3. Alguma orientação ?

![image](https://user-images.githubusercontent.com/30034873/28002288-18bed8fc-650a-11e7-8cb2-c7b317b5c8e0.png)

**Comment by carloscds** [comment]
@alegsantos Esta versão compila apenas no VS 2017.

**Comment by rafd75** [comment]
@carloscds - acho que pode fechar essa issue!

**Comment by Merotto** [comment]
Ola amigos uso o vs2012 e preciso emitir boletos, vcs podem me ajudar???

**Comment by rafd75** [comment]
@Merotto -> https://github.com/BoletoNet/boletonet

O link acima, é a versão 1 do BoletoNet... não sei se compila em 2012, mas vc pode tentar... Eu comecei usando ela, e depois migrei tudo para o Boleto2Net.......

@carloscds - vc sabe dizer se roda no VS2012 ?

**Comment by carloscds** [comment]
@rafd75 No VS 2012 nao roda!
