### ISSUE TITLE
Webservices Registro de Boleto

### ISSUE THREAD

**Issue by cidmacedo** [BoletoNet/boleto2net#70]
Pessoa alguém já utiliza webservice para registro de boletos do banco ITAU ? Enviar arquivo para registrar um boleto inviabiliza os negócios online, onde o usuário cria e para o boleto praticamente na mesma hora. Vi o seguinte link.

https://boletosimples.zendesk.com/hc/pt-br/articles/360000855973-Conexão-online-com-o-banco-através-de-Webservice

**Comment by rafd75** [comment]
Eu não uso, mas isso é interessante... Seria legal implementar isso no projeto.
