### ISSUE TITLE
Identificação de pagamento pelo arquivo retorno

### ISSUE THREAD

**Issue by leopipolo** [BoletoNet/boleto2net#73]
Boa noite !

Implementei a geração de boleto com a Boleto2Net e agora estou tentando implementar a leitura do arquivo retorno para atender a dois requisitos: computar os pagamentos e debitar as taxas cobradas dos boletos baixados.

Estou com algumas dúvidas. As duas principais aqui são: como saber quais ocorrências correspondem ao pagamento do boleto e como identificar o pagamento mesmo. 

No caso, agora estou olhando o manual do Itaú e temos as ocorrências que parecem com pagamento:

- 06 LIQUIDAÇÃO NORMAL
- 07 LIQUIDAÇÃO PARCIAL – COBRANÇA INTELIGENTE (B2B)
- 08 LIQUIDAÇÃO EM CARTÓRIO

No caso, eu devo entender todas essas como pagamento do boleto? Ou seja, devo, para cada boleto no retorno, analisar a propriedade `CodigoOcorrencia` e, no caso do Itaú sendo um desses, devo entender como pagamento? No geral, tudo que for referente a liquidação, eu devo entender como pagamento? 

Sobre o valor eu peguei um arquivo retorno do Itaú para exemplo (CNAB400) e a propriedade `ValorPago` dos boletos com ocorrência 06 está vindo zero, mas a propriedade `ValorPagoCredito` vem preenchida com valores em geral diferentes do valor do boleto (alguns vem a mais, outros a menos). Eu vi nos comentários que essa `ValorPagoCredito` é o que vai ser creditado na conta. 

Valores a mais eu consigo entender, estou imaginando que seja multa e juros de boletos em atraso, mas por que alguns vem a menos?

Qual é a forma correta de ler o valor pago para computar na aplicação: é utilizar a propriedade `ValorPagoCredito` mesmo?

**Comment by rafd75** [comment]
@leopipolo boa tarde...

Você está fazendo corretamente mesmo... não tem uma regra... Alguns bancos mandam o valor líquido, outros o valor do boleto (sem descontar a tarifa) e assim sucessivamente.

Aqui, eu uso o ValorPago e ValorPagoCredito - mas em uma discussão algum tempo atrás com o Carlos, cheguei a conclusão que o melhor a fazer é pegar o valor do título + juros + multa - descontos e fazer a baixa por este valor.

Eu ainda não mudei isso aqui, pq quero saber se realmente daria certo. Para isso, vou pegar alguns clientes (em produção) e fazer uma comparação entre o resultado da expressão acima, e o ValorPago/Credito... se bater por algum tempo, vou abandonar essas propriedades que o banco envia e passar a fazer calculo internamente...

O melhor para você, é acompanhar com o cliente e ver se está dando certo... Lembre-se - cada banco faz de um jeito... já apanhei muito aqui com isso...

**Comment by leopipolo** [comment]
@rafd75 boa tarde !

A diferença entre o ValorPago e o ValorPagoCredito é só que o ValorPagoCredito já tem todos os descontos? A propósito, você sabe por que no Itaú esse ValorPago está vindo zerado na ocorrência 06 (liquidação normal)?

**Comment by rafd75** [comment]
@leopipolo 

Abaixo está o código de leitura do Itau. O ValorPago não é preenchido... provavelmente, pq no manual do Itau, diz que é o ValorPagoCredito que está na posição 254... entendeu?

Foi o que expliquei antes... cada banco implementa de um jeito... tem que acompanhar de perto com o cliente até entender a lógica disso.

Já aconteceu aqui do título de R$ 100, o cliente pagar R$ 100, e o banco informar R$ 97 (ou seja, R$ 3 da tarifa já foi descontado)... Quando isso ocorreu, no nosso sistema, o pagamento era feito com R$ 97, deixando R$ 3 em aberto... o cliente reclamou e ai, o velho IF (ItaU) então soma a tarifa no valor pago... entendeu o pepino? ???

```
//Valores do Título
                boleto.ValorTitulo = Convert.ToDecimal(registro.Substring(152, 13)) / 100;
                boleto.ValorTarifas = Convert.ToDecimal(registro.Substring(175, 13)) / 100;
                boleto.ValorOutrasDespesas = Convert.ToDecimal(registro.Substring(188, 13)) / 100;
                boleto.ValorIOF = Convert.ToDecimal(registro.Substring(214, 13)) / 100;
                boleto.ValorAbatimento = Convert.ToDecimal(registro.Substring(227, 13)) / 100;
                boleto.ValorDesconto = Convert.ToDecimal(registro.Substring(240, 13)) / 100;
                **boleto.ValorPagoCredito = Convert.ToDecimal(registro.Substring(253, 13)) / 100;**
                boleto.ValorJurosDia = Convert.ToDecimal(registro.Substring(266, 13)) / 100;
                boleto.ValorOutrosCreditos = Convert.ToDecimal(registro.Substring(279, 13)) / 100;
```

**Comment by rafd75** [comment]
@leopipolo bom dia.

Sobre MULTA e JUROS.... uma informação adicional ai ---> vou te falar do Bradesco (que eu sou o correntista)... multa e juros vem tudo somado, em uma só propriedade "Juros de Mora" no registro 1, posição 267 a 279...

ou seja... cliente pagou R$ 10 de multa, e R$ 2 de juros, eu recebo R$ 12 na posição acima...

**Comment by leopipolo** [comment]
@rafd75 obrigado pela ajuda e por mais essa informação ! Pelos testes que eu fiz isso acontece no Itaú também, vem tudo junto na mesma propriedade. 

Vou fechar a issue, porque já entendi o procedimento: o negócio é realmente acompanhar com o cliente para ver como o banco envia o que ele precisa.
