### ISSUE TITLE
Dúvida no preenchimento de alguns campos

### ISSUE THREAD

**Issue by faelfigueiredo** [BoletoNet/boleto2net#75]
Bom dia, estou vendo alguns exemplos em relação a utilização da dll para geração de boletos mas estou com algumas dúvidas quanto a alguns campos - talvez seja porque será a primeira vez que vou trabalhar com boletos.

Por exemplo:

Em relação ao cedente, o que devo preencher nos campos Codigo, CodigoDV e CodigoTransmissao?

E nos campos CarteiraPadrao e VariacaoCarteiraPadrao da conta do cedente? À quê se refererem esses campos?

Existe alguma documentação que explique os campos?

Obrigado desde já!

**Comment by rafd75** [comment]
Bom dia @faelfigueiredo  --- estou enrolado aqui, mas vou tentar te dar um norte, ok?

Cedente -> Codigo e CodigoDV - alguns bancos tem essa informação e são usadas para gerar o boleto, e o arquivo remessa.... Já o CódigoTransmissao, eu não vou me lembrar qual banco usa, mas acho que é 1 só... (mas se você procurar as referências dessa propriedade no projeto, vai encontrar onde é usado.)

Com relação as propriedades CarteiraPadrao e VariacaoCarteiraPadrao, busquei aqui no meu histórico... Antes, elas existiam apenas na classe ContaCorrente, e não existiam na classe Boleto. Em um determinado momento, percebi que, dentro de um arquivo retorno, existiam títulos de carteiras diferentes (no mesmo arquivo) e a classe não conseguia tratar isso, pois só tinha a propriedade na ContaCorrente... 

Então, foi incluída as propriedades Carteira, VariacaoCarteira, TipoCarteira também na classe Boleto e as propriedades que já existiam na classe ContaCorrente, foram renomeadas para CarteiraPadrao, VariacaoCarteiraPadrao, TipoCarteiraPadrao.

**Comment by rafd75** [comment]
Complementando...

O melhor jeito de você entender a classe, é através do manual do próprio banco... Usando as posições do manual, você irá entender (olhando as classes ArquivoRemessa e ArquivoRentorno), irá identificar exatamente quais propriedades cada banco utiliza...

**Comment by faelfigueiredo** [comment]
Ótimo, amigo, muito obrigado! Já ajudou bastante, abraço!
