### ISSUE TITLE
Dúvida sobre geração de "Nosso Número"

### ISSUE THREAD

**Issue by faelfigueiredo** [BoletoNet/boleto2net#77]
Anexo: [Cálculo para confecção de Dígito Verificador de Nosso Número (002).docx](https://github.com/BoletoNet/boleto2net/files/1885016/Calculo.para.confeccao.de.Digito.Verificador.de.Nosso.Numero.002.docx)
Estou tentando gerar boletos para a Sicoob e estou com dúvida quanto ao "Nosso Número".
O banco me enviou o manual em anexo aqui, que contém uma lógica para geração do número. 
Essa lógica já está implementada no Boleto2Net ou é minha função fazer esse código?
Eu [vi esse exemplo](https://github.com/BoletoNet/boleto2net/blob/master/Boleto2.Net.Testes/BancoSicoobCarteira1_01Tests.cs) onde é passado apenas um número no campo NossoNumero. Basta eu criar um sequencia que nunca se repete e usar nesse campo?

**Comment by rafd75** [comment]
Isso mesmo...

NossoNumero = 1
depois 2, 3, 4, 5... 

Ao executar o método Validar(), o Boleto2Net vai calcular para você o NossoNumeroDV ... 

Observe que, após validar, a propriedade NossoNumeroFormatado sempre haverá um "-" entre os valores do NossoNumero e NossoNumeroDV 

Mesmo depois de emitido (ou seja, vc já gerou o nosso numero), e precisar emitir a segunda via do boleto, no banco de dados, você teria esse valor "12345678-9" - Ao gerar a segunda via, use apenas o NossoNumero = 12345678 e VALIDAR() novamente... o resto o Boleto2Net faz.

**Comment by faelfigueiredo** [comment]
Obrigado!
