### ISSUE TITLE
Carteira Bradesco e .NET Core / Standard

### ISSUE THREAD

**Issue by erickmcarvalho** [BoletoNet/boleto2net#8]
Olá pessoal.

Gostaria de saber se o BoletoNet 2 já aceita a Carteira 6 do Bradesco.
Também gostaria de me oferecer para portar o projeto para .NET Core ou .NET Standard, visto que várias empresas (inclusive onde trabalho) já fazem uso do .NET Core.

Desde já obrigado e um abraço!

**Comment by carloscds** [comment]
@erickmcarvalho Alguns componentes utilizados não tem suporte para .Net Core ainda!

**Comment by erickmcarvalho** [comment]
@carloscds Mas estes não podem ser substituídos?

Por exemplo, recentemente portei uma SDK que utilizava o `NameValueCollection` para `Dictionary<string, string>`.
Ou são componentes mais complexos?

Não estariam sendo desenvolvidos no .NET Standard 2.0 que já está em preview?

**Comment by carloscds** [comment]
@erickmcarvalho Precisamos dar uma "geral" no projeto e ver isto? Topa fazer ?

**Comment by erickmcarvalho** [comment]
@carloscds 

Segue uma análise que fiz utilizando o .NET Portability Analysis: [http://cameraman-alternates-41213.bitballoon.com/](ApiPortAnalysis).

Creio que ainda tem alguns recursos não suportados, sendo que devemos levar em consideração que ele ficou mais próximo de ser suportado no .NET Core 2.0 e .NET Standard 2.0.
Estes tem sua previsão de lançamento ainda para Terceira Quinzena de 2017, lá para Setembro de 2017, creio eu.
Atualmente só temos preview do .NET Core/Standard 2.0.

**Comment by carloscds** [comment]
@erickmcarvalho Se voce fizer a mesma analisa somente no Boleto.Net que e a DLL, isto cai bastante, msa ainda assim exigiria um trabalho.

**Comment by rafd75** [comment]
@erickmcarvalho - boa tarde! ... sobre a carteira 6 (sem registro), não está implementada não.

Mas essas carteiras (sem registro) não estão saindo de produção? Pelo que li, parece que já não são aceitas em algumas situações e até o final do ano, será extinta... 

Tem alguma informação sobre isso?

OBS: Se for para implementar, não deve ser muito complicado (o @AlbertoMonteiro separou "banco" de "carteira") - teoricamente é uma classe (BancoBradescoCarteira06) pequena que deve ser implementada. Mas se for fazer, providencie todos os testes da carteira também...

**Comment by erickmcarvalho** [comment]
@rafd75 boa noite.

Na verdade elas ainda são utilizada, apenas não são mais liberado novos contratos nas carteiras sem registro.
Elas estarão totalmente fora de circulação no final do ano, por hora, apenas valores altos são exigidos.

Aqui na empresa ainda fazemos uso da carteira 6 do Bradesco, pois ainda não foi fechado contrato com à carteira com registro, e por estarmos desenvolvendo o sistema novo, é necessário manter do jeito que ainda está operando.

**Comment by fernadan** [comment]
Pessoal...

Fiz a análise só da parte da DLL e tivemos o seguinte resultado em anexo...
[ApiPortAnalysis.xlsx](https://github.com/BoletoNet/boleto2net/files/1135830/ApiPortAnalysis.xlsx)

Acredito que será melhor esperar a liberação final do Core 2.0 e migrar só os itens dela.

Entretanto, pelo tipo das APIs que faltam, eu imagino que será um pouco complicado. Tem coisa relacionada a imagens e tals.

Enfim, me coloco a disposição para ajudar na migração, já que tenho bastante interesse nesta migração.

**Comment by carloscds** [comment]
@fernadan As dependências de web e images dá para resolver, mas o grande problema são as DLLs de terceiro, como a geração de PDF.

**Comment by fernadan** [comment]
@carloscds qual o componente que é utilizada atualmente? Será que ela mesma não já foi portada?

**Comment by fernadan** [comment]
Até então eu irei criar uma WebApi full framework 4.5, só para calcular e gerar os boletos. Ela devolverá os links para os PDFs. É uma gambiarra, mas é o que resolverá temporariamente minha situação de não ter a API de boleto para o Core.

A versão 4.5 tem suporte, certo?

**Comment by carloscds** [comment]
@fernadan Tem o NReco.PdfGenerator.dll e até onde eu vi ainda não portaram, então precisaria mudar a biblioteca para uma outra que seja suportada.

**Comment by carloscds** [comment]
@fernadan Para a versão full tem suporte

**Comment by fernadan** [comment]
@carloscds to achando que já portaram viu:

https://www.nuget.org/packages/NReco.PdfGenerator.LT/

**Comment by carloscds** [comment]
@fernadan Verdade, parece que sim. Precisamos fazer um teste!

**Comment by marcelodiasr** [comment]
Sobre a carteira 06 é inútil perder tempo criando-a, por ser sem registro, é um caso apenas do @erickmcarvalho Ele que crie um fork e implemente.

Sobre o .net core, o System.Drawing para a class BarCode não foi portado 100%, terá que usar este pacote: https://github.com/CoreCompat/CoreCompat
Ao que testei,  funciona corretamente a class BarCode

**Comment by erickmcarvalho** [comment]
Pessoal, tem um detalhe.

Agora que o .NET Core 2 / .NET Standard 2 está em release, vale considerar que é possível referenciar algumas dependências do .NET Framework direto no .NET Standard 2, embora não é 100%, depende muito dos recursos que a biblioteca utilizar.

@marcrib

`System.Drawing` parece que já foi bem desenvolvido no .NET Standard 2.0.
https://docs.microsoft.com/en-us/dotnet/api/?term=System.Drawing&view=netstandard-2.0

**Comment by rafd75** [comment]
Olha... acho que não foi para frente não... tem 6 meses da última mensagem do Erick.

**Comment by Tagliatti** [comment]
Eu comecei a portar para o .net core 2, se quiserem ajudar, só falta corrigir um bug na geração do arquivo de remeça, a parte de boleto já está funcionando.
https://github.com/Tagliatti/BoletoNetCore

**Comment by cleberkoplin** [comment]
Opa! Não iniciei o projeto ainda, mas tenho interesse... assim que
definirmos o inicio do projeto por aqui vou verificar a biblioteca, vejo as
pendências e conversamos.
Um Abraço, valeu!




*Cleber Koplin*
*Tecnologia da Informação*
*Celular: +55 51 993193873*
cleberkoplin.com.br



2018-05-07 15:54 GMT-03:00 Filipe Tagliatti <notifications@github.com>:

**Comment by thiagosoeiro** [comment]
Alguma novidade com relação à isso?

**Comment by Tagliatti** [comment]
@thiagosoeiro o bug ainda ta lá pq eu desconheço o tipo de exception que acontece, se vc executar os testes do projeto, vc vai ver q os de geração de boleto vai passar, mas os de remeça vai acontecer um erro. Da uma olhada, é só clonar o projeto e executar os testes.

**Comment by thiagosoeiro** [comment]
@Tagliatti Joia.
Percebi que seu fork está um pouco desatualizado com a master.
Você ainda pretende mergear?
Sabe se foram mudanças importantes?

**Comment by Tagliatti** [comment]
Atualmente está 3 commits atrás e todas as alterações foram na parte q n está funcionando atualmente, então primeiro é resolver esse bug e depois vai ser muito de boa de mergear.

**Comment by thiagosoeiro** [comment]
@Tagliatti, bom dia.
Realizei uns testes aqui. Alterei a linha 594 da classe BoletoBancario para "**return MontaHtmlEmbedded();**" e o erro cessou.
Porém agora recebo o erro abaixo na seguinte linha ao gerar o pdf "**new HtmlToPdfConverter().GeneratePdf(html.ToString())**"

__System.Exception: This feature requires PdfGenerator commercial license key: http://www.nrecosite.com/pdf_generator_net.aspx__

Aparentemente esse pacote nuget não é gratuito.

**Comment by Tagliatti** [comment]
Blz, vou abrir uma issue lá e verificar isso, vlw pela ajuda.

**Comment by thiagosoeiro** [comment]
Tranquilo!
Não vejo a geração em PDF como um problema impeditivo, até porque o boleto já é gerado em HTML tranquilamente.
Você consegue mergear agora de boa?

**Comment by Tagliatti** [comment]
Continua com erro só na parte de remessa.

![image](https://user-images.githubusercontent.com/4907036/42799322-d55b5db8-896d-11e8-9afe-b9708ee6be88.png)

**Comment by thiagosoeiro** [comment]
Sim, como falei anteriormente, esse erro é por causa do pacote NReco.PdfGenerator.LT. Na versão Net Core, ele é pago. Por isso estoura essas exceções.

**Comment by Tagliatti** [comment]
Não sabia q gerava pdf na remessa. Já ta publicado o pacote em pre-release https://www.nuget.org/packages/BoletoNetCore

**Comment by carloscds** [comment]
@Tagliatti Seria interessante este código ajustado para Core estar no repositorio também.

**Comment by Tagliatti** [comment]
a questão é que eu não sou contribuidor aqui e nenhum contribuidor nunca deu atenção para isso, então ficou mais fácil lá mesmo, pra ver se dessa vez essa lib sai logo.

**Comment by carloscds** [comment]
@Tagliatti E porque ainda não é contribuidor ? Afinal é graças as contribuições de todos que temos este projeto no nível que está. Pense nisto.

**Comment by thiagosoeiro** [comment]
@Tagliatti Seria bom mergear com o repositório principal. Está 16 commits pra trás?
Será que foram alterações significativas que ocorreram no repositório principal?

**Comment by Tagliatti** [comment]
@thiagosoeiro já igualei os commits nessa versão beta, tava só 3 commits atras, foi bem fácil igualar.

**Comment by carloscds** [comment]
@Tagliatti Sempre tem atualização no projeto.

**Comment by Tagliatti** [comment]
@carloscds sim, qual sua sugestão?

**Comment by thiagosoeiro** [comment]
@Tagliatti No seu repositório ta dizendo ainda que tem "16 commits behind BoletoNet:master."

**Comment by carloscds** [comment]
@Tagliatti Podemos criar uma branch específica para o Core ou manter tudo em um único projeto. @rafd75 @AlbertoMonteiro O que acham ?

**Comment by AlbertoMonteiro** [comment]
Acho que um branch espcifico fica mais visível para quem chegar agora @carloscds

**Comment by Tagliatti** [comment]
@carloscds Por mim pode ser, mas posso ser adicionado como contribuidor pra poder continuar tocando o projeto?

**Comment by Tagliatti** [comment]
@thiagosoeiro vou passar um pente fino pra ver se não esqueci nada, mas vai sempre estar falando q ta atrás pq eu não fiz merge, eu fui alterando na mão pq tem muito coisa q n pode ser mergeado diretamente da repo atual, se n vai quebrar no .net core, por isso foi fazendo na mão.

**Comment by carloscds** [comment]
@thiagosoeiro Excelente, se precisar de ajuda chama a gente aqui! E obrigado por colaborar com o projeto!

**Comment by Tagliatti** [comment]
@thiagosoeiro realmente estava faltando alguns commits, fiz o merge manual dos commits q estavam faltando e publiquei o beta2.
https://github.com/Tagliatti/BoletoNetCore/commit/a35c769d714ac78f74291b33d328328087b57952

**Comment by aubrym** [comment]
Bom dia pessoal em especial @Tagliatti .
Gostaria de saber o que seria necessário para trazer as alterações que você realizou que viabilizaram o Boleto.Net no .NET Core para esse fork original do Boleto.Net.

Isso está nos planos de vocês?

Acho isso importante porque as atualizações que estão sendo lançadas nesse fork estão ficando de fora da sua versão.
