### ISSUE TITLE
Cáculo do DV do Nosso Número - Itaú - Carteira 112

### ISSUE THREAD

**Issue by ricardodec** [BoletoNet/boleto2net#85]
Srs,

Comecei usar o projeto de vocês e gostaria de parabenizá-los pela qualidade do trabalho. Estou utilizando a carteira 112 do Itaú (CNAB 400) e, o cálculo do DV do nosso número está considerando AGENCIA+CONTA+CARTEIRA+NOSSO NUMERO, correto? Nos boletos que emiti a segunda via diretamente do site do banco está sendo considerado somente CARTEIRA+NOSSO NUMERO. Estou fazendo algo errado?

Grato

**Comment by ricardodec** [comment]
Boa tarde Rodolfo,

 

Pelos testes que fiz aqui, aparentemente essa alteração deve solucionar o problema. Tenho uma razoável urgência, pois, sem a geração do boleto pelo sistema, tenho que fazê-la manualmente pelo site do banco sempre que solicitado por algum cliente. Aguardarei ansiosamente essa correção.

 

Obrigado,

Ricardo

 

De: Rodolfo Duarte <notifications@github.com> 
Enviada em: quarta-feira, 2 de maio de 2018 16:02
Para: BoletoNet/boleto2net <boleto2net@noreply.github.com>
Cc: ricardodec <ricardodec@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [BoletoNet/boleto2net] Cáculo do DV do Nosso Número - Itaú - Carteira 112 (#85)

 

@ricardodec <https://github.com/ricardodec>  --- boa tarde...

Estou com essa alteração pendente (já implementada) aqui... mas ainda não conclui os testes unitários...

Para deixar esta rotina segura, eu solicitei para um cliente que emitisse 9 boletos com o DV da linha digitável de 1 a 9, e outros 10 boletos com o DV do nosso número entre 0 e 9. Ele já me mandou, apenas não tive tempo de testar o que ele me mandou (PDF gerado pelo Itaú) vai bater com o PDF gerado pela minha versão do Boleto2Net....

Qual sua urgência disso? ... estou enrolado e não conseguiria ver isso agora... mas seria uma ótima oportunidade para deixar tudo documentado e testado...

Apenas para seu conhecimento, segue o código (que eu já alterei aqui) que valida a carteira 112 (abaixo).... veja se é o mesmo que você está falando:

Na classe BancoItauCarteira112 (Falta testar)
boleto.NossoNumeroDV = (boleto.Banco.Cedente.ContaBancaria.Agencia + boleto.Banco.Cedente.ContaBancaria.Conta + boleto.Banco.Cedente.ContaBancaria.DigitoConta + boleto.Carteira + boleto.NossoNumero).CalcularDVItau();

Na classe BancoItauCarteira109 (Obs: essa eu sei que está correta)
boleto.NossoNumeroDV = (boleto.Banco.Cedente.ContaBancaria.Agencia + boleto.Banco.Cedente.ContaBancaria.Conta + boleto.Carteira + boleto.NossoNumero).CalcularDVItau();

**Comment by rafd75** [comment]
@ricardodec - bom dia............. (tarde)

eu tinha anotado para fazer isso hoje pela manhã.... masssssssssssssssssss pensa num dia confuso... acabou que não consegui nem abrir o projeto.

2 opções:

1 - Por sua conta e risco, atualiza o projeto ai na sua máquina com a instrução acima, gera a DLL e utiliza até que o projeto aqui no GIT seja atualizado (vou subir já com os testes, para manter seguro sempre, mesmo com as atualizações futuras)

2 - Esperar mais um pouco, até eu conseguir completar aqui e atualizar o git... 

Por favor, me cobra (respondendo essa mensagem) na quarta que vem (se eu não tiver feito ainda), que eu vou dar um jeito de matar essa tarefa aqui.... 

abs, bom final de semana.

**Comment by rafd75** [comment]
@nhnelio - eu acredito que a informação que passei, é a correta.

Minha experiência com essa carteira é com um cliente em produção. Mas só uso a remessa. Então, um dia, ele solicitou a impressão da segunda via pelo sistema... E quando eu fui checar, o calculo estava errado... 

Então, fui no código da versão "antiga" do BoletoNet , e copiei essa lógica. Se funciona lá, vai funcionar aqui...

Mas, por precaução, eu quero testar com os boletos gerados pelo próprio Itaú (estou com 14 boletos, diferentes DV da linha digitável e também do nosso número)... Acho que vai dar certo, mas melhor ter precaução e fazer o teste (comparar tudo)... 

Espero fazer isso em breve... já separei os boletos... mas meus dias estão muito complicados... vou precisar esperar um tempinho livre... mas já já eu consigo fazer isso.....

**Comment by gugaoliveira** [comment]
nenhum update desta questão?

**Comment by rafd75** [comment]
Oi @gugaoliveira , boa noite.

Eu nem me lembrava disso... E agora não lembro onde estão os boletos (de 2018) do cliente para validar os testes novamente.

Você tem boletos emitidos pelo Itau nessa carteira, para teste?

**Comment by gugaoliveira** [comment]
> Oi @gugaoliveira , boa noite.
> 
> Eu nem me lembrava disso... E agora não lembro onde estão os boletos (de 2018) do cliente para validar os testes novamente.
> 
> Você tem boletos emitidos pelo Itau nessa carteira, para teste?

SIm, tenho boletos emitidos posso enviar para teste, preciso gerar a 2a via nesta carteira, é necessario o nosso numero gerado pelo Itau? ou tem como gerar o nosso numero por algoritmo ?

**Comment by rafd75** [comment]
@gugaoliveira  -  bom dia.

O componente é capaz de gerar o nosso número, mas precisamos testar se o algoritmo está correto... 
Com os boletos, é possível fazer isso... Para os testes do componente, usamos sempre 9 boletos, com o dígito verificador da linha digitavel variando de 1 a 9.

Quanto ao dígito do nosso número, da uma olhada nessa issue que eu acabei de criar:
#337

É exatamente o mesmo caso aqui ... 

Problema: Estou sem tempo nenhum para assumir essa tarefa (de fazer os testes, etc) - nem nessa carteira do Itau, nem de seguir com o Banco Inter agora.

**Comment by gugaoliveira** [comment]
Olá eu posso testar, mas tenho uma dúvida, para gerar a carteira 112 eu preciso aguardar o Itaú gerar o nosso número e aí eu posso imprimir a segunda via com o nosso número gerado, é isso?

**Comment by rafd75** [comment]
Estou sem o manual aqui ... mas se a carteira 112 indicar que o banco é o responsável pela geração do boleto, então a resposta é sim... 

Vc comentou que tem a necessidade de impressão de segunda via do boleto, não é?  Talvez pq neste caso, o boleto sempre será gerado pelo Itaú... (se for isso, é o mesmo caso do Inter)

**Comment by gugaoliveira** [comment]
Isso mesmo, eu posso testar aqui
