### ISSUE TITLE
Banco Sicredi

### ISSUE THREAD

**Issue by guimagcpd** [BoletoNet/boleto2net#88]
Boa noite caros.
Já utilizo o BoletoNet2 para emissão de boletos do Sicoob, Bradesco, Banco do Brasil e tudo corre perfeitamente bem.
Gostaria de saber se existe alguma previsão para inclusão do banco Sicredi.
Vi que este tem já disponível no BoletoNet,, mais ainda não no BoletoNet2.
Desde já agradeço a atenção.

**Comment by rafd75** [comment]
@guimagcpd boa noite... 

O projeto é colaborativo... Não existe um mapa de atualização ou novas homologações... O jeito é você seguir as instruções do README.MD do projeto e implementar a carteira:

> Atenção: Para manter a ordem do projeto, qualquer solicitação de Pull Request de um novo banco ou carteira implementada, deverá seguir o formato dos bancos/carteiras já implementados e vir acompanhado de teste unitário da geração do boleto (PDF), arquivo remessa e geração de 9 boletos, com dígitos da linha digitável variando de 1 a 9, checando além do próprio dígito verificador, o cálculo do nosso número, linha digitável e código de barras.

**Comment by guimagcpd** [comment]
Entendi muito Obrigado rafd75, 
a propósito... criei uma DLL para leitura do retorno dos bancos que estão homologados no boletoNet2
testei o Sicoob, Bradesco, até ai blz, le que é uma maravilha , porem o Banco do Brasil da o erro..
Erro ao Ler o Arquivo..
tentei de varias formas ler o retorno do BB e sempre deparo com isso. pensei que talvez fosse um erro na rotina que adaptei pra fazer a leitura, mais descartei isso porque se fosse isso não leria os demais certo.
Desde já agradeço a atenção.

**Comment by guimagcpd** [comment]
![image](https://user-images.githubusercontent.com/11932503/39824297-ffcecc8c-537c-11e8-9201-19ee01f77c21.png)
esta acima é a rotina que fiz simples apenas para ler os arquivos...
e abaixo ta a exceção que da quando da a leitura do BB
![image](https://user-images.githubusercontent.com/11932503/39824355-1d953ca6-537d-11e8-9ac9-9d881edff75d.png)
eu acredito que caia nessa parte do código quando mando ler...
detalhe apenas o banco do brasil, neste caso o arquivo é CNAB 240
![image](https://user-images.githubusercontent.com/11932503/39824842-58a95be6-537e-11e8-9785-9d4df3e87de3.png)
desculpa incomodar com este problema...
é que eu achei de fato estranho apenas isso com o bb

**Comment by rafd75** [comment]
Imagino que o TipoArquivo já é CNAB240... 

O que tem dentro do objeto "ex" dentro do LerArquivoRetorno (vc mandou o print do ex lá no seu código, estou falando de onde deu a exceção - no Boleto2Net)? qual a mensagem de erro exatamente?

Se "ex" não mostrar Coloca um breakpoint e depura... vai aparecer o que está ocorrendo...

**Comment by guimagcpd** [comment]
Então to coletando os erros aqui apontam pra isso..

em Boleto2Net.BancoBrasil.LerHeaderRetornoCNAB240(ArquivoRetorno arquivoRetorno, String registro)
em Boleto2Net.ArquivoRetorno.LerLinhaDoArquivoRetornoCNAB240(String registro)
em Boleto2Net.ArquivoRetorno.LerArquivoRetorno(Stream arquivo)

O método ou a operação não está implementada.

sera que to deixando de apontar alguma coisa específica para o BB. ?

**Comment by guimagcpd** [comment]
Estava olhando dentro do Projeto BoletoNet2...
e vi isso.
![image](https://user-images.githubusercontent.com/11932503/39826458-c1329d72-5382-11e8-8dd8-fc769ddb9576.png)

Não seria esse o problema ?
Desculpa minha insistência, e ignorância, é que nem manjo de C# mais fuçando vi isso ai.
e todos os demais bancos tem isso implementado

**Comment by rafd75** [comment]
é isso mesmo... 

Banco do Brasil tem implementado o CNAB400 (que eles chamam de CBR641 e CBR643), mas não tem o CNAB240... por isso o erro.

Para usar o CNAB240, precisa implementar... tem que solicitar o manual no banco, e fazer a implementação usando como modelo outro banco que já tenha o CNAB240 pronto (para seguir o mesmo padrão em todo o projeto...)

**Comment by guimagcpd** [comment]
Certo. mais a remessa está gerando normal na CNAB240 o BB né. ?

**Comment by rafd75** [comment]
Abri o projeto aqui... sim, está implementado a remessa, mas não o retorno (CNAB240)... 
Se eu não deixei passar algum detalhe menor, está fácil de implementar... são 2 funções da classe BancoBrasil -> LerDetalheRetornoCNAB240SegmentoT e LerDetalheRetornoCNAB240SegmentoU

O resto parece estar ok.

A classe BancoCaixa implementa essas 2 funções... pode servir de modelo para implementar no BancoBrasil... mas fique atento pois tem diferenças entre os bancos... precisa pegar o manual e verificar.

**Comment by guimagcpd** [comment]
Certo Muito Obrigado...
