### ISSUE TITLE
Erro de Arquitetura (Arquivo Retorno)

### ISSUE THREAD

**Issue by rafd75** [BoletoNet/boleto2net#9]
Acabei de pegar um BUG aqui.

Ao ler um arquivo retorno, criamos um objeto BANCO (que contém Conta Corrente, que contém a Carteira) que é utilizado para todos os boletos.

Acabei de ler um arquivo do Itaú, com títulos de sistemas diferentes (e carteiras diferentes). Por ter um objeto BANCO comum a todos os boletos, a carteira indicada pelo Boleto2Net é sempre a do último boleto (linha detalhe) lido.

Vou verificar o que precisa ser alterado.

**Comment by rafd75** [comment]
Corrigido:

#10

**Comment by carloscds** [comment]
@rafd75 Show, manda o PR!

**Comment by rafd75** [comment]
@carloscds - já mandei #10 --- e já fez o MERGE também.....

**Comment by rafd75** [comment]
@dannieljunior boa tarde...

Entendi sua explicação... Realmente (pensando rapidamente aqui) não haveria necessidade, no caso do arquivo retorno, de instanciar a carteira.... mas, como está dando erro, em algum momento da leitura, essa classe é utilizada.

Você consegue depurar isso e informar em que linha ocorre o erro?

**Comment by dannieljunior** [comment]
https://github.com/BoletoNet/boleto2net/pull/10#pullrequestreview-113624326
