### ISSUE TITLE
Bradesco CNAB240

### ISSUE THREAD

**Issue by douglascantomelo** [BoletoNet/boleto2net#91]
Pessoal, bom dia! Acabei de enviar um arquivo de remessa para o Bradesco e eles me retornaram o seguinte:

Linha 1, colunas 072 a 072, Header de arquivo, Dígito verificador. Deixar em branco.
Linha 1, colunas 157 a 163, Header de arquivo, número sequencial de arquivo está zerado.
Linha 1, colunas 167 a 171, Header de arquivo, densidade de gravação do arquivo inválida. 01600 ou 06250.
Linha 2, colunas 072 a 072, Header de lote, dígito verificador. Deixar em branco.
Linha 2, colunas 184 a 191, Header de lote, sequencial de remessa zerado.
Linha 3, colunas 037 a 037, dígito verificador. Deixar em branco.
Linha 6, colunas 037 a 037, dígito verificador. Deixar em branco.
...
Linha 274, colunas 030 a 035, Trailer de arquivo, quantidade de contas exclusivo para conciliação bancária. Informar zeros.

Alguém teve problema parecido? Estou usando a dll do Nuget

**Comment by rafd75** [comment]
@douglascmelo - aqui, eu uso o Bradesco, mas no padrão CNAB400.

Da uma olhada no manual, e compara o que o suporte te falou, com o que está escrito lá, e se for o caso, faça o ajuste...

Também pode ser, por exemplo, que você não informou o número sequencial do arquivo ao gerar o arquivo. Neste caso, o Boleto2Net pode estar OK, mas sua chamada ai, faltando algo.

**Comment by douglascmelo** [comment]
@rafd75 , é alguns campos estão inconsistentes, vou baixar o projeto e mudar aqui, quando o banco validar eu dou retorno

**Comment by douglascmelo** [comment]
@rafd75 , consegui um retorno positivo do Bradesco agora pela manhã depois que fiz os ajustes no 240, como proceder para subir minhas contribuições?

**Comment by rafd75** [comment]
@carloscds - tem algum tutorial básico sobre o Git para passar para o Douglas?

@douglascmelo  - se não tiver esse tutorial, eu combino com você de pegar as alterações e eu subo junto com o outro recurso que estou alterando aqui (Itaú Carteira 112)

**Comment by douglascmelo** [comment]
Então, eu sei usar o Git hehehe é pq eu vi em algum lugar por aqui que vcs mudaram as regras pra fazer pull request, tinha que fazer uns testes e tal, eu já usava/uso a versão anterior do BN.

**Comment by rafd75** [comment]
ah, então pode subir... essa alteração que você fez, não mudaria os testes implantados... 

@carloscds desconsidere a msg anterior.

**Comment by mateusdev25** [comment]
@rafd75 eu estou com esse mesmo problema e não sei como resolver, será que dava pra me dar uma mão?

**Comment by mateusdev25** [comment]
@douglascantomelo voce fez oque pra resolver esse erro ?

**Comment by mateusdev25** [comment]
entendi, e pra usar o layout 400 ?

**Comment by rafd75** [comment]
Esse eu uso aqui... toda semana... e funciona... 

Mas nesse caso, o banco precisa ser avisado para o gerente configurar lá...   senão vai rejeitar seu arquivo.

**Comment by mateusdev25** [comment]
então quando fui homologar minha carteira com o banco eles disseram que o layout é o 400, possa ser por isso que o 240 não está funcionando

**Comment by rafd75** [comment]
são formatos diferentes... se estão esperando o 400 lá, você tem que gerar no formato 400...

**Comment by mateusdev25** [comment]
vix então como faço pra mudar o boletonet/boleto2net pro layout 400 ?

**Comment by rafd75** [comment]
Da uma olhada nesse código (é o teste do bradesco)

https://github.com/BoletoNet/boleto2net/blob/master/Boleto2.Net.Testes/BancoBradescoCarteira09.cs

**Comment by mateusdev25** [comment]
@rafd75 me desculpa o incomodo e tudo mais, é porque sou novo na area programação sera que dava pra voce me dar uma força, porque nao sei como eu iria fazer essa troca, voce tem algum meio de contato alem do github ?

**Comment by mateusdev25** [comment]
@rafd75 sera que voce poderia me dar uma força me ajudando a fazer essa troca ? eu sou novo na area de programação e não sei como vou fazer essa troca.

**Comment by rafd75** [comment]
Baixa o fonte do projeto, e da uma olhada no teste "BancoBradescoCareira09" ... 

mais ou menos, é isso:

cria uma instancia de conta bancaria (no construtor do teste), e depois , para gerar o arquivo CNAB400, é através dessa chamada:
     Utils.TestarHomologacao(_banco, TipoArquivo.CNAB400, nameof(BancoBradescoCarteira09), 5, true, "?", 223344);

Esse método fica aqui:

https://github.com/BoletoNet/boleto2net/blob/7038fb2e15ac200de6a24f3fa9c2aaa9eb855487/Boleto2.Net.Testes/Utils.cs#L148

**Comment by mateusdev25** [comment]
agora so ta dando esse erro 

Linha 3, colunas 395 a 400, Número sequencial de registro inválido.
Linha 3, Tamanho do registro inválido.

**Comment by rafd75** [comment]
isso no bradesco?

sem olhar o código, não faço ideia... baixa o fonte da biblioteca e coloca um breakpoint para vc ver qual variavel está sendo utilizada nessa posição...

Possivelmente é nessa linha que preenche esse campo ai:

https://github.com/BoletoNet/boleto2net/blob/7038fb2e15ac200de6a24f3fa9c2aaa9eb855487/Boleto2.Net/Banco/BancoBradesco.cs#L885

**Comment by mateusdev25** [comment]
É bradesco CNAB400

**Comment by mateusdev25** [comment]
Rodolfo você tem discord ou algum meio de contato pra mim te mostrar o código?

**Comment by mateusdev25** [comment]
Provávelmente seja coisa rápida de resolver

**Comment by mateusdev25** [comment]
Eu te dou um agrado qualquer coisa

**Comment by rafd75** [comment]
Linha 3, colunas 395 a 400, Número sequencial de registro inválido.
Linha 3, Tamanho do registro inválido.

esse erro => foi no teste do bradesco? ou a biblioteca que alertou?

**Comment by rafd75** [comment]
Não consigo parar aqui... cola aqui como vc está gerando o arquivo... 

mas estou de saída, e na semana que vem, devo ficar alocado em cliente.

**Comment by mateusdev25** [comment]
Imports Boleto2Net
Imports System.IO


Public Class Form1
    Private Sub btnGerar_Click(sender As Object, e As EventArgs) Handles btnGerar.Click
        Dim objBoletos As New Boletos
        Dim strImpressora As String = Nothing
        Dim blnImprimir As Boolean = False
        Dim intCopias As Short = 1

        Try
            ''CRIAÇÃO DA PARTE DO CEDENTE
            'Cabeçalho do Banco
            objBoletos.Banco = Banco.Instancia(237)
            objBoletos.Banco.Cedente = New Cedente
            objBoletos.Banco.Cedente.CPFCNPJ = "07.744.000/0001-45"
            objBoletos.Banco.Cedente.Nome = "SANTANA MACEDO REPRESENTACOES COMERCIAIS"
            objBoletos.Banco.Cedente.Observacoes = "Sem observacoes"

            Dim conta As New ContaBancaria
            conta.Agencia = "3029"
            conta.DigitoAgencia = "5"
            conta.OperacaoConta = String.Empty
            conta.Conta = "1288"
            conta.DigitoConta = "2"
            conta.CarteiraPadrao = "09"

            conta.VariacaoCarteiraPadrao = ""
            conta.TipoCarteiraPadrao = TipoCarteira.CarteiraCobrancaSimples
            conta.TipoFormaCadastramento = TipoFormaCadastramento.ComRegistro
            conta.TipoImpressaoBoleto = TipoImpressaoBoleto.Empresa
            conta.TipoDocumento = TipoDocumento.Tradicional

            Dim ender As New Endereco
            ender.LogradouroEndereco = "AV JOAQUIM DIAS GUIMARAES"
            ender.LogradouroNumero = "300"
            ender.LogradouroComplemento = ""
            ender.Bairro = "SAO FRANCISCO"
            ender.Cidade = "GUANAMBI"
            ender.UF = "BA"
            ender.CEP = "46430000"

            objBoletos.Banco.Cedente.Codigo = "5510841"
            objBoletos.Banco.Cedente.CodigoDV = "2"
            objBoletos.Banco.Cedente.CodigoTransmissao = "0070900"
            objBoletos.Banco.Cedente.ContaBancaria = conta
            objBoletos.Banco.Cedente.Endereco = ender

            objBoletos.Banco.FormataCedente()

            For I As Integer = 1 To 1
                ''CRIAÇÃO DO TITULO
                Dim Titulo As New Boleto(objBoletos.Banco)
                Titulo.Sacado = New Sacado With {
                    .CPFCNPJ = textBox11.Text,
                    .Endereco = New Boleto2Net.Endereco With {
                    .Bairro = textBox5.Text,
                    .CEP = textBox1.Text,
                    .Cidade = textBox9.Text,
                    .LogradouroComplemento = "Casa",
                    .LogradouroEndereco = textBox7.Text,
                    .LogradouroNumero = textBox8.Text,
                    .UF = "BA"},
                    .Nome = textBox3.Text,
                    .Observacoes = TextBox6.Text
                }
                Titulo.CodigoOcorrencia = "01"
                Titulo.DescricaoOcorrencia = "Registrar Boleto"
                Titulo.NumeroDocumento = I
                Titulo.NumeroControleParticipante = "12"
                Titulo.NossoNumero = "0004000" & I
                Titulo.DataEmissao = Now.Date
                Titulo.DataVencimento = Now.Date.AddDays(15)
                Titulo.ValorTitulo = textBox10.Text
                Titulo.Aceite = "N"
                Titulo.EspecieDocumento = TipoEspecieDocumento.DM
                Titulo.DataDesconto = Now.Date.AddDays(15)
                Titulo.ValorDesconto = 0

                '
                'PARTE DA MULTA
                Titulo.DataMulta = Now.Date.AddDays(15)
                Titulo.PercentualMulta = 2
                Titulo.ValorMulta = Titulo.ValorTitulo * Titulo.PercentualMulta / 100
                Titulo.MensagemInstrucoesCaixa = $"Cobrar multa de {FormatNumber(Titulo.ValorMulta, 2)} após a data de vencimento."
                '
                'PARTE JUROS DE MORA
                Titulo.DataJuros = Now.Date.AddDays(20)
                Titulo.PercentualJurosDia = 10 / 30
                Titulo.ValorJurosDia = Titulo.ValorTitulo * Titulo.PercentualJurosDia / 100
                Dim instrucoes As String = $"Cobrar juros de {FormatNumber(Titulo.PercentualJurosDia, 2)} por dia."
                If String.IsNullOrEmpty(Titulo.MensagemInstrucoesCaixa) Then
                    Titulo.MensagemInstrucoesCaixa = instrucoes
                Else
                    Titulo.MensagemInstrucoesCaixa += Environment.NewLine + instrucoes
                End If
                '
                'Titulo.CodigoInstrucao1 = String.Empty
                'Titulo.ComplementoInstrucao1 = String.Empty

                'Titulo.CodigoInstrucao2 = String.Empty
                'Titulo.ComplementoInstrucao2 = String.Empty

                'Titulo.CodigoInstrucao3 = String.Empty
                'Titulo.ComplementoInstrucao3 = String.Empty
                Titulo.CodigoProtesto = TipoCodigoProtesto.NaoProtestar
                Titulo.DiasProtesto = 0
                Titulo.CodigoBaixaDevolucao = TipoCodigoBaixaDevolucao.NaoBaixarNaoDevolver
                Titulo.DiasBaixaDevolucao = 0
                Titulo.ValidarDados()
                objBoletos.Add(Titulo)
            Next


            '
            If File.Exists(Application.StartupPath & "\remessa.txt") Then
                File.Delete(Application.StartupPath & "\remessa.txt")
            End If
            'GERA ARQUIVO DE REMESSA
            Dim st As New MemoryStream
            Dim remessa = New ArquivoRemessa(objBoletos.Banco, TipoArquivo.CNAB400, 1)
            remessa.GerarArquivoRemessa(objBoletos, st)
            Dim arquivo As New FileStream(Application.StartupPath & "\remessa.txt", FileMode.Create, FileAccess.ReadWrite)

            st.WriteTo(arquivo)
            arquivo.Close()
            st.Close()


            Dim LerArquivo As New StreamReader(Application.StartupPath & "\remessa.txt")

            Dim RefazArquivo As New StreamWriter(Application.StartupPath & "\remessa2.txt") 'Arquivo verificado para ser enviado ao banco
            Dim strTexto As String = Nothing
            Dim conta1 As Integer = 0
            Do While LerArquivo.Peek <> -1
                strTexto = LerArquivo.ReadLine
                conta1 = strTexto.Length
                If conta1 < 240 Then
                    conta1 = 240 - conta1
                    Dim strEspaco As String = Nothing
                    For I As Integer = 1 To conta1
                        strEspaco = strEspaco & " "
                    Next
                    RefazArquivo.WriteLine(strTexto & strEspaco)
                Else
                    RefazArquivo.WriteLine(strTexto)
                End If

            Loop
            RefazArquivo.Close()
            LerArquivo.Close()

            'Solicita se vai imprimir os boletos
            If MessageBox.Show("Deseja imprimir os boletos agora?", "Atenção", MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button1) = DialogResult.Yes Then
                Dim imp As New PrintDialog
                If imp.ShowDialog = DialogResult.OK Then
                    strImpressora = imp.PrinterSettings.PrinterName
                    intCopias = imp.PrinterSettings.Copies
                    blnImprimir = True
                End If
            End If

            'Gera boletos
            Dim numBoletos As Integer = 0
            For Each linha In objBoletos
                numBoletos += 1
                Dim NovoBoleto = New BoletoBancario
                NovoBoleto.Boleto = linha
                Dim pdf = NovoBoleto.MontaBytesPDF(False)
                File.WriteAllBytes(Application.StartupPath & "\boleto" & numBoletos & ".pdf", pdf)


                'Parte da impressão do boleto
                If blnImprimir = True Then
                    Dim MyProcess As New Process
                    MyProcess.StartInfo.CreateNoWindow = False
                    MyProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden
                    MyProcess.StartInfo.Verb = "print"
                    MyProcess.StartInfo.Arguments = strImpressora

                    MyProcess.StartInfo.FileName = Application.StartupPath & "\boleto" & numBoletos & ".pdf"
                    MyProcess.Start()
                    'MyProcess.WaitForExit(10000)
                    MyProcess.WaitForInputIdle()

                    If MyProcess.Responding Then
                        MyProcess.CloseMainWindow()
                    Else
                        MyProcess.Kill()
                    End If

                    'MyProcess.Close()
                End If
            Next

            MessageBox.Show("Boleto Gerado.")
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Sub

    Private Sub btnRetorno_Click(sender As Object, e As EventArgs)
        Dim arquivo As FileStream = File.OpenRead("C:\Users\Marcio\Desktop\Temp\Retorno\25102018-1.ret")
        Dim bol As New MemoryStream()
        bol.SetLength(arquivo.Length)
        arquivo.Read(bol.GetBuffer(), 0, CInt(Fix(arquivo.Length)))
        Dim objRetorno As New ArquivoRetorno(bol)

        Dim meus As New Boletos

        For Each Linha In objRetorno.Boletos
            meus.Add(Linha)
            MessageBox.Show(Linha.Sacado.Nome)

            MessageBox.Show(Linha.CodigoOcorrencia) 'Código de Movimento de Retorno
        Next
    End Sub

    Private Sub pictureBox6_Click(sender As Object, e As EventArgs) Handles pictureBox6.Click

    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub

    Private Sub label21_Click(sender As Object, e As EventArgs)
    End Sub

    Private Sub label15_Click(sender As Object, e As EventArgs)

    End Sub
End Class

**Comment by mateusdev25** [comment]
Imports Boleto2Net
Imports System.IO


Public Class Form1
    Private Sub btnGerar_Click(sender As Object, e As EventArgs) Handles btnGerar.Click
        Dim objBoletos As New Boletos
        Dim strImpressora As String = Nothing
        Dim blnImprimir As Boolean = False
        Dim intCopias As Short = 1

        Try
            ''CRIAÇÃO DA PARTE DO CEDENTE
            'Cabeçalho do Banco
            objBoletos.Banco = Banco.Instancia(237)
            objBoletos.Banco.Cedente = New Cedente
            objBoletos.Banco.Cedente.CPFCNPJ = "07.744.000/0001-45"
            objBoletos.Banco.Cedente.Nome = "SANTANA MACEDO REPRESENTACOES COMERCIAIS"
            objBoletos.Banco.Cedente.Observacoes = "Sem observacoes"

            Dim conta As New ContaBancaria
            conta.Agencia = "1111"
            conta.DigitoAgencia = "5"
            conta.OperacaoConta = String.Empty
            conta.Conta = "1111"
            conta.DigitoConta = "2"
            conta.CarteiraPadrao = "09"

            conta.VariacaoCarteiraPadrao = ""
            conta.TipoCarteiraPadrao = TipoCarteira.CarteiraCobrancaSimples
            conta.TipoFormaCadastramento = TipoFormaCadastramento.ComRegistro
            conta.TipoImpressaoBoleto = TipoImpressaoBoleto.Empresa
            conta.TipoDocumento = TipoDocumento.Tradicional

            Dim ender As New Endereco
            ender.LogradouroEndereco = "AV JOAQUIM DIAS GUIMARAES"
            ender.LogradouroNumero = "300"
            ender.LogradouroComplemento = ""
            ender.Bairro = "SAO FRANCISCO"
            ender.Cidade = "GUANAMBI"
            ender.UF = "BA"
            ender.CEP = "46430000"

            objBoletos.Banco.Cedente.Codigo = "1111111"
            objBoletos.Banco.Cedente.CodigoDV = "2"
            objBoletos.Banco.Cedente.CodigoTransmissao = "0070900"
            objBoletos.Banco.Cedente.ContaBancaria = conta
            objBoletos.Banco.Cedente.Endereco = ender

            objBoletos.Banco.FormataCedente()

            For I As Integer = 1 To 1
                ''CRIAÇÃO DO TITULO
                Dim Titulo As New Boleto(objBoletos.Banco)
                Titulo.Sacado = New Sacado With {
                    .CPFCNPJ = textBox11.Text,
                    .Endereco = New Boleto2Net.Endereco With {
                    .Bairro = textBox5.Text,
                    .CEP = textBox1.Text,
                    .Cidade = textBox9.Text,
                    .LogradouroComplemento = "Casa",
                    .LogradouroEndereco = textBox7.Text,
                    .LogradouroNumero = textBox8.Text,
                    .UF = "BA"},
                    .Nome = textBox3.Text,
                    .Observacoes = TextBox6.Text
                }
                Titulo.CodigoOcorrencia = "01"
                Titulo.DescricaoOcorrencia = "Registrar Boleto"
                Titulo.NumeroDocumento = I
                Titulo.NumeroControleParticipante = "12"
                Titulo.NossoNumero = "0004000" & I
                Titulo.DataEmissao = Now.Date
                Titulo.DataVencimento = Now.Date.AddDays(15)
                Titulo.ValorTitulo = textBox10.Text
                Titulo.Aceite = "N"
                Titulo.EspecieDocumento = TipoEspecieDocumento.DM
                Titulo.DataDesconto = Now.Date.AddDays(15)
                Titulo.ValorDesconto = 0

                '
                'PARTE DA MULTA
                Titulo.DataMulta = Now.Date.AddDays(15)
                Titulo.PercentualMulta = 2
                Titulo.ValorMulta = Titulo.ValorTitulo * Titulo.PercentualMulta / 100
                Titulo.MensagemInstrucoesCaixa = $"Cobrar multa de {FormatNumber(Titulo.ValorMulta, 2)} após a data de vencimento."
                '
                'PARTE JUROS DE MORA
                Titulo.DataJuros = Now.Date.AddDays(20)
                Titulo.PercentualJurosDia = 10 / 30
                Titulo.ValorJurosDia = Titulo.ValorTitulo * Titulo.PercentualJurosDia / 100
                Dim instrucoes As String = $"Cobrar juros de {FormatNumber(Titulo.PercentualJurosDia, 2)} por dia."
                If String.IsNullOrEmpty(Titulo.MensagemInstrucoesCaixa) Then
                    Titulo.MensagemInstrucoesCaixa = instrucoes
                Else
                    Titulo.MensagemInstrucoesCaixa += Environment.NewLine + instrucoes
                End If
                '
                'Titulo.CodigoInstrucao1 = String.Empty
                'Titulo.ComplementoInstrucao1 = String.Empty

                'Titulo.CodigoInstrucao2 = String.Empty
                'Titulo.ComplementoInstrucao2 = String.Empty

                'Titulo.CodigoInstrucao3 = String.Empty
                'Titulo.ComplementoInstrucao3 = String.Empty
                Titulo.CodigoProtesto = TipoCodigoProtesto.NaoProtestar
                Titulo.DiasProtesto = 0
                Titulo.CodigoBaixaDevolucao = TipoCodigoBaixaDevolucao.NaoBaixarNaoDevolver
                Titulo.DiasBaixaDevolucao = 0
                Titulo.ValidarDados()
                objBoletos.Add(Titulo)
            Next


            '
            If File.Exists(Application.StartupPath & "\remessa.txt") Then
                File.Delete(Application.StartupPath & "\remessa.txt")
            End If
            'GERA ARQUIVO DE REMESSA
            Dim st As New MemoryStream
            Dim remessa = New ArquivoRemessa(objBoletos.Banco, TipoArquivo.CNAB400, 1)
            remessa.GerarArquivoRemessa(objBoletos, st)
            Dim arquivo As New FileStream(Application.StartupPath & "\remessa.txt", FileMode.Create, FileAccess.ReadWrite)

            st.WriteTo(arquivo)
            arquivo.Close()
            st.Close()


            Dim LerArquivo As New StreamReader(Application.StartupPath & "\remessa.txt")

            Dim RefazArquivo As New StreamWriter(Application.StartupPath & "\remessa2.txt") 'Arquivo verificado para ser enviado ao banco
            Dim strTexto As String = Nothing
            Dim conta1 As Integer = 0
            Do While LerArquivo.Peek <> -1
                strTexto = LerArquivo.ReadLine
                conta1 = strTexto.Length
                If conta1 < 240 Then
                    conta1 = 240 - conta1
                    Dim strEspaco As String = Nothing
                    For I As Integer = 1 To conta1
                        strEspaco = strEspaco & " "
                    Next
                    RefazArquivo.WriteLine(strTexto & strEspaco)
                Else
                    RefazArquivo.WriteLine(strTexto)
                End If

            Loop
            RefazArquivo.Close()
            LerArquivo.Close()

            'Solicita se vai imprimir os boletos
            If MessageBox.Show("Deseja imprimir os boletos agora?", "Atenção", MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button1) = DialogResult.Yes Then
                Dim imp As New PrintDialog
                If imp.ShowDialog = DialogResult.OK Then
                    strImpressora = imp.PrinterSettings.PrinterName
                    intCopias = imp.PrinterSettings.Copies
                    blnImprimir = True
                End If
            End If

            'Gera boletos
            Dim numBoletos As Integer = 0
            For Each linha In objBoletos
                numBoletos += 1
                Dim NovoBoleto = New BoletoBancario
                NovoBoleto.Boleto = linha
                Dim pdf = NovoBoleto.MontaBytesPDF(False)
                File.WriteAllBytes(Application.StartupPath & "\boleto" & numBoletos & ".pdf", pdf)


                'Parte da impressão do boleto
                If blnImprimir = True Then
                    Dim MyProcess As New Process
                    MyProcess.StartInfo.CreateNoWindow = False
                    MyProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden
                    MyProcess.StartInfo.Verb = "print"
                    MyProcess.StartInfo.Arguments = strImpressora

                    MyProcess.StartInfo.FileName = Application.StartupPath & "\boleto" & numBoletos & ".pdf"
                    MyProcess.Start()
                    'MyProcess.WaitForExit(10000)
                    MyProcess.WaitForInputIdle()

                    If MyProcess.Responding Then
                        MyProcess.CloseMainWindow()
                    Else
                        MyProcess.Kill()
                    End If

                    'MyProcess.Close()
                End If
            Next

            MessageBox.Show("Boleto Gerado.")
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Sub

    Private Sub btnRetorno_Click(sender As Object, e As EventArgs)
        Dim arquivo As FileStream = File.OpenRead("C:\Users\Marcio\Desktop\Temp\Retorno\25102018-1.ret")
        Dim bol As New MemoryStream()
        bol.SetLength(arquivo.Length)
        arquivo.Read(bol.GetBuffer(), 0, CInt(Fix(arquivo.Length)))
        Dim objRetorno As New ArquivoRetorno(bol)

        Dim meus As New Boletos

        For Each Linha In objRetorno.Boletos
            meus.Add(Linha)
            MessageBox.Show(Linha.Sacado.Nome)

            MessageBox.Show(Linha.CodigoOcorrencia) 'Código de Movimento de Retorno
        Next
    End Sub

    Private Sub pictureBox6_Click(sender As Object, e As EventArgs) Handles pictureBox6.Click

    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub

    Private Sub label21_Click(sender As Object, e As EventArgs)
    End Sub

    Private Sub label15_Click(sender As Object, e As EventArgs)

    End Sub
End Class

**Comment by rafd75** [comment]
e o arquivo gerado? (o TXT) - copia tb

**Comment by rafd75** [comment]
Já uma dica ai:

Dim remessa = New ArquivoRemessa(objBoletos.Banco, TipoArquivo.CNAB400, 1)

Esse número 1 ai, você precisa controlar... isso indica que é o primeiro arquivo... depois quando vc for enviar o seguinte, tem que ser 2, e assim por adiante.

O Bradesco deve rejeitar o segundo arquivo, se o sequencial dele for 1 (repetindo o primeiro arquivo)

**Comment by rafd75** [comment]
E para que serve isso:

`Dim LerArquivo As New StreamReader(Application.StartupPath & "\remessa.txt")

        Dim RefazArquivo As New StreamWriter(Application.StartupPath & "\remessa2.txt") 'Arquivo verificado para ser enviado ao banco
        Dim strTexto As String = Nothing
        Dim conta1 As Integer = 0
        Do While LerArquivo.Peek <> -1
            strTexto = LerArquivo.ReadLine
            conta1 = strTexto.Length
            If conta1 < 240 Then
                conta1 = 240 - conta1
                Dim strEspaco As String = Nothing
                For I As Integer = 1 To conta1
                    strEspaco = strEspaco & " "
                Next
                RefazArquivo.WriteLine(strTexto & strEspaco)
            Else
                RefazArquivo.WriteLine(strTexto)
            End If

        Loop
        RefazArquivo.Close()
        LerArquivo.Close()`

**Comment by mateusdev25** [comment]
Ta bom, vou mudar isso. provávelmente deve ser esse o primeiro erro

**Comment by rafd75** [comment]
copia aqui o conteúdo do "remessa1.txt" ... não sei pq vc está lendo o remessa1 e gerando o remessa2.

**Comment by mateusdev25** [comment]
> e o arquivo gerado? (o TXT) - copia tb

Ok

**Comment by rafd75** [comment]
> Ta bom, vou mudar isso. provávelmente deve ser esse o primeiro erro

Não é... se não me engano, essa informação vai na primeira linha (cabeçalho)... a linha 3, já é detalhe.

Copia o conteúdo do REMESSA1.TXT aqui... 3... 2... 1... estou indo embora.... go go go

**Comment by mateusdev25** [comment]
01REMESSA01COBRANCA       00000000000005510841SANTANA MACEDO REPRESENTACOES 237BRADESCO       161222        MX0000001                                                                                                                                                                                                                                                                                     000001
100000 000000000000 0009030290001288212                       0002020000000040001P00000000002               011         31122200000000012000000000001N161222000000000000000040000000000000000000000000000000000000000000000100008715208508MATEUS COSTA ALVES                      AV.PRESIDENTE DULTRA 1800 CASA                      46430000                                                            000002
9

**Comment by mateusdev25** [comment]
01REMESSA01COBRANCA       00000000000005510841SANTANA MACEDO REPRESENTACOES 237BRADESCO       161222        MX0000001                                                                                                                                                                                                                                                                                     000001
100000 000000000000 0009030290001288212                       0002020000000040001P00000000002               011         31122200000000012000000000001N161222000000000000000040000000000000000000000000000000000000000000000100008715208508MATEUS COSTA ALVES                      AV.PRESIDENTE DULTRA 1800 CASA                      46430000                                                            000002
9

**Comment by rafd75** [comment]
está cortando os espaços... coloca formatado como código aqui, vamos ver se ele preserva.
eu quero saber se as linhas estão com 400 caracteres cada uma.

Obs: no final do registro 9 (trail) deveria ter 000003 lá na posição 395..400 - o problema está no registro RODAPE , me parece...

**Comment by mateusdev25** [comment]
`01REMESSA01COBRANCA       00000000000005510841SANTANA MACEDO REPRESENTACOES 237BRADESCO       161222        MX0000001                                                                                                                                                                                                                                                                                     000001
100000 000000000000 0009030290001288212                       0002020000000040001P00000000002               011         31122200000000012000000000001N161222000000000000000040000000000000000000000000000000000000000000000100008715208508MATEUS COSTA ALVES                      AV.PRESIDENTE DULTRA 1800 CASA                      46430000                                                            000002
9                                                                              
[remessa.txt](https://github.com/BoletoNet/boleto2net/files/10248639/remessa.txt)
                                                                                                                                             `

**Comment by rafd75** [comment]
vc está pegando o REMESSA1.TXT ou REMESSA2.TXT?

vc não me respondeu pq vc está abrindo o 1 e gerando o 2 ... to achando que o problema está ai... pq vc está lendo e gravando novamente o arquivo?

**Comment by rafd75** [comment]
> E para que serve isso:
> 
> `Dim LerArquivo As New StreamReader(Application.StartupPath & "\remessa.txt")
> 
> ```
>     Dim RefazArquivo As New StreamWriter(Application.StartupPath & "\remessa2.txt") 'Arquivo verificado para ser enviado ao banco
>     Dim strTexto As String = Nothing
>     Dim conta1 As Integer = 0
>     Do While LerArquivo.Peek <> -1
>         strTexto = LerArquivo.ReadLine
>         conta1 = strTexto.Length
>         If conta1 < 240 Then
>             conta1 = 240 - conta1
>             Dim strEspaco As String = Nothing
>             For I As Integer = 1 To conta1
>                 strEspaco = strEspaco & " "
>             Next
>             RefazArquivo.WriteLine(strTexto & strEspaco)
>         Else
>             RefazArquivo.WriteLine(strTexto)
>         End If
> 
>     Loop
>     RefazArquivo.Close()
>     LerArquivo.Close()`
> ```

A meleca deve estar aqui... Pq vc testa se é 240?...

**Comment by mateusdev25** [comment]
remessa 1 e o remessa 2 tao igual

**Comment by mateusdev25** [comment]
então eu posso apagar essa parte que voce citou ?

**Comment by rafd75** [comment]
https://github.com/BoletoNet/boleto2net/blob/7038fb2e15ac200de6a24f3fa9c2aaa9eb855487/Boleto2.Net/Banco/BancoBradesco.cs#L935

Nesse local que está quebrando seu arquivo... Não sei pq não está gerando o 000003 lá no final do seu TXT. Deveria estar funcionando

**Comment by mateusdev25** [comment]
private string GerarTrailerRemessaCNAB400(ref int numeroRegistroGeral)
        {
            try
            {
                numeroRegistroGeral++;
                var reg = new TRegistroEDI();
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0001, 001, 0, "9", '0');
                reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0002, 393, 0, Empty, ' ');
                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0395, 006, 0, numeroRegistroGeral, '0');
                reg.CodificarLinha();
                return reg.LinhaRegistro;
            }
            catch (Exception ex)
            {
                throw new Exception("Erro durante a geração do registro TRAILER do arquivo de REMESSA.", ex);
            }

**Comment by mateusdev25** [comment]
ta igual o seu

**Comment by rafd75** [comment]
> então eu posso apagar essa parte que voce citou ?

Olha... vc deveria entender, pelo menos, o que cada bloco desse código faz.
Não sei de onde você tirou essa parte ai ... 

o código que gera o arquivo, no Boleto2Net, é essa:

` 'GERA ARQUIVO DE REMESSA
        Dim st As New MemoryStream
        Dim remessa = New ArquivoRemessa(objBoletos.Banco, TipoArquivo.CNAB400, **esse 1 aqui eu já expliquei - não pode ser fixo, é um sequencial dos arquivos que serão enviados para o banco**)
        remessa.GerarArquivoRemessa(objBoletos, st)
        Dim arquivo As New FileStream(Application.StartupPath & "\remessa.txt", FileMode.Create, FileAccess.ReadWrite)

        st.WriteTo(arquivo)
        arquivo.Close()
        st.Close()`

Com o código acima, gera o REMESSA.TXT e pronto... dai pra frente, não entendi pq vc le, e grava o remessa2.

**Comment by mateusdev25** [comment]
vou fazer as alterações

**Comment by mateusdev25** [comment]
@rafd75 então eu fiz as alterações, e o problema é pq nao gera o 000003 igual voce havia dito, eu não como  resolver isso

**Comment by rafd75** [comment]
@mateusdev25 --- boa noite!

rapaz, sem chance esse fim de ano... estou virando um sistema, e ta complicado.

como ficou o código? copia aqui... 

mas o mais rapido para vc encontrar esse problema, é colocar um breakpoint ao mandar gerar o arquivo, e ir depurando o problema, até descobrir onde está desviando o código para não gerar o contador da ultima linha.

**Comment by mateusdev25** [comment]
eu usei o breakpoint, quando eu inverti essas 2 linhas ele gera o 000003 mas não gera os espaços, e sem inverter ele não gera o 000003, e os espaços da 3 linha so vão até a linha 221
```
reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0002, 393, 0, Empty, ' ');
reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0395, 006, 0, numeroRegistroGeral, '0');
```
