### ISSUE TITLE
Mensagem Instruções Bradesco

### ISSUE THREAD

**Issue by RodolphoChagas** [BoletoNet/boleto2net#92]
Boa tarde!!
Estou tentando inserir algumas mensagens no boleto porém a quebra de linha não funciona.

Ex.: 
boleto.MensagemInstrucoesCaixa = "xxxxxxxxx" + Environment.NewLine +"aaaaaaaaa";

Já tentei de outras maneiras também, estou fazendo algo de errado ?

**Comment by rafd75** [comment]
@RodolphoChagas , no chute aqui... tenta:

boleto.MensagemInstrucoesCaixa = "xxxxxxxxx" + "<br>" +"aaaaaaaaa";

Não lembro se é no Boleto2Net ou o outro componente que a gente usava aqui... mas isso funciona(va)... kk

**Comment by RodolphoChagas** [comment]
Não rolou kkk
