### ISSUE TITLE
Envio de boletos em lote (por email)

### ISSUE THREAD

**Issue by RodolphoChagas** [BoletoNet/boleto2net#94]
Estou trabalhando com C# Windows Forms, já consigo gerar o boleto em PDF.
Exite alguma função ou rotina para envio dos boletos em Lote ?

Vocês salvam os boletos gerados(PDF ou HTML) em disco para depois enviar ?

**Comment by rafd75** [comment]
@RodolphoChagas  bom dia.

Considerando "em lote" como sendo uma nota fiscal com N vencimentos, eu adiciono os N vencimentos na coleção de boletos, e em seguida gero o PDF (1 arquivo PDF com N boletos).

Depois, disparo um email (usando outra biblioteca) para o destinatário.

**Comment by RodolphoChagas** [comment]
E como voce gera esses vencimentos em apenas um PDF ?
Eu faço isso para gerar os PDFs que estão na lista :

            foreach (var boleto in boletos)
            {
                var boletoBancario = new BoletoBancario() { Boleto = boleto };
                var pdf = boletoBancario.MontaBytesPDF(false);
                var pathPDF = @"C:\Boletos\" + boleto.NossoNumero + ".pdf";
                File.WriteAllBytes(pathPDF, pdf);
            }

Você salva em disco para o envio posteriormente ?

**Comment by rafd75** [comment]
Eu uso a classe Bolero2NetProxy que está no projeto... da uma olhada no método GerarBoletos()

Basicamente é isso aqui:

```
                var html = new StringBuilder();
                foreach (Boleto boletoTmp in boletos)
                {
                    using (BoletoBancario imprimeBoleto = new BoletoBancario
                    {
                       Boleto = boletoTmp,
                        OcultarInstrucoes = false,
                        MostrarComprovanteEntrega = true,
                        MostrarEnderecoCedente = true
                    })
                    {
                        html.Append("<div style=\"page-break-after: always;\">");
                        html.Append(imprimeBoleto.MontaHtml());
                        html.Append("</div>");
                    }
                }
```

**Comment by RodolphoChagas** [comment]
Testei aqui e deu certo!!
Como pelo o exemplo que voce colocou ele primeiro gera um HTML para depois converter para PDF, consegui quebrar a linha com '<br />' nas instruções do Boleto que antes não estava conseguindo kkkk'

Valeu mais uma vez @rafd75

**Comment by rafd75** [comment]
pronto....

com relação a questão da quebra de linha ... a mensagem veio com a quebra de linha, mas não entendi o que tem dentro das aspas...

**Comment by RodolphoChagas** [comment]
Com a quebra de linha do html consegui resolver meu problema da outra issue #92 

            string instrucoes = "";
            instrucoes "aaaaaaa <br />" + "bbbbbbbb <br />" + "cccccccccc <br />";
            boleto.MensagemInstrucoesCaixa = instrucoes;

**Comment by joaopelizari** [comment]
Bom dia. Desculpe a beginagem mas não entendi a solução. tendo a boletos criada com vários boletos, como gero um único pdf? grato.

**Comment by rafd75** [comment]
@joaopelizari bom dia.

Você tem

**Comment by rafd75** [comment]
@joaopelizari bom dia...

Primeiro você tem uma coleção de boletos... agora é só fazer um FOREACH na coleção, pegando o HTML de cada boleto.... e somando a uma mesma string.

depois disso, vc gera o PDF... o código abaixo deve ajudar a resolver ai... 

```
var html = new StringBuilder();
                foreach (Boleto boletoTmp in boletos)
                {
                    using (BoletoBancario imprimeBoleto = new BoletoBancario
                    {
                       Boleto = boletoTmp,
                        OcultarInstrucoes = false,
                        MostrarComprovanteEntrega = true,
                        MostrarEnderecoCedente = true
                    })
                    {
                        html.Append("<div style=\"page-break-after: always;\">");
                        html.Append(imprimeBoleto.MontaHtml());
                        html.Append("</div>");
                    }
                }

var pdf = new NReco.PdfGenerator.HtmlToPdfConverter().GeneratePdf(html);
            using (FileStream fs = new FileStream(nomeArquivo, FileMode.Create))
            {
                fs.Write(pdf, 0, pdf.Length);
                fs.Close();
            }
```

**Comment by joaopelizari** [comment]
Grato novamente. Agora ficou funcional. Deixei assim... *** aspx.vb
                    html = New StringBuilder()

                    For Each boleto In boletos

                        Using imprimeBoleto As BoletoBancario = New BoletoBancario With {
                            .Boleto = boleto,
                            .OcultarInstrucoes = True,
                            .OcultarReciboSacado = True,
                            .MostrarComprovanteEntrega = False,
                            .MostrarEnderecoCedente = False
                                                                                        }
                            'html.Append("<div style=""page-break-after: always;"">")
                            html.Append(imprimeBoleto.MontaHtml())
                            'html.Append("</div>")
                        End Using
                    Next

                    pathPDF = String.Concat(rootPath, boleto.NumeroControleParticipante.ToString(), ".pdf")

                    pdf = New NReco.PdfGenerator.HtmlToPdfConverter().GeneratePdf(html.ToString())

                    File.WriteAllBytes(pathPDF, pdf)
                    EnviaEmail(pathPDF)
