### ISSUE TITLE
Campo Beneficiário com Endereço

### ISSUE THREAD

**Issue by RodolphoChagas** [BoletoNet/boleto2net#95]
Bom dia.
Ao ser analisado pelo banco Bradesco o meu boleto gerado, fui informado que seria necessário dois ajustes:

- Campo Local de Pagamento, mencionar: “Pagável preferencialmente na Rede Bradesco ou Bradesco Expresso”.
- Campo Beneficiário deve ser preenchido com Razão Social, CNPJ/CPF e o Endereço.

O primeiro foi resolvido, porém não consigo de jeito nenhum colocar o endereço no campo Beneficiário, no comprovante de entrega do Boleto aparece o campo do Endereço, porém na parte de baixo do Boleto não

Alguém poderia me ajudar com isso ?

**Comment by rafd75** [comment]
@RodolphoChagas  bom dia!

Consegue colocar uma foto do boleto aqui e destacar onde não está aparecendo?

**Comment by RodolphoChagas** [comment]
![sem titulo](https://user-images.githubusercontent.com/20188061/40430876-755b24dc-5e7c-11e8-8112-0b629c2fdd32.png)

No Beneficiário só falta aparecer o Endereço.

**Comment by rafd75** [comment]
Sobre a mensagem:

Após instanciar o BancoBradesco e preencher os dados do Cedente, tenta isso:
bancoBrad.Cedente.ContaBancaria.LocalPagamento = "agável preferencialmente na Rede Bradesco ou Bradesco Expresso"

Sobre o CNPJ/Endereço do Beneficiário.. 

using (BoletoBancario imprimeBoleto = new BoletoBancario
                    {
                        Boleto = boletoTmp,
                        OcultarInstrucoes = false,
                        MostrarComprovanteEntrega = true,
                        **MostrarEnderecoCedente = true**

Para mostrar o CNPJ:
Boleto.Banco.Cedente.MostrarCNPJnoBoleto = true;

obs: não me pergunte o motivo de endereço estar na classe "BoletoBancario" (para impressão) e o CNPJ estar no Cedente ...

Deveria estar em um só local... 

Também não sei se, de fato, irá imprimir do jeito que você precisa... Caso negativo, vai precisar ajustar isso ai...

**Comment by rafd75** [comment]
Hum, já entendi.

sobre o local de pagamento, em teoria, não deveria ser alterado, pois segue o padrão implementado em cada banco. Talvez, o Bradesco alterou isso, e neste caso, deveria ser alterado dentro do BancoBradesco (evitando ter que chamar após o FormataCedente) - ou seja, a razão de estar ali, é que teoricamente, ninguém precisaria implementar isso ... já estaria (deveria estar) correto. Se for o caso (de ter alterado no Bradesco), o certo seria alterar dentro do FormataCedente()...

já do endereço, agora entendi... já tem um local que aparece, mas em outro não.
Para resolver isso, tem que alterar o HTML... Eu estou parado aqui, por conta disso #96 - mas assim que conseguir entender o motivo deste teste estar falhando... (antes não ocorria, pois a data atual era menor que a de hoje)...  Só que não vou conseguir estudar isso melhor agora.

**Comment by RodolphoChagas** [comment]
Putz, apenas importei a dll..
Como meu prazo esta apertado, vou ver se baixo o projeto e faço as alterações

**Comment by RodolphoChagas** [comment]
Consegui fazer a alteração, tive que fazer um .Replace() no html gerado.

**Comment by rafd75** [comment]
beleza... o certo mesmo, é implementar isso no HTML, e então o próprio BOleto2Net já resolve ... 

vou tentar fazer depois...

**Comment by RodolphoChagas** [comment]
Concordo!
Não é nada complicado essa alteração no HTML..
Vou deixar assim por enquanto, mas fico no aguardo da atualização assim que puder.

**Comment by thiagoamd** [comment]
Teve alguma novidade sobre esse item? pelo site do boleto eu consigo validar o arquivo remessa, porem quando mando o boleto por email para o Bradesco homologar eles apontam justamente essa parte do endereço e cpf que não aparece na parte de baixo do boleto.

**Comment by rafd75** [comment]
@thiagoamd @RodolphoChagas bom dia... 

Fiz um ajuste que deve resolver o problema...

Mas tem uma limitação: pelo espaço do boleto, adicionei apenas o Logradouro e CEP (ficou de fora o bairro, cidade e estado)... 

Atualiza sua versão, faça um teste e me retorne se resolveu o problema...

#153

@carloscds --- precisa aprovar o PR...

**Comment by thiagoamd** [comment]
Estou realizando a montagem do html manualmente e pegando os dados que o boletoNet gera.
Obrigado pela resposta.
