### ISSUE TITLE
Manual ou Wiki

### ISSUE THREAD

**Issue by anzolinsolucoes** [BoletoNet/boleto2net#97]
Desculpe minha ignorância, estou iniciando em VB.net, bom vamos ao que interessa, onde eu acho um manual, tutorial , que explique como usar?

Sou novo em VB.net!!

**Comment by carloscds** [comment]
@anzolinsolucoes Existe um projeto de teste: https://github.com/BoletoNet/boleto2net/tree/master/Boleto2.Net.Testes
